### ISSUE TITLE
sku field

### ISSUE THREAD

**Issue by eliseoalegre** [XiaoFaye/WooCommerce.NET#1]
how to save and update sku field?

**Comment by XiaoFaye** [comment]
try this line: 
`await wc.UpdateProducts(new [] { new { id = 110, sku = "skucode" } })`
or 
`await wc.UpdateProduct(110,  new { sku = "skucode" })`

**Comment by eliseoalegre** [comment]
Thank you
It worked to upgrade, but not for wc.PostProduct () when I want to register a new product.

**Comment by XiaoFaye** [comment]
Unfortunately, the product class doesn't contain the sku field, you might need to change the source code to have it. This will be fixed in the next version. Thanks for bringing this up.

**Comment by XiaoFaye** [comment]
The version 0.4.0 has fixed this issue, please update your nuget package.
