### ISSUE TITLE
UpdateProduct response when save Tags

### ISSUE THREAD

**Issue by jerryxcoke** [XiaoFaye/WooCommerce.NET#10]
Product Tags is not save when use UpdateProduct()
Tags is a `List<object> `
response is always: `"{\"product\":{...,\"tags\":[],...}}"`
```
 public async Task<string> UpdateProduct()
        {
            rest = new RestAPI("site, ck, cs");


            WCObject wc = new WCObject(rest);
            string result="";                      
            try
            {

                //result = await wc.UpdateProduct((int)id, product); -- good except tags
                //result = await wc.UpdateProduct((int)id, new Product { tags = Tags, name=Name, title=Title } ); -- good except tags
                result = await wc.UpdateProduct((int)product.id, new Product { tags = Tags }); -- do "nothing"
            }

            catch (Exception)
            {
                return "Cannot connect";
            }
            return result;

        }
```

**Comment by XiaoFaye** [comment]
The WooCommerce document says: **In write-mode need to pass a array of tags IDs (integer),** 
Have you tried to pass list of Integer instead of list of object?

**Comment by jerryxcoke** [comment]
No i did not try. How can I get tags IDs? need dependences?

**Comment by XiaoFaye** [comment]
You can go to the Admin page and manually get some Tag ids to do the testing, at least prove it will work or not. As I know the new version of WooCommerce has provided the Product_tags resource, will add support for this ASAP.
