### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by vbergara** [XiaoFaye/WooCommerce.NET#100]
I want to use it with parallelism so I was wondering if it's thread-safe or not.

**Comment by XiaoFaye** [comment]
I believe so, but do let me know if you found any issues.

**Comment by vbergara** [comment]
@XiaoFaye I made a simple DeleteAllProducts routine that I run on multiple parallel Tasks and I'm getting a nonce related error. It says that the nonce has already been used. I'm guessing it's because you generate the nonces based on time, so it's possible that multiple threads are generating identical nonces. The behaviour supports this as a random number of the Tasks run successfully.

I'll clone the repo and do some deeper debugging to confirm this and maybe come up with a way to always generate a unique nonce.

**Comment by vbergara** [comment]
I tried using a GUID as the nonce and it worked. I ran 50 tasks simultaneously deleting products and had no problem at all. Is there any caveat in using a simple `Guid.NewGuid` for the `oauth_nonce` parameter? If that's allright I can submit a pull request later today.

**Comment by XiaoFaye** [comment]
GUID will be fine, thanks for your work on this. :)

**Comment by vbergara** [comment]
[Pull request](https://github.com/XiaoFaye/WooCommerce.NET/pull/102) created.

> GUID will be fine, thanks for your work on this. :)
Thank you for this great library =D
