### ISSUE TITLE
Can't use Library!

### ISSUE THREAD

**Issue by mhandersen** [XiaoFaye/WooCommerce.NET#101]
I added the package to a ASP.NET 4.5 WebForm website in VS 2015, but keep getting error about I need to add various references:

First this one: System.Runtime.dll --> fixed this by adding a reference to: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Runtime.dll 

Second this one: System.Net.Requests --> I have no idea what this is, where to find it (it's not in my list when I choose "Add refererences..." - and tried to find an answer on Google, no help!?

So how do I actually use this?  It does not seem to be working on my solution at all :-(

Any help / answer would be great! :-)

**Comment by XiaoFaye** [comment]
When you are creating a new project, can you try to use the project type "WebApplication" instead of "WebSite"?

**Comment by mhandersen** [comment]
Yes, that works. I can now create a new customer and a new order. However, I need to get the "payment url", which looks like this: 

https://www.domain.com/checkout/order-pay/541/?pay_for_order=true&key=wc_order_58d4c7efbfd0c

I know the OrderID (541) and if I look at the data comming back from the JSON API when I retrieve an order, I see this:

   "orders":[
      {
         "id":541,
         "order_number":541,
         "order_key":"wc_order_58d4c7efbfd0c",
         .....

As you can see the data contains the "order_key" - and this is the one I need to be able to reproduce the payment URL, as this only works if it contains the key: &key=wc_order_58d4c7efbfd0c

But the Order object in your API does not contain this data (order_key). I thought it might be in the "order_meta" dictionary, but this is just NULL. I have this code, which works (Order 541 is loaded), but I cannot find the "order_key"

 var newlyCreatedOrder = await wc.GetOrder(541);
            if (newlyCreatedOrder.id.HasValue)
            {
               // order_key --> key=wc_order_58d4c7efbfd0c
                string key = newlyCreatedOrder.order_meta["order_key"];
            }

Are there any way to retrive "order_key" using your API ?

**Comment by XiaoFaye** [comment]
What is your url when using the library? similar as below?
http://www.yourstore.co.nz/wp-json/wc/v1/

If not, you might be using the legacy api, which doesn't contain the order_key property.

**Comment by mhandersen** [comment]
I use:
RestAPI rest = new RestAPI("https://www.zorkytech.com/wc-api/v3/", .....

**Comment by XiaoFaye** [comment]
yes, that's the legacy one. please use the similar url as I mentioned.

**Comment by mhandersen** [comment]
Yes, that works. Thanks.

However, now I have another issue. What I want to do is this:

1: Create a new customer = is working
2: Create a new order = is working
3: Generate the Payment URL - for this I need the order id and the order_key, the URL is looking like this: https://www.domain.com/checkout/order-pay/542?pay_for_order=true&key=wc_order_58d4ea10398a2

However, as I create a new order, I don't know the ID of the order - and this is not being returned when I call: wc.PostOrder(o) 

So I have made this test code (I have looked up the Order ID in WooCommerce for testing purpose):

 // ** GET ORDER BY ORDER ID **
            var newlyCreatedOrder = await wc.GetOrder(542);  // we don't know order Id :-(
            if (newlyCreatedOrder.id.HasValue)
            {
                txtResult.Text += "New order retrived - ID: " + newlyCreatedOrder.id.Value + Environment.NewLine;
                txtResult.Text += string.Format("Payment URL: https://www.zorkytech.com/checkout/order-pay/{0}?pay_for_order=true&key={1}", newlyCreatedOrder.id.Value, newlyCreatedOrder.order_key) + Environment.NewLine;
            }

The above code works, but I don't know the order ID - so I can't use this in "real life" - so I have to get all orders for the Customer and get the newest one, like this:

            // ** GET ORDER FOR CUSTOMER (AS WE DO NOT KNOW ORDER ID) **
            var customerOrders = await wc.GetCustomerOrders(10);      // newCustomerID
            if (customerOrders.Count > 0)
            {   .... }

BUT .. the call to "wc.GetCustomerOrders(10)" fails with this message: 

{"{\"code\":\"rest_no_route\",\"message\":\"No route was found matching the URL and request method\",\"data\":{\"status\":404}}"}

My REST API URL is: 

RestAPI rest = new RestAPI("https://www.domain.com/wp-json/wc/v1/", ...

Any help to how I get the newly created order, without knowing the ID of the order  (in order to get the "order_key"), would be great!

**Comment by XiaoFaye** [comment]
PostOrder returns the json string of the order, you can deserialize it into Order object, which will have the order id.

**Comment by mhandersen** [comment]
Yes, this works:

var orderJson = await wc.PostOrder(o);
Order newOrder = JsonConvert.DeserializeObject<Order>(orderJson);
int id = newOrder.id.Value;

Any idea why:

var customerOrders = await wc.GetCustomerOrders(10); 

Is not working and returns:
{"{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}"}

And thank for awesome and very quick help. Your wrapper is really nice! :-)

**Comment by XiaoFaye** [comment]
GetCustomerOrders is from the legacy api, so it won't work in the latest v1 api, I will remove it in the next release. 

In the meantime, you can use GetOrders with customer parameter to get specific orders.

**Comment by XiaoFaye** [comment]
@mhandersen  GetCustomerOrders  has been marked as deprecated, you can use GetOrders with customer parameter instead.

**Comment by yonahs** [comment]
> When you are creating a new project, can you try to use the project type "WebApplication" instead of "WebSite"?

I need to use this in an existing website and not a webapplication. Is there a solution to this problem?
