### ISSUE TITLE
Unable to pass categories while creating a product

### ISSUE THREAD

**Issue by jmd007** [XiaoFaye/WooCommerce.NET#103]
- WP: 4.7.3 /WC: 2.6.14 / WooCommerce.NET 0.6.0

Adding a product I want to specify one or more categories for this product, here is my code and it gets rejected. Can you help me with the right syntax for the categories? Thank you.

Product p = new Product()
            {
                name = "test product 8",
                sku = "BRATEST001",
                title = "test product 8",
                description = "test product 8",
                price = 35,
                regular_price = 36,
                sale_price = 37,
                categories = {"id":56}

            };
            await wc.PostProduct(p);

**Comment by goguvi** [comment]
Take a look here #41

**Comment by jmd007** [comment]
Hello,

(WP 4.7.3 , WC 3.0.1 and WooCommerce.NET DLL version 0.5.6.0, VS Studio Community 2015)

Trying to use WooCommerceNET, I'm able to get products or even update products in the WooCommerce Website.

Now I'm trying to extend it's use to do more stuff like adding existing categories to products. For this I need to have code like yours:

WooCommerceNET.RestAPI rest = new WooCommerceNET.RestAPI("http://www.mysite.com/wp-json/wc/v1/", "ck.............................

await wc.UpdateProduct(314, new WooCommerceNET.WooCommerce.Product() { categories = new CategoryList() { new Category() { id = 9 } } });

OR 

CategoryList cl = new CategoryList();

VS Studio does not find the namespace "**CategoryList**" or "**CustomerList**" can you let me know why? Or what should I do?

Thank you.

Best regards

JM Duchi

**Comment by goguvi** [comment]
you can use `List<Category>`, for example the following code will add a product to a category:

```
int catID = <Your category id>;
Product artWoo = new Product()
artWoo.categories = new List<Category> { new Category() { id = catId } };
```
