### ISSUE TITLE
Product Tag issue/use?

### ISSUE THREAD

**Issue by pistolgrip69** [XiaoFaye/WooCommerce.NET#104]
I've been working on testing using WooCommerceNET and have ran in to an issue with trying to figure out how to add product tag(s) when creating products. I've tried using several different methods of adding tags, but nothing seems to work to actually get the tag(s) written to database.

Adding global/local attributes seems to work just fine with the code/method below, but I can't seem to crack the code on adding tags when creating products.

Thanks for any help/guidance. Very impressed with how well the library works overall.

Example code below:

`   
             //Add new product
            Product p = new Product();
           // Product Details
            p.type = "simple";

            //Add Tags
            p.tags = new List<WooCommerceNET.WooCommerce.Tag>();
            Tag tg = new Tag();
            tg.name = "Test Brand";
            tg.slug = "test-brand";
            p.tags.Add(tg);

            // Add Attributes (Brand)
            p.attributes = new List<WooCommerceNET.WooCommerce.Attribute>();
            WooCommerceNET.WooCommerce.Attribute att = new            WooCommerceNET.WooCommerce.Attribute();

            att.id = 1;
            att.name = "Brand";
            att.position = 0;
            att.variation = false;
            att.visible = true;
            att.options = new List<string>();
            // Brand Name
            att.options.Add("Test Brand");
            p.attributes.Add(att);

          //Take json result and deserialize into Product before returning
            var s = await wc.PostProduct(p);
            var pOut = JsonConvert.DeserializeObject<Product>(s);
            //return product 
            return pOut;`

**Comment by goguvi** [comment]
First you have to create the tag and then add the id to the product.
Refer here #77

**Comment by pistolgrip69** [comment]
I looked through previous issues before posting, but must have missed #77. 

Thanks!
