### ISSUE TITLE
Count records - Orders, Product etc.

### ISSUE THREAD

**Issue by hikarushin** [XiaoFaye/WooCommerce.NET#105]
Is there any way to count all records? Ex: orders

**Comment by goguvi** [comment]
Legacy API has a count endpoint see: http://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#view-products-count

The new REST API expose these values throgt the response Header see: https://woocommerce.github.io/woocommerce-rest-api-docs/#pagination

**Comment by hikarushin** [comment]
It seems I don't have choice, just follow #83
