### ISSUE TITLE
Get error woocommerce_api_authentication_error with https

### ISSUE THREAD

**Issue by trungdh** [XiaoFaye/WooCommerce.NET#106]
Hi Mr. XiaoFaye
After my Woocommerce site changed to https protocol. I request to its API via WooCommerce.NET library and I got error :
`{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Key is missing"}]}`

with request look like :
`https://mysite.com/wc-api/v1/customers/email/testmailregistered@gmail.com?consumer_key=ck_xxx&consumer_secret=cs_xxx`

It's got same error for any Woocommerce legacy version (v1,v2,v3)
I don't have any idea for this problem because in my request which already has consumer key.
Could you kindly give me any suggestion for my problem ? Mr. XiaoFaye ?

Thank you so much !

**Comment by XiaoFaye** [comment]
Can you please try to use the lastest v1 api instead of the legacy one? simply change your url to https://mysite.com/wp-json/wc/v1/

**Comment by trungdh** [comment]
Thanks for reply, Mr. XiaoFaye
I'm tried to used wp-json/wc/v1/ instead for legacy, but I got the error : The remote server returned an error: (401) Unauthorized.

**Comment by XiaoFaye** [comment]
https://mysite.com/wp-json/wc/v1/   is different from    https://www.mysite.com/wp-json/wc/v1/ , make sure you use the correct URL as the one in your Wordpress url setting.

**Comment by trungdh** [comment]
yes, sure Mr. Xiao
In settings, my  WordPress address and Site Address are : 
WordPress Address : https://mysite.com
Site Address : https://mysite.com

**Comment by XiaoFaye** [comment]
Can you try to use the authorizedHeader parameter in RestAPI? set it to True and see how it goes.

**Comment by trungdh** [comment]
I tried to used authorizedHeader is true and program jump to code : 
`httpWebRequest = (HttpWebRequest)WebRequest.Create(wc_url + GetOAuthEndPoint(method.ToString(), endpoint, parms));
                        httpWebRequest.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(wc_key + ":" + wc_secret));`
to generate httpWebRequest object. But I got error : 
`The remote server returned an error: (403) Forbidden.` for that, Mr. Xiao

**Comment by XiaoFaye** [comment]
this seems have something to do with your web server setting, can you please have a look?

**Comment by goguvi** [comment]
For example my test server returns 403 Forbidden when I don't pass a User-Agent (see # 63)

**Comment by bssol** [comment]
Https request throws error in xamarin forms android what to do

**Comment by XiaoFaye** [comment]
@bssol https://github.com/XiaoFaye/WooCommerce.NET/issues/241
