### ISSUE TITLE
Add Product with Existing Category

### ISSUE THREAD

**Issue by eGiNiusPOS** [XiaoFaye/WooCommerce.NET#108]
Hi,

I use Visual Studio 2015, as in the subject 
I don't know how Add new Product with an Existing Category
I've read other issue, but I don't find in my .net CategoryList

thank's in advance
nicola

- Wordpress version 4.7.3, WooCommerce version 3.0.0,  WooCommerce.NET 0.6.1

**Comment by goguvi** [comment]
something like that should work:
```
int catID = <Your category id>;
Product artWoo = new Product()
artWoo.categories = new List<Category> { new Category() { id = catId } };
```

**Comment by eGiNiusPOS** [comment]
Ok try immediatly,

how can I get categorylist?
