### ISSUE TITLE
Implementation on a Windows Service.

### ISSUE THREAD

**Issue by HugoRodriguesPT** [XiaoFaye/WooCommerce.NET#109]
Objective: Create a Windows Service that syncs all process
Using: **Visual Studio 2015
           WooCommerce 3.0**
Note: Sorry my english 👍 

Hello,

Im trying to create a service that syncs all the data from a ERP(Local DataBase) to the website. The easy part, getting data from the DB is easy, now im working on the connection whit the Rest API.  Im starting using your framework and i love it! But whit the new version i am afraid that the error is in my calls..

Anyways im trying to insert some products and customers and im getting stuck... probably is a easy fix! 
my company wants the service to support the last version of WC and as i see all old methods still works.

In some issues i see ppl trying to call the "v3/" URL but now im using this configs:
![image](https://cloud.githubusercontent.com/assets/26927729/24708901/26b13e0e-1a10-11e7-96a1-749ed7c39ef0.png)
![image](https://cloud.githubusercontent.com/assets/26927729/24708988/7210fa56-1a10-11e7-9372-050c7bf4a35a.png)

and that works!! but when i try to add a customer nothing happens:
![image](https://cloud.githubusercontent.com/assets/26927729/24708960/59caaf0a-1a10-11e7-9dfb-b13165d88d8f.png)

Probably is something abou Legacy or as i said some wrong calls.

Greetings,
Hugo Rodrigues

**Comment by XiaoFaye** [comment]
First of all, it's good to know that the wrapper is helpful for you. :)

By looking into your code, I can see 2 problems:
1. When insert product, you are using the latest V1 api, but in InsertCustomer, you are using the legacy object.
2. I don't see PostCustomer has been called in InsertCustomer.

**Comment by HugoRodriguesPT** [comment]
Thanks! i was using legacy because i follow the example... i told u it was easy fix! ahah
anyways now i have my WService running a schedule process that will check if any of the products suffers updates. I made this method but i think that whit good amount of data that will slow the machine. Take a look:
![image](https://cloud.githubusercontent.com/assets/26927729/24731508/7a78571e-1a62-11e7-9534-582480560a9c.png)
to solve my case i can do Triggers but i find in some issue that u recomend using this: 
![image](https://cloud.githubusercontent.com/assets/26927729/24731532/a93a299c-1a62-11e7-9e02-52b4e6bdc2d5.png)
what is your suggestion??

**Comment by XiaoFaye** [comment]
Record all product changes, use ProductBatch to do a batch update at the end of your loop.

**Comment by HugoRodriguesPT** [comment]
![image](https://cloud.githubusercontent.com/assets/26927729/24732269/d47d1074-1a67-11e7-9394-d16b1889ab43.png)


1- ProductBatch up = new ProductBatch();
2 - i will storage my changes in the Lists
3 - in the end of the loop i need to batch the lists but i get this error... 
And now i need to use Legacy?

**Comment by XiaoFaye** [comment]
Please remove the legacy here:

![image](https://cloud.githubusercontent.com/assets/6334728/24732367/8986af82-1ac4-11e7-9ac3-af6c352fe22a.png)

Never use legacy if you don't have to as it's not being maintained anymore.

**Comment by HugoRodriguesPT** [comment]
this methods are from legacy: 
![image](https://cloud.githubusercontent.com/assets/26927729/24732439/e06056b6-1a68-11e7-9ea3-d8595738f526.png)
Once again, thanks for helping!

**Comment by XiaoFaye** [comment]
On the top of your code file, if you see any "using xxxx.xxx.legacy", please remove it.

**Comment by XiaoFaye** [comment]
if you want to use legacy functions, please do it in another code file with a legacy WCObject, so it will not mix with the latest API.

**Comment by HugoRodriguesPT** [comment]
easy then, can i suggest that you add that in the main documentation? some kind for legacy use, so new users like me dont get lost ;) or adding this lines instead 
![image](https://cloud.githubusercontent.com/assets/26927729/24732679/507f81e6-1a6a-11e7-80ae-6d7a5bdd3037.png)

**Comment by XiaoFaye** [comment]
I have been thinking of a better way to keep the legacy and latest API working side by side, hopefully I can include that in the next release.

**Comment by HugoRodriguesPT** [comment]
Another think since the new version of WC was released yesterday i dont know for sure if i am using the right url since v1-v3 json response... u said in another post to use always /wp-json/wc/v1/
![image](https://cloud.githubusercontent.com/assets/26927729/24732805/3c855cfa-1a6b-11e7-8e26-12aef0dc77a2.png)

**Comment by XiaoFaye** [comment]
Already working on the WC 3.0 API, expecting a pre-release in early May.

**Comment by XiaoFaye** [comment]
When you pass the URL as ***wc-api/v3/, that is the legacy one, 

And **/wp-json/wc/v1/** will be the latest API.

**Comment by HugoRodriguesPT** [comment]
Nice! I'm completing the computer engineering course and for 5 months im working as a trainee in a company and it's the first time I'm creating a windows service, you dont know how happy i am to have this framework eheh Thanks :) i will struggle whit all the changes

**Comment by HugoRodriguesPT** [comment]
Hey! 
My Service is running nicely but now my company added a UC. At the moment every time i start the service I create a new RestAPI instance. Now, because the local machine is always running, i need a scheduled task to validate the RestApi key and secret every hour for example... Can you give me a example of how to do it? 
Thanks!
