### ISSUE TITLE
ProductBatch syntax

### ISSUE THREAD

**Issue by templar1971** [XiaoFaye/WooCommerce.NET#112]
Hi,
I usede the piece of code below to upadate many product at time,
to try I've used only ten rows, but this operation take loooong time

It's correct my sybtax ?
could  you help me

thanks in advance
nicola

Dim product As Product

            Dim PB As New ProductBatch
            Dim productList As List(Of Product) = New List(Of Product)
            For i As Integer = 0 To dtjson.Rows.Count - 1
                product = New Product
                With product
                    .categories = New List(Of Category)() From {
                    New Category() With {.id = 30}}
                    .name = dtjson.Rows(i)("Descrizione") & " NEW"
                    .short_description = dtjson.Rows(i)("Ingredienti")
                    .description = dtjson.Rows(i)("IDPietanza")
                    .regular_price = CDec(dtjson.Rows(i)("PrezzoVendita"))
                    .shipping_class = "costo-domicilio"
                End With
                productList.Add(product)
            Next
            PB.create = productList
            Await wc.UpdateProducts(PB)

**Comment by XiaoFaye** [comment]
Can you please check your server speed?
