### ISSUE TITLE
Incorrect Decimal separator in price

### ISSUE THREAD

**Issue by uurapp** [XiaoFaye/WooCommerce.NET#113]
- Wordpress version: 4.7.3–nl_NL
- WooCommerce version: 2.6.14
- WooCommerce.NET version: v4.0.30319

Running on a non-English pc, where comma's are used as decimal separator.
In C# I haved tried to solve this issue by setting **CurrentCulture ** to **American English** but it has no effect.

```
var ci = new CultureInfo("en-US");
Thread.CurrentThread.CurrentCulture = ci;
Thread.CurrentThread.CurrentUICulture = ci;

```
Create a product, set it's price to e.g. 2,97 
Execute an async **ProductBatch** update: 

`var result = await wc.UpdateProducts(productCreateBatch);`

The **price** in **result** now contains a comma as decimal separator.

![image](https://cloud.githubusercontent.com/assets/8829775/25184149/e24ed8e2-2519-11e7-9055-140c4496c62c.png)

In WooCommerce the price is also displayed with a comma, but the decimal numbers (after the comma) are simply ignored. If you edit the field and change the comma into a point (and save the product) the price is updated correctly and works as expected.

**Comment by uurapp** [comment]
I was able to work-around this issue by creating a JsonSerializeFilter:

```
RestAPI rest = new RestAPI("http://xxxxx.nl/wp-json/wc/v1/",
                "ck_12344567890",
                "cs_12344567890", true, fixPrice);


public string fixPrice(string input)
{
	string pattern = @"price\"":\""(\w*)\,(\w*)\""";            
	string replacement = @"price"":""$1.$2""";

	return Regex.Replace(input, pattern, replacement);
}
```
This searches for the price-string in the JSON and replaces the comma with a dot.
A better solution is still preferred.

**Comment by vbergara** [comment]
Do you get this same behaviour when posting/updating single products instead of batches? I'm also running on a computer where comma is the decimal separator and everything works fine, the only difference from your case is that I'm not using product batches.

**Comment by uurapp** [comment]
Thanks @vbergara . 
I have just tested with a single post and it that fails too. Interesting that you don't have this issue. Do you set the CultureInfo?

If that is required I know that in versions before .NET 4.5 this CultureInfo was not passed to an asynchronous task [(http://stackoverflow.com/questions/30662668/keep-currentculture-in-async-await)](http://stackoverflow.com/questions/30662668/keep-currentculture-in-async-await) and all methods in this library are async. But I'm developing in 4.6x so this should be an issue. Also, I'm not sure if setting the culture is required in the first place (I tried both: with and without). 

It can't be caused by WordPress either because I see in the result of a POST that the string already contains comma's.
Any ideas?

**Comment by uurapp** [comment]
I did some extra testing and I can now confirm that this issue was caused by a local (non-English) **CurrentCulture**.

I was setting the **CurrentCulture** to "**en-US**" at the beginning of the application but it was reset to it's default (non-English) culture later in the application. I haven't figured out what caused this, but I have moved it just before I call **UpdateProducts** and now it works fine.

**Comment by vbergara** [comment]
@uurapp Good to know you figured it out, thanks for sharing the solution.

I never had to change my CurrentCulture and never had this issue, that's really weird. I'll check to see if it's already set to "en-US" but I don't think it is.

**Comment by uurapp** [comment]
I placed this just before the call and listed my local culture (nl-NL)

`Console.WriteLine("CurrentCulture.Name: " + Thread.CurrentThread.CurrentCulture.Name);`

Now it prints en-US and it works fine. I checked it several times to make sure. I don't know how the JSON is created but if something like `decimal.ToString()` is used, that could cause the issue.

**Comment by vbergara** [comment]
Just tested it and it lists my local culture as well (pt-BR), but I still don't have the error. Go figure. But now I know what to do if it ever happens. =)

**Comment by uurapp** [comment]
Could it be this?

![image](https://cloud.githubusercontent.com/assets/8829775/25269398/c1eae7c6-267c-11e7-8f2a-05ffa995f936.png)

In the deserialization I see that the culture is set specifically:

![image](https://cloud.githubusercontent.com/assets/8829775/25269445/f48daaec-267c-11e7-886d-fb3a0ee2ae5a.png)
