### ISSUE TITLE
Create product with Variations

### ISSUE THREAD

**Issue by fernando6666** [XiaoFaye/WooCommerce.NET#114]
How do I post a product with variations? I've tried to add a list of variations to the property "variations" but it wont upload the variations, it is creating the attributes correctly but not the variations.

Also if I try to get a product with variations it returns an error:

The 'Element' state is expected. 'Text' with the name '', namespace '' was found.

**Comment by uurapp** [comment]
Can you include your code?

**Comment by fernando6666** [comment]
The problem is that in woocommerce 3.0 the variations property is a list of ID's and not of objects, I know there is not compatibility of this library for that version of woocommerce, so I am modifiying the source code until the next release.

**Comment by hikarushin** [comment]
You can try to the following: #121 and #93 when adding variations to your product

**Comment by athsk** [comment]
I have the same problem. Can you please include some code on how to create the product with variations?
I tried adding the product and then adding variation but I cant get the product id back to use for the variations.

**Comment by code54nl** [comment]
@athsk , I add the variants when I create the product. The product (including all variants) is posted in a single post. I even post multiple products (including all variants) by a batch. The problem I have however, is that I can't included more than +/- 25 variants or the WooCommerce API gives a Gateway Timeout (after 60 seconds). Even with a single product (and > 25 variants).

This is a sample for a product with multiple lengths. I edited to remove some extra non-relevant code so it's semi-code now ;-)

```
private Product MyItemToWooProduct(MyItem myItem, IEnumerable<ItemSize> sizes)
{
	Product product = new Product();
	product.date_modified = myItem.date;
	product.sku = myItem.sku;
	product.description = myItem.description;
	product.name = myItem.description;
	product.price = myItem.salesPrice;
	product.regular_price = myItem.salesPrice;


	product.attributes.Add(new WooCommerceNET.WooCommerce.Attribute()
	{
		id = productLengthAttributeId,
		variation = true,
		options = sizes.Select(x => x.name).ToList()
	});

	product.type = "variable";
	product.variations = new List<Variation>();
	foreach (var size in sizes.OrderBy(x => x.size))
	{
		product.variations.Add(new Variation()
		{
			price = price,
			regular_price = price,
			attributes = new List<VariationAttribute>()
			{
				new VariationAttribute()
				{
					id = productLengthAttributeId,
					option = size.name,
					name = size.name
				}
			}
		});
	}

	return product;
}
```

**Comment by athsk** [comment]
So you make  a List<Variation> and store inside the Variations of the product. Did that but I get the error 

> Cannot implicitly convert type 'System.Collections.Generic.List<WooCommerceNET.WooCommerce.v2.Variation>' to 'System.Collections.Generic.List<int>'

It looks like the variation property of Product is List<int>
I am using the WoocommerceNET 0.7.0 do I need to use other version?

**Comment by code54nl** [comment]
@athsk , when you use `product.variations = new List<Variation>(); `the list is of type `Variation`, not int. If you include your code in your question we might see what goes wrong.

**Comment by athsk** [comment]
@code54nl  
 I get the sizes and the colors from the Database but i put them like that for the code to work without the need of my database. This is a test method to create a demo product. 

I refenerce the v2 that is available for compatbility with the v2 of the api.
 
```
using WooCommerceNET.WooCommerce.v2;

 private async void TestCreateProduct(object sender, EventArgs e)
        {
            try
            {
                RestAPI rest = new RestAPI("http://" + WCUrl + WCEndpoint, WCKey, WCSecret);
                WCObject wc = new WCObject(rest);
                
                //add colors and  sizes 
                List<string> colors = new List<string>() { "901", "902", "903", "904", "905", "906" };
                List<string> sizes = new List<string>() { "S", "M", "L", "XL" };

                ProductAttributeLine pal = new ProductAttributeLine()
                { name = "Color", variation = true, visible = true, options = colors };
                ProductAttributeLine pal2 = new ProductAttributeLine()
                { name = "Size", variation = true, visible = true, options = sizes };
                List<ProductAttributeLine> attribs = new List<ProductAttributeLine>();
                attribs.Add(pal);
                attribs.Add(pal2);

          //generate the variations
                List<Variation> vrs = new List<Variation>();

                List<VariationAttribute> vatrib = new List<VariationAttribute>()
                { new VariationAttribute() { name="Color",option="901" },
                  new VariationAttribute() { name="size",option="S" } };
                Variation var1 = new Variation()
                {
                    regular_price = 13.99M,
                    sale_price = 9.99M,
                    visible = true,
                    attributes = vatrib,
                    stock_quantity = 5,
                    manage_stock = true
                };
                vrs.Add(var1);

                vatrib = new List<VariationAttribute>()
                { new VariationAttribute() { name="Color",option="902" },
                  new VariationAttribute() { name="size",option="M" } };
                var1 = new Variation()
                {
                    regular_price = 20.99M,
                    sale_price = 15.99M,
                    visible = true,
                    attributes = vatrib,
                    stock_quantity = 5,
                    manage_stock = true
                };
                vrs.Add(var1);
              

                //Add new product
                Product p = new Product()
                {
                    name = "The Test " + DateTime.Now.ToString("HHmmss"),
                    short_description = "hm this is a <b>short</b> description ",
                    description = "well this is a <b>looooooooooooooong</b> description blah blah blah..... ",
                    slug = "slug",
                    type = "variable",
                    status = "publish",
                    // i have more options here....
                    attributes = attribs,
                    variations = vrs,
                  };
                await wc.Product.Add(p);   
            }
            catch (Exception expt)
            {
                MessageBox.Show(expt.Message);
            }
        }
```
I get the error below:
![image](https://cloud.githubusercontent.com/assets/13262550/26252037/cca7679c-3cb7-11e7-88c0-18afd33691e4.png)

**Comment by code54nl** [comment]
@athsk , I think you are using the wrong Variations. Please hover both variables (`variations `and `vrs`) and check they are of type: 

![image](https://cloud.githubusercontent.com/assets/8829775/26253705/934243da-3cb4-11e7-99bc-e5c2bacdafc8.png)

**Comment by athsk** [comment]
@code54nl They are not the same

![image](https://cloud.githubusercontent.com/assets/13262550/26269847/e29aafe4-3cff-11e7-92f2-e3dfef7934e4.png)

![image](https://cloud.githubusercontent.com/assets/13262550/26269849/e82d40a2-3cff-11e7-91e1-7e83138fd526.png)

**Comment by 50l3r** [comment]
I have the same error in my code

**Comment by wdvalena** [comment]
Product variation needs an existing product.
So you need to create the Product before you can add a variation.

//Add new product
Product p = new Product()
{
    name = "The Test " + DateTime.Now.ToString("HHmmss"),
    short_description = "hm this is a <b>short</b> description ",
    description = "well this is a <b>looooooooooooooong</b> description blah blah blah..... ",
    slug = "slug",
    type = "variable",
    status = "publish",
    // i have more options here....
    attributes = attribs
 };
p = await wc.Product.Add(p);   

 //Add Variations
Variation var1 = new Variation()
{
    regular_price = 13.99M,
    sale_price = 9.99M,
    visible = true,
    attributes = vatrib,
    stock_quantity = 5,
    manage_stock = true
};
var1 = await wc.Product.Variations.Add(variation, p.id.Value);
p.variations.add(var1.id);
wc.Product.Update(p.id.Value, p);
