### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by code54nl** [XiaoFaye/WooCommerce.NET#115]
- Wordpress version: 4.7.3–nl_NL
- WooCommerce version: 2.6.14
- WooCommerce.NET version: v4.0.30319

When using a batch to post products (including variations) I sometimes get this exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.WooCommerce.WCObject`14.<UpdateProducts>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ... my function that calls the post....
```

I have experimented with different numbers of products in the batch.  I have to upload a total amount of more than 5000 product(variation)s but I'm limiting the number of products, including variations, to a maximum of 100, or even just 80 or 60 per batch. Sometimes I get this exception after uploading around 80%, sometimes, at 20% or immediately. I can't pinpoint what is causing this. If I lower the amount of products I sometimes get this error sooner. It might nothing have to do with it.

Anyone any idea what can cause this issue?
Thanks for your support,
Robert

**Comment by code54nl** [comment]
It is a time-out exception that is not properly handled:

The Split causes the exception:

![image](https://cloud.githubusercontent.com/assets/8829775/25271094/3e514a34-2683-11e7-9f97-6005ff168bff.png)

The exception is:
![image](https://cloud.githubusercontent.com/assets/8829775/25271111/4a21d13a-2683-11e7-96ce-97f52b2a3a6f.png)

**Comment by code54nl** [comment]
I would suggest something like this:
```

catch (WebException we)
{
	if (httpWebRequest != null && httpWebRequest.HaveResponse)
		if (we.Response != null)
		{
			if (((HttpWebResponse)we.Response).StatusCode == HttpStatusCode.GatewayTimeout)
			{
				throw new Exception("Gateway Timeout");
			}
			throw new Exception(await GetStreamContent(we.Response.GetResponseStream(), we.Response.ContentType.Split('=')[1]));
		}
		else
			throw we;
	else
		throw we;
}
catch (Exception e)
{
	return e.Message;
}

```

**Comment by code54nl** [comment]
See: https://github.com/XiaoFaye/WooCommerce.NET/issues/90

**Comment by vbergara** [comment]
Thanks for looking into this, I've been getting this error myself and it's good to know that it's a server-side timeout. I'm probably doing too much simultaneously for my server to handle.
Thanks again.

**Comment by code54nl** [comment]
@vbergara, on the other hand, it's difficult to solve server side issues when you are not in control of that part. I'm posting products with a lot (more than 40) variants and a single product sometimes fails. Even with 25 variants.  Only if I limit it to approx. 10 variants it always works well. But I'm not sure if can post a single product with multiple variants in more than one single post. I would rather increase the timeout on the server ;-)

**Comment by vbergara** [comment]
@code54nl my problem is that I'm running a lot of updates in parallel, all single products but a 100 at a time so the server is being overwhelmed, I'm not savvy on the server-side config stuff so I'm not sure a timeout increase would help much.

@XiaoFaye this error is actually hiding almost all request errors. I'll se if I can code a fix tonight and send you a request.

**Comment by XiaoFaye** [comment]
hi @vbergara , this has been fixed and the new code will be committed soon.
