### ISSUE TITLE
GetOrders Error Deserialization

### ISSUE THREAD

**Issue by eGiNiusPOS** [XiaoFaye/WooCommerce.NET#117]
Hi,
I'm trying to get orders, but Iìve this error

Dim rest As New RestAPI("http://xxxxxxxxx/wp-json/wc/v1/", "xxxx", "xxxx")
            Dim wc = New WCObject(rest)
            Dim ps = New System.Collections.Generic.Dictionary(Of String, String)() From {
                {"per_page", "100"}
            }

            Dim listCategories = Await wc.GetProductCategories(ps)
            Dim listOrders = Await wc.GetOrders(New System.Collections.Generic.Dictionary(Of String, String)() From {
                {
                "after", new DateTime(2017, 04, 15).ToString("yyyy-MM-ddThh:mm:ss")
                }
            })

Errore durante la deserializzazione dell'oggetto di tipo System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Order, WooCommerceNET, Version=0.5.6.0, Culture=neutral, PublicKeyToken=null]]. Il valore 'total' non può essere analizzato come tipo 'Int32'.

**Comment by goguvi** [comment]
Take a look at this issue https://github.com/XiaoFaye/WooCommerce.NET/issues/107#issuecomment-295159349

**Comment by eGiNiusPOS** [comment]
Hi thank you,
I've solved using "v2" in 
Dim rest As New RestAPI("http://xxxxxxxxx/wp-json/wc/v2/", "xxxx", "xxxx")
