### ISSUE TITLE
Product Images

### ISSUE THREAD

**Issue by HugoRodriguesPT** [XiaoFaye/WooCommerce.NET#118]
#109
Will the option to insert Product main image be implemented? if not, is there any alternative option to do that? 
for now when i update products all images go to gallery...
![image](https://cloud.githubusercontent.com/assets/26927729/25348008/b14d8f64-2914-11e7-8e1b-a9d007c9bff3.png)

Thanks!

**Comment by goguvi** [comment]
Try setting image positon as zero.
See: http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**Comment by HugoRodriguesPT** [comment]
you are like god to me ahah 
![image](https://cloud.githubusercontent.com/assets/26927729/25349437/bcae3dc2-2919-11e7-858c-3d52d7d99fc0.png)
thank you so much!!
another thing if i use local ftp server (filezilla) nothing happens: 
![image](https://cloud.githubusercontent.com/assets/26927729/25349513/06d7c094-291a-11e7-9585-8c52e937d7b3.png)
any idea why??

**Comment by goguvi** [comment]
I tried to do it with a local server using HttpListener (not by ftp), the web browser showed me the images correctly, but the upload did not work.
I noticed that that src is interpreted on the server and therefore that local resource to my computer is not found.

I have solved it by uploading the image using a wordpress plugin that uses the media_handle_upload function and returns the image ID (https://developer.wordpress.org/reference/functions/media_handle_upload/).
You can also use the API wordpress, but requires its own authentication (https://developer.wordpress.org/rest-api/reference/media/).

**Comment by HugoRodriguesPT** [comment]
Thanks, i will allocate my project on a web service so i will be able to use that src i think...

**Comment by goguvi** [comment]
I think the function that upload the image from src is  'set_product_images( $product, $images )' from 
'includes/api/v1/class-wc-rest-products-controller.php' of WooCommerce.
It calls the method 'wc_rest_upload_image_from_url' that internally uses:
```
function wp_safe_remote_get( $url, $args = array() ) {
    $args['reject_unsafe_urls'] = true;
    $http = _wp_http_get_object();
    return $http->get( $url, $args );
}
```
