### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by Jimc65** [XiaoFaye/WooCommerce.NET#12]
I don't know if this is a bug or a usage problem, but every time I try to execute a request (GetCustomer, GetOrder, UpdateOrder), I am getting a Null Reference Error.

Here's a snippet of my code (the url, key, and secret are all initialized strings):
            try
            {
                RestAPI rest = new RestAPI(wc_url, wc_key, wc_secret);
                WCObject wc = new WCObject(rest);

                Customer cust = await wc.GetCustomer(1);

![null reference error](https://cloud.githubusercontent.com/assets/20483023/16889470/ba7f0c50-4ab4-11e6-996e-ea252d4f7450.JPG)

**Comment by XiaoFaye** [comment]
Have you tried to debug into the code and see which object was null?

**Comment by Jimc65** [comment]
Yes, but I think that the async design is making that a challenge.  I trace through it fine, and it pops back out to my call, and then the error dialog above pops up a few seconds later.

I am trying to create a SOAP web service as a wrapper, and that may be part of the problem.  I just tried to create a very simple console app with the same few lines, and VS is telling me that I can't use the await operator inside a method that's not async (the Main(string[] args) method).  How can I call the library without making all of my code aync?  I had the same problem with my web service WebMethod, so I added async to it, but I am skeptical that will work.

**Comment by XiaoFaye** [comment]
1. Could you please copy the exception detail above and paste it here?
2. Just don't use await operator in your Main method, you will get a warning, but it's fine.

**Comment by Jimc65** [comment]
If I don't use await, then I get the following error.
Cannot implicitly convert type 'System.Threading.Tasks.Task<WooCommerceNET.WooCommerce.Customer>' to 'WooCommerceNET.WooCommerce.Customer'

**Comment by XiaoFaye** [comment]
Could you please try the code below:

var cust = wc.GetCustomer(1).Result;

**Comment by Jimc65** [comment]
That works.  I got a tip on another approach that works as well.

var result = wc.GetCustomer(1);
Task.WaitAll(result);

I think that the original null reference error was happening from the VS test code that is used to invoke the web service, and show the result.  It was trying to show the result before it had been returned.

Thanks for your help and the quick replies!

**Comment by jerryxcoke** [comment]
```
//logic/model:
  public async void Init()
        {        
            try
            {
                this.currentCustomer = await GetCustomerFromDatabase(1);
            }
            catch(Exception) {
                var error = "something went wrong ";
            }
            error= "";
        }

//data tier
private async Task<ProductList> GetCustomerFromDatabase(int customer)
 {
   var result = await wc.GetCustomer(customer);
   return result;
}
```
