### ISSUE TITLE
Product Update issue

### ISSUE THREAD

**Issue by sammydubai6** [XiaoFaye/WooCommerce.NET#120]
- Wordpress Version 4.7.4, 
- WooCommerce Version 3.0.3 and 
- WooCommerce.NET version 0.6.0

Hello,
    I am able to GET & POST the product. But when i tried to update product getting this error:405.
Method:  await wc.UpdateProduct(18, new Product { name = "test product 14" });  

- Error: The remote server returned an error: (405) Method Not Allowed.
Im trying to do simple update with given example in WooCommerece.NET

Any help would be greatly appreciated..

Thanks for your support,
Sam

**Comment by vbergara** [comment]
It seems like your server is configured to not accept POST/PUT methods (not sure wich is used to update the products). If your server is Windows/IIS then it's likely that the problem is related to WebDAV.
