### ISSUE TITLE
Value in Duth

### ISSUE THREAD

**Issue by teunlielu** [XiaoFaye/WooCommerce.NET#124]
in Country works with 12,50 ( comma) and not dot
Give verry high values. = 1250.
Bug fixed by:

        [OnSerializing]
        void OnSerializing(StreamingContext ctx)
        {

            NumberFormatInfo nfi = new NumberFormatInfo();
            nfi.NumberDecimalSeparator = ".";

            //AmountValue = Amount.ToString();

            foreach (PropertyInfo pi in GetType().GetRuntimeProperties())
            {
                PropertyInfo objValue = GetType().GetRuntimeProperties().FindByName(pi.Name + "Value");
                if (objValue != null)
                {
                    if (pi.PropertyType == typeof(decimal?))
                    {
                        if (pi.GetValue(this) != null)
                        {
                            decimal decvalue = decimal.Parse(pi.GetValue(this).ToString());

                            objValue.SetValue(this, decvalue.ToString(nfi));
                        }
                    }
                    else if (pi.PropertyType == typeof(DateTime?))
                    {
                        if (pi.GetValue(this) != null)
                            objValue.SetValue(this, ((DateTime?)pi.GetValue(this)).Value.ToString("yyyy-MMddTHH:mm:ss"));
                    }
                }
            }
        }

**Comment by XiaoFaye** [comment]
Can you please check this #113

**Comment by teunlielu** [comment]
your suggenstion better. i hvave me add
