### ISSUE TITLE
Suggestion for return value 

### ISSUE THREAD

**Issue by teunlielu** [XiaoFaye/WooCommerce.NET#125]
Your return now a string in the fuction of  WCObject:
is better to give the object of Woocommerce 
you works with te oject for next steps.
        
public async Task<Product> PostProduct(Product p, Dictionary<string, string> parms = null)
        {
            string json = await API.SendHttpClientRequest("products", RequestMethod.POST, p, parms);
            return API.DeserializeJSon<Product>(json);
        }

        public async Task<Product> UpdateProduct(int productid, Product p, Dictionary<string, string> parms = null)
        {
            string json = await API.SendHttpClientRequest("products/" + productid.ToString(), RequestMethod.PUT, p, parms);
            return API.DeserializeJSon<Product>(json);
        }

**Comment by XiaoFaye** [comment]
sounds reasonable, will add this changes in next version.

**Comment by XiaoFaye** [comment]
Source code of version 0.7.0 has been committed, however, I need to do more testing to release the new version in Nuget.

**Comment by teunlielu** [comment]
The sounds verry nice. Check your source. But nut testit.   Fory me is it close
