### ISSUE TITLE
How to GET meta_data of an order

### ISSUE THREAD

**Issue by ccvp** [XiaoFaye/WooCommerce.NET#127]
Wordpress Version 4.7.4,
WooCommerce Version 3.0.5
WooCommerce.NET Version 0.6.1 NUGET

Hello
Is there a way to receive the meta_data of an order? Referring to the official REST API documentation I should receive the meta_data as well:

```
"meta_data": [
    {
      "id": 13106,
      "key": "_download_permissions_granted",
      "value": "yes"
    }
  ],
```

Thank you...

**Comment by goguvi** [comment]
The meta_data is available with the v2 of the API (http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties).
Version 1 didn't have it (http://woocommerce.github.io/woocommerce-rest-api-docs/wp-api-v1.html#orders).

Currently the implemented API of WooCommerce for this library is V1.

**Comment by ccvp** [comment]
Thank you goguvi
So it seems like we have to wait for a version update from the author. Does somebody know when a new version will be released, that support the V2 API?

**Comment by goguvi** [comment]
the author said it'll be soon https://github.com/XiaoFaye/WooCommerce.NET/issues/115#issuecomment-299348976

**Comment by XiaoFaye** [comment]
Hi @ccvp , @goguvi ,  source code of version 0.7.0 has been committed, however, I need to do more testing to release the new version in Nuget.

**Comment by ccvp** [comment]
Thank you @XiaoFaye  
I can confirm that I'm receiving the property `meta_data` correctly with the latest version (0.7).
Looking forward to the next nuget release.
