### ISSUE TITLE
Featured image to external URL

### ISSUE THREAD

**Issue by thiagoteles** [XiaoFaye/WooCommerce.NET#129]
I`m trying to use a images collection of api (product.images) to create a batch import of images to my e-commerce but when I fill the src property the image is re-uploaded to /uploads/2017/... folder.

Exists any way to point the featured image to an external image using WooCommerce.NET without re-upload the image?

**Comment by XiaoFaye** [comment]
@thiagoteles  This is the way to do it:

![image](https://cloud.githubusercontent.com/assets/6334728/26137510/b429ab14-3b16-11e7-8c7d-0f78ea23a37f.png)
