### ISSUE TITLE
User's auth and items variations

### ISSUE THREAD

**Issue by MakarkinPRO** [XiaoFaye/WooCommerce.NET#13]
I want to cross your WooCommerce component with another WordPress. Does it'll work with WordPress auth correctly?

As well does it working properly with variable product in Cyrylic language?

**Comment by XiaoFaye** [comment]
1. What do you mean by Wordpress auth? the component works with WooCommerce REST API key and secret, does not need login.

2. Yes, it should work with all WooCommerce REST API resources regardless the language.

**Comment by MakarkinPRO** [comment]
By Auth I mean. When user going to Cart (he don't need enter Login Details again) and hist Address (and some custom_field) will be load from the server.

**Comment by XiaoFaye** [comment]
This component doesn't deal with login details, instead, with the correct  key and secret, it can access all resources that provide by WooCommerce REST API.
