### ISSUE TITLE
GetProducts Issue

### ISSUE THREAD

**Issue by JsonPowell** [XiaoFaye/WooCommerce.NET#131]
Wordpress Version: 4.7.4
WooCommerce Version: 2.6.14
WooCommerce.NET Version: 0.6.1

Seems to be a missmatch between the API docs and the actual data.
Docs state that the manage_stock property on the Product Variation is a Boolean, when in fact it is not.
If "Manage Stock" is checked in the admin for a variation, API returns True:
![image](https://cloud.githubusercontent.com/assets/25716628/26003374/cc988716-3732-11e7-9447-8d7cb61b0a6d.png)

If it is unchecked, the API returns "parent":
![image](https://cloud.githubusercontent.com/assets/25716628/26003318/a5d39198-3732-11e7-8f75-47a58b1452c0.png)

This causes a deserialising error when calling the GetProducts() method as the datatype for manage_stock is bool?

**Comment by XiaoFaye** [comment]
Yes, this has been a problem for a while, I'm thinking of changing the data type to object as WooCommerce  doesn't return a fixed data type value.

**Comment by XiaoFaye** [comment]
@JsonPowell  the data type for manage_stock property has been changed to object in the latest commit, you should not get this error anymore.

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.7.2
