### ISSUE TITLE
WooCommerce.Net 0.7 GetAll Issue

### ISSUE THREAD

**Issue by shawnvdb** [XiaoFaye/WooCommerce.NET#134]
When using the following:

`wc.Product.GetAll(New Dictionary(Of String, String)() From {{"page", iPage.ToString}, {"per_page", "100"}})`

I am getting the error:

Additional information: There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.Product, WooCommerceNET, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null]]. End element 'value' from namespace '' expected. Found element 'item' from namespace ''.

at 

T obj = (T)ser.ReadObject(stream);

I have attached below the JSON for the item its complaining about.

**Comment by XiaoFaye** [comment]
it seems the value in product meta doesn't be a string always, it can be a Dictionary as well. for now I can  change the data type of value to object, but the Dictionary values will be lost, string values will remain. If you have a better solution, please let me know.

**Comment by XiaoFaye** [comment]
@shawnvdb  the data type for value property has been changed to object in the latest commit, however, any non-string values might be lost when parsing json.
