### ISSUE TITLE
Order.GetAll() shipping_lines are wrong

### ISSUE THREAD

**Issue by ccvp** [XiaoFaye/WooCommerce.NET#135]
WooCommerce.NET Version 0.7.0

When I get all open orders like this with the V1: 
```
var orders = await wc.GetOrders(new Dictionary<string, string>()
{
   { "per_page", "30" },
   { "status", "on-hold" }
});
```
I get a list of orders including the property `shipping_lines` of type `ShippingLine`, which shows the shipping method.

When I do this request with the new version:
```
var orders = await wc.Order.GetAll(new Dictionary<string, string>()
{
  { "per_page", "30" },
  { "status", "on-hold" }
});
```
The property `shipping_lines` is of type `OrderShipping` and includes shipping information like address, name, city, etc.
Looks like there is a bug in the new version...

**Comment by XiaoFaye** [comment]
Thanks for reporting this, I will commit the changes tonight.

**Comment by XiaoFaye** [comment]
@ccvp  This has been fixed in the latest commit.
