### ISSUE TITLE
Coupon expiration date does not get updated.

### ISSUE THREAD

**Issue by novashorts** [XiaoFaye/WooCommerce.NET#136]
coupon expiry date returns nothing when retrieving a coupon. Also it does not set to anything when posting a coupon. 

Don't know if this is a rest api issue. using v2 of rest and the latest woocommerce.

WordPress 4.7.4
woocommerce Version 3.0.6
The version of woocommerce.net dll I used is 5.6.0 dated 3/24/2017. 

I really like what you have done with this wrapper.  Are you considering doing a wrapper for wordpress too?

**Comment by XiaoFaye** [comment]
It seems working fine to me, do you have more details?

![image](https://cloud.githubusercontent.com/assets/6334728/26082631/098afc40-3a25-11e7-9a11-8dfc1a03e3a6.png)

or you can download the latest code of wrapper, which supports v2 now.

no plans for wordpress now, might be in the future.

**Comment by novashorts** [comment]
I got it working using V1, V2 seems to have some of the methods like postcoupon missing in WC.

I did notice a bug though.  The amount of the coupon was set to decimal but I get and error back that it is expecting a string so I changed the code to the following and everything seems to work now.

        /// <summary>
        /// The amount of discount.
        /// </summary>
        [DataMember(EmitDefaultValue = false, Name = "amount")]
        private object amountValue { get; set; }

        public string amount { get; set; }

**Comment by XiaoFaye** [comment]
in V2 you can wcobject.Coupon.Add() to create a new coupon, I will update the readme file soon.

**Comment by novashorts** [comment]
Got it I will try that.
