### ISSUE TITLE
 GetProducts - The value '' cannot be parsed as the type 'Int32'.

### ISSUE THREAD

**Issue by SeanoNET** [XiaoFaye/WooCommerce.NET#138]
- **Wordpress version, WooCommerce version and WooCommerce.NET version**
WC version:		3.0.5
WP version:		4.7.5
WC database version:		3.0.5

- **Steps to replicate the issue**
Run GetProducts. For some reason, in some cases the stock_quantity on a variation returns a string.
`{
    "id": 0,
    "date_created": "2016-08-03T09:29:30",
    "date_modified": "2016-08-03T09:30:24",
    "permalink": "***",
    "sku": "***",
    "price": "64.95",
    "regular_price": "74.95",
    "sale_price": "64.95",
    "date_on_sale_from": "",
    "date_on_sale_to": "",
    "on_sale": true,
    "purchasable": true,
    "visible": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "tax_status": "none",
    "tax_class": "",
    "manage_stock": "parent",
    "stock_quantity": "",
    "in_stock": true,
    "backorders": "yes",
    "backorders_allowed": true,
    "backordered": false,
    "weight": "1.5",
    "dimensions": {
        "length": "21",
        "width": "21",
        "height": "18.5"
    },
    "attributes": []
}`

- **Details of the error message if there is any**
There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Product, WooCommerceNET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. The value '' cannot be parsed as the type 'Int32'.

- **Fix**
` /// <summary>
/// Stock quantity. If is a variable variation this value will be used to control stock for all variations, unless you define stock at variation level.
/// </summary>
        [DataMember(EmitDefaultValue = false)]
        public object stock_quantity { get; set; }`

This should be raised in WooCommerce github, the API doesn't operate according to their documentation.

> stock_quantity	integer	Stock quantity. If is a variable variation this value will be used to control stock for all variations, unless you define stock at variation level.

**Comment by XiaoFaye** [comment]
@SeanoNET You are right, their API doesn't operate according to their documentation. This has been a problem since legacy API, still happening in the latest v2 API. I have to do workarounds to prevent errors in the wrapper.

**Comment by XiaoFaye** [comment]
@SeanoNET Could you please try version 0.7.2?

**Comment by SeanoNET** [comment]
@XiaoFaye i have implemented a fix, i will try this new version in the near future. Thanks.
