### ISSUE TITLE
ShippingLine V2 missing in Nuget 0.7.0

### ISSUE THREAD

**Issue by ccvp** [XiaoFaye/WooCommerce.NET#139]
Thank you @XiaoFaye for updating the nuget package.
I have successfully upgraded the nuget package to the latest version (0.7.0). I have noticed that `ShippingLine` is missing in the v2 version (see picture below).

![image](https://cloud.githubusercontent.com/assets/16879023/26188510/dd91e5fa-3b9f-11e7-8d46-f482680e7a64.png)

Can you verify this?

**Comment by XiaoFaye** [comment]
It's called OrderShippingLine now.

**Comment by ccvp** [comment]
You're right. Sorry for bothering you...

**Comment by XiaoFaye** [comment]
@ccvp  that's fine :)
