### ISSUE TITLE
Legacy API and latest version of API give different results

### ISSUE THREAD

**Issue by dandersson79** [XiaoFaye/WooCommerce.NET#14]
When calling GetAllCategories(), I get the full list using the Legacy API (v3), but only a limited set from the v1 of the latest API (10 out of 18 categories).
Any idea what the problem might be?

**Comment by XiaoFaye** [comment]
As far as I know, it will always return the first 10 items unless you have specified a limit filter.

**Comment by dandersson79** [comment]
Indeed, that was the explanation.
For my filter, I added "per_page" with a value 100 and then I got everything.
Many thanks for your quick and great help!

**Comment by JM63** [comment]
I am having the same problem I am trying to build the filter as follows 
 
var ps = new Dictionary<string, string>() {
                { "filter[limit]", "100" }
            };
var listCategories = await wc.GetProductCategories(ps);

What am I doing wrong? You can show how you build you the filter.

Thanks!

**Comment by XiaoFaye** [comment]
By the below official doc, I don't think the "limit" or "equal" filters are avaliable for product category, however "search" and "per_page" will meet your needs.

http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-product-categories

**Comment by dandersson79** [comment]
I used the "per_page" function to filter, that was the quickest way for me. So, using your example, my code would look like this:
var ps = new Dictionary() {
{ "per_page", "100" }
};
var listCategories = await wc.GetProductCategories(ps);

I used the same concept for product tags as well
