### ISSUE TITLE
First Chance Exception when Serializing

### ISSUE THREAD

**Issue by piotrgulbis** [XiaoFaye/WooCommerce.NET#140]
I have an object in the Product Meta Data value  instead of a string and when posting the Product I get a A first chance exception of type 'System.Runtime.Serialization.InvalidDataContractException'.

I replaced your SerializeJSon<T>(T t) function contents with a Newtonsoft JSON.NET function:

return JsonConvert.SerializeObject(t);

Now it works. Don't know if this is the best solution but it works :)

**Comment by XiaoFaye** [comment]
I'm thinking of using JSON.NET in the future version, however, as the WooCommerce API doesn't always return json as its specification, there might still be some workarounds to do.

Have you set DataContract attribute for your object? and DataMember attribute for its properties? If all set, it should be fine.

**Comment by piotrgulbis** [comment]
Do you see any problems using JSON.NET for the serialization portion as it is now? I've tried with products, customers and categories (adding, removing and updating) and it ran through everything okay...

I did set DataContract for classes and DataMember attributes for all properties.

**Comment by XiaoFaye** [comment]
I will have a look and see if JSON.NET works fine.

**Comment by XiaoFaye** [comment]
@piotrgulbis  You can use JSON.NET now, please see the wiki pages.
