### ISSUE TITLE
wc.GetOrder.GetAll / Get

### ISSUE THREAD

**Issue by markldavison** [XiaoFaye/WooCommerce.NET#141]
Trying to migrate to WooCommerce.NET 0.7.0.

When I call:

Dim orderslist as List(of [Order]) = Await wc.Order.GetAll(dict)

I get the response:

"There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.Order, WooCommerceNET, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null]]. End element 'value' from namespace '' expected. Found element 'item' from namespace ''."

The same problem with Order.Get(x) which gives the message:

"There was an error deserializing the object of type WooCommerceNET.WooCommerce.v2.Order. End element 'value' from namespace '' expected. Found element 'refundable_txns' from namespace ''."

**Comment by XiaoFaye** [comment]
Can you send the json so I can have a look?

**Comment by markldavison** [comment]
Hi,

As the JSON contains order information, can I email to you directly without posting onto the forum?



Kind Regards,

Mark Davison
The ID Band Company
www.theidbandco.com<http://www.theidbandco.com/>
0845 269 4523

**Comment by XiaoFaye** [comment]
sure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markldavison** [comment]
Sorry, what is your email address?

**Comment by markldavison** [comment]
Here is the JSON from an order. If you need the one from the all orders then I can get that as well. I have stripped out name and address information.

[orders.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/1011456/orders.txt)

**Comment by XiaoFaye** [comment]
This is due to the value type in the OrderMate, change it from string to object will fix the error, however, the extra meta information will not show. 

I will try to use JSON.NET in the next version and see if the extra meta information will show correctly.

**Comment by XiaoFaye** [comment]
@markldavison  Please check the wiki pages for solution to this.

**Comment by markldavison** [comment]
Perfect! Thank you for the quick work.

Kind Regards,

Mark Davison
The ID Band Company
http://www.theidbandco.com
0845 2694523

On 20 May 2017, at 06:12, James Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


@markldavison<https://github.com/markldavison> Please check the wiki pages for solution to this.

**Comment by markldavison** [comment]
This is now working really well. Thank you for the continued support.

**Comment by markldavison** [comment]
I am still struggling with this for products. I am working in VB.net and I am struggling with step 3 of the wiki page (handle different types...). Has anyone taken this to vb.net yet? All the data I need is in the meta date and this is what I am not able to get. If I use the original RestAPI object I do not get the meta data at all. If I use JSON.net and MyRestAPI as per the instructions I get an error trying to deserialise the meta data.

I am following the instructions to "Define a MetaValueProcessor for V2 WCObject.". Where am I doing this? I have translated the code to VB but then struggle with where to put this and with the "WCObject.MetaValueProcessor = ProcessMetaValue;".

Does anyone have any examples of this new implementation in vb.net?

**Comment by XiaoFaye** [comment]
@markldavison  have a look here: https://msdn.microsoft.com/en-us/library/018hxwa8(v=vs.110).aspx?cs-save-lang=1&cs-lang=vb#code-snippet-2

**Comment by markldavison** [comment]
Thanks.
