### ISSUE TITLE
GetCustomer Meta Data can also return value other than string

### ISSUE THREAD

**Issue by piotrgulbis** [XiaoFaye/WooCommerce.NET#142]
changing the type of the value to object fixes this problem.

I image the same will be true for any other Meta Data properties.

**Comment by XiaoFaye** [comment]
The problem is that meta data doesn't return a fixed type value, change to object will bypass the error, however, the meta data will not show correctly.

**Comment by XiaoFaye** [comment]
@piotrgulbis Please check the wiki page for the solution.

**Comment by piotrgulbis** [comment]
@XiaoFaye Thank you! Will begin testing today.

**Comment by piotrgulbis** [comment]
Works perfectly thanks Xiao!
