### ISSUE TITLE
Add.Product : The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by shawnvdb** [XiaoFaye/WooCommerce.NET#143]
Firstly, the orders works fine, now I am again testing the products.

When I try add a product, Product.Add using the v2 api I get a Bad Request Error at 

`var response = (HttpWebResponse)request.EndGetResponse(iar);`

Additional information: The remote server returned an error: (400) Bad Request.

Stacktrace:

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at WooCommerceNET.Base.Extension.<>c__DisplayClass2_0.<GetResponseAsync>b__0(IAsyncResult iar) in C:\Dev\WooCommerce.NET-master\WooCommerce.NET-master\Base\Extension.cs:line 55

**Comment by XiaoFaye** [comment]
Adding product will not use any methods under WooCommerceNET.WooCommerce.v2.Extension, can you please show me your code?

**Comment by shawnvdb** [comment]
Dim p As New Product
                            Dim a As New ProductAttributeLine()
                            Dim img As New WooCommerceNET.WooCommerce.v2.ProductImage

                            a.name = "DistributorCode"
                            a.options = New List(Of String)
                            a.options.Add(Tag)
                            a.visible = False

                            p.attributes = New List(Of ProductAttributeLine)
                            p.attributes.Add(a)
                            p.regular_price = Price
                            p.name = ProductName
                            p.sku = DistributorCode
                            p.status = "draft"
                            p.images = New List(Of ProductImage)

                            img.name = WooDefaultImageName
                            img.date_created = Now
                            img.date_modified = Now
                            img.src = WooDefaultImage
                            img.id = WooDefaultImageID
                            img.alt = WooDefaultImageName
                            img.position = 0

                            p.images.Add(img)
                            p.in_stock = True
                            p.reviews_allowed = False

                            Dim NewProduct As Product = Await wc.Product.Add(p).ConfigureAwait(False)

**Comment by XiaoFaye** [comment]
You need to add the attribute to wc first, then assign it to a product.
try wc.Attribute.Add(xx);

**Comment by shawnvdb** [comment]
This code was working with the previous version. Its the same as adding a custom product attribute in WooCommerce.

**Comment by XiaoFaye** [comment]
It seems there is a bug in the latest version of WooCommerce, the price has to passed as a string in the json. Can you try to remove the line **p.regular_price = Price** and see if it's working?

**Comment by shawnvdb** [comment]
Yip, that fixed the error.

**Comment by shawnvdb** [comment]
I am also testing my product update and getting the same error and I am not setting the price. I will see if I can track the culprit.

**Comment by sotiristsogkos** [comment]
First of all Great Job on this dll ! Very helpfull!!! also same error on sale_price. Field price does not create an error but isn't saved anywhere on woocommerce product. Is there an estimated time for new version?

**Comment by XiaoFaye** [comment]
@sotiristsogkos there will be a new version in the weekend, however, this looks like a WooCommerce bug.

**Comment by shawnvdb** [comment]
It could be because WooCommerce stores prices as strings?

**Comment by XiaoFaye** [comment]
that shouldn't have changed as v1 is working fine, looks like v2 handles price fields in a different way.

**Comment by shawnvdb** [comment]
So to follow on, when updating I get the following error. I am not setting the price, the price is already set.

Additional information: {"code":"rest_invalid_param","message":"Invalid parameter(s): regular_price","data":{"status":400,"params":{"regular_price":"regular_price is not of type string."}}}

**Comment by shawnvdb** [comment]
So look like v1 is best for products and v2 for orders :)

**Comment by XiaoFaye** [comment]
it seems regular_price becomes a required field now, even you don't need it, you have to pass it in the JSON string. Something must be wrong here. 
Do you mind open an issue on the woocommerce side? I have to go to bed now...

**Comment by shawnvdb** [comment]
Where exactly does one open a ticket for the API?

**Comment by XiaoFaye** [comment]
@shawnvdb  

> So to follow on, when updating I get the following error. I am not setting the price, the price is already set.
 Additional information: {"code":"rest_invalid_param","message":"Invalid parameter(s): regular_price","data":{"status":400,"params":{"regular_price":"regular_price is not of type string."}}}

For this error, can you try to use jsonSerializeFilter and add **"regular_price": ""** to the json string, see if it's working.

**Comment by shawnvdb** [comment]
I am away for the next 8 days, so only be able to look at this again then unfortunately.

**Comment by jeffreyleblanc225** [comment]
Has anyone got an update on this issue? I'm trying to do what you said

@XiaoFaye 
But I'm having some issue understanding how exactly I would do the adding regular_price. Thanks.

**Comment by XiaoFaye** [comment]
@jeffreyleblanc225 This issue should have been fixed in the latest code, can you download the latest code and try again? The nuget package is not update-to-date.

**Comment by jeffreyleblanc225** [comment]
Is it possible for you to update the nuget package and/or make it target a
.netstandard  target? I'm trying to use this in .netcore

**Comment by XiaoFaye** [comment]
@jeffreyleblanc225 I'm trying to release a new version early next month.

**Comment by sterenas** [comment]
@XiaoFaye Brilliant work on this project! Quick question, as is, I'm not really able to create/update a SKU since regular price and dimensions attributes generate errors.  Creating a SKU with no regular price is really missing one of the most important parts of the automation (I understand I can create a SKU and manually update its price within WooCommerce).
Are you working on a fix and if so do you have an estimated date to make it public?
Thanks!
Sergio

**Comment by XiaoFaye** [comment]
@sterenas Please give a try on the latest version 0.7.2
