### ISSUE TITLE
Problem deserializing Product Category Image with JSON.NET

### ISSUE THREAD

**Issue by piotrgulbis** [XiaoFaye/WooCommerce.NET#144]
Getting the following error when using Product.GetAll :

> Additional information: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'tboswebshop.WooCommerce.v2.ProductCategoryImage' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
> 
> To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
> 
> Path '[0].image', line 1, position 128.

**Comment by piotrgulbis** [comment]
I think it may have something to do with me adding:

` public class ProductCategoryBatch : BatchObject<ProductCategory> { }`

to ProductCategory.cs so that I could use Categories as Batch. We have to transfer 800-1000 Product Categories so Batch makes sense here too.

**Comment by piotrgulbis** [comment]
Changed:
        public ProductCategoryImage image { get; set; }
to:
        public ProductCategoryImage images { get; set; }

**Comment by XiaoFaye** [comment]
@piotrgulbis  do you mean the official doc is incorrect? image should be images?

![image](https://cloud.githubusercontent.com/assets/6334728/26325562/7bfcaa88-3f8b-11e7-8d0d-4cc8d31f8925.png)

**Comment by piotrgulbis** [comment]
I'm not sure. If I leave it as image then I get the above exception, if I change it to images, then it works. It may be something else I am doing in my code though... I will double check.

**Comment by XiaoFaye** [comment]
The PHP source code shows "image", can you check again?

![image](https://cloud.githubusercontent.com/assets/6334728/26442909/92946ed8-418a-11e7-9f4f-62818ab770a7.png)
