### ISSUE TITLE
Ability to use Rest Api with plugins

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#145]
WooCommerce authentification allows third party extensions to use theirs auth methods 

You can see this behabiour here (code extracted from 'class-wc-rest-authentication.php'):
```
	/**
	 * Check if is request to our REST API.
	 *
	 * @return bool
	 */
	protected function is_request_to_rest_api() {
		if ( empty( $_SERVER['REQUEST_URI'] ) ) {
			return false;
		}

		$rest_prefix = trailingslashit( rest_get_url_prefix() );

		// Check if our endpoint.
		$woocommerce = ( false !== strpos( $_SERVER['REQUEST_URI'], $rest_prefix . 'wc/' ) );

		// Allow third party plugins use our authentication methods.
		$third_party = ( false !== strpos( $_SERVER['REQUEST_URI'], $rest_prefix . 'wc-' ) );

		return apply_filters( 'woocommerce_rest_is_request_to_rest_api', $woocommerce || $third_party );
	}
```
I was able to use WooCommerce.NET with plugin endpoints in the previous realese, but I've update to version 0.7.1 and now I'm getting "Unknow WooCommerce Restful API version.".

I've comment the Exception line and all seems to work correctly. 

I know that this error has nothing to do with the purpose of this repository.
It would be great if you can adapt the code to allow this, but I'll change the auth method for extensions if you can't.

**Comment by XiaoFaye** [comment]
Can you give me an example what third-party endpoints look like?

**Comment by goguvi** [comment]
for example: http://www.example.com/wp-json/wc-conectadelsol/v1/upload-file

**Comment by XiaoFaye** [comment]
@goguvi Please help to test this with version 0.7.2

**Comment by goguvi** [comment]
Sorry for the late reply I have been busy and I have not been able to test  0.7.2 changes.
Apparently everything works correctly with the plugin.
Thank you @XiaoFaye
