### ISSUE TITLE
Getproducts ( I can't deserilize the object) Iv been stuck for day

### ISSUE THREAD

**Issue by digital1989** [XiaoFaye/WooCommerce.NET#146]
Getproducts ( I can't deserilize the object) Iv been stuck on it for days. 

### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by XiaoFaye** [comment]
I can't help you unless you provide more details.

**Comment by digital1989** [comment]
WP - Version 4.7.5, Woocommerce - Version 3.0.7
Thank you for the speedy responce!

I am pretty new to this. I have used the follwing to get all products, which i can see it had done but i cant deserilize it to a listbox in my windows form. What other info do you require and i will round it up.

var products = await wc.Product.GetAll();
Product response = JsonConvert.DeserializeObject<Product>(products.ToString());

Im not sure where to go from here.

Nick

**Comment by piotrgulbis** [comment]
You're trying to deserialize a string that you created from a Products Object.

JsonConvert requires a JSON formatted string.

GetAll will return a List of Product Objects, you will need to go through each of these using a loop and parse them that way.

I suggest you read through some C# List tutorials and also read the JSON.NET documentation.
