### ISSUE TITLE
WooCommerce Prices

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#147]
- Wordpress version: Versión 4.7.5 | WooCommerce version: 3.0.7 | WooCommerce.NET version: 0.7.1

First Product price is serialized wrong. 
This code:
```
WooCommerceNET.WooCommerce.v2.Product p = new WooCommerceNET.WooCommerce.v2.Product()
{
      name = "test product 8",
      description = "test product 8",
      regular_price = 8.0M,
      type = "variable",
};
```
Is serialized as:
`{"description":"test product 8","name":"test product 8","regular_price":80,"type":"variable"}`

"regular_price" is not a string, so API return an error:
{"regular_price":"regular_price is not of type string."}

--------------------------------------------
Second I think WooCommerceNET.WooCommerce.v2.Variation should inherit from JsonObject because the following code: 
```
WooCommerceNET.WooCommerce.v2.Variation p1 = new WooCommerceNET.WooCommerce.v2.Variation()
{
    description = "test product 8",
    regular_price = 9.0M
};
```
gets serialized as `{"description":"test product 8"}`. As you can see regular_price is missing

--------------------------------------------

Third I was using an inherited class of WooCommerceNET.WooCommerce.v1.Product with custom properties. Something like:
```
public class WCProduct : WooCommerceNET.WooCommerce.v1.Product
{
  ......
}
```

When serializing, the code `GetType().GetRuntimeProperties().FindByName(pi.Name + "Value")` returns null for regular_price because  GetRuntimeProperties() doesn't have regular_priceValue property.

**Comment by piotrgulbis** [comment]
regular_price is defined as a string in the Woocommerce REST API. So it's not serializing wrong, you are passing the wrong type.

**Comment by goguvi** [comment]
@piotrgulbis 
Yes, regular_price should be serialized as string. 
Is serialized as string because regular_price is decimal? so regular_priceValue is set as decimal too at JsonObject:
  ```
if (pi.PropertyType == typeof(decimal?))
 {
      if (pi.GetValue(this) != null)
           objValue.SetValue(this, decimal.Parse(pi.GetValue(this).ToString(), CultureInfo.InvariantCulture));
}
```

I think it should serialize as string if you do this: 
```
WooCommerceNET.WooCommerce.v2.Product p = new WooCommerceNET.WooCommerce.v2.Product()
{
        name = "test product 8",
        description = "test product 8",
        regular_price = 8.0M,
        type = "variable",
};
p = await wcV2.Product.Add(p);
```

Could you please show me how you convert the decimal value to a string.

**Comment by XiaoFaye** [comment]
@goguvi @piotrgulbis It seems in v2, they have changed all price values to string to prevent null or empty string issue in previous versions, I will make the necessary changes ASAP.

**Comment by goguvi** [comment]
Thanks @XiaoFaye.

Until you check the code I have put this in JsonObject as a temporary workaround:
```
if (pi.Name.Equals("regular_price"))
{
   if (pi.GetValue(this) != null)
      objValue.SetValue(this, (pi.GetValue(this) as decimal?).Value.ToString(CultureInfo.InvariantCulture));
}
```

The second point is resolved by https://github.com/XiaoFaye/WooCommerce.NET/commit/e1c75caba88580a29268806cafda9b6fae8a1d62.

It seems that third point could be resolved changing WooCommerceNET.WooCommerce.v1.Product private properties to protected. I don't know if there is a better way to do it.

**Comment by hikarushin** [comment]
@goguvi , can you send me the full code for JsonnObject? I don't know where to put that. I'm still having the 
```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): regular_price",
  "data": {
    "status": 400,
    "params": {
      "regular_price": "regular_price is not of type string."
    }
  }
}
```

**Comment by goguvi** [comment]
@hikarushin If you update to last version of the repository it should solve your problem since pull request  #156 was merged

**Comment by hikarushin** [comment]
@goguvi, yup. Already did and it's working now. Thanks.

**Comment by goguvi** [comment]
The first and second points have been resolved. So I'll close this thread an open another one with third point.
