### ISSUE TITLE
Batch with V1

### ISSUE THREAD

**Issue by jerryxcoke** [XiaoFaye/WooCommerce.NET#15]
Try to use V1 (new REST API version), but UpdateProducts is not working
```
 public async Task<string> UpdateProducts(Product[] ps, Dictionary<string, string> parms = null)
        {
            return await API.SendHttpClientRequest("products/batch", RequestMethod.PUT, ps, parms);
        }
```
response with empty json, because batch waiting something like this:

````
var data = {
  create: [
    {
      name: 'Woo Single #1',
    },
    {
      name: 'New Premium Quality',
      type: 'simple',
      regular_price: '21.99',     
    }
  ],
  update: [
    {
      id: 165,
      variations: [
        {
          id: 170,
          regular_price: '29.99'
        },
        {
          id: 172,
          regular_price: '29.99'
        }
      ]
    }
  ],
  delete: [
    162
  ]
};`
```
But there are only **Products** in the request body

Thank you if you will fix this.

**Comment by XiaoFaye** [comment]
Thanks for letting me know the issue, it has been fixed now. example code as below:

`

            CustomerBatch cb = new CustomerBatch();

            CustomerList create = new CustomerList();
            create.Add(new Customer()
            {
                first_name = "first",
                last_name = "last",
                email = "first@lastsss.com",
                username = "firstnlast",
                password = "12345"
            });

            CustomerList update = new CustomerList();
            update.Add(new Customer()
            {
                id = 4,
                last_name = "xu2"
            });

            List<int> delete = new List<int>() { 8 };
            cb.create = create;
            cb.update = update;
            cb.delete = delete;
            var c = await wc.UpdateCustomers(cb);
`

**Comment by jerryxcoke** [comment]
Thank you!

**Comment by mk0808** [comment]
Hi, 
Can you update library in Nuget? 
Thank you ;)

**Comment by XiaoFaye** [comment]
It's in Nuget now. :)
