### ISSUE TITLE
Getting back the created Product,Category,Customer etc with ID

### ISSUE THREAD

**Issue by athsk** [XiaoFaye/WooCommerce.NET#153]
- WordPress 4.7.5, WooCommerce version 3.0.6 and WooCommerce.NET version 0.7.0

I am creating products, and categories and customers as in the eamples. I need to know the new product's id to store it in local database. Now I am creating the product and then getting it using the SKU.

```
Product p = new Product();
p.name="name";
p.sku="thissku";
await wc.PostProduct(p);

//then get it back
 var newproduct = await wc.GetProducts(new Dictionary<string, string>() {{ "sku", p.sku }});

```
Is it possible when the product is created to give me back a the created product with id?

Also the filtering does not work whith categories. When i do this it returns all the categories.
 ```
var filter = new Dictionary<string, string>() { { "name", cat.name } };
 var products = await wc.GetProductCategories(filter);
```

**Comment by goguvi** [comment]
Try this:

```
Product p = new Product();
p.name="name";
p.sku="thissku";
string json = await wc.PostProduct(p);

Product returnProduct = rest.DeserializeJSon<Product>(json);
var product_id = returnProduct.id.Value;
```

**Comment by athsk** [comment]
Thank you.  This works like a charm!!
