### ISSUE TITLE
Creating an authentication endpoint URL. Response is either HTML or 404?

### ISSUE THREAD

**Issue by yash5596** [XiaoFaye/WooCommerce.NET#154]
I cant get the authentication endpoint URL implemente in the WooCommerce.NET?
While I tried to do it myself....Directly appending the "/wc-auth/v1/authorize" responds with 404.
and the other url i tried was through the wordpress admin  /wp-admin/admin.php/wc-auth/v1/authorize but it provides me with the Wordpress Admin Login Page! I dont know how to move further.

Completely newbie to this. Kindly let me know how can I implement this. Please provide any code references if available!
Thanks.

**Comment by XiaoFaye** [comment]
I don't think this is how the url looks like, any details?
