### ISSUE TITLE
Assign a product to a category in woocommerce v2

### ISSUE THREAD

**Issue by MartaSilvaLlobera** [XiaoFaye/WooCommerce.NET#158]
- Wordpress version: 4.6.6, WooCommerce version: 2.6.13 and WooCommerce.NET version: 0.7.1

Hi,

I am trying to assign an existing category to a product, but just let me assign the product to a "ProductCategoryLine". What is a "ProductCategoryLine"? How can I assign a "ProductCategory" to a product?

```
Dim _Product As WooCommerce.v2.Product
Dim _Category As WooCommerce.v2.ProductCategory
_Product.categories.Add(_Category) 
```

This code does not work since in the last line it requests a "ProductCategoriLine"

Thanks!

**Comment by goguvi** [comment]
I haven`t test it, but it should be something like:
```
Dim _Product As new WooCommerce.v2.Product
Dim lstCat As new List<ProductCategoryLine>();
_Product.categories = lstCat
Dim _Category As new WooCommerceNET.WooCommerce.v2.ProductCategoryLine
Category.id = <YOUR CATEGORY ID HERE>
_Product.categories.Add(_Category) 
```

**Comment by MartaSilvaLlobera** [comment]
Hi, thanks for the quick response. This is my code

```
 Dim _Product As WooCommerce.v2.Product = Await wc.Product.Get(49068)
 Dim lstCat As New List(Of ProductCategoryLine)
  _Product.categories = lstCat
 Dim _CategoryLine As New WooCommerceNET.WooCommerce.v2.ProductCategoryLine
 _CategoryLine.id = 6
 _Product.categories.Add(_CategoryLine)
 Await wc.Product.Update(49068, _Product)
```

Does not give any compilation error, but when executing the code appears the following error in the last line of code

> {"code":"rest_invalid_param","message":"Par\u00e1metro(s) no v\u00e1lido(s): backorders","data":{"status":400,"params":{"backorders":"backorders no es ninguna de las siguientes no, notify, yes."}}}

What is happening? Thanks!

**Comment by goguvi** [comment]
I've try the following code and It seems to work:

```
Product pWoo = new Product();

pWoo.categories  = new List< ProductCategoryLine>();
WooCommerceNET.WooCommerce.v2.ProductCategoryLine _CategoryLine = new WooCommerceNET.WooCommerce.v2.ProductCategoryLine();
 _CategoryLine.id = 59;
 pWoo.categories.Add(_CategoryLine);
try
 {
         var pWooResult = await wcV2.Product.Update(codWeb, pWoo);
}
catch (Exception ex)
{
          throw ex;
 }
```
The only problem I can guess is that you are first getting all the data of the product:
` Dim _Product As WooCommerce.v2.Product = Await wc.Product.Get(49068)`

This is not necessary, the API will ONLY update the data you set, the remaining data will not change. So try without this.

**Comment by goguvi** [comment]
@MartaSilvaLlobera Have you test it without getting the product first?

**Comment by MartaSilvaLlobera** [comment]
Hello,

Thanks for all your help, I managed to make the code I needed thanks to you.

Thanks for everything @goguvi !
