### ISSUE TITLE
cant connect to rest api and there is not excecption being thrown

### ISSUE THREAD

**Issue by egarim** [XiaoFaye/WooCommerce.NET#163]
woocommerce 3.0.7
wordpress 4.7.5
WooCommerce.NET version: 0.7.1

Hi have been trying to connect to woocommerce  rest using the csharp nuget version 0.7.1.0 and i never get a response  the code basically do nothing, i have  been able to connect to the api using the php client but not with c#, i know the secret and the key are good. I have try to debug the  source of the nuget and on the class rest api  on the line 143 just exit the code without any exception

this is the line that have the problem
                // asynchronously get a response
                WebResponse wr = await httpWebRequest.GetResponseAsync();

any idea how can I fix this problem

**Comment by XiaoFaye** [comment]
Can you put some of your code here?

**Comment by egarim** [comment]
im using the example that you posted on the main page
