### ISSUE TITLE
Extended Product serialize error

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#165]
I was using an inherited class of WooCommerceNET.WooCommerce.v1.Product with custom properties. Something like:
```
public class WCProduct : WooCommerceNET.WooCommerce.v1.Product
{
  ......
}
```
With an extented WCObject:

```
   public class WCObjectEx: WooCommerceNET.WooCommerce.v1.WCObject<Coupon, Customer, WCOrder, OrderNote, OrderRefund, WCProduct, WCProductCategory,
                                    ProductAttribute, ProductAttributeTerm, ShippingClass, ProductTag, TaxRate, TaxClass, Webhook>
    {
        public WCObjectEx(RestAPI api) : base(api)
        {

        }

    }
```

When serializing, the code `GetType().GetRuntimeProperties().FindByName(pi.Name + "Value")` returns null for regular_price because  GetRuntimeProperties() doesn't have regular_priceValue property.

Apparently if I change the `___Value` properties from private to protected everything works correctly.

**Comment by XiaoFaye** [comment]
You are correct, it should be a protected property. Thanks for pointing this out.

**Comment by goguvi** [comment]
Ok, I've added the change to pull request #164
