### ISSUE TITLE
Cannot connect to woocommerce

### ISSUE THREAD

**Issue by AndrewZb** [XiaoFaye/WooCommerce.NET#17]
Write code like this

` RestAPI rest = new RestAPI("http://www.simplegames.com.ua/wp-json/wc/v1/", "ck_f03bbd67e26a96604ddb188dbd63be3d252891ab", " cs_f8583f42dd1d75da832574b7ad6e649a0687f88f");

                WCObject wc = new WCObject(rest);
                //Get all products
                var products = await wc.GetProducts();

                Debug.WriteLine(products);`

and have this error

[http://i.stack.imgur.com/7d0cD.png](url)

**Comment by jerryxcoke** [comment]
Need woocommerce  2.6.x. 
Enable wc rest api in admin page

**Comment by AndrewZb** [comment]
Hello!
My WC version is 2.6.3 and I am already activated REST API in the WC settings page.

Now I have this kind of error:

An exception of type 'System.Exception' occurred in WooCommerceNET.dll but was not handled in user code Additional information: You need to use the legacy WCObject on the legacy version of WooCommerce Restful API.

**Comment by XiaoFaye** [comment]
are you still using url as "http://www.simplegames.com.ua/wp-json/wc/v1/"?

**Comment by AndrewZb** [comment]
Hello, XiaoFaye!
Here you are:

RestAPI rest = new RestAPI("http://simplegames.com.ua/wc-api/v3", "ck_9d64c027d2c5f81b8b*****", "cs_60697b1e6cbdeb8d62d19**********");
                //WCObject wc = new WCObject(rest);
                WCObject wc = new WCObject(rest);
                //Get all products
                var products = await wc.GetProducts();


                Debug.WriteLine(products);
---------------
I changed keys.

**Comment by XiaoFaye** [comment]
***/wc-api/v1, ***/wc-api/v2, ***/wc-api/v3 are legacy restful api, you need to use the WCObject under WooCommerceNET.WooCommerce.Legacy namespace.

**Comment by AndrewZb** [comment]
Done.


Have this now.

`An exception of type 'System.Exception' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: {"errors":[{"code":"woocommerce_api_no_route","message":"\u041d\u0435 \u0437\u043d\u0430\u0439\u0434\u0435\u043d\u043e \u043c\u0430\u0440\u0448\u0440\u0443\u0442\u0443, \u0449\u043e \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0430\u0454 \u043f\u043e\u0441\u0438\u043b\u0430\u043d\u043d\u044e \u0442\u0430 \u0437\u0430\u043f\u0438\u0442\u0443\u0432\u0430\u043d\u043e\u043c\u0443 \u043c\u0435\u0442\u043e\u0434\u0443."}]}`



Have this now

**Comment by XiaoFaye** [comment]
Could you please send me the keys so I can test it?   please send to xiaofaye@msn.com

**Comment by AndrewZb** [comment]
I sent you keys

**Comment by XiaoFaye** [comment]
not receive anything, I have checked the junk as well.

**Comment by AndrewZb** [comment]
Maybe error in pretty permalinks?

**Comment by XiaoFaye** [comment]
Pretty permalinks in Settings > Permalinks so that the custom endpoints are supported. Default permalinks will not work.

Can you check this ?

**Comment by AndrewZb** [comment]
I will check now

**Comment by AndrewZb** [comment]
I need to write custom permalink in Settings?

**Comment by AndrewZb** [comment]
http://s011.radikal.ru/i318/1608/fc/8a741846ebc4.png

**Comment by XiaoFaye** [comment]
the one with post name will be fine.

**Comment by AndrewZb** [comment]
You talk about CommonSettings - Post name?

**Comment by XiaoFaye** [comment]
yes, the one you have selected in your pic.

**Comment by AndrewZb** [comment]
Okay. So I need to leave it how it on pic?


What url I need to write in C# code? To recieve products

**Comment by XiaoFaye** [comment]
RestAPI rest = new RestAPI("http://www.simplegames.com.ua/wp-json/wc/v1/", "ck_9d64c027d2c5f81b8bed3342eeccc6d337be8xxx", "cs_60697b1e6cbdeb8d62d19e0765e339f8e3334xxx");
WCObject wc = new WCObject(rest);
var c = await wc.GetProducts();

**Comment by AndrewZb** [comment]
Has this now.

```
An exception of type 'System.Exception' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: {"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}
```




Sorry that I take you time, but can you test it on your pc?

**Comment by XiaoFaye** [comment]
I have tried many times in different ways, it always gives me the woocommerce_rest_authentication_error. I'm thinking the error might be in WooCommerce itself, which I can do any testing on my side.

Can you try to use the php library below and see if you will get the same error?
https://packagist.org/packages/automattic/woocommerce

**Comment by AndrewZb** [comment]
I will

**Comment by AndrewZb** [comment]
Maybe htacess blocking http queries?

**Comment by XiaoFaye** [comment]
can you temporary disable the htaccess and try the above code again?

**Comment by AndrewZb** [comment]
After disabling htacess

`Additional information: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`


I will try wrapper.

I need to add wrapper to website?

**Comment by XiaoFaye** [comment]
no need, just run it as an independent php website and fill out all necessary parameters.

**Comment by AndrewZb** [comment]
okay.

Thank's I will try and then write about results

**Comment by AndrewZb** [comment]
Hello again.


We found trouble with permalinks, we have this one `/shop/%product_cat%/` and changed it to this one `/product/sample-product/`


It connected but now I have this error


Additional information: There was an error deserializing the object of type WooCommerceNET.WooCommerce.ProductList. Encountered unexpected character '<'.

**Comment by AndrewZb** [comment]
When I write GetOrders();

It all okay

**Comment by XiaoFaye** [comment]
I'm still getting the woocommerce_rest_authentication_error with the keys you gave me .

**Comment by AndrewZb** [comment]
I make it like this 
`RestAPI rest = new RestAPI("http://simplegames.com.ua/wp-json/wc/v1/", "ck_9d64c027d2c5f81b8bed3342eeccc6d337be813d", "cs_60697b1e6cbdeb8d62d19e0765e339f8e3334754");
 WCObject wc = new WCObject(rest);
                //Get all products
                var products = await wc.GetOrders();

`

**Comment by XiaoFaye** [comment]
i see, you can't put " www " in the restful url, now I'm getting the deserializing  error , I will have a look and let you know.

**Comment by AndrewZb** [comment]
Okay. Thank's

**Comment by AndrewZb** [comment]
I found this  error in GetProducts

In GetOrders all ok.

**Comment by XiaoFaye** [comment]
Can you give me some product IDs for testing?

**Comment by AndrewZb** [comment]
Yes .

id - 121

**Comment by XiaoFaye** [comment]
something wrong with your website, following is what returned when I tried GetProducts, if you have other plugins or customized code in your website, you might want to have a look.

![image](https://cloud.githubusercontent.com/assets/6334728/17642797/55004fa0-61a8-11e6-9905-1c01c746c960.png)

**Comment by AndrewZb** [comment]
okay I will have a look.

**Comment by suhomlineugene** [comment]
Hello. We fixed error. Try now

**Comment by suhomlineugene** [comment]
Try GetProducts method.

Have error `Additional information: There was an error deserializing the object of type WooCommerceNET.WooCommerce.ProductList. Encountered unexpected character '<'.` Again

**Comment by XiaoFaye** [comment]
This is because the Restful API returns the source code of a page as above pic shows.

**Comment by suhomlineugene** [comment]
How I can open Text visualizer?

**Comment by XiaoFaye** [comment]
You need to download the WooCommerce.NET source code and debug into it.

**Comment by jerryxcoke** [comment]
If you have wp api or wc api plugin, try to disable it.

**Comment by suhomlineugene** [comment]
Disabled. Getting this error again.

**Comment by suhomlineugene** [comment]
XiaoFaye


Can you test now  and if you will have error send screenshot please.

**Comment by XiaoFaye** [comment]
![image](https://cloud.githubusercontent.com/assets/6334728/17660284/878aa210-632c-11e6-9b0a-0a6daa4c763c.png)

![image](https://cloud.githubusercontent.com/assets/6334728/17660298/a1584602-632c-11e6-892b-ee2ef549262b.png)

**Comment by suhomlineugene** [comment]
Hello. All okay. We fix issue with request.

I have one question.

I make GetOrders request. Display Date like this `Date:{order.date_created}`


But I recieve date and time that not in my UTC

`Date:8/15/2016 1:06:14 PM`


Where is error?

**Comment by XiaoFaye** [comment]
This is because the restful api doesn't return a datetime string with "Z" at the tail anymore. But I have compared with the legacy version, I got the same value from both, so it shouldn't be a problem. Unless you have got wrong values?

![image](https://cloud.githubusercontent.com/assets/6334728/17683581/429bdeb8-63a8-11e6-83ae-858f52aa61cb.png)
