### ISSUE TITLE
regular_price datatype not of type string in v2

### ISSUE THREAD

**Issue by shstat1** [XiaoFaye/WooCommerce.NET#170]
When I try to add a product, and set regular_price = 20.88M it shows error in runtime:

{"code":"rest_invalid_param","message":"Invalid parameter(s): regular_price","data":{"status":400,"params":**{"regular_price":"regular_price is not of type string."}**}}

- I am using WooCommerce.NET version 0.7.1

Product product = new Product();
product.name = "Test name";
product.short_description = "Test desc.";
...
**product.regular_price = 20.88M;**
...
wc.Product.Add(product);

- Error: **{"regular_price":"regular_price is not of type string."}**

**Comment by goguvi** [comment]
This bug was resolved since pull request #156 was merged. Maybe if you're using the version from the nuget it's not updated yet.

**Comment by shstat1** [comment]
Yes, I was using version from the nuget.
But now I downloaded the source from git and included as existing project in my sol, and now 
I am facing another error:

**{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}**

It was working well with version from nuget, except regular_price.
My wordpress version is 4.7 and Woocommerce API is configured like it was when using the version from nuget.

**Comment by XiaoFaye** [comment]
Please look at the double slashing issue here #166 , I haven't merged the code yet.

**Comment by shstat1** [comment]
Now it is working fine, also now i am able to set regular_price without error.
Thank you for your fast replay.

**Comment by SolucionesPOS** [comment]
Hello I have problems with the regular price and I followed the steps of changing

` if (pi.GetValue(this) != null)
                        //objValue.SetValue(this, (pi.GetValue(this) as decimal?).Value.ToString(CultureInfo.InvariantCulture));
`
Still working error with version   WooCommerceNET 0.7.1 please help

**Comment by XiaoFaye** [comment]
@SolucionesPOS what was the details of the error?

**Comment by SolucionesPOS** [comment]
@XiaoFaye Thank you for responding ... Show me the following message when I send the regular price `e = {"{\"code\":\"rest_invalid_param\",\"message\":\"Par\\u00e1metro(s) no v\\u00e1lido(s): regular_price\",\"data\":{\"status\":400,\"params\":{\"regular_price\":\"regular_price no es del tipo string.\"}}}"}` 
I have the last update with the changes in the class RestAPI.cs still persite the error 
this is my repository I do not know if you can help mehttps://github.com/SolucionesPOS/SincronizadorWoocommerce.git

**Comment by XiaoFaye** [comment]
@SolucionesPOS  could you send a sample of the josn string so I can have a look?

**Comment by SolucionesPOS** [comment]
Thanks @XiaoFaye  for your time I have managed to solve the error thanks for your work and performance greetings from Mexico

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.7.2

**Comment by GarnettC** [comment]
Getting the error in December 2021. Using version 0.84

**Comment by GarnettC** [comment]
Used Newtonsoft instead of System.Text.Json and the error went away but the price is not set
