### ISSUE TITLE
Getting product count

### ISSUE THREAD

**Issue by gtaylor44** [XiaoFaye/WooCommerce.NET#171]
Just wondering what the best way to get the product count is? I need the product count to be able to show a progress bar. 

I notice that the legacy API has a method GetProductCount but is this the recommended approach? 

From the documentation page:
The total number of resources and pages are always included in the X-WP-Total and X-WP-TotalPages HTTP headers.

I don't think your library exposes this data.

**Comment by XiaoFaye** [comment]
No, the library doesn't expose the header.  Sure you can use the legacy API to get the product count.

**Comment by Kamalsurya** [comment]
Is there a way to pull specific columns data from the apis instead of all the data.

**Comment by XiaoFaye** [comment]
@Kamalsurya check #326
