### ISSUE TITLE
woocommerce_rest_cannot_view and woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by hikarushin** [XiaoFaye/WooCommerce.NET#173]
Hi guys, I need little help. When accessing my live website using http, it gives `woocommerce_rest_authentication_error Invalid signature - the given signature does not match.`
and if I'm using https, it gives `woocommerce_rest_cannot_view sorry you can not list the resources`. What should I check?

**Comment by XiaoFaye** [comment]
please check if the url matches your wordpress settings.
