### ISSUE TITLE
Error 400 when Product.GetAll(new Dictionary<string, string>(){{ "per_page", "1000" }}));

### ISSUE THREAD

**Issue by jmfloreszazo** [XiaoFaye/WooCommerce.NET#174]
Hello,

I have the following error: "The remote server returned an error: (400) Bad Request."

- Wordpress version: 4.8
- WooCommerce version: 3.0.8
- WooCommerce.NET version: 0.7.1

Steps to replicate the issue:

 RestAPI rest = new RestAPI(StaticResources.woocommerUri, StaticResources.woocommerKey, StaticResources.woocommerSecret);
WCObject wc = new WCObject(rest);
//Task<List<Product>> taskForProducts = Task.Run(() => Product.GetAll());
Task<List<Product>> taskForProducts = Task.Run(() => wc.Product.GetAll(new Dictionary<string, string>(){{ "per_page", "1000" }}));
var responseProducts = taskForProducts.GetAwaiter().GetResult();

If I use this param:

Task<List<Product>> taskForProducts = Task.Run(() => wc.Product.GetAll(new Dictionary<string, string>() { { "page", "2" } })); 

Work fine.

Wordpress have a "posts_per_page" set to 1000, and I use a PHP Woocommer API to test in parallel and I haven't got any issue. And .NET only retrieve 10.

Thank you.

**Comment by hikarushin** [comment]
You cannot set per_page more than 100.

**Comment by jmfloreszazo** [comment]
OK,

Thank you.

**Comment by Progytech** [comment]
Hi all,
If the maximum per_page is 100, how one would get all records?  
I would have over 3,000 products and at some point I need to get the list of all products, what would be the right code to do that?
Thanks.

**Comment by richardaubin** [comment]
If you know the total product count, then looping through should be fairly easy.  If you don't know, then loop through your 100 product pages until the product count is less than 100, then you'll know you've reached the last page.

On 2019-04-15 12:52:24 AM, Edhy Rijo <notifications@github.com> wrote:

Hi all,
If the maximum per_page is 100, how one would get all records?
I would have over 3,000 products and at some point I need to get the list of all products, what would be the right code to do that?
Thanks.

**Comment by Progytech** [comment]
Hi Richard,
Thanks for the reply. 
I may not know the total product count, so where I am confused is how to loop the product pages until I get to the last one?
Is there a page collection somewhere which I can loop?

Sorry if this is a simple question, but I am new to WordPress/WooCommerce and trying to understand the proper way to deal with this.

Thanks in advance for any cooperation.

**Comment by richardaubin** [comment]
Since you can specify which page of products you would like to get...
if thisPageProductCount  == 100 then nextPageNo += 1...

**Comment by Progytech** [comment]
Thanks again Richard, I will try that.

**Comment by Progytech** [comment]
Hi Richard,
Just to let you know that your suggestion worked.  Here is my code which basically will update my database with the Product.ID if the Product.SKU matches my database items:

```
        Dim nextPageNumber As Integer = 1
        While nextPageNumber > 0

            Dim allProductsList As List(Of Product) = Await wc.Product.GetAll(New Dictionary(Of String, String)() From {
                                                                                          {"page", nextPageNumber.ToString},
                                                                                          {"per_page", "10"}})

            If allProductsList IsNot Nothing AndAlso allProductsList.Count > 0 Then
                For Each webItem As Product In allProductsList
                    With webItem
                        If Not String.IsNullOrEmpty(.sku) Then
                            If tempBizItems.Seek($"{NameOf(tempBizItems.Barcode)}='{ .sku.Trim}'") Then
                                If tempBizItems.ItemWebID <= 0 Then
                                    tempBizItems.ItemWebID = .id
                                End If
                            End If
                        End If
                    End With
                Next webItem

                nextPageNumber += 1
            Else
                nextPageNumber = -1
            End If
        End While

```
Thanks again!

**Comment by richardaubin** [comment]
Cool, glad you got it going 😊

With my own tests managing lots of products, I set the per_page value to 100, and use a parallel for loop to get as many pages as I can at once, a check for the page count < 100 to happen, wait for running threads to finish, then exit.

I would also test your per_page value to optimize fetching times for your specific application/server setup.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Progytech** [comment]
Awesome, thanks again.
I will follow your suggestions to optimize the loop.

**Comment by richardaubin** [comment]
You’re welcome.  FYI on my remote server, I was getting only 2 threads, with local server running WAMP, I think it’s between 15 to 25 on my machine.

Good luck and do keep me posted 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
