### ISSUE TITLE
Products and ProductCategories Filter

### ISSUE THREAD

**Issue by JM63** [XiaoFaye/WooCommerce.NET#18]
I'm not able to get Products or ProductCategory with a particular filter. 
I need to get the productcategories that are equal a "Cars".
I tried this code, but does not work, wil return all productcategories.

RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wc/v1/", "<WooCommerce Key>", "<WooCommerce Secret");
WCObject wc = new WCObject(rest);
// Create filter parameters
var filtro = new Dictionary<string, string>() { { "fields", "name" }, { "filter[equal]", "Cars" }}; 
// Get Product Categories
var cat = await wc.GetProductCategories(filtro);

Thanks,
Marcos

**Comment by XiaoFaye** [comment]
By the below official doc, I don't think the "limit" or "equal" filters are avaliable for product category, however "search" and "per_page" will meet your needs.

http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-product-categories
