### ISSUE TITLE
Can not get price and availability for variable products

### ISSUE THREAD

**Issue by NGame1** [XiaoFaye/WooCommerce.NET#181]
Hey there , I can't find any way to check variable products Price and Availability of each attribute in the product 
Something like this product : http://damatik.com/product/%d9%85%d8%ad%d8%b5%d9%88%d9%84-%d9%85%d8%aa%d8%ba%db%8c%d8%b1
- Wordpress 4.8, WooCommerce V2 and WooCommerce.NET 0.7.1 (NuGet)

**Comment by XiaoFaye** [comment]
Try WCObject.Product.Variations

**Comment by NGame1** [comment]
OK but what is ID and Parent ID ? Parent ID is product id and ID is attribute ID or something else ?

**Comment by XiaoFaye** [comment]
It should be the main product ID.

**Comment by NGame1** [comment]
Solved, Thanks
