### ISSUE TITLE
Error Getting Products by Tag

### ISSUE THREAD

**Issue by ikymasie** [XiaoFaye/WooCommerce.NET#182]
Trying to get all products for a particular Tag (i.e. "France") but it keeps returning all products

Heres my code

var tags=new string[] { "South-Africa" })
return await mClient.Product.GetAll(new Dictionary<string, string>() { { "tags", JsonConvert.SerializeObject(tags) }, { "per_page","100"} });

Please help

**Comment by XiaoFaye** [comment]
Please use the tag parameter as the docs:

![image](https://user-images.githubusercontent.com/6334728/27765564-08d9016c-5f09-11e7-9daa-82ee7eefd993.png)

**Comment by ikymasie** [comment]
Hi James..

Thanks for the timely response.... but its still not working... could you
show me some sample code?

Regards

**Comment by XiaoFaye** [comment]
return await mClient.Product.GetAll(new Dictionary<string, string>() { { "tag", "111" }, { "per_page","100"} });

**Comment by ikymasie** [comment]
Is it possible to use the tag name instead of I'd?

**Comment by XiaoFaye** [comment]
Not at the moment, but you can easily get the ID using the tag name.

**Comment by ikymasie** [comment]
Trying that now! Thank you so much!!  You're library is incredible!!
