### ISSUE TITLE
Getting ShippingZone locations

### ISSUE THREAD

**Issue by sasjacobs** [XiaoFaye/WooCommerce.NET#183]
Wordpress version 4.8, WooCommerceNET.0.7.1, .NET 4.5.1

I can't see how to return the ShippingZoneLocations for a specific ShippingZone. The public properties don't include a collection of locations.

From the MetaData, I can see the object WCShippingZoneItem has a property
public WCSubItem<ShippingZoneLocation> Locations { get; protected set; }

but this is not available.

Can you please advise how I can return the locations?

Thanks!

**Comment by XiaoFaye** [comment]
Seems it works fine with me:
![image](https://user-images.githubusercontent.com/6334728/27938089-ccd95f9e-630f-11e7-8511-dd23740f1662.png)

**Comment by sasjacobs** [comment]
OK. Thanks. I'll investigate further.

**Comment by XiaoFaye** [comment]
@sasjacobs  Any feedback on this?

**Comment by sasjacobs** [comment]
Thanks so much. I was able to get it to work after doing some updates.
