### ISSUE TITLE
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.v2.CustomerMeta]

### ISSUE THREAD

**Issue by hikarushin** [XiaoFaye/WooCommerce.NET#184]
Hi, I'm trying to deserialize below JSON. But I received this error: 

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.v2.CustomerMeta]

I think the error is from MetaData.

Full stack error:

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.v2.CustomerMeta]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> Path 'meta_data.0', line 1, position 935.

```
{
  "id": 13536,
  "date_created": "2017-07-01T11:21:20",
  "date_created_gmt": "2017-07-01T09:21:20",
  "date_modified": "2017-07-01T13:24:20",
  "date_modified_gmt": "2017-07-01T11:24:20",
  "email": "sssss@hotmail.com",
  "first_name": "ss",
  "last_name": "sss",
  "role": "subscriber",
  "username": "facebook - ss sasssnz",
  "billing": {
    "first_name": "ss",
    "last_name": "sss ss",
    "company": "",
    "address_1": "zxc",
    "address_2": "",
    "city": "cxz",
    "state": "BU",
    "postcode": "qwe",
    "country": "AU",
    "email": "sss@hotmail.com",
    "phone": "1234"
  },
  "shipping": {
    "first_name": "ss",
    "last_name": "sss ss",
    "company": "",
    "address_1": "zxc",
    "address_2": "",
    "city": "cxz",
    "state": "AU",
    "postcode": "qwe",
    "country": "AU"
  },
  "is_paying_customer": false,
  "orders_count": 1,
  "total_spent": "79.85",
  "avatar_url": "",
  "meta_data": {
    "0": {
      "id": 481986,
      "key": "braintree_production_vault_id",
      "value": "1759565601"
    },
    "1": {
      "id": 481987,
      "key": "_yoast_wpseo_profile_updated",
      "value": "1498908081"
    },
    "2": {
      "id": 481990,
      "key": "fb_profile_picture",
      "value": ""
    },
    "4": {
      "id": 481994,
      "key": "braintree_next_payment_update",
      "value": "1499080887"
    },
    "5": {
      "id": 482012,
      "key": "shipping_method",
      "value": [
        "free_shipping:2"
      ]
    }
  }
}
```

**Comment by XiaoFaye** [comment]
You can re-define the meta_value type to solve this:
```
    public class MyCustomer : wcv2.Customer
    {
        [DataMember(EmitDefaultValue = false)]
        public new Dictionary<string, wcv2.CustomerMeta> meta_data { get; set; }
    }

    MyCustomer c = rest2.DeserializeJSon<MyCustomer>(jsonstr);
```

**Comment by XiaoFaye** [comment]
@hikarushin Any feedback on this?

**Comment by keie** [comment]
I have the same problem but i dont understand your suggest  @XiaoFaye

**Comment by jannagy** [comment]
In my scenario this issue happened on Media deserialization, Monster Insight changed Media meta from array to object. So probably some plugin in your WP installation is changing  meta from array to object. Note that your Json meta value is also object, not an array.
