### ISSUE TITLE
Cannot set regular_price nor sale_price on Variation

### ISSUE THREAD

**Issue by arnarleifs** [XiaoFaye/WooCommerce.NET#185]
### Problems setting the regular_price and sale_price on Variation
 
I am using Wordpress version 4.7, WooCommerce version 3.1.0 and WooCommerce.NET version 0.7.1

Whenever I add a variation to product the regular_price and sale_price does not appear on the website and it always gives me "null" when trying to access the property. I am using WooCommerceNET.WooCommerce.V2 reference for Variation. Below is the code:

``` c
var newVariation = await _wc.Product.Variations.Add(new Variation
            {
                sku = product.ItemCode,
                attributes = new List<VariationAttribute>
                {
                    new VariationAttribute
                    {
                        id = updatedParentProduct.attributes.Find(a => a.name == "Litur").id,
                        name = "Litur",
                        option = product.Description2
                    }
                },
                manage_stock = true,
                stock_quantity = (int?)product.TotalQuantityInWarehouse,
                regular_price = (decimal?)product.UnitPrice1WithTax,
                sale_price = product.PropositionPrice == 0 ? null : (decimal?)product.PropositionPrice,
                date_on_sale_to = product.PropositionDateTo,
                on_sale = product.PropositionDateTo > DateTime.Now
            }, parentProduct.id.Value);
```

**Comment by arnarleifs** [comment]
For now I made a workaround, which uses RestSharp as REST client. Code is here:

``` c
var request = new RestRequest("products/{product_id}/variations/{variation_id}", Method.PUT);
            request.AddUrlSegment("product_id", parentId.ToString());
            request.AddUrlSegment("variation_id", variationId.ToString());
            request.AddHeader("Content-Type", "application/json");
            request.AddJsonBody(new
            {
                regular_price = product.UnitPrice1WithTax.ToString(CultureInfo.InvariantCulture),
                sale_price = product.PropositionPrice == 0 ? null : product.PropositionPrice.ToString(CultureInfo.InvariantCulture),
                date_on_sale_to = product.PropositionDateTo,
                on_sale = product.PropositionDateTo > DateTime.Now
            });

            var response = _client.Execute(request);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                Logger.Error(response.Content);
            }
```

**Comment by XiaoFaye** [comment]
Can you try this? It's working per my testing.

https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-JSON.NET-in-WooCommerce.NET

**Comment by sterenas** [comment]
@arnarleifs I'm having the same issue with regular_price also.  Unfortunately the suggested fix to this involves downloading the whole project, modifying some lines and compiling it, something I'm not too sure I can do.  If anyone has an updated DLL that could send or update this project on Nuget that would be great.

**Comment by arnarleifs** [comment]
@XiaoFaye, this fix you posted is it something which should be added to the code or only for this specific scenario?

**Comment by XiaoFaye** [comment]
@arnarleifs @sterenas It's a workaround, you don't need to download the whole project. I will try to fix the code so you don't need this workaround in the future.

**Comment by arnarleifs** [comment]
I was wondering because I am receiving SerializationException whenever I use 

``` c
// Whenever this returns no results, I receive a SerializationException
var products = await _wc.Products.GetAll(new Dictionary<string, string>{
    { "sku", sku }
});
```

I just wanted to ask if this is somehow related or not.

```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.Product, WooCommerceNET, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.
```

**Comment by XiaoFaye** [comment]
@arnarleifs I think there is something wrong with the return json string,

**Comment by sterenas** [comment]
Thanks @XiaoFaye , let me just recap the issue.  Using VS 2017, download WooCommerce.Net 0.71 from NuGet, add the references to the project and the following code fails on the regular_price assignment.  I've tried both .regular_price=120 and .regular_price = "120", it won't work either way and shows 
Invalid parameter: regular_price is not of type string (translated from Spanish below:
{"code":"rest_invalid_param","message":"Par\u00e1metro(s) no v\u00e1lido(s): regular_price","data":{"status":400,"params":{"regular_price":"regular_price no es del tipo string."}}}

Perhaps an update to 0.72 on NuGet would fix this issue? :)
Thanks again for your time!
Sergio

Code to create a SKU:

 Dim rest As New WooCommerceNET.RestAPI("http://******.***/wp-json/wc/v2/", "ck_*****", "cs_*****")
 Dim wc As New WCObject(rest)
 Dim d As New ProductDimension
 Try
    Dim p As New Product
    With p
      .sku = "SKU1"
      .name = "Product 1"
      .description = "Description <b>Product</b> 1"
      .short_description = "Short Description <I><B>Product</B></I> 1"
      .manage_stock = True
      .backorders_allowed = False
      .stock_quantity = 90
      .date_on_sale_from = Today()
      .date_on_sale_to = Today.AddDays(5)
      .on_sale = True
      d.height = "10"
      d.length = "11"
      d.width = "12"
      .dimensions = d
      .weight = "800"
     .regular_price = 120
     .price = "100"
     .downloadable = False
     .featured = True
     .in_stock = True
     .reviews_allowed = False
    End With
    
    Dim resp = Await wc.Product.Add(p)
Catch ex As Exception
    MsgBox(ex.Message)
End Try

**Comment by arnarleifs** [comment]
It seems to only happen for products which are not found within WooCommerce

**Comment by XiaoFaye** [comment]
@arnarleifs use the fix I post and set a breakpoint in `return JsonConvert.DeserializeObject<T>(jsonString);`, see what json string you will get.

**Comment by arnarleifs** [comment]
```
		jsonString	"<br />\n<b>Fatal error</b>:  Uncaught Error: Call to a member function get_id() on boolean in /home4/******/public_html/******/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-crud-controller.php:338\nStack trace:\n#0 /home4/******/public_html/******/wp-includes/rest-api/class-wp-rest-server.php(927): WC_REST_CRUD_Controller-&gt;get_items(Object(WP_REST_Request))\n#1 /home4/******/public_html/******/wp-includes/rest-api/class-wp-rest-server.php(323): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))\n#2 /home4/******/public_html/******/wp-includes/rest-api.php(271): WP_REST_Server-&gt;serve_request('/wc/v2/products')\n#3 /home4/******/public_html/******/wp-includes/class-wp-hook.php(298): rest_api_loaded(Object(WP))\n#4 /home4/******/public_html/******/wp-includes/class-wp-hook.php(323): WP_Hook-&gt;apply_filters(NULL, Array)\n#5 /home4/******/public_html/******/wp-includes/plugin.php(515): WP_Hook-&gt;do_action(Array)\n#6 /home4/******/public_html/******/wp-includes/class-wp.php(386): do_action_ref_array('parse_req in <b>/home4/******/public_html/******/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-crud-controller.php</b> on line <b>338</b><br />\n"	string

```

**Comment by XiaoFaye** [comment]
@arnarleifs there is something wrong with your Wordpress/WooCommerce code, you will need to fix it first.

**Comment by arnarleifs** [comment]
That sounds weird considering I am using a theme which is widely used and recommended and haven't modified the code in WP/WooCommerce.

**Comment by XiaoFaye** [comment]
@arnarleifs Could be a server setting issue, permission issue.

**Comment by arnarleifs** [comment]
``` php
if ( ! wc_rest_check_post_permissions( $this->post_type, 'read', $object->get_id() ) ) {
    continue;
}
```

This is the line pointing to within the WooCommerce plugin. I am using a consumer key and secret issued by an R/W key.

**Comment by XiaoFaye** [comment]
@arnarleifs this could be a WooCommerce bug, but it will be helpful if you can use Postman to double confirm the issue.

**Comment by sterenas** [comment]
You're a genius @XiaoFaye! 0.7.2 indeed fixes the sales_price issue.  I can now create/update products.  Still need to play with the category and image attributes to get it going.
Thanks so much for your help!
Regards!
ST
