### ISSUE TITLE
Regular price is not type of string in woocommerce using .net SDK

### ISSUE THREAD

**Issue by sagaraloha** [XiaoFaye/WooCommerce.NET#186]
WooCommerceNET, Version=0.7.1.0

When i am creating new product using  WooCommerceNET.WooCommerce.v2 .net, it gives me error as, 
Error = 'regular_price is not type of string'.

But it's there in Model as decimal. Please provide us solution  as soon as possible, so we can complete our integration with  WooCommerce system. 

Thanks,

**Comment by goguvi** [comment]
This topic have been solved in github repository. Maybe is not in NuGet yet.
You can review several topic regarding this like #170 #156 #147 and more https://github.com/XiaoFaye/WooCommerce.NET/issues?utf8=%E2%9C%93&q=regular_price

**Comment by sagaraloha** [comment]
I am not getting a solution yet, please provide me the right direction to fix this.

and when it will be in NuGet?

**Comment by goguvi** [comment]
For a code fix you could review the issues I've mentioned or take a look at JsonObject class here:
https://github.com/XiaoFaye/WooCommerce.NET/blob/master/Base/BaseObject.cs

GitHub repository has this problem solved, but if you use NuGet I think you must wait untill next release.

NuGet releases depend on @XiaoFaye

**Comment by XiaoFaye** [comment]
@sagaraloha @goguvi  Version 0.7.2 is on Nuget now.
