### ISSUE TITLE
Create bundle products

### ISSUE THREAD

**Issue by 50l3r** [XiaoFaye/WooCommerce.NET#188]
I guys,

i need to create a bundle products with api rest. I use the official plugin: https://docs.woocommerce.com/document/bundles/

¿How can i define the bundled items?

```
Product WooProduct = new Product()
{
    name = Product.Key.Description,
    regular_price = Product.Key.Price,
    status = "publish",
    sku = Product.Key.No,
    type = "bundle"
};
```

**Comment by XiaoFaye** [comment]
@50l3r you can use third-party rest api in the latest version, please give it a try.

**Comment by hakimloup21** [comment]
not Any solution yet please !?

**Comment by luiscreates** [comment]
Leaving this for anyone who is looking to use product bundles with this library. I've forked the base library and added the product bundles feature to support the extension. I'll be doing the same for composites too.

[Forked repo can be found here:] (https://github.com/luiscreates/WooCommerce.NET.Extensions)

Thanks James for this great library!
