### ISSUE TITLE
Can't UpdateProduct - Invalid or duplicated SKU

### ISSUE THREAD

**Issue by QuAzI** [XiaoFaye/WooCommerce.NET#189]
I can't update product data

- Steps to replicate the issue
```cs
WCObject WooCommerce;
Dictionary<string, WooCommerceNET.WooCommerce.v1.Product> productsCache = new Dictionary<string, Product>();
...
var wcProduct = productsCache[productId]; // productsCache filled from WooCommerce.GetProducts().Result;
wcProduct.in_stock = false;
wcProduct.status = "private";
var json = WooCommerce.UpdateProduct((int)wcProduct.id, wcProduct).Result; // <-- crash
var result = API.DeserializeJSon<Product>(json);
productsCache[productId] = result;
```
- Details of the error message if there is any
```
WebException: {"code":"product_invalid_sku","message":"Invalid or duplicated SKU.","data":{"status":400,"resource_id":9}}
```

Wordpress version: 4.8 (bitnami image)
WooCommerce version: Version 3.1.1
WooCommerce.NET version: 0.7.1.0
API Version: v1

**Comment by XiaoFaye** [comment]
try this:

`var json = WooCommerce.UpdateProduct((int)wcProduct.id,  new Product() {  in_stock = false,  status = "private" } ).Result;`

**Comment by QuAzI** [comment]
Oh, that's mean I must send not full state of object, just changed fields and unchanged fields must be null? Ok.
How can I add variations? If product have one varioation and in update I fill list with old variation + new variation it is crashed with 
```
{"code":"product_invalid_sku","message":"Invalid or duplicated SKU.","data":{"status":400,"resource_id":205}}
```
So, how can I remove attribute (Description as example)?
How can I remove images? If I send empty list I have exception about id #0.
How can I add new Category for product without removing previous categories items in case when product available in two categories?

**Comment by QuAzI** [comment]
In UI I see: "Title" is Image.name, "Alt Test" is Image.alt, but "Caption" and "Description" missed. It is API version restriction? In my case "Description" field can be used to store info about image to prevent twice uploading because it is not published on site.

**Comment by rtmrodrigues** [comment]
Hello my friend.

I might have some answers for you.
Are you still facing this questions?
