### ISSUE TITLE
SystemStatus - Question

### ISSUE THREAD

**Issue by sterenas** [XiaoFaye/WooCommerce.NET#190]
Hi!
Can anyone provide a quick example on how to obtain SystemStatus?  I can't seem to get it to work and it seems to be a trivial one to call.
I'd expect to retrieve the info shown [in the docs](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-system-status-items)

This is what I have so far but VS doesn't like the Await wc.SystemStatus line and shows:
"'Await' requires that the type have a suitable GetAwaiter method."

Private Async Sub btnWooCommerceStatusConexion_ClickAsync(sender As Object, e As EventArgs) Handles btnWooCommerceStatusConexion.Click
    Dim rest As New WooCommerceNET.RestAPI("http://######.###/wp-json/wc/v2/", "ck_#####", "cs_#####")
    Dim wc As New WCObject(rest)

    Dim sysstatus = Await wc.SystemStatus
    MsgBox("")
 End Sub

Thanks!
Sergio

**Comment by sterenas** [comment]
Hi again, is this an API issue?  Anyone else having this same problem?
Thanks!
Sergio

**Comment by XiaoFaye** [comment]
I think it should be `Await wc.SystemStatus.GetAll()`

**Comment by sterenas** [comment]
Thanks @XiaoFaye.  .Getall() compiles but returns nothing.  I also tried Await wc.SystemStatus.Get() but there's an id integer input parameter I don't  know what it is for.
Is there any quick C# sample for this that works as I can easily convert it to VB.NET ?
Thanks again!
Sergio

**Comment by sterenas** [comment]
Has anyone got a working V2 SystemStatus returning data?  I can't seem to have it return anything no matter what I try.  Appreciate it if you can share a short working example.
Thanks!
Sergio

**Comment by lucasxyang** [comment]
@sterenas Unlike other things you can get (eg. Order or Products) from WooCommerce which are JSON arrays, SystemStatus is a JSON object. See http://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#list-all-system-status-items. 
If you wrap the code in a try-catch block you will see JSON.NET library throw a JsonSerializationException. I think the library was trying to deserialize the object as an array and got an error. @XiaoFaye may have a better insight. If I were you I would probably develop my own solution to bypass this or fix the code then submit a pull request.

**Comment by guiadevoo** [comment]
Hi, I created a new method GetObject, to get the result

public async Task<T> GetObject(Dictionary<string, string> parms = null)
        {
            return API.DeserializeJSon<T>(await API.GetRestful(APIEndpoint, parms).ConfigureAwait(false););
        }


In application i use
await wcObjV3.SystemStatus.GetObject();
