### ISSUE TITLE
https cause 401 "Only authenticated users can access the REST API"

### ISSUE THREAD

**Issue by QuAzI** [XiaoFaye/WooCommerce.NET#191]
- Steps to replicate the issue

Application work with local version of WC (except variations update #189) but can't work with main site over https. Even GetProducts() throws exception.

In WooCommerce REST API enabled and keys generated. I can open https://main.site/wp-json/wc/v1/
 in browser and it shows right json structure.

- Details of the error message if there is any
```
{"code":"rest_cannot_access","message":"Only authenticated users can access the REST API.","data":{"status":401}}
```

- Wordpress version, WooCommerce version and WooCommerce.NET version

WP Version: 4.7.5
WC Version: 2.6.14
WooCommerce.NET version: 0.7.1.0
API Version: v1

**Comment by XiaoFaye** [comment]
https://www.mainsite.com/ and https://mainsite.com/ makes difference, have you checked that?

**Comment by QuAzI** [comment]
If I use www prefix site return 301 Moved Permanently with Location without www.

**Comment by XiaoFaye** [comment]
Just for your information: the api url need to be the same as your settings in Wordpress.

**Comment by QuAzI** [comment]
It is "Home URL" from "WooCommerce - System Status" + "/wp-json/wc/v1/"
I will request to upgrade version of WooCommerce to support API V2 and
possible it will solve access restrictions.

**Comment by XiaoFaye** [comment]
then it should be all right, I can think of any reason this will fail. The only thing left to check is your server settings may be.

**Comment by QuAzI** [comment]
After upgrade REST with https works but only with AuthorizedHeader=false.

**Comment by iaps** [comment]
Thanks QuAzI, AuthorizedHeader=false was exactly what I needed to make things work between WordPressPCL and WooCommerceNET.
