### ISSUE TITLE
 html escaping issue in categories (&amp;)

### ISSUE THREAD

**Issue by QuAzI** [XiaoFaye/WooCommerce.NET#192]
I create new category "Computer & Networking" in shop and it shown like "Computer & Networking". But GetProductCategories() return "Computer &amp; Networking".

When I check if same category is not available in shop and try to create it I have exception
```
{"code":"term_exists","message":"A term with the name provided already exists with this parent.","data":{"status":400,"resource_id":30}}
```

Wordpress version: 4.8 (bitnami image)
WooCommerce version: Version 3.1.1
WooCommerce.NET version: 0.7.1.0
API Version: v1

**Comment by QuAzI** [comment]
With product name no problems. But category can't use next chars: & < > "

**Comment by QuAzI** [comment]
Looks like bug in API because JSON for product have name as is but JSON for category have escaped chars

**Comment by QuAzI** [comment]
Blask list of chars extended by `\`

**Comment by XiaoFaye** [comment]
has this been confirmed as woocommerce bug? or something I need to do in the DLL?

**Comment by QuAzI** [comment]
WooCommerce API bug
