### ISSUE TITLE
Variations - Question

### ISSUE THREAD

**Issue by sterenas** [XiaoFaye/WooCommerce.NET#193]
Hi!
Is there any way of obtaining ALL variations for ALL products using:
Dim variations As List(Of Variation) = Await wc.Product.Variations.GetAll(objvar) ?
Thanks!
Sergio

**Comment by XiaoFaye** [comment]
You will need to do this in a Product loop.

**Comment by sterenas** [comment]
Thanks @Xiaofaye indeed:
Dim products As List(Of Product) = Await wc.Product.GetAll() has a variations node where I can get all of the, per productid.
Thanks again!
Sergio
