### ISSUE TITLE
Again with regular_price issues

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#194]
After I upgrade to Wocommerce.NET 0.7.2. I have the regular_price error again.

My problem is that I have a derived class of product:

```
public class WCProduct : WooCommerceNET.WooCommerce.v1.Product
{
  ...
}
```
So the following code:
```
if (pi.PropertyType == typeof(decimal?))
{
    if (GetType().FullName.StartsWith("WooCommerceNET.WooCommerce.v1") || GetType().FullName.StartsWith("WooCommerceNET.WooCommerce.v2"))
        objValue.SetValue(this, (pi.GetValue(this) as decimal?).Value.ToString(CultureInfo.InvariantCulture));
    else
        objValue.SetValue(this, decimal.Parse(pi.GetValue(this).ToString(), CultureInfo.InvariantCulture));
}
```
return "ConectaDelSol.WooCommerce.Clases.WooEx.V1.WCProduct" for `GetType().FullName` , so the condition is not fulfilled, and therefore it is serialized as text.

I guess the condition is set for the legacy api, so I have commented it as a workaround.

**Comment by XiaoFaye** [comment]
Seems `GetType().GetTypeInfo().BaseType.FullName` will work?

**Comment by goguvi** [comment]
yes, I think that should work.
