### ISSUE TITLE
Missing metadata on OrderLines

### ISSUE THREAD

**Issue by plinnet** [XiaoFaye/WooCommerce.NET#195]
Hi guys,

After upgrading to version WooCommerce.NET 0.7.2 from version 0.6.1 and now using V2, I have run into some problems.
After using Order.GetAll() I'm running through all the orders->orderlines I have in retrieved, but none of the orderlines contains metadata, which the I know exists in the woocommerce data tables.

Order.Get() has the same issue.

I have attached sample code [test.cs.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/1204937/test.cs.txt)

 and also a screenshot of the metadata for orderlines
![wps6_woocommerce_order_itemmeta](https://user-images.githubusercontent.com/30800110/29028573-0e181cb0-7b85-11e7-9f28-4d45106d61ab.jpg)

Any help would be greatly appreciated :)

/Peter

**Comment by XiaoFaye** [comment]
this link might be helpful for you: https://github.com/XiaoFaye/WooCommerce.NET/wiki/Handle-different-types-of-Meta-Value-in-WC-Restful-API-V2

**Comment by plinnet** [comment]
Thanks for the link. It actually help me quite a bit to understand the underlying mechanics.

For me, the specific problem was with OrderLineItem.Meta_data. After downloading the sourcecode for WooCommerce.Net I figured out that the problem actually was with the definition:

So correcting the datatype in OrderLineItem datacontract solved the problem for me. 
      //public List<OrderMeta> meta_data { get; set; } 
        public Dictionary<string, OrderMeta> meta_data { get; set; }

Thanks a lot for the support :)

**Comment by XiaoFaye** [comment]
Thanks for the feedback, we have had this before #184
