### ISSUE TITLE
webResponseFilter usage

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#196]
One of the changes of version 0.7.2 is webResponseFilter
> 1. Add webResponseFilter in RestAPI, which allows you to get information from the HttpWebResponse object, e.g.:X-WP-Total and X-WP-TotalPages.

@XiaoFaye Could you please provide and example of usage?

**Comment by XiaoFaye** [comment]
Please check this wiki page: https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET

**Comment by goguvi** [comment]
I tried the following method without success:
```
private void ResponseFilter(HttpWebResponse response)
{
   var total = int.Parse(response.Headers["X-WP-Total"]);
    var pagecount = int.Parse(response.Headers["X-WP-TotalPages"]);
}
```

I'm not sure, but I think it shouls be invoked in RestApi like this:

```
// asynchronously get a response
WebResponse wr = await httpWebRequest.GetResponseAsync().ConfigureAwait(false);
if (webResponseFilter != null)
    webResponseFilter.Invoke((HttpWebResponse)wr);
return await GetStreamContent(wr.GetResponseStream(), wr.ContentType.Contains("=") ? wr.ContentType.Split('=')[1] : "UTF-8").ConfigureAwait(false);
```

**Comment by XiaoFaye** [comment]
You are correct, thanks for pointing this out, will update this ASAP.

**Comment by TezWingfield-RetainMe** [comment]
Hi, Was the `ResponseFilter` bug fixed? I've been strategically adding break points, to understand how the logic runs, The `ResponeFilter` method is never fired. I cannot access the header values.

Although I'm running a nuget version, So I cannot debug the compiled library.

@goguvi Did you manage to get this working?

Regards,

**Comment by RobertLalenoh** [comment]
@TezWingfield-RetainMe i had the same issue. It looks like the nugget version is an older version of the Woocommerce project. 

I resolve this by:
1. Download the whole project from Github.
2. Compile the project.
3. Delete Woocommere reference in your own project.
4. Put a reference to the new compiled Woocommerce DLL.

Et voila, the responsefilter will do it's work now!
