### ISSUE TITLE
Help to remove sale_price in api v2

### ISSUE THREAD

**Issue by thiagobsq** [XiaoFaye/WooCommerce.NET#197]
I need help updating a product and removing sale_price in api v2. In the documentation of the woocommerce api it is necessary to send "", but the field sale_price is decimal. Someone has an example of how to do this.

Wordpress 4.8.1
Woocommerce 3.1.1
WooCommerce.NET NuGet 0.7.2

**Comment by XiaoFaye** [comment]
field sale_price is **decimal?** , you can set it to null.

**Comment by thiagobsq** [comment]
I tried, but the value is not removed.
In this topic below the developers say to send "" instead of sending null.
Https://github.com/woocommerce/woocommerce/issues/8828

To remove it would need to pass like this:
{
  "id": 335,
  "regular_price": "12.41",
  "sale_price": "",
  "date_on_sale_from": "",
  "date_on_sale_to": ""
}

**Comment by XiaoFaye** [comment]
That doesn't sound a correct way to do so.
But for now, you can use **jsonSerializeFilter** , to manually alter the json string as a workaround.

**Comment by SeanoNET** [comment]
A solution that worked for me is to set the sale_price to a string in Product.cs giving you the ability to remove the sale price.

`
        [DataMember(EmitDefaultValue = false)]
        public string sale_price { get; set; }
`

According to the WooCommerce API v2 documentation the sale_price is of type string.

Attribute | Type | Description
sale_price | string | Product sale price.
