### ISSUE TITLE
Allow calling third party Plugins restful apis

### ISSUE THREAD

**Issue by jmd007** [XiaoFaye/WooCommerce.NET#199]
- Wordpress version 4.8.1
- WooCommerce 3.1.1
- WooCommerce.NET 0.7.1.0

Hello,

I've seen that in version 0.7.2.0 change log you've added:
"Allow calling third party Plugins restful apis"

Is it only WooCommerce related plugins or any plugin with a REST endpoint?

Do you have a code example to use another plugin REST endpoint?

Thank you. It's really a great tool!
( Currently automating a full WooCommerce catalog with more than 7000 Hierarchical categories and 70000 products)

Best regards

JM Duchi (TransConnector.com)

**Comment by XiaoFaye** [comment]
Currently only for WooCommerce related plugins. Just pass the REST endpoints to the RESTAPI class will do.
