### ISSUE TITLE
Product Image Upload

### ISSUE THREAD

**Issue by JM63** [XiaoFaye/WooCommerce.NET#20]
Hi,
I'm having a problem to POST a Product when the image souce is local PC.

When i use this code it works nice
image.src = (@"http://www.mydomain.com/imagesstore/imagetest.jpg"),

But when i try a local url like this
src = (@"file:///C:/TEMP/LOCALIMAGES/imagetest.jpg")
always return {"{\"code\":\"woocommerce_product_image_upload_error\",\"message\":\"Error getting remote image . Error: Not a valid URL has been specified..\",\"data\":{\"status\":400}}"}

I can not use a local URL?
I have to first upload the images with FTP client to the server to use it in the POST product ?
Thanks ,
Marcos

**Comment by XiaoFaye** [comment]
no, you can't use a local URL. it's better to upload all images to wordpress gallery first, then use the wordpress image URL in your POST.
