### ISSUE TITLE
Cannot deserialize the current JSON array when calling wc.Category.GetAll()

### ISSUE THREAD

**Issue by mazenlhm** [XiaoFaye/WooCommerce.NET#200]
Good day,

 I am trying to retrieve all product categories with the following code:

 MyRestAPI rest = new MyRestAPI(_domainName + "/wp-json/wc/v2/", _consumerKey, _secKey);
 WCObject wc = new WCObject(rest);            
 List<ProductCategory> cats = await wc.Category.GetAll();

but I am getting the following error:
Message: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'WooCommerceNET.WooCommerce.v2.ProductCategoryImage' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '[0].image', line 1, position 100.
Source: Newtonsoft.Json

- Wordpress version: WordPress 4.8.1
- WooCommerce version:  3.1.2
- WooCommerce.NET version: 0.7.2.0

Thank you

**Comment by mazenlhm** [comment]
Hello,

I have changed ProductCategoryImage  according to issues 
https://github.com/XiaoFaye/WooCommerce.NET/issues/144
 and it is working now

in ProductCategory.cs changed:
public ProductCategoryImage image { get; set; }
to:
public ProductCategoryImage images { get; set; }

**Comment by XiaoFaye** [comment]
Seems it's a typo in official document, I will make this change in the next version. Thanks.

**Comment by mazenlhm** [comment]
thank you. We appreciate your work and commitment.

**Comment by DemiladeA** [comment]
How do I edit the Nuget package please @XiaoFaye  @mazenlhm

**Comment by DemiladeA** [comment]
On a Mac

**Comment by kokorambo** [comment]
I have same problem in woocommerce v2. It looks like you haven't updated this version yet, @XiaoFaye ? The function GetAll() of ProductTag still have same error.

**Comment by kokorambo** [comment]
I have tried to changed ProductCategoryImage in ProductCategory like @mazenlhm, but it's still not working. This is my error I get:
"There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.ProductCategory, WooCommerce.NET, Version=0.7.7.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character 'V'."
