### ISSUE TITLE
I would like to batch multiple attribute terms at ones, I can make it work but have to change the source code.

### ISSUE THREAD

**Issue by joey-wondergem** [XiaoFaye/WooCommerce.NET#201]
Sorry I'm new to github.com and I don't know if I can just commit my changes that I have made locally.
I'm using Wordpress 4.8.1 and WooCommerce 3.1.2 and WooCommerce.NET 0.7.2.

I have added the function Batch in class WCSubItem

`public async Task<string> Batch(BatchObject<T> items, int parentId, Dictionary<string, string> parms = null)
        {
            return await API.PostRestful(APIParentEndpoint + "/" + parentId.ToString() + "/" + APIEndpoint + "/batch", items, parms).ConfigureAwait(false);
        }`

When I test this it works fine for multiple attribute terms at one attribute.

Before I commit this I would like to know why there are 3 equal function implementations for AddRange, UpdateRange and DeleteRange in class WCItem instead of one function as above?

Best regards,
Joey Wondergem

**Comment by XiaoFaye** [comment]
I believe having AddRange, UpdateRange and DeleteRange will be more human-readable for people who using this library, even though they are having the same implementation.

Yes, the Batch functions are missing from the WCSubItem, we will need to add it in the next release.

**Comment by joey-wondergem** [comment]
Ok thanks for the response!
Ill wait till the next update :)
