### ISSUE TITLE
Product Batch Update for Variations

### ISSUE THREAD

**Issue by MarcoCordes** [XiaoFaye/WooCommerce.NET#202]
Hi, 
is there a batch way to upload variations?

My problem is, that i must upload about 10.000 Variations and i want to use the ProductBatch Class. But acutally there is only one posibility to upload one variation at the same time or? 

`await wc.Product.Variations.Add(lVariation, lOberArtikel.id.Value);`

I search somethink like 

`wc.Product.Variations.AddRange(lOberArtikel.variations);`

to use the ProductBatch and Update 100 Products :-/ 

Thank you 4 your nice API!

**Comment by XiaoFaye** [comment]
Yes, you are right, there should be a batch function for variations. please see issue #201 .

**Comment by 50l3r** [comment]
+1

**Comment by XiaoFaye** [comment]
This is in version 0.7.4 now.
