### ISSUE TITLE
@XiaoFaye i am uploading product with some attributes but when i upload them using wc.product.add(p) it returns a product in response with no attributes , no Idea whats happening . Kindly Respond, Thank You

### ISSUE THREAD

**Issue by shariqshahzad** [XiaoFaye/WooCommerce.NET#203]
4.8.1 Wordpress , WP restAPI v2 WooCommerce and Latest WooCommerce.NET version

**Comment by goguvi** [comment]
Its hard to know what's happening if you don't post part of your code.
For example: have you set product type to variable?

**Comment by shariqshahzad** [comment]
issue is solved i was not adding the options in attributes
