### ISSUE TITLE
Update product attributes

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#204]
- Wordpress: 4.8.1, WooCommerce: 3.1.2 and lastest WooCommerce.NET

I have for example a product with 3 attributes, two of then are for variations (size and color), but the other one is used to show information in the frontend.

I have been trying to update just an attribute, for example to uptate his terms. I also tried to add a new attribute for variation to an existing product that already have attributes.
 
Both cases clear all currently attributes and set just the new ones, I guess this is WooCommerce API default behabior and not a WooCommerce.NET issue. 

Is there any workaround to solve this? 
The only solution I can think of is to first retrieve the product to have its current attributes and then update or create the necessary attributes, but I'd have to do this with the whole catalog and it's tricky.

Thanks in advance.

**Comment by XiaoFaye** [comment]
There is no easy way to do this, hooking into WooCommerce Rest API is a solution.
