### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by arber** [XiaoFaye/WooCommerce.NET#206]
- Wordpress version: 4.8.1, WooCommerce version: 3.1.2, WooCommerce.NET version: 0.7.2

Calling any endpoint with https throws this error:
The underlying connection was closed: An unexpected error occurred on a send.

RestAPI rest = new RestAPI(
                    "https://<domain>/wp-json/wc/v2", 
                    "consumer_key", 
                    "consumer_secret",
                    false
                    );
_service = new WCObject(rest);
var products = await _service.Product.GetAll();

Regards,
Arber

**Comment by XiaoFaye** [comment]
It seems there is something wrong with your wordpress server, needs to check that.

**Comment by arber** [comment]
Hello,

thank you for your reply!

I thought that too, but it works with other libraries (python), so I think something is wrong with the request.

Regards,
Arber

**Comment by arber** [comment]
Hello again,

I fixed the issue by adding this line of code in SendHttpClientRequest method when calling https:

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

I am not sure how this affects calling not https servers so you may have to check it yourself.

Regards,
Arber

**Comment by goguvi** [comment]
You can try using a RequestFilter instead of changing SendHttpClientRequest. 
Take a look at https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET

**Comment by arber** [comment]
Hello goguvi,

thank you for you reply!

I don't think that will help in my situation, but I found out that I can insert that line of code (ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;) anywhere on my main project without the need to change the library and it will work.

Regards,
Arber

**Comment by XiaoFaye** [comment]
Hi Arber,

Thanks for letting us know the problem. 
This is relate to some global security protocol settings, and the default .NET settings are incompatible with your server, do you think it's because the SSL certificate that you are using? Is there any special with your SSL certificate? 

And for the place that insert that line of code, you are correct, just need to insert before calling the library. Another similar situation I can think of is bypassing invalid SSL certificate error. It needs another line of code as below:
`ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };`

Regards,
James

**Comment by arber** [comment]
Hello James,

I don't think the SSL certificate is special and I don't have much information about the server configuration because it is a shared host on BlueHost, but I suspect they changed something lately because the code was working before.

I tried bypassing the SSL check but it didn't work.

Thank you for your time!

Regards,
Arber

**Comment by XiaoFaye** [comment]
Hi Arber,

The below article has all detail regarding this issue: http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

If your project is targeting .NET 4.6, it should be all good, otherwise, you will need to change the default protocol manually.

Regards,
James
