### ISSUE TITLE
Unable to delete order notes

### ISSUE THREAD

**Issue by lucasxyang** [XiaoFaye/WooCommerce.NET#207]
WordPress version 4.8.1
WooCommerce version 3.1.2
WooCommerce.NET 0.7.2

Create an order notes (either public, private, or system note) (id 3 for example) for an order (id 67 for example). I am unable to delete the orderNote using the call `String s = await wc.Order.Notes.Delete(3, 67, true);` The thrown exception has a message, `Webhooks do not support trashing`? Why is it Webhook? 

I tried to delete an order refund with same syntax. It went through with force parameter being either true or false. The scenario where using force=false would remove the refund does not seem to agree with WooCommerce documentation. This is however a very minor issue.

**Comment by XiaoFaye** [comment]
The order refund doesn't support trashing, so whatever parameter you have set, it will always be true.

![image](https://user-images.githubusercontent.com/6334728/29966883-ef1fb09c-8f67-11e7-8b64-8170eed8afb4.png)

And the order note as well, but I need to have a look why you got that error.
