### ISSUE TITLE
Call Products of a certain category - Question

### ISSUE THREAD

**Issue by DemiladeA** [XiaoFaye/WooCommerce.NET#209]
- Wordpress version - WP 4.8.1
- WooCommerce version -  WC 3.1.2
- WooCommerce.NET version - 0.7.2

Is it possible to use ProductCategoryLine as a parameter in calling products, if yes how is this achieved.

e.g..
    `Dictionary<string, string> dic = new Dictionary<string, string>();`
    `dic.Add("categories", category.id);`
    `  var products = await wc.Product.GetAll(dic);`

**Comment by DemiladeA** [comment]
So I have been able to successfully filter the products to a certain category using 

`protected async override void OnAppearing()
        {
            var tappeditem = BindingContext as Category;
            BindingContext = null;
            title.Text = tappeditem.name;
            dic.Add("category", tappeditem.id);
            base.OnAppearing();
            Offset = 0;
            products = new List<Product>(await wc.Product.GetAll(dic));
            productlist.FlowItemsSource = products;
        }`

Binding Context is taken from the tapped item of a list of categories.

when I run on Postman using the parameters ("category", "categoryid") I get a list of products under that category but in Xamarin forms I get this error

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.v2.ProductMeta]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '[17].meta_data.0', line 1, position 119466.


When I take out `dic.Add("category", tappeditem.id);` I do not get the error

**Comment by XiaoFaye** [comment]
Try JSON.NET for deserializing.

**Comment by DemiladeA** [comment]
What should I deserialise, is there a way to request the deserialised string?

**Comment by DemiladeA** [comment]
What should I deserialise, is there a way to request the serialised string?

**Comment by DemiladeA** [comment]
I am already deserialising with JSON.NET (using Newtonsoft.Json) in my RESTAPI class, I have compared the Json response (using Postman) of a product with the category parameter and one without, the responses are the same and without the category parameter everything deserialises fine, with it I get the error

**Comment by XiaoFaye** [comment]
Try to get the product few per page and locate the item that has the problem.
