### ISSUE TITLE
Problem using the library in ASP.NET

### ISSUE THREAD

**Issue by bomyras** [XiaoFaye/WooCommerce.NET#210]
I'm using WooCommerce.NET (v0.7.1.0) in an ASP.NET (v4.0.30319) MVC app, and can't get the code to work. My view is calling a method in my Controller.cs to return a custom Order object containing data about a woocommerce order:

```[HttpPost]
public JsonResult GetOrder(int orderId)
{
	var order = store.GetOrder(orderId);

	return Json(new
	{
		msg = order
	});
}
```
The Controller calls a function in a different class, Store.cs, where the API is called, and the thread is blocked at t.Wait(), and the Ajax request in the browser dies:

```public Order GetOrder(int orderId)
{
	MyRestAPI rest = new MyRestAPI(apiUrl, key, secret);
	WCObject wc = new WCObject(rest);

	Task<WooCommerceNET.WooCommerce.v2.Order> t = wc.Order.Get(orderId);
	
	t.Wait();
	var wo = t.Result;
	
	// Populate order object
	Order order = new Order();
	order.Id = wo.id.HasValue ? wo.id.Value : 0;
	order.Total = wo.total.HasValue ? wo.total.Value : 0;
	
	return order;
}
```

Although I (think) I understand why the t.Wait() blocks the thread on the web server, I'm not able to find a workaround. I've tried using await, but ends up not understanding how to properly implement Task<T> (or similar) as return type and use it all the way up to my Controller that returns the result to the browser.

Would it be possible to explain how to go about to make this work?

**Comment by XiaoFaye** [comment]
You don't need `t.Wait()`, remove it and try again.

**Comment by bomyras** [comment]
Hi, thanks for the suggestion. I tried:

`Task<WooCommerceNET.WooCommerce.v2.Order> t = wc.Order.Get(orderId);

//t.Wait();
var wo = t.Result;`

and now the thread dies on:

`var wo = t.Result;`

**Comment by XiaoFaye** [comment]
Please update to the version 0.7.2 as it has the below fix:

>  3. Avoid Deadlocking on the UI Thread on non-async calls.

**Comment by bomyras** [comment]
Thanks, that worked perfectly!
