### ISSUE TITLE
Invalid signature provided signature does not match

### ISSUE THREAD

**Issue by lomache13** [XiaoFaye/WooCommerce.NET#211]
Wordpress version : 4.8.1
WooCommerce version : 3.1.2
WooCommerce.NET version : 0.7.2 (installed from NuGet Package Manager)

I was just trying to get all products from woocommerce using this code.

Code :
   ```
string URL = "http://example.com/wp-json/wc/v2";
   string ConsumerKey = "ck_xxxxxxxxxxxxxxxxxxxxxxxxxxx";
   string ConsumerSecret = "cs_xxxxxxxxxxxxxxxxxxxxxxxxxxx";

   RestAPI rest = new RestAPI(URL, ConsumerKey, ConsumerSecret);
   WCObject wc = new WCObject(rest);

   var products = await wc.Product.GetAll(); //throws error on this line
```

An exception of type 'System.Net.WebException' occurred in mscorlib.dll but was not handled in user code

Additional information: 
{
 "code":"woocommerce_rest_authentication_error",
 "message":"Invalid signature - provided signature does not match.",
 "data":{"status":401}
}

**Comment by XiaoFaye** [comment]
Can you check your wordpress url settings? it needs to match the one you are using in the api.

**Comment by lomache13** [comment]
Hi XiaoFaye  ,
Thank you for replying.

I wrote https instead of http and it worked but it thrown another Web Exception.

An exception of type 'System.Net.WebException' occurred in mscorlib.dll but was not handled in user code

Additional information:
"code":"woocommerce_rest_cannot_view",
"message":"Sorry, you cannot list resources.",
"data":{"status":401}

**Comment by XiaoFaye** [comment]
Check your wordpress / web server permissions.

**Comment by lomache13** [comment]
I changed 
`RestAPI rest = new RestAPI(URL, ConsumerKey, ConsumerSecret);`
to
`RestAPI rest = new RestAPI(URL, ConsumerKey, ConsumerSecret, false);`
and it worked should I use it this way ?

**Comment by XiaoFaye** [comment]
Sure, seems your server only accepts authorize through header.
