### ISSUE TITLE
C# code Invalid signature since last connection in june

### ISSUE THREAD

**Issue by Zoktrax** [XiaoFaye/WooCommerce.NET#214]
- Wordpress version 4.8.2 , WooCommerce version 3.1.2 and WooCommerce.NET version 072 (nuget)

Trying to connect to rest api from a C# project and tested this in june with success and now when I was ready to finalize the job I directly got this authentication issue with the keys even if I was using the same key. 

The difference is that I have updated wordpress and most likely the woocommerce plugin. Nothing is changed on the wp server side.

I have read every little piece of text around this issue and tested suggestions from other posts with no luck. (created new keys, new urls etc etc)

I also tested with postman and the url did not pass unless I clicked "Add params to header" and I am thinking this is some kind of clue to why it is not working but I do not know it means.

Very helpful for any help on this.

Code :

string URL = "http://example.com/wp-json/wc/v2";
string ConsumerKey = "ck_xxxxxxxxxxxxxxxxxxxxxxxxxxx";
string ConsumerSecret = "cs_xxxxxxxxxxxxxxxxxxxxxxxxxxx";

RestAPI rest = new RestAPI(URL, ConsumerKey, ConsumerSecret);
WCObject wc = new WCObject(rest);

var products = await wc.Product.GetAll(); //throws error on this line

Additional information:
{
"code":"woocommerce_rest_authentication_error",
"message":"Invalid signature - provided signature does not match.",
"data":{"status":401}
}

**Comment by quintonv** [comment]
I have the exact same issue with the latest version of WordPress and WooCommerce. It worked on older versions while testing and now just doesn't want to work anymore :(
