### ISSUE TITLE
Invalid decimal separator on decimal to string conversion

### ISSUE THREAD

**Issue by rtnet** [XiaoFaye/WooCommerce.NET#215]
I'm using legacy API.
Steps to reproduce:
- Set your Windows locales to polish (or any other which uses comma instead of dot as decimal separator)
- Try to update product price with decimal value, i.e.:
> int product_id = 2092;
> var product = new WooCommerceNET.WooCommerce.Legacy.Product();
> product.price = 10.44m;
> product.regular_price = 10.44m;
> await wc.UpdateProduct(product_id, product);
- This results as setting product price meta field = 10,44 instead of 10.44

WordPress 4.8.2, WC 3.1.2, WC-API v4.0.30319

**Comment by XiaoFaye** [comment]
Do you mean in Wordpress, the price shows as 10,44 instead of 10.44 after updating the price?

**Comment by rtnet** [comment]
That's right.
My solution is changing default decimal separator for all application threads

` string CultureName = Thread.CurrentThread.CurrentCulture.Name;
            CultureInfo ci = (CultureInfo)Thread.CurrentThread.CurrentCulture.Clone();
            if (ci.NumberFormat.NumberDecimalSeparator != ".")
            {
                ci.NumberFormat.NumberDecimalSeparator = ".";
                Thread.CurrentThread.CurrentCulture = ci;
                CultureInfo.DefaultThreadCurrentCulture = ci;
            }`

**Comment by XiaoFaye** [comment]
What if in Wordpress `,` has been chosen as separator?

**Comment by rtnet** [comment]
If You mean currency formatting - it doesn't matter
