### ISSUE TITLE
XmlException: Encountered unexpected character 'ï'.

### ISSUE THREAD

**Issue by StefanRotaru** [XiaoFaye/WooCommerce.NET#216]
I am getting the error XmlException: Encountered unexpected character 'ï'
 when I try to call any method (Product.GetAll, Order.Get(id)...)

Example:
RestAPI rest = new RestAPI("https://carnavalfiesta.com/wp-json/wc/v2/", "XXX", "XXX");
WCObject wc = new WCObject(rest);
var order = wc.Order.Get(25677).Result;

WooCommerce version is 3.2.0, maybe this is the problem.

**Comment by XiaoFaye** [comment]
It seems the API doesn't return the correct json string, please check what result has been returned, it will contain the error message.

**Comment by thanhliemldzz** [comment]
I found the same issue, after change my WC store language to Vietnamese. I pasted the json string into notepad++ and found some unexpected unicode chars at the beginning of the string. To fix it, just remove these charaters. Try the below code:

 private async Task<string> GetStreamContent(Stream s, string charset)
        {
            StringBuilder sb = new StringBuilder();
            byte[] Buffer = new byte[512];
            int count = 0;
            count = await s.ReadAsync(Buffer, 0, Buffer.Length).ConfigureAwait(false);
            while (count > 0)
            {
                sb.Append(Encoding.GetEncoding(charset).GetString(Buffer, 0, count));
                count = await s.ReadAsync(Buffer, 0, Buffer.Length).ConfigureAwait(false);
            }

            //Remove unexpected Unicode char
            string jsonStr = Regex.Replace(sb.ToString(), @"[^\u0000-\u007F]+", string.Empty);

            return jsonStr;
        }

**Comment by XiaoFaye** [comment]
you can use jsonDeserializeFilter to fix this issue.

**Comment by goguvi** [comment]
Same thing happened to me, my problem was a special character at the beginning of wordpress wp-config.
