### ISSUE TITLE
Update product variation price

### ISSUE THREAD

**Issue by rtmrodrigues** [XiaoFaye/WooCommerce.NET#217]
- Wordpress version: 4.8.2, WooCommerce version: 3.2.1 and WooCommerce.NET version: 0.7.2

1. Setup a product with one attribute used for variations;
2. Add variations to the product and specify a price for each variation;
3. Invoque UpdateProduct with some changes on stock and price i.e.:

        Dim pr As Legacy.Product = Nothing
        pr = Await WCAPI.GetProduct("4123")
        Dim prVar As Legacy.VariationList = Nothing
        prVar = pr.variations

        pr.stock_quantity = 12
        prVar(0).price = "17.87"
        prVar(0).regular_price = "17.87"

        Dim resUpdateProduct As String = ""
        resUpdateProduct = Await WCAPI.UpdateProduct("4123", pr)

4. Check that the price does not suffer any changes.

-------------------------------------------------------------------------------------------------------------
- What i´ve checked:
1. For some reason, in class Variation, the data members for price, regular Price and sale_price are set as private (please let me know why);
2. If we setup those data members has public, and change our "UpdateProduct" as follows, the price is updated.

        Dim pr As Legacy.Product = Nothing
        pr = Await WCAPI.GetProduct("4123")
        Dim prVar As Legacy.VariationList = Nothing
        prVar = pr.variations

        pr.stock_quantity = 12
        prVar(0).priceValue = "17.87"   ->'priceValue' instead of just 'price'
        prVar(0).regular_priceValue = "17.87"  ->'regular_priceValue' instead of just 'regular_price'

        Dim resUpdateProduct As String = ""
        resUpdateProduct = Await WCAPI.UpdateProduct("4123", pr)

Am I doing something wrong by changing the members to public?

Thank you.

**Comment by XiaoFaye** [comment]
1. Check the JsonObject, you can see how it handles the prices. It's because sometimes WC will return empty string or null in the json string. It needs to be handled manually.

2. In Product.cs file, if you make the Variation object inherit from JsonObject, it should fix the problem.

3. I will suggest you use the latest version of the API instead of the legacy one.

**Comment by rtmrodrigues** [comment]
Thank you.

I will check it out and give some feedback.

**Comment by rtmrodrigues** [comment]
Ok then...i have changed from legacy to V2 and build some code as follows to test:

        Dim pr As Product = Nothing
        Dim resUpdateProduct As Product
        Dim prVars As List(Of Variation) = Nothing

        pr = Await MFP_WCAPI.Product.Get(Me.TextBox1.Text)
        prVars = Await MFP_WCAPI.Product.Variations.GetAll(pr.id)
        For Each var As Variation In prVars
            var.price = 99
            var.regular_price = 98
            var.sale_price = 97
        Next

        resUpdateProduct = Await MFP_WCAPI.Product.Update(Me.TextBox1.Text, pr)
        prVars = Nothing
        pr = Nothing
        MsgBox("End!")

I´m getting the same problems has on legacy!
May its because i did not understood how to "make the Variation object inherit from JsonObject"...can you give me a hint?

Thank you.

**Comment by XiaoFaye** [comment]
Change 
`public Class Variation`
to
`public Class Variation : JsonObject`
