### ISSUE TITLE
.Net Standard 2.0 Support

### ISSUE THREAD

**Issue by reader-man** [XiaoFaye/WooCommerce.NET#218]
Hi,
 Thanks for this great plugin, but is it possible to port this library to .Net Standard 2.0, so it can be used on multiple types of devices?

Regards.

**Comment by vankampenp** [comment]
@reader-man  I assume if you include the source in your project, it will compile on .NET Standard 2.0.

**Comment by vankampenp** [comment]
I can confirm that I can compile and execute 0.7.2.0 on .NETStandard 2.0

Three changes:
- WooCommerceNet.csproj changes to migrate to 2.0
- Removed Properties\AssemblyInfo.cs and put these properties in csproj
- Removed public class JsonObject from BaseObject.cs as there is a separate Jsonobject class

After compiling, my app was able to use V1 as before. 

I only use a small set of features, so I have not tested everything.

Regards

**Comment by HakanL** [comment]
I didn't see this initially. Duplicate (and PR) #242

**Comment by XiaoFaye** [comment]
It's in version 0.7.4 now.
