### ISSUE TITLE
ProductCategoryLine versus ProductCategory?

### ISSUE THREAD

**Issue by Zoktrax** [XiaoFaye/WooCommerce.NET#219]
Wordpress version 4.8.2 , WooCommerce version 3.1.2 and WooCommerce.NET version 072 (nuget)

Hi all woocommerce.net hackers,
I am having some trouble to understand the changes in latest version in handling categories when creating a product.

What is the relation between ProductCategory and ProductCategoryLine?

To first get all the categories that exist I use:
var prod_cats = await wc.Category.GetAll();
This is to be able to assign correct categoryID to a certain product that I will create.

I get all the ProductCategorys but cannot use these to assign to a product since it is not a ProductCategoryLine.

`//Add new product
                Product p = new Product()
                {
                    name = "test product 8",

                    description = "test product 8",

                    status = "draft",
                    short_description = "Test produkt 8",
                    sku = "1234566",
                    Categories = categoryListOfProductCategories //This does not work to cannot assign ProductCategory to ProductCategoryLine
                };`

Any info would be super!
Thanks in advance.
//Z

**Comment by MarcoCordes** [comment]
I have the same Problem - i have a List from Categories 
`List<ProductCategory>`

and the Product Item need a List from CategoryLine Items :-/ 

Pls help..

**Comment by Zoktrax** [comment]
Sorry for late reply.

I just do it like this with CategoryLine.

` 
//First add certain product
Product pWoo = await wc.Product.Add(p);

pWoo.categories = new List<ProductCategoryLine>();
WooCommerceNET.WooCommerce.v2.ProductCategoryLine _CategoryLine = new WooCommerceNET.WooCommerce.v2.ProductCategoryLine();
// Then create a Category line
 var simple_cat3 = new WooCommerceNET.WooCommerce.v2.ProductCategory
                                                {
                                                    //not needed id = cats.id,
                                                    name = strItemGroupDescription,
                                                    slug = strItemGroupDescription_S,
                                                    parent = catIDLevel2
                                                };
ProductCategory pC3 = await wc.Category.Add(simple_cat3);
 _CategoryLine3.id = pC3.id;
 pWoo.categories.Add(_CategoryLine3);

//And then update the product with new category
 var pWooResult = await wc.Product.Update((int)pWoo.id, pWoo);
`
