### ISSUE TITLE
Products meta fields are not returned

### ISSUE THREAD

**Issue by DaniusLabs** [XiaoFaye/WooCommerce.NET#22]
Hello,

this one is probably due to my lack of knowledge of WP API but any help is appreciated. 
I dont seem to be able to retrieve customer product file fields in json. 
I doo see placeholders if i use the old wc-api/v3 but no data.

Thank You!

**Comment by XiaoFaye** [comment]
I think you need to set parameter filter[meta] on GetProducts to get the meta data.

**Comment by DaniusLabs** [comment]
i think that filter only works for legacy api?!

Cheers

**Comment by XiaoFaye** [comment]
You are right, I can't find anything regarding meta data in the latest WP API. You might want to use the native WP API to get the post mate directly, getting post id won't be an issue. rest-api plugin will be needed as they haven't fully integrated into Wordpress core.

**Comment by XiaoFaye** [comment]
You might be able to use the filter parameter as it accepts WP_Query arguments.

filter	string	Use WP Query arguments to modify the response; private query vars require appropriate authorization.

**Comment by DaniusLabs** [comment]
Thanks James. I will have to dig in deeper. As I am struggling with the WP API, all i have is Woo endpoints. I appreciate is not an issue with our wrapper. Happy to close this thread. Thanks.
