### ISSUE TITLE
Order Count Questions

### ISSUE THREAD

**Issue by TezWingfield-RetainMe** [XiaoFaye/WooCommerce.NET#224]
First of all, fantastic work! Saved me a lot of time!

However, I do have one question, How do I use the library to obtain the order count (int)? I feel I have gone through the code to understand that the functionality may not exist?

I don't want to have to "GetAll" to get the order count, this probably would return "x" amount in page 1 anyway. 

What I'd ideally like to do, is get the order count, divide by "per_page=50" to give me a list of pages, in which I then can loop through client side, passing in the page number.

Regards,

**Comment by XiaoFaye** [comment]
Please check this one: #196

**Comment by TezWingfield-RetainMe** [comment]
@XiaoFaye Much appreciated, I'll move further queries to the other thread.

Regards,
