### ISSUE TITLE
creating new line_items in order

### ISSUE THREAD

**Issue by TompieD** [XiaoFaye/WooCommerce.NET#226]
I was wondering if i can create new line lineitems in a order?
this is my code now:
`var order = new Order(){status="pending"};
order.line_items.Add(new OrderLineIItem()
{
product_id=product.id,
quantity = 1
});
wc.Order.Add(order);`
i can create the order, but without line items
please help, making a POS system

**Comment by XiaoFaye** [comment]
Are you using the API version 2?

**Comment by TompieD** [comment]
using api version 2 and woocommerce 3.2.4.
and my code above is not correct.
i create a order when clicked on btnAdd and store the order in a class variable.
then i get product by sku and add it in the order.lineitems.
so i the order is already created in woocommerce and then i try to add the line_items.

**Comment by TompieD** [comment]
this was my error.
i have to do this with 1 request to woocommerce.
so you cant add new line_items to a pending order in woocommerce

**Comment by XiaoFaye** [comment]
can't add new line_items to a pending order in woocommerce makes sense.

Good to hear that you have solved the problem, I will close this issue now.
