### ISSUE TITLE
Product - Variants use external URL

### ISSUE THREAD

**Issue by hohuuhau** [XiaoFaye/WooCommerce.NET#227]
Hello,
I'm trying to create product and variants with external URL.
I created product and variants with external URL with #129 but images will re-upload in my server.
I'm tried to use meta_data, but can't load images by color.
It's possible or not? And how can i do it?
Note: API version 2.

Many thanks,
Tomy Ho

**Comment by XiaoFaye** [comment]
If the image is already uploaded, you will need to pass the image ID.

**Comment by hohuuhau** [comment]
Thanks for reply, but i want external from other site and i don't want image re-upload in my server.
Example:
- My site: abc.com
- Image external: xyz.com/img.jpg
Do you have any solution for this?

**Comment by XiaoFaye** [comment]
I don't think featured image supports external url in Wordpress directly.

**Comment by hohuuhau** [comment]
Thanks you XiaoFaye. I will wait Wordpress update new version.
