### ISSUE TITLE
The type 'HttpWebRequest' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by raulcarrion** [XiaoFaye/WooCommerce.NET#229]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

WooCommerce.NET versión 0.7.2 
.Net Framework 4.5.2
Newtonsoft.Json 10.0.3

- Steps to replicate the issue

public RCRestAPI(string url, string key, string secret, bool authorizedHeader = true,
            Func<string, string> jsonSerializeFilter = null,
            Func<string, string> jsonDeserializeFilter = null,
            Action<HttpWebRequest> requestFilter = null) : **base**(url, key, secret, authorizedHeader, jsonSerializeFilter, jsonDeserializeFilter, requestFilter)
        {
    }

- Details of the error message if there is any

`The type 'HttpWebRequest' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Requests, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Hi, When declaring my RestAPI class this error is generated. How can I solve that?

Thank you very much

**Comment by XiaoFaye** [comment]
What was your project type? I have tried on Console App with .NET Framework 4.5.2, works fine.

```
        public RCRestAPI(string url, string key, string secret, bool authorizedHeader = true,
                            Func<string, string> jsonSerializeFilter = null,
                            Func<string, string> jsonDeserializeFilter = null,
                            Action<HttpWebRequest> requestFilter = null) : base(url, key, secret, authorizedHeader, jsonSerializeFilter, jsonDeserializeFilter, requestFilter)
        {

        }
```
