### ISSUE TITLE
List of products

### ISSUE THREAD

**Issue by suhomlineugene** [XiaoFaye/WooCommerce.NET#23]
Hello.

How can I retrieve list of products in order?

**Comment by XiaoFaye** [comment]
Use GetProducts with orderby filter.

http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by suhomlineugene** [comment]
So how I need to write code?
I try this. But I dont have orderby
var product = await wc.GetProducts();

            Debug.WriteLine(product[0].orderby);

**Comment by XiaoFaye** [comment]
Please check the code example in project home page: https://github.com/XiaoFaye/WooCommerce.NET

**Comment by suhomlineugene** [comment]
You talk about `//Use filters`

**Comment by XiaoFaye** [comment]
yes

**Comment by suhomlineugene** [comment]
Okay.

For orderid filter i need to write it like this?

```
var p = await wc.GetProducts(new Dictionary<string, string>() {
                { "fields", "id" },
                { "filter[limit]", "15" } });
```

**Comment by XiaoFaye** [comment]
try var p = await wc.GetProducts(new Dictionary<string, string>() {{ "orderby", "id" } });

**Comment by suhomlineugene** [comment]
in id I need to write id of order?

**Comment by suhomlineugene** [comment]
and how  I can display to console data of this query?

**Comment by suhomlineugene** [comment]
I try to use this code

`  var p = await wc.GetProducts(new Dictionary<string, string>() {
                { "orderby", "id" }, { "filter[search]", "1884" }
                 });`



How I can display data in debug console?

**Comment by XiaoFaye** [comment]
Console.WriteLine("your debug info...");

**Comment by javapach** [comment]
Hello, I am trying to list the products, but when I run `var products = await wc.GetProducts();` , I always returns, "STATUS=WaitingForActivation", you know why ?.  thanks

**Comment by XiaoFaye** [comment]
Have you used async and await?
