### ISSUE TITLE
Can't update Orders through API after update to Wordpress 4.9.1

### ISSUE THREAD

**Issue by bomyras** [XiaoFaye/WooCommerce.NET#230]
I upgraded to WordPress 4.9 and then it automatically updated to Wordpress 4.9.1 on the same day.
WooCommerce version: 3.2.3 (also tested with WooCommerce version 3.2.5 with same behavior)
WooCommerce.NET version: 0.7.2.0

I'm using the code below to modify the status of the order and add or update 7 OrderMeta objects to the order. When executed, wo = t.Result contains the order with the updated data, but in Wordpress the order is not completed and the meta data is not added. 

This was working before the update of Wordpress, and now it's not.

`
                Task<WooCommerceNET.WooCommerce.v2.Order> t = wc.Order.Get(order.OrderId);
                var wo = t.Result;

                switch(order.Status)
                { 
                    case OrderStatusEnum.Completed:
                        wo.status = "completed";
                        break;
                    default:
                        wo.status = "pending";
                        break;
                }

                if(order.Consignment.Response.Status == ConsignmentResponseStatus.Successful)
                {
                    var om1 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om1.key = "consignment_trackingurl";
                    if (wo.meta_data.Find(m => m.key == om1.key) != null)
                        om1 = wo.meta_data.Find(m => m.key == om1.key);
                    else
                        wo.meta_data.Add(om1);
                    om1.value = order.Consignment.Response.TrackingUrl;

                    var om2 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om2.key = "consignment_number";
                    if (wo.meta_data.Find(m => m.key == om2.key) != null)
                        om2 = wo.meta_data.Find(m => m.key == om2.key);
                    else
                        wo.meta_data.Add(om2);
                    om2.value = order.Consignment.Response.NumberWithChecksum;

                    var om3 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om3.key = "consignment_carrier";
                    if (wo.meta_data.Find(m => m.key == om3.key) != null)
                        om3 = wo.meta_data.Find(m => m.key == om3.key);
                    else
                        wo.meta_data.Add(om3);
                    om3.value = order.Consignment.Agreement.CarrierName;

                    var om4 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om4.key = "consignment_cost";
                    if (wo.meta_data.Find(m => m.key == om4.key) != null)
                        om4 = wo.meta_data.Find(m => m.key == om4.key);
                    else
                        wo.meta_data.Add(om4);
                    om4.value = order.Consignment.Response.CostEstimateNet;

                    var om5 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om5.key = "consignment_weight";
                    if (wo.meta_data.Find(m => m.key == om5.key) != null)
                        om5 = wo.meta_data.Find(m => m.key == om5.key);
                    else
                        wo.meta_data.Add(om5);
                    om5.value = order.Consignment.Items.Sum(i => i.Amount * i.Weight);

                    var om6 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om6.key = "consignment_count";
                    if (wo.meta_data.Find(m => m.key == om6.key) != null)
                        om6 = wo.meta_data.Find(m => m.key == om6.key);
                    else
                        wo.meta_data.Add(om6);
                    om6.value = order.Consignment.Items.Sum(i => i.Amount);

                    var om7 = new WooCommerceNET.WooCommerce.v2.OrderMeta();
                    om7.key = "consignment_product";
                    if (wo.meta_data.Find(m => m.key == om7.key) != null)
                        om7 = wo.meta_data.Find(m => m.key == om7.key);
                    else
                        wo.meta_data.Add(om7);
                    om7.value = order.Consignment.Product.Name;
                }

                Task<WooCommerceNET.WooCommerce.v2.Order> ot = wc.Order.Update(order.OrderId, wo);
                wo = t.Result;
`

Can you advice on what to do?

**Comment by XiaoFaye** [comment]
Can you try to update the order status only and see how it goes?

**Comment by FernandoHlibka** [comment]
I have the same problem, how o fix it?

**Comment by FernandoHlibka** [comment]
I have the same error, how i fix it? *

**Comment by CowTail** [comment]
Same happens for me. In update 4.9, they apparently made the following changes:

- REST API: Support registering complex data structures for settings and meta
- REST API: Support for objects in schema validation and sanitization (#[38583](https://core.trac.wordpress.org/ticket/38583))

Here's an example of the error message I get:
{"code":"rest_invalid_param","message":"Invalid parameter(s): line_items, shipping_lines","data":{"status":400,"params":{"line_items":"line_items[0][subtotal] is not of type string.","shipping_lines":"shipping_lines[0][total] is not of type string."}}}

Seems they're utilizing data structures now. I believe this will happen for more than one parameter and not just in the error above.

Any chance of a quick fix?

**Comment by XiaoFaye** [comment]
@CowTail Have you try to using Json.NET for deserilizing?

**Comment by CowTail** [comment]
That is the error response I get when sending an order via wc.Order.Update(). I've been using the same code implementation for months, and it had been working perfectly until the wordpress 4.9 update occurred.

But yes, I'm serializing/deserializing with Newtonsoft.Json. Judging by the error message, subtotal and total now need to be string instead of decimal. I'll dive into the wc.NET code myself later but any insight would be helpful.

**Comment by bomyras** [comment]
@XiaoFaye I tried commenting out the meta data, and just updating the oder status, but the order is not updated at all.

**Comment by arber** [comment]
Hello,

it looks like the problem is in the data type of "subtotal", "subtotal_tax" fields in OrderLineItem class and "discount" and "discount_tax" fields in OrderCouponLine. Change the data type of these properties from decimal? to string and it will work, at least it did in my case.

Regards,
Arber

**Comment by FernandoHlibka** [comment]
@arber i tried and your solutions and return this message: 

---------------------------

---------------------------
System.Net.WebException: {"code":"rest_invalid_param","message":"Par\u00e2metro(s) inv\u00e1lido(s): meta_data","data":{"status":400,"params":{"meta_data":"meta_data[0][value] n\u00e3o \u00e9 type string."}}}

**Comment by arber** [comment]
@FernandoHlibka 

I think wordpress expects meta_data[0][value] to be of type String so you should change that too.

Regards,
Arber

**Comment by FernandoHlibka** [comment]
@arber i tried change List<OrderMeta> meta_data to string but i have the same problem... can you publish a pic with meta_data property to change to string?

**Comment by FernandoHlibka** [comment]
I got it \o/ I just updated woocommerce and it works fine

**Comment by bomyras** [comment]
Updating to WooCommerce version 3.2.5 solved the issue.

**Comment by Luke03** [comment]
Getting the exact same error with WooCommerce 3.2.6 and WooCommerceNET 0.7.4 when trying to update an order:
`                        if (order.id.HasValue)
                        {
                            order.status = "completed";
                            await wc.Order.Update(order.id.Value, order);
                        }
`
Error:
> WebException: {"code":"rest_invalid_param","message":"Invalid parameter(s): line_items","data":{"status":400,"params":{"line_items":"line_items[0][subtotal] is not of type string."}}}

Previously with WooCommerce 3.2.3 this was working just fine.

**Comment by IcuScc** [comment]
I get the same problem.
i try several options but i dont get the solution.
