### ISSUE TITLE
Woocommerce webhooks

### ISSUE THREAD

**Issue by vankampenp** [XiaoFaye/WooCommerce.NET#232]
### Make sure you have included the below details when open an issue. Thank you.

Sorry if this the wrong place to ask. Is there a way to use a Woocommerce webhook? I want to react to an order.

Thx Pieter

**Comment by XiaoFaye** [comment]
Try this, it might help:

https://growdevelopment.com/woocommerce-webhooks/

**Comment by vankampenp** [comment]
Thanks James,
I am looking for the C# implementation of a webhook that I can call from Woocommerce.

Regards Pieter



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: James Yang <notifications@github.com>
Datum: 07-01-18 05:52 (GMT+01:00)
Aan: "XiaoFaye/WooCommerce.NET" <WooCommerce.NET@noreply.github.com>
Cc: pieter@datec.nl, Author <author@noreply.github.com>
Onderwerp: Re: [XiaoFaye/WooCommerce.NET] Woocommerce webhooks (#232)


Try this, it might help:

https://growdevelopment.com/woocommerce-webhooks/

-

**Comment by vankampenp** [comment]
What is the Woocommerce Net webhook class? Can I use it for this?

**Comment by vankampenp** [comment]
I found that Webhooks will be supported in Asp.NET Core in the next release. There is a Microsoft project that supports it on other platforms now. The last announcement dates back to 2016, but there seems some recent life to it on GitHub, and the new release is announced and will ship with Core 2.1.
