### ISSUE TITLE
Unable to create coupon

### ISSUE THREAD

**Issue by Manthan2611** [XiaoFaye/WooCommerce.NET#235]
Hi All,

Using V1 API to post/create coupon  using the following code.
`Coupon c = new Coupon()
            {
                code = "111off"
            };

       var res =  wc.PostCoupon(c)`

After executing it is not getting created. 
Am i doing anything wrong? please correct me if i am wrong. 

However i am able to create coupons using V2 API.  

Thanks,
Manthan

**Comment by XiaoFaye** [comment]
Have you set discount_type?

**Comment by Manthan2611** [comment]
Nop, I didn't set that.

Thank XiaoFaye
