### ISSUE TITLE
Encountered unexpected character '<'

### ISSUE THREAD

**Issue by rex644** [XiaoFaye/WooCommerce.NET#236]
There was an error deserializing the object of type WooCommerceNET.WooCommerce.v2.Product. Encountered unexpected character '<'.

Code:
`wc.Product.Add(p)`

**Comment by XiaoFaye** [comment]
What was the returned json string?

**Comment by rex644** [comment]
at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.Base.WCItem`1.<Add>d__11.MoveNext()

**Comment by tjoubert** [comment]
Hi
I am getting exactly this same error. The returned JSON in my case is as follows. Actually, it looks like a mixture of JSON and HTML:

`<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="http://www.pondconsulting.biz/wp-json/wc/v2/products/13">here</a></body>{"id":13,"name":"Product 99e0466d-a0c5-4b9b-a231-d3074e2d49f1","slug":"product-99e0466d-a0c5-4b9b-a231-d3074e2d49f1","permalink":"http:\/\/www.pondconsulting.biz\/product\/product-99e0466d-a0c5-4b9b-a231-d3074e2d49f1\/","date_created":"2018-02-16T10:56:40","date_created_gmt":"2018-02-16T10:56:40","date_modified":"2018-02-16T10:56:40","date_modified_gmt":"2018-02-16T10:56:40","type":"simple","status":"publish","featured":false,"catalog_visibility":"visible","description":"","short_description":"","sku":"","price":"","regular_price":"","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"price_html":"","on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"in_stock":true,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0","rating_count":0,"related_ids":[12,8],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":15,"name":"Uncategorized","slug":"uncategorized"}],"tags":[],"images":[{"id":0,"date_created":"2018-02-16T10:56:42","date_created_gmt":"2018-02-16T10:56:42","date_modified":"2018-02-16T10:56:42","date_modified_gmt":"2018-02-16T10:56:42","src":"http:\/\/www.pondconsulting.biz\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","name":"Placeholder","alt":"Placeholder","position":0}],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"meta_data":[],"_links":{"self":[{"href":"http:\/\/www.pondconsulting.biz\/wp-json\/wc\/v2\/products\/13"}],"collection":[{"href":"http:\/\/www.pondconsulting.biz\/wp-json\/wc\/v2\/products"}]}}`


Any assistance that you could provide would be very much appreciated.

Best regards

Terence

**Comment by rex644** [comment]
We had to run an older version of PHP to fix the issue. Also we found we could use the older WooCommerce functions (or was version 2 the older option, I cant remember). Also we found that the Linux version of PHP was much better and I think we could run the newer version of PHP and WooCommerce on Linux.

**Comment by tjoubert** [comment]
I am developing in C# in .NET 4.5 on Windows (not PHP on Linux).
I followed the instructions in the post at https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-JSON.NET-in-WooCommerce.NET

The workaround to solve this problem, is to replace the DeserializeJSon<T>() method under point 3 with the following:

`        public override T DeserializeJSon<T>(string jsonString)
        {
            if (jsonString.Trim().StartsWith("<"))
                jsonString = jsonString.Substring(jsonString.IndexOf("{"), jsonString.Length - jsonString.IndexOf("{"));
            return JsonConvert.DeserializeObject<T>(jsonString);
        }`

This removes all the XML elements that appears before the JSON string. It's not the best solution, but it works for now!

**Comment by PolyXGO** [comment]
@tjoubert !
It working for me! you save my application.
Thank you so much!!!
