### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by rex644** [XiaoFaye/WooCommerce.NET#237]
Both of these lines of code would cause the error.

**Code**
```
wc.Product.Add(p)
wc.Product.Delete(128)
```

**Error I am getting:**

<title>IIS 8.5 Detailed Error - 405.0 - Method Not Allowed</title> 
<h4>More Information:</h4> 
  This error means that the request sent to the Web server contained an HTTP verb that is not allowed by the configured module handler for the request. 
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=405,0,0x80070001,9600">View more information &raquo;</a></p> 

**Detailed Error**

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 8.5 Detailed Error - 405.0 - Method Not Allowed</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 405.0 - Method Not Allowed</h3> 
  <h4>The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.</h4> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Most likely causes:</h4> 
  <ul> 	<li>The request sent to the Web server used an HTTP verb that is not allowed by the module configured to handle the request.</li> 	<li>A request was sent to the server that contained an invalid HTTP verb.</li> 	<li>The request is for static content and contains an HTTP verb other than GET or HEAD.</li> 	<li>A request was sent to a virtual directory using the HTTP verb POST and the default document is a static file that does not support HTTP verbs other than GET or HEAD.</li> </ul> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Things you can try:</h4> 
  <ul> 	<li>Verify the list of verbs enabled for the module handler this request was sent to, and ensure that this verb should be allowed for the Web site.</li> 	<li>Check the IIS log file to see which verb is not allowed for the request.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>Detailed Error Information:</h4> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;StaticFileModule</td></tr> 
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;StaticFile</td></tr> 
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070001</td></tr> 
     
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://pointofsalestore.jeffcomputers.com:80/point_of_sale_store/index.php?oauth_consumer_key=ck_ca8cfda922984877e364ad6a2f366b14db623f0a&amp;oauth_nonce=5fba6d99894e4c7f98f186c73121b97c&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_timestamp=1515517298&amp;consumer_key=ck_ca8cfda922984877e364ad6a2f366b14db623f0a&amp;consumer_secret=cs_303ac6a3ca19c674df0c6774ccc54a73105a5fe9%26&amp;oauth_signature=LCZky5XKG1GqCuLGjDGHeEseGHyb8JnNNNsH4%2BhLZfU%3D</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\inetpub\studyx\point_of_sale_store\index.php</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
     
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>More Information:</h4> 
  This error means that the request sent to the Web server contained an HTTP verb that is not allowed by the configured module handler for the request. 
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=405,0,0x80070001,9600">View more information &raquo;</a></p> 
   
 </fieldset> 
</div> 
</div> 
</body> 
</html>

**Comment by XiaoFaye** [comment]
This is a permission issue, make sure your web server settings are all correct.

**Comment by rex644** [comment]
We added more permissions:
Delete is still giving me the same error.

On add we get this error but it still works:
{"code":"woocommerce_rest_product_invalid_id","message":"Invalid ID.","data":{"status":400}}
