### ISSUE TITLE
There is an error in price format

### ISSUE THREAD

**Issue by kamcioju** [XiaoFaye/WooCommerce.NET#24]
on woocomerence we can choose decimal separator, and it produce an error when we change it
should be:
 pi.SetValue(this, decimal.Parse(value.ToString().Replace(".",",")))
instead of:
 pi.SetValue(this, decimal.Parse(value.ToString()))

**Comment by XiaoFaye** [comment]
I tried to change the thousand separator and decimal separator in version 2.6.4, no error, it seems the REST API will always return standard format for decimal numbers.

**Comment by XiaoFaye** [comment]
Could you please confirm this or provide more information? so I can close this issue. Thanks!
