### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by AliciaRabbit** [XiaoFaye/WooCommerce.NET#241]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by shariqshahzad** [comment]
im getting the same error 
woocommerce version v2 and .net version 0.7.2
The details of error message are 
'{"code":"woocommerce_rest_authentication_error","message":"Klant-geheim is ongeldig.","data":{"status":401}}'

**Comment by danielmoorehbd** [comment]
I believe that the authentication via headers is failing here: https://github.com/woocommerce/woocommerce/blob/3.3.3/includes/api/class-wc-rest-authentication.php#L146 which is to say that one or both of $_SERVER['PHP_AUTH_USER'] $_SERVER['PHP_AUTH_PW'] is being stripped/emptied

**Comment by XiaoFaye** [comment]
Check here : https://github.com/XiaoFaye/WooCommerce.NET/blob/85d79bee931607650fa068dcb6ee7fccffd87e1d/RestAPI.cs#L40
