### ISSUE TITLE
DeserializeJSon Error by using latest API

### ISSUE THREAD

**Issue by vip30** [XiaoFaye/WooCommerce.NET#25]
Used Plugin:wp-json/wc/v1/
WooCommerce.Net 0.5.1
Wordpress Version 4.6.1
WooCommerce 2.6.4

It stuck on API.DeserializeJSon<ProductList>(json)

`There was an error deserializing the object of type WooCommerceNET.WooCommerce.ProductList. The value '' cannot be parsed as the type 'decimal'.`

But using the wc-api/v3/, it's ok.

**Comment by XiaoFaye** [comment]
Could you tell me which decimal field in your json shows as '' (empty string)? Thanks.

**Comment by vip30** [comment]
`[{\"id\":77,\"name\":\"BallBall\",\"slug\":\"%e6%b3%a2%e6%b3%a2\",\"permalink\":\"http:\\/\\/example.com\\/product\\/%e6%b3%a2%e6%b3%a2\\/\",\"date_created\":\"2016-09-07T07:26:51\",\"date_modified\":\"2016-09-09T07:56:50\",\"type\":\"variable\",\"status\":\"publish\",\"featured\":false,\"catalog_visibility\":\"visible\",\"description\":\"<p>ballballballballballball<\\/p>\\n\",\"short_description\":\"\",\"sku\":\"dsfdsfdsfsdf\",\"price\":\"234\",\"regular_price\":\"\",\"sale_price\":\"\",\"date_on_sale_from\":\"\",\"date_on_sale_to\":\"\",\"price_html\":\"<span class=\\\"woocs_price_code\\\" data-product-id=\\\"77\\\"><span class=\\\"woocommerce-Price-amount amount\\\">234.00<span class=\\\"woocommerce-Price-currencySymbol\\\">&#36;<\\/span><\\/span><\\/span>\",\"on_sale\":false,\"purchasable\":true,\"total_sales\":0,\"virtual\":false,\"downloadable\":false,\"downloads\":[],\"download_limit\":-1,\"download_expiry\":-1,\"download_type\":\"standard\",\"external_url\":\"\",\"button_text\":\"\",\"tax_status\":\"taxable\",\"tax_class\":\"\",\"manage_stock\":true,\"stock_quantity\":200,\"in_stock\":true,\"backorders\":\"no\",\"backorders_allowed\":false,\"backordered\":false,\"sold_individually\":false,\"weight\":\"\",\"dimensions\":{\"length\":\"\",\"width\":\"\",\"height\":\"\"},\"shipping_required\":true,\"shipping_taxable\":true,\"shipping_class\":\"\",\"shipping_class_id\":0,\"reviews_allowed\":true,\"average_rating\":\"0.00\",\"rating_count\":0,\"related_ids\":[],\"upsell_ids\":[],\"cross_sell_ids\":[],\"parent_id\":0,\"purchase_note\":\"\",\"categories\":[],\"tags\":[],\"images\":[{\"id\":0,\"date_created\":\"2016-09-09T15:57:46\",\"date_modified\":\"2016-09-09T15:57:46\",\"src\":\"http:\\/\\/example.com\\/wp-content\\/plugins\\/woocommerce\\/assets\\/images\\/placeholder.png\",\"name\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"alt\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"position\":0}],\"attributes\":[{\"id\":1,\"name\":\"Size\",\"position\":0,\"visible\":true,\"variation\":true,\"options\":[\"\\u4e2d\"]}],\"default_attributes\":[],\"variations\":[{\"id\":112,\"date_created\":\"2016-09-09T07:56:25\",\"date_modified\":\"2016-09-09T07:56:43\",\"permalink\":\"http:\\/\\/example.com\\/product\\/%e6%b3%a2%e6%b3%a2\\/?attribute_pa_size=%25e4%25b8%25ad\",\"sku\":\"dsfdsfdsfsdf\",\"price\":\"234\",\"regular_price\":\"234\",\"sale_price\":\"\",\"date_on_sale_from\":\"\",\"date_on_sale_to\":\"\",\"on_sale\":false,\"purchasable\":true,\"visible\":true,\"virtual\":false,\"downloadable\":false,\"downloads\":[],\"download_limit\":-1,\"download_expiry\":-1,\"tax_status\":\"taxable\",\"tax_class\":\"\",\"manage_stock\":\"parent\",\"stock_quantity\":200,\"in_stock\":true,\"backorders\":\"no\",\"backorders_allowed\":false,\"backordered\":false,\"weight\":\"\",\"dimensions\":{\"length\":\"\",\"width\":\"\",\"height\":\"\"},\"shipping_class\":\"\",\"shipping_class_id\":0,\"image\":[{\"id\":0,\"date_created\":\"2016-09-09T15:57:46\",\"date_modified\":\"2016-09-09T15:57:46\",\"src\":\"http:\\/\\/example.com\\/wp-content\\/plugins\\/woocommerce\\/assets\\/images\\/placeholder.png\",\"name\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"alt\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"position\":0}],\"attributes\":[{\"id\":1,\"name\":\"Size\",\"option\":\"%e4%b8%ad\"}]}],\"grouped_products\":[],\"menu_order\":0,\"_links\":{\"self\":[{\"href\":\"http:\\/\\/example.com\\/wp-json\\/wc\\/v1\\/products\\/77\"}],\"collection\":[{\"href\":\"http:\\/\\/example.com\\/wp-json\\/wc\\/v1\\/products\"}]}}]""\n\n[{\"id\":77,\"name\":\"BallBall\",\"slug\":\"%e6%b3%a2%e6%b3%a2\",\"permalink\":\"http:\\/\\/example.com\\/product\\/%e6%b3%a2%e6%b3%a2\\/\",\"date_created\":\"2016-09-07T07:26:51\",\"date_modified\":\"2016-09-09T07:56:50\",\"type\":\"variable\",\"status\":\"publish\",\"featured\":false,\"catalog_visibility\":\"visible\",\"description\":\"<p>ballballballballballball<\\/p>\\n\",\"short_description\":\"\",\"sku\":\"dsfdsfdsfsdf\",\"price\":\"234\",\"regular_price\":\"\",\"sale_price\":\"\",\"date_on_sale_from\":\"\",\"date_on_sale_to\":\"\",\"price_html\":\"<span class=\\\"woocs_price_code\\\" data-product-id=\\\"77\\\"><span class=\\\"woocommerce-Price-amount amount\\\">234.00<span class=\\\"woocommerce-Price-currencySymbol\\\">&#36;<\\/span><\\/span><\\/span>\",\"on_sale\":false,\"purchasable\":true,\"total_sales\":0,\"virtual\":false,\"downloadable\":false,\"downloads\":[],\"download_limit\":-1,\"download_expiry\":-1,\"download_type\":\"standard\",\"external_url\":\"\",\"button_text\":\"\",\"tax_status\":\"taxable\",\"tax_class\":\"\",\"manage_stock\":true,\"stock_quantity\":200,\"in_stock\":true,\"backorders\":\"no\",\"backorders_allowed\":false,\"backordered\":false,\"sold_individually\":false,\"weight\":\"\",\"dimensions\":{\"length\":\"\",\"width\":\"\",\"height\":\"\"},\"shipping_required\":true,\"shipping_taxable\":true,\"shipping_class\":\"\",\"shipping_class_id\":0,\"reviews_allowed\":true,\"average_rating\":\"0.00\",\"rating_count\":0,\"related_ids\":[],\"upsell_ids\":[],\"cross_sell_ids\":[],\"parent_id\":0,\"purchase_note\":\"\",\"categories\":[],\"tags\":[],\"images\":[{\"id\":0,\"date_created\":\"2016-09-09T15:57:46\",\"date_modified\":\"2016-09-09T15:57:46\",\"src\":\"http:\\/\\/example.com\\/wp-content\\/plugins\\/woocommerce\\/assets\\/images\\/placeholder.png\",\"name\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"alt\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"position\":0}],\"attributes\":[{\"id\":1,\"name\":\"Size\",\"position\":0,\"visible\":true,\"variation\":true,\"options\":[\"\\u4e2d\"]}],\"default_attributes\":[],\"variations\":[{\"id\":112,\"date_created\":\"2016-09-09T07:56:25\",\"date_modified\":\"2016-09-09T07:56:43\",\"permalink\":\"http:\\/\\/example.com\\/product\\/%e6%b3%a2%e6%b3%a2\\/?attribute_pa_size=%25e4%25b8%25ad\",\"sku\":\"dsfdsfdsfsdf\",\"price\":\"234\",\"regular_price\":\"234\",\"sale_price\":\"\",\"date_on_sale_from\":\"\",\"date_on_sale_to\":\"\",\"on_sale\":false,\"purchasable\":true,\"visible\":true,\"virtual\":false,\"downloadable\":false,\"downloads\":[],\"download_limit\":-1,\"download_expiry\":-1,\"tax_status\":\"taxable\",\"tax_class\":\"\",\"manage_stock\":\"parent\",\"stock_quantity\":200,\"in_stock\":true,\"backorders\":\"no\",\"backorders_allowed\":false,\"backordered\":false,\"weight\":\"\",\"dimensions\":{\"length\":\"\",\"width\":\"\",\"height\":\"\"},\"shipping_class\":\"\",\"shipping_class_id\":0,\"image\":[{\"id\":0,\"date_created\":\"2016-09-09T15:57:46\",\"date_modified\":\"2016-09-09T15:57:46\",\"src\":\"http:\\/\\/example.com\\/wp-content\\/plugins\\/woocommerce\\/assets\\/images\\/placeholder.png\",\"name\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"alt\":\"\\u6a19\\u8a18\\u7b26\\u865f\",\"position\":0}],\"attributes\":[{\"id\":1,\"name\":\"Size\",\"option\":\"%e4%b8%ad\"}]}],\"grouped_products\":[],\"menu_order\":0,\"_links\":{\"self\":[{\"href\":\"http:\\/\\/example.com\\/wp-json\\/wc\\/v1\\/products\\/77\"}],\"collection\":[{\"href\":\"http:\\/\\/example.com\\/wp-json\\/wc\\/v1\\/products\"}]}}]`


Here is the JSON I think it possibly because of variable product
Thanks

**Comment by XiaoFaye** [comment]
You are correct, that was the issue, I will commit a fix soon.

**Comment by XiaoFaye** [comment]
It has been fixed with this [commit](https://github.com/XiaoFaye/WooCommerce.NET/commit/3c1e4fcf50d9640de3a3cc8d7969793aa25542e8) 

Thanks!
