### ISSUE TITLE
Update order status 400

### ISSUE THREAD

**Issue by NodCaleb** [XiaoFaye/WooCommerce.NET#250]
Hello.
We are using Wordpress 4.9.2 and Woocommerce 3.2.6.

Several days ago I started to catch exception, while using UpdateOrder, but boefore it worked fine.

Exception message is:
{"code":"rest_invalid_param","message":"Invalid parameter(s): line_items","data":{"status":400,"params":{"line_items":"line_items[0][subtotal] is not of type string."}}}

**Comment by iaps** [comment]
ANy idea when this will be fixed?  I'm on WP 4.9.3.

**Comment by XiaoFaye** [comment]
@iaps @NodCaleb  seems this happened after a WooCommerce update?

**Comment by NodCaleb** [comment]
Probably.
But we have updated both WP and WooCommerce simultaneously, so I cant say for sure.

**Comment by NodCaleb** [comment]
I've changed type of the following properties to string:

WooCommerceNET.WooCommerce.v2.OrderLineItem.subtotal
WooCommerceNET.WooCommerce.v2.OrderLineItem.subtotal_tax

And my UpdateOrder request was competed successfully.

But I haven't tested it properly.

**Comment by iaps** [comment]
I am trying to rebuild the project, with that var type change from int? to string, but V0.7.4 now targets .NET Standard 2.0, which is preventing me from adding it to my Xamarin Cross-Platform Portable application: The type 'Nullable<>' is defined in an assembly that is not referenced.  You must add ... 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=...'.

**Comment by XiaoFaye** [comment]
@iaps  I believe Xamarin support .NET standard 2.0 as well, please check here: https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/net-standard/

**Comment by iaps** [comment]
I attempted to move everything over to .NET standard 2.0, but I'm getting so many errors that I cannot seem to resolve.  Is there any way to remove that requirement?  My project was essentially complete until this decimal to string issue came up, and now the whole thing is broken, and can no longer resolve without issue using .net standard 2.0.  If I could find the 0.7.3 version of WooCommerce.NET, and make my change in there, all would be fine.

**Comment by XiaoFaye** [comment]
Version 0.7.4 is targeting .net standard 2.0.
