### ISSUE TITLE
Unable to install version 0.7.4 using NuGet

### ISSUE THREAD

**Issue by Petje1972** [XiaoFaye/WooCommerce.NET#251]
When trying to install version 0.7.4 using NuGet, the installation failes.
The error message is 'Could not install package 'WooCommerceNET 0.7.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.'.
This message appears using VS2010 and VS2015.
Targetted framework set to:
4.6.2
4.5.1
4.0 Client Profile
2.0

When trying to install version 0.7.3, installation succeeds.
I guess there is something missing in the installation of version 0.7.4

**Comment by Vallekano** [comment]
I am getting the same error

**Comment by Vallekano** [comment]
Ok, I already solved it. You need to open your proyect with VS2017 (compatible with .NET Standard 2.0) and then it will get the update properly.

**Comment by XiaoFaye** [comment]
@Petje1972 Please see @Vallekano 's comment.

**Comment by Petje1972** [comment]
@XiaoFaye, So the nuget package of 0.7.4 can only be used with VS2017 ?

**Comment by XiaoFaye** [comment]
@Petje1972  Yes, as it targets .NET Core 2.0 now.
