### ISSUE TITLE
Set predefined attribute on Product

### ISSUE THREAD

**Issue by Zoktrax** [XiaoFaye/WooCommerce.NET#252]
Wordpress version 4.8.2 , WooCommerce version 3.1.2 and WooCommerce.NET version 072 (nuget)

Hi all woocommerce.net hackers,

I have setup predefined attribute for Colors (Named Colors2 and set up with "Select" type) in Woocommerce, basically the base colors as conditions.

Then I try to add to a new product with this Colors2 attribute and a certain condition red. I assumed that if I use the same name of the attribute it will automatically connect to this predefined attribute but instead it is created a custom attribute only for this product with the same name.

So I am wondering how i retrieve the predefined color attribute and then set the new product with?

Code that does not work as planned:

```
      List<string> colors = new List<string>() { "Silver" };
     WooCommerceNET.WooCommerce.v2.ProductAttributeLine _AttributeLine = new WooCommerceNET.WooCommerce.v2.ProductAttributeLine() { name = "Color2", variation = true, visible = true, options = colors };//Instead of creating a new here I want to connect to the predifined attribute

     attribs.Add(_AttributeLine);
 pWoo.attributes =attribs;
```

**Comment by stevecurrey** [comment]
I am having the same issue. All of my attributes are coming in as custom and not adding to the predefined.  Any answers to this?

Thank you
