### ISSUE TITLE
GetOrders or Order.GetAll not return all orders

### ISSUE THREAD

**Issue by achillf** [XiaoFaye/WooCommerce.NET#253]
I use this piece of code:

> private async void button5_Click(object sender, EventArgs e)
>         {
>             RestAPI rest = new RestAPI("http://mysite/wp-json/wc/v2", "key", "key");
>             WCObject wc = new WCObject(rest);
>             wc.Setting.
>             var ordersss = await wc.Order.GetAll();
>         }

and that it return me only the last 10 orders.. Same thing and this code:

> RestAPI rest = new RestAPI("http://mysite/wp-json/wc/v1", "key", "key");
>             WooCommerceNET.WooCommerce.v1.WCObject wc = new WooCommerceNET.WooCommerce.v1.WCObject(rest);
> 
>            var orders = await wc.GetOrders();

Why?

**Comment by XiaoFaye** [comment]
This is by default, please refer to WooCommerce documents.

**Comment by achillf** [comment]
ok and how can i getOrder by date or by hour?

**Comment by goguvi** [comment]
I recommend you check #260
