### ISSUE TITLE
Could not create SSL/TLS secure channel. at WooCommerceNET.RestAPI

### ISSUE THREAD

**Issue by danielmoorehbd** [XiaoFaye/WooCommerce.NET#256]
Hi,

Despite using a TLS 1.2 SSL certificate on the website and seeing it work in the browser, we continue to have the following error:
`Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__20`1.MoveNext()`

- Wordpress version, WooCommerce version and WooCommerce.NET version
We are using the latest version of all of these, as a troubleshooting step, we updated them both. That said, we're not sure on the version numbers in use...

**Comment by Manthan2611** [comment]
same issue with me

**Comment by XiaoFaye** [comment]
@danielmoorehbd @Manthan2611  have a look at #271
