### ISSUE TITLE
Error with install-package using Visual Studio 2015 

### ISSUE THREAD

**Issue by GavinDixon69** [XiaoFaye/WooCommerce.NET#257]
Using Visual Studio 2015

Am getting error when executing command "install-package woocommercenet"
Error Message is:
install-package : Could not install package 'WooCommerceNET 0.7.4'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by XiaoFaye** [comment]
WooCommerceNET 0.7.4 is targeting .NET Core 2.0, it will not work on projects that targeting .net 4.5.2. Please try to install the version 0.7.3

**Comment by GavinDixon69** [comment]
Thank you for your helpful comment.
I went to "Releases" and can only see version 0.7.2 
How can I get version 0.7.3?

**Comment by JohnKyle14** [comment]
I'm getting the same error when targeting .NET 2.0 on VS 2015

"Could not install package 'WooCommerceNET 0.7.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Also tried a few previous versions but to no success.

**Comment by IcuScc** [comment]
Hi. I have the same problem.
I create a new console project in VS 2013. I try to install and I get the same error message.

What is the solution?
Thanks.

**Comment by tomAsh00** [comment]
Dear @XiaoFaye , could you please tell why version 0.7.4 targets .NET Core 2.0 ?
As you saw above, it might be confusing.

**Comment by diegoaraujolima** [comment]
I had the same problem. Is it possible to change this to work in 4.5.2?

**Comment by IcuScc** [comment]
Yes. I get to change, installing from here

![imagen](https://user-images.githubusercontent.com/5454095/39225383-50c62f90-484c-11e8-9548-b685c336b33c.png)

I hope you get it
:smiley:
