### ISSUE TITLE
https

### ISSUE THREAD

**Issue by FernandoHlibka** [XiaoFaye/WooCommerce.NET#259]
Does woocommerceNET have any problems with site "https"?

**Comment by Magnetize** [comment]
I am using Let's Encrypt certificate on a site running Woo 3.2.6 and WordPress 4.9.4 with WooCommerce.NET version 0.7.1
Did not update to 0.7.4 yet, but perhaps someone else can share their experiences using the latest version.

**Comment by FernandoHlibka** [comment]
i have a problem with jwt-auth and https... this error: "jwt auth malformed header", anyone have a solutions? thanks for reply

**Comment by XiaoFaye** [comment]
please check the authorizeHeader parameter in RestAPI.
