### ISSUE TITLE
GetOrders error

### ISSUE THREAD

**Issue by suhomlineugene** [XiaoFaye/WooCommerce.NET#26]
Hello.

I try to receive all order like this:

```
var orders = await wc.GetOrders();
            foreach (var order in orders)
            {


               
                Debug.WriteLine($"ID:{order.id}");
```

But I see only first 10 orders in console. But in admin panel I see about 28 orders.

**Comment by XiaoFaye** [comment]
You will need to use the per_page parameter to change the default page size.

http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-orders

**Comment by suhomlineugene** [comment]
This is filter or what?

**Comment by XiaoFaye** [comment]
These are WooCommerce REST API parameters.

**Comment by suhomlineugene** [comment]
Okay how I need to write code?

**Comment by suhomlineugene** [comment]
I get orders like this. Where I need to write per_page parameter?

` var orders = await wc.GetOrders();
`

**Comment by XiaoFaye** [comment]
Something like:

var p = await wc.GetProducts(new Dictionary<string, string>() {
                { "per_page", "20" } });

**Comment by suhomlineugene** [comment]
Wrote like this 

```
 var orders = await wc.GetProducts(new Dictionary<string, string>() {
                 { "per_page", "100" }});
```

Has this error

`An exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: There was an error deserializing the object of type WooCommerceNET.WooCommerce.ProductList. Encountered unexpected character '<'.`

**Comment by suhomlineugene** [comment]
Thank's it helps.
