### ISSUE TITLE
Getting Orders...how to get all after some date/time

### ISSUE THREAD

**Issue by CaptainBly** [XiaoFaye/WooCommerce.NET#260]
Having issues getting all orders downloaded.  just calling orders is only giving me 10.  I figured out the per_page parameter but that maxes out at 100 evidently.  So I am getting a 100 orders but then not sure how to get the "next" 100 and the next "100", etc...  Tried all sorts of ways but I can't seem to figure out which date Woocommerce is using for the before and after parameters.

- Wordpress version, WooCommerce version and WooCommerce.NET version

Using V1

- Steps to replicate the issue

                        var ordersv1 = await wcv1.GetOrders(new Dictionary<string, string>() {
                        { "status", "processing" },
                        { "context","view" },
                        { "per_page","100" },
                        { "after",lastdate},
                        });

- Details of the error message if there is any
I am trying to download all orders with a "processing" status after a certain date.  

It SEEMS to initially only grab 10 records.  I found the per_page attribute and that maxes out at 100 from what I can tell.  

So, I successfully get the first 100 orders and process them.  My problem is how do I get the next hundred, and the next and the next.

I have tried as I go through the first 100 orders saving the latest date in that group.  I used all the dates in the orders dataset - date_created, date_modified, date_completed, and date_paid.  date_created or date_paid SEEM to be the date woocommerce is using but not sure.

Then I do the next get with that date assuming one of those is what the "after" parameter is using.  No matter what I do, I am getting gaps and missing orders.  

Then I tried the page parameter.
I tried to send page 2 with the same initial afterdate but I get the same original 100 orders.

The crazy solution I have come up with so far is to grab in 10 minute increments from some date so I am using the before and after parameters.

                        var ordersv1 = await wcv1.GetOrders(new Dictionary<string, string>() {
                        { "status", "processing" },
                        { "context","view" },
                        { "per_page","100" },
                        { "after",afterdate},
                        { "before",beforedate},
                        });

Figuring there would never be more than a 100 orders in 10 minutes.  If there was, I can handle that and do a per minute call or whatever but so far that has not been an issue.

This gets me EXPONENTIALLY closer to getting all the orders but out of 1900 orders, I still missed a handful of orders somehow.

Anyone have any input on how to download ALL orders successfully?

**Comment by goguvi** [comment]
It should be with the page parameter, although you already indicate that you have tried it. You can look at issue #83 to see if it clarifies your doubts.

**Comment by goguvi** [comment]
Regarding the doubts with the dates I recommend you look at the function prepare_objects_query of WC_REST_CRUD_Controller that is the one that manages it (https://docs.woocommerce.com/wc-apidocs/source-class-WC_REST_CRUD_Controller.html#289-298).

On the other hand I recommend you look at the documentation of WP_Query that is responsible for executing the query, specifically the paragraph of parameters of date (https://codex.wordpress.org/Class_Reference/WP_Query#Date_Parameters).

Taking these two points into account and seeing that a value is not assigned to the date_query column, the value used would be the default value ('post_date')

**Comment by CaptainBly** [comment]
Thanks for the reply.  Maybe I am not using the page parameter properly.  I started off with page 1.

pagestring="1" to start

                        var ordersv1 = await wcv1.GetOrders(new Dictionary<string, string>() {
                        { "status", "processing" },
                        { "context","view" },
                        { "per_page","100" },
                        { "Page", pagestring },
                        { "after",downdate},
                        });

pagestring =2 

                        var ordersv1 = await wcv1.GetOrders(new Dictionary<string, string>() {
                        { "status", "processing" },
                        { "context","view" },
                        { "per_page","100" },
                        { "Page", pagestring },
                        { "after",downdate},
                        });

but seemed to get the same orders.  Do I not send the rest of the parameters?  Just page?

Thanks again for the quick feedback.

**Comment by goguvi** [comment]
In my code I use "per_page" with value "50" and "page" with value "1", "2", "3", ...
Now I do not remember if the parameters are case-sensitive, but you can try using "page" instead of "Page". Otherwise, your code seems correct in my opinion

**Comment by CaptainBly** [comment]
Thanks.  I do definitely have a capital P.  I will try that.  My bad.  Close...but off by one freaking letter...Have a great day.
