### ISSUE TITLE
Secret is included in requests

### ISSUE THREAD

**Issue by mashbrno** [XiaoFaye/WooCommerce.NET#261]
Sample code:

    RestAPI rest2 = new RestAPI("http://example.com/wp-json/wc/v2", "key", "secret");
    WCObject wc2 = new WCObject(rest2);
    var x = wc2.Product.GetAll().Result;

Produces request:

GET http://example.com/wp-json/wc/v2/products?oauth_consumer_key=key&oauth_nonce=ce43a503eebb4675bb7ab1ec425d941a&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1520924810&consumer_key=key&consumer_secret=secret%26&oauth_signature=IWc2j0gQ9W0sL%2FXKRZxHs5jcxLzlRxyrlXx1gHBMIOQ%3D HTTP/1.1

Secret should not be revealed publically in URL!

**Comment by XiaoFaye** [comment]
Thanks for pointing this out, a fix is included in commit: https://github.com/XiaoFaye/WooCommerce.NET/commit/85d79bee931607650fa068dcb6ee7fccffd87e1d
