### ISSUE TITLE
Console Application

### ISSUE THREAD

**Issue by run4mi** [XiaoFaye/WooCommerce.NET#262]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
wp: V4.9.4, woocomm: 3.3.1, wc.NET 0.7.3 
- Steps to replicate the issue
get order, get product
- Details of the error message if there is any
Hi! Everything is fine in WPF Application, but now I have to create a console program for importing some objects to a database. My pattern same as in WPF doesn't work in console, but there is no exception, the program close immeditly afert call "await wc.Order.Get(...)". 

Can someone help?

**Comment by goguvi** [comment]
Maybe a problem with the async /  await in main: https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/

**Comment by run4mi** [comment]
Sorry, for my stupid question, that's it! Thanxs a lot!
