### ISSUE TITLE
Get Order Line Information

### ISSUE THREAD

**Issue by bradtors** [XiaoFaye/WooCommerce.NET#264]
Hello, 

I am pulling order information with vb.net like this.

`Public orderlist As List(Of Order)`
`Public Async Sub Get_All_Orders()`
`orderlist = New List(Of Order)(Await wc.Order.GetAll(New Dictionary(Of String, String)() From {{"status", "processing"}}))`
`End Sub`

But how do i get the order line information?

Thank you

**Comment by XiaoFaye** [comment]
try orderlist(1).lines

**Comment by bradtors** [comment]
Thank you. got me on the right track. 

ended up with
```

    Public Function Get_Order_Lines(ByVal p As Integer)
        Dim orderlines = orderlist(p).line_items
        Return orderlines
    End Function
```
