### ISSUE TITLE
Get Categorie by name

### ISSUE THREAD

**Issue by IcuScc** [XiaoFaye/WooCommerce.NET#268]
I have Wordpress 4.9.5 and woocommerce 3.3.4

I try to get a category by name and i dont got it.

my last example is this

 var laCat = await wc.Category.GetAll(new Dictionary<string, string>() {
                                        { "name", "mycategoryname"}});

is it possible to doit?
thanks a lot

:-)

**Comment by RobertoBrandini** [comment]
Try "search" in the place of name

Em Sex, 6 de abr de 2018 13:47, Sergio <notifications@github.com> escreveu:

**Comment by IcuScc** [comment]
Hey... Roberto... Great.... Thanks a lot..
but it is possible to made a exactly search? for example, i have 3 categories
- Game Arcade
- Retro Game
- Game

if I search "Game", returns to me the 3 categories. 
it is possible to?

Thanks...

**Comment by RobertoBrandini** [comment]
I don`t know

Enviado do Email para Windows 10

De: Sergio
Enviado:sábado, 7 de abril de 2018 04:38
Para: XiaoFaye/WooCommerce.NET
Cc:Roberto Brandini; Comment
Assunto: Re: [XiaoFaye/WooCommerce.NET] Get Categorie by name (#268)

Hey... Roberto... Great.... Thanks a lot..
but it is possible to made a exactly search? for example, i have 3 categories
• Game Arcade
• Retro Game
• Game
if I search "Game", returns to me the 3 categories.
it is possible to?
Thanks...

**Comment by IcuScc** [comment]
Thanks Roberto. Now I stoped my project because another priorities. But I will back soon and i will put my solution.
