### ISSUE TITLE
Connection Challenges

### ISSUE THREAD

**Issue by mgpetryk** [XiaoFaye/WooCommerce.NET#27]
I cannot seem to get past the "401" error indicating authentication issues.  I've:

1.) Using HTTPS
2.) Deleted and recreated the API key pairs in WOOCommerce and verified they are correct in the C# code
3.) Tested with GetStoreInfo which returns lots of data successfully
4.) All other calls to routines like GetCustomers() / GetProducts() all fail with a 401 error
5.) Traced the call into RestAPI.cs / SendHttpClientRequest and I see the httpWebRequest.Credentials appear to be created correctly (username & password contain the api keys)
6.) The user profile assigned to the API key pairs is an "admin" level account

Any idea of where I might be going wrong?
Thanks!
Mike

**Comment by XiaoFaye** [comment]
Hi Mike, are you using the legacy API or the latest one? have you updated to the latest version? Thanks.

**Comment by mgpetryk** [comment]
Hi James,

 

I’m using nuget WooCommerceNET.0.5.1 and the url is:

 

        private string wc_url = "https://soundhealthportal.com/wp-json/wc/v1/";

 

So not the legacy API , using the latest version.

 

Thanks!

Michael Petryk

Office: 206-201-2367

Cell: 425-392-5019

**Comment by XiaoFaye** [comment]
In your WooCommerce settings, the shop url is "https://soundhealthportal.com/" or "https://**www**.soundhealthportal.com/" ?

**Comment by mgpetryk** [comment]
Hi James,

 

Would it help if I send you a set of API keys?

 

Mike

**Comment by mgpetryk** [comment]
private async void WooCommerceSyncAction_Execute(object sender, SimpleActionExecuteEventArgs e)

        {

            RestAPI rest = new RestAPI(wc_url, wc_key, wc_secret);

            WCObject wc = new WCObject(rest);

            string orders = await wc.GetStoreInfo();

 

        }

Hi James,

 

This is my code.  GetStoreInfo works, but GetProducts()

 

Mike

**Comment by XiaoFaye** [comment]
Could you please check the WooCommerce settings, and see that is the shop url ?  "https://soundhealthportal.com/" or "https://www.soundhealthportal.com/" ?

**Comment by mgpetryk** [comment]
WordPress Address (URL)	
https://soundhealthportal.com
Site Address (URL)	
https://soundhealthportal.com

**Comment by XiaoFaye** [comment]
Then it shouldn't be a problem, as the wc_url should match the wordpress settings. Have you been able to get it working?

**Comment by mgpetryk** [comment]
Hi James,   Here is part of the answer to GetStoreInfo:   Can I assume that GetProducts()  should work?

{\"required\":false,\"description\":\"Menu order, used to custom sort products.\"}}}],\"_links\":
{\"self\":\"https:\\/\\/soundhealthportal.com\\/wp-json\\/wc\\/v1\\/products\"}},\"\\/wc\\/v1\\/products\\/(?P<id>[\\\\d]+)\":
{\"namespace\":\"wc\\/v1\",\"methods\":[\"GET\",\"POST\",\"PUT\",\"PATCH\",\"DELETE\"],\"endpoints\":[{\"methods\":[\"GET\"],\"args\":
{\"context\":
{\"required\":false,\"default\":\"view\",\"enum\":[\"view\",\"edit\"],\"description\":\"Scope under which the request is made; determines fields present in response.\"}}},{\"methods\":[\"POST\",\"PUT\",\"PATCH\"],\"args\":

**Comment by XiaoFaye** [comment]
no, it's not like that, GetStoreInfo can work without authentication, but not others. If you could send me a set of API keys directly, I would be able to have a look.

**Comment by mgpetryk** [comment]
private string wc_url = "https://soundhealthportal.com/wp-json/wc/v1/";
        private string wc_key = "ck_a454774b15550b37c780e3e45fcc942cd7ecdc7c";
        private string wc_secret = "cs_28e7dbddeaf46929b6c2b1a21b03bf944ec1f7fd";

**Comment by mgpetryk** [comment]
private string wc_url = "https://soundhealthportal.com/wp-json/wc/v1/";
        private string wc_key = "ck_a454774b15550b37c780e3e45fcc942cd7ecdc7c";
        private string wc_secret = "cs_28e7dbddeaf46929b6c2b1a21b03bf944ec1f7fd";

**Comment by XiaoFaye** [comment]
I'm getting below error, you might need to check your settings.

![image](https://cloud.githubusercontent.com/assets/6334728/18605241/7969ce2c-7ce0-11e6-9e01-67d502314895.png)

**Comment by mgpetryk** [comment]
Hi James,

 

OK, I turned off Mod Security and ran another test.  It continues to fail on 401 error

**Comment by XiaoFaye** [comment]
Hi Mike, 
The issue has been fixed, please download the latest code.
Cheers,
James

**Comment by mgpetryk** [comment]
Thank you James… All is good!
