### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by EbrahimHamzeh** [XiaoFaye/WooCommerce.NET#271]
I am getting this exception "The request was aborted: Could not create SSL/TLS secure channel." at the time of ExpressCheckout at following line.
# Solution
after use HttpWebRequest
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
ServicePointManager.DefaultConnectionLimit = 9999;

Nuget System.Data.DataSetExtensions

**Comment by XiaoFaye** [comment]
Thanks for providing the information.
