### ISSUE TITLE
wp character

### ISSUE THREAD

**Issue by HKhedr** [XiaoFaye/WooCommerce.NET#272]
Hello.
When Product Description
I get html tags and character Like [/vc_column_text][/vc_column] ..
How can I remove it.

**Comment by XiaoFaye** [comment]
have a look at #78

**Comment by HKhedr** [comment]
Sorry. but still not working.
`            MyRestAPI rest = new MyRestAPI("https://localhost/wp-json/wc/v2/",
                "ck_489afa8c231845fc1ea4f70eb8",
                "cs_50915cca0f01f6c845a10a41df",
                jsonDeserializeFilter: Trimstr);

        public static string Trimstr(string json)
        {
            return json.Trim(new char[] { '\uFEFF', '\u200B' });
        }
`
Thank you.

**Comment by HKhedr** [comment]
![untitled](https://user-images.githubusercontent.com/11136926/39398435-87f6b21a-4b16-11e8-8162-5f25296c3134.png)



I'm Installed Version 0.7.4 but still get wp character.
any help !!!?

Thank you.

**Comment by XiaoFaye** [comment]
Some plugins or code in your website have caused this issue,  I will suggest you disable the plugins and try again.
