### ISSUE TITLE
You dont have permissions...

### ISSUE THREAD

**Issue by OscarLate** [XiaoFaye/WooCommerce.NET#275]
- Wordpress version, WooCommerce version and WooCommerce.NET version

WooCommerce:3.2.6
WordPress:4.9.5
WooCommerce.NET:7.3

I have more than 4 WebSites with this dll currently working, but all with certificate HTTPS. I'm testing new WebSite without certificate and dont works.

> 403 ForbiddenYou don't have permission to access /wp-json/wc/v1/orders on this server.

Postman only works with OAuth 1.0. I'm sure this error is some stupid but I can't found any solution, Any Ideas?

**Comment by XiaoFaye** [comment]
Only /wp-json/wc/v1/orders not working? what about other endpoints?
