### ISSUE TITLE
Failed to deserialize for Unexpected character 'ï'

### ISSUE THREAD

**Issue by MarcATinfo** [XiaoFaye/WooCommerce.NET#278]
Hello all,

I have this problem when deserialize the received json, I have the Woocommerce version 3.3.3 and wordpress 4.9.5 in all requests made (orders, products )....

any ideas?

Attached file with the information received
[json.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/2009456/json.txt)

thanks for all

************************
   en System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   en System.Runtime.Serialization.Json.XmlJsonReader.Read()
   en System.Xml.XmlBaseReader.IsStartElement()
   en System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   en System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(XmlReaderDelegator reader)
   en System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   en System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)

**********************

**Comment by XiaoFaye** [comment]
It's working fine here:

![image](https://user-images.githubusercontent.com/6334728/40148312-7467e610-59c1-11e8-80de-2eb7352b08e9.png)

**Comment by MarcATinfo** [comment]
To add a bit more information to receive the request, copy it into a file and perform deserialization from file, it works perfectly.

**Comment by MarcATinfo** [comment]
Hello again,
I have already found the solution:

 private static string RemoveBom(string p)
        {
            string BOMMarkUtf8 = Encoding.UTF8.GetString(Encoding.UTF8.GetPreamble());
            if (p.StartsWith(BOMMarkUtf8))
                p = p.Remove(0, BOMMarkUtf8.Length);
            return p.Replace("\0", "");
        }
and

 jsonString = RemoveBom(jsonString);

Image:
![image](https://user-images.githubusercontent.com/39339401/40165974-a78d1104-59bd-11e8-881f-f4d2323cd7e8.png)

Thanks for all ^^
