### ISSUE TITLE
Cannot connect to my webshop anymore

### ISSUE THREAD

**Issue by heinkramerurk** [XiaoFaye/WooCommerce.NET#28]
Hey, 

Since a while I can't connect anymore to my webshop.
It has worked for a couple months just fine.

I try this:

`var woocommerceApiClient = new WoocommerceApiClient("http://solideogloria.nl/", "ck_6abbd76a97dc245eed7c4e6bf6572e48983c557f", "cs_cee0aaa2bcd42e5a790b75a7d89576d80292ee9a");

var importedProductsParameters = new WoocommerceParameters();
importedProductsParameters.AddFilterLimit(1000);
var importedProducts = woocommerceApiClient.Products.Get(importedProductsParameters);
`

Can u see whats wrong?
I created this keys for u to test it.
I hope u can help me.

Thanks.

**Comment by XiaoFaye** [comment]
I have ran some testing, works fine for me. Just a remainder: you will need to pass the URL as http://www.solideogloria.nl/ , Not http://solideogloria.nl/, which should be the same as your WooCommerce settings.

**Comment by heinkramerurk** [comment]
Hello,

You'r right. It works now! Thank you verry much.
