### ISSUE TITLE
401 Exception

### ISSUE THREAD

**Issue by PoliSafety** [XiaoFaye/WooCommerce.NET#281]
Wordpress version: 4.9.6
Woocommerce version: 3.4.0
Woocommerce.NET version: 0.7.3

First things first, I know I am not using the latest Woocommerce.NET version but I am unable to update since I get dependency errors no matter which .NET Framework I use. I am also developing in VB.NET and not C#.

The site has a valid SSL certificate and tested the REST API keys using Postman and they also work.

Issue:
Woocommerce 401 exception when trying to get a product, order, etc.

Two lines of code that I use:
```
Dim ord = wc.Order.Get(76326)
TextBox1.Text = JsonConvert.SerializeObject(ord.Result.ToString)
```

**Comment by XiaoFaye** [comment]
There is a parameter called "authorizeHeader" in RestAPI, try changing its value.

**Comment by PoliSafety** [comment]
Thank you very much! That did solve my issue.
