### ISSUE TITLE
Empty .sale_to_date and .sale_price

### ISSUE THREAD

**Issue by PoliSafety** [XiaoFaye/WooCommerce.NET#283]
Wordpress: 4.9.6
Woocommerce: 3.4.0
Woocommerce.NET: 0.7.3

When I try to empty the value ".date_on_sale_to" it either gets an exception or does not remove it.
```
wc.Product.Update(current_product_id, New Product() With {.date_on_sale_to = DateTime.Parse(Nothing)}) //Returns exception
wc.Product.Update(current_product_id, New Product() With {.date_on_sale_to = ""}) //Does not change anything
wc.Product.Update(current_product_id, New Product() With {.date_on_sale_to = Nothing}) //Does not change anything
```
Is there a way to properly remove the date?
I would also like some help if possible in order to remove the .sale_price I found some other commits but I wasn't able to implement them.

UPDATE: I am having the same issue with .weight

Thanks in advance.

**Comment by PoliSafety** [comment]
Any feedback?

**Comment by XiaoFaye** [comment]
Have you tried to set the min date value? you might need to empty the value for **date_on_sale_to_gmt** as well.

**Comment by PoliSafety** [comment]
I have tried sending an _empty value ("")_, sending _Nothing_, sending a _past date (2008/01/01)_ and also emptying _date_on_sale_to_gmt_ but unfortunately it did not work, that's why I filled an issue in the first place.

**Comment by XiaoFaye** [comment]
I see, a new update will be coming next week to fix this issue.

**Comment by PoliSafety** [comment]
Thank you very much for your help.
One more question: Are there any tips on how to change the .sale_price and .weight variables from Decimal to String?

**Comment by XiaoFaye** [comment]
Hi, @PoliSafety , you can now use the 0.7.5 version with **UpdateWithNull** to fix your issues.

**Comment by PoliSafety** [comment]
Thank you very much for your support. Using **UpdateWithNull** seems really simple.
The problem that I am having though is that the platform that I am working on does not support .NET Standard/Core. Is there a way to get an updated version that targets .NET Framework 4.5 and above.

I would really appreciate it.

**Comment by XiaoFaye** [comment]
I understand the needs of standard .NET framework support, but maintaining versions targeting different framework has always been a problem, I will see what I can do.

**Comment by PoliSafety** [comment]
I understand that is a great inconvenience especially since this an open source project. The past few days I tried porting it by myself but I had no luck, and that's why I am asking for your help.

Much appreciated!
