### ISSUE TITLE
nuget - Could not install package

### ISSUE THREAD

**Issue by A3ed** [XiaoFaye/WooCommerce.NET#285]
Hi
I need it in a project but couldn't install it, this error appears:
![2018-06-10_10-40-12](https://user-images.githubusercontent.com/33343170/41198806-d65321e8-6c75-11e8-8fb7-e813330cc100.png)

**Comment by XiaoFaye** [comment]
Try version 0.7.3

**Comment by A3ed** [comment]
error 0.7.3
![2018-06-11_10-21-25](https://user-images.githubusercontent.com/33343170/41214603-bc1e103c-6d3b-11e8-89a5-bd76bf0efb4b.png)

**Comment by A3ed** [comment]
you Can Send Example project with WooCommerce.NET libbry ?
