### ISSUE TITLE
How can I filter through the categories to only return the parent?

### ISSUE THREAD

**Issue by MoAleem1** [XiaoFaye/WooCommerce.NET#289]
Using WooCommerce v0.75

Here is a snippet of my code:

 Dictionary<string, string> catDictionary = new Dictionary<string, string>();
            catDictionary.Add("per_page", "100");
            int pageNum = 1;
            catDictionary.Add("page", pageNum.ToString());
            List<ProductCategory> categories = new List<ProductCategory>();
            bool endWhile = false;
            while (!endWhile)
            {
                var catTemp = await wc.Category.GetAll(catDictionary);
                if (catTemp.Count > 0)
                {
                    categories = catTemp.Where(p => p.parent == 0).ToList();
                    categories.AddRange(catTemp);
                    pageNum++;
                    catDictionary["page"] = pageNum.ToString();
                }
                else
                {
                    endWhile = true;
                }
            }

this method seems to work but it's not cycling through all the entries, its stopping at 100. I need to  get all the Parent Categories only.

Please point me in the right direction.

**Comment by XiaoFaye** [comment]
What did you get when the page = 2?

**Comment by MoAleem1** [comment]
Page one returns the 100 products plus the 4 parents, the second page returns the 100 products plus 1 parent, and so on... it doesn't just give me the parents.
Any ideas?

**Comment by XiaoFaye** [comment]
Have you try to use the parent parameter and set it to 0?
