### ISSUE TITLE
Legacy WCObject

### ISSUE THREAD

**Issue by raulbv** [XiaoFaye/WooCommerce.NET#29]
Hi, everyone...
I´m trying to use the method "GetProducts", but when I try this:
WCObject wc = new WCObject(rest);
I get this message: "You can't use the legacy WCObject on the latest version of WooCommerce Restful API."

 What I doing wrong?? Is a issue in my code or something in config of wordpress??

Thanks!

**Comment by XiaoFaye** [comment]
There are 2 ways of using WC API:

//Legacy way of calling WooCommerce REST API
//RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wc-api/v3/", "<WooCommerce Key>", "<WooCommerce Secret");
//WooCommerceNET.WooCommerce.Legacy.WCObject wc = new WooCommerceNET.WooCommerce.Legacy.WCObject(rest);

RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wc/v1/", "<WooCommerce Key>", "<WooCommerce Secret");
WCObject wc = new WCObject(rest);

**Comment by raulbv** [comment]
Hi, XiaoFaye, thanks a lot.

Actually I´m trying with the second option:

RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wc/v1/", "", "<WooCommerce Secret");
WCObject wc = new WCObject(rest);

But when I debug my code, in the line: "RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wc/v1/", "", "<WooCommerce Secret");" I get the IsLegacy propertie = False

So, when I try the "WCObject wc = new WCObject(rest);" that gives me the message: "You can't use the legacy WCObject on the latest version of WooCommerce Restful API"

I don´t have idea whats is going on... :|

**Comment by XiaoFaye** [comment]
You might have imported the WooCommerceNET.WooCommerce.Legacy namespace in the top of the source code, could you please have a look at that?

**Comment by raulbv** [comment]
I have it already...

**Comment by XiaoFaye** [comment]
then you will need to change it to **WooCommerceNET.WooCommerce**  or you can change your code in the following way:

WooCommerceNET.WooCommerce.WCObject wc = new WooCommerceNET.WooCommerce.WCObject(rest);

**Comment by raulbv** [comment]
Thanks a lot!!! now when a I try to use "GetProducts()", gives me a "NullReferenceException"... I'm trying something like this:

WooCommerceNET.WooCommerce.WCObject wc =  new WooCommerceNET.WooCommerce.WCObject(rest);

var products = await wc.GetProducts();

**Comment by XiaoFaye** [comment]
Could you please send me the full detail of the exception? screenshot or anything.

**Comment by raulbv** [comment]
Yes, sure... The message complete shows:

"An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll

Additional information: Object reference not set to an instance of an object."

P.D.: I can send you a screenshot, but there is in spanish... is that a problem?? ':)

**Comment by XiaoFaye** [comment]
not a problem, It will help me to trace the exception.

**Comment by raulbv** [comment]
![exception](https://cloud.githubusercontent.com/assets/22373057/18766311/333cb600-80df-11e6-899b-6696c367b649.png)

**Comment by XiaoFaye** [comment]
This doesn't say much, If you can send me a set of the API keys (with Read Only rights), I might be able to do some testing on my side.

**Comment by raulbv** [comment]
Ok, let me change the config and I will send you... Give me a few minutes, please

**Comment by raulbv** [comment]
Do you have a email to send you the API Keys?? Please

**Comment by XiaoFaye** [comment]
yes, please send it to xiaofaye(at)msn.com

**Comment by raulbv** [comment]
Ready, I just send you the keys. 👍

**Comment by XiaoFaye** [comment]
It seems I have no permission to access the API, even I ran it from curl.

![image](https://cloud.githubusercontent.com/assets/6334728/18767918/0a2737f8-8176-11e6-8991-c67b67f1c6c2.png)

**Comment by raulbv** [comment]
Sorry for that... But already works... could you please have a look again?

**Comment by XiaoFaye** [comment]
Yes, it's working now, I have tested the code.
![image](https://cloud.githubusercontent.com/assets/6334728/18768415/17192522-8179-11e6-8abe-7c89291445f5.png)


Still, you will need to change the url to https://beta.bikeworld.com.mx/wp-json/wc/v1/ , which should be the same as your WooCommerce settings.

**Comment by raulbv** [comment]
Excuse my ignorance... but let me see if I understand, I need change the URL without "www" in the code and WooCommerce Settings too??

**Comment by raulbv** [comment]
![image](https://cloud.githubusercontent.com/assets/22373057/18769048/5e11de18-80ef-11e6-94d6-891953983fdc.png)

Thank you a lot James!!! You're so kind!! But...

I change teh URL in the WooCommerce settings, but when a I try "GetProducts()" still send me the same "NullReferenceException"

I put you the way I'm using the method, I'm missing something??

**Comment by XiaoFaye** [comment]
What I mean is in your WooCommerce settings, the store url is https://beta.bikeworld.com.mx , is that right?  So when you are making API calls, you need to use the same url prefix: https://beta.bikeworld.com.mx/wp-json/wc/v1/  , the url host need to be the same.

**Comment by raulbv** [comment]
Ok I understand... actually I'm sure the store url is https://beta.bikeworld.com.mx and that is the same url prefix that I'm using... However, I don't know if I'm missing something in code or why shows me "NullReferenceException"...

I need to have a look something in my project settings??

**Comment by XiaoFaye** [comment]
Can you debug into the source code and see which line of code cause the error?

**Comment by raulbv** [comment]
Yes, sure... actually I did debug the classes and I found that in "RestAPI.cs" in the line 85:
"WebResponse wr = await httpWebRequest.GetResponseAsync();"
I got the exception...

I can found too, that in the line 59:
"httpWebRequest = (HttpWebRequest)HttpWebRequest.Create(wc_url + GetOAuthEndPoint(method.ToString(), endpoint, parms));"
The properties "ChallengedURI" and "ResponseStatusCode", returns "NullReferenceException".

Thanks a lot!!

**Comment by XiaoFaye** [comment]
are you using wc.GetProducts() ? or other routes?

BTW: GetProducts works fine for me.

**Comment by raulbv** [comment]
actually I used two routes: wc.GetProducts() and wc.GetProduct(idProduct)... but both gives me the same exception...

**Comment by XiaoFaye** [comment]
I have tried both, all working fine for me. Is your network behind a proxy?

**Comment by raulbv** [comment]
No, we don't have a proxy in office... Really I don´t know what is happining... I've searched a solution, but I haven't found anything... :|

**Comment by XiaoFaye** [comment]
Is it possible to run your application from another environment? like from home? sometimes the company firewall might have blocked it.

**Comment by raulbv** [comment]
Ok, I will try it... Anyway, thanks for all.
