### ISSUE TITLE
Error deleting multiple ProductAttributeTerms

### ISSUE THREAD

**Issue by Aldwoni** [XiaoFaye/WooCommerce.NET#291]
Wordpress version(4.9.7), 
WooCommerce version(3.4.3) 
WooCommerce.NET version(0.7.3,also tried on 0.7.4 & 0.7.5) 

Sending in Multiple ProductAttributeTerms to remove like:
- var result = await service.Attribute.Terms.UpdateRange(row.Key, batch).ConfigureAwait(false);

I see a result coming to the RestAPI.cs DeserializeJSon<T>(string jsonString) methode where jsonString is

{"delete":[
	{"id":25483,"name":"Nee","slug":"nee","description":"","menu_order":0,"count":58,"_links":{"self":[{"href":"https:\/\/wordpress.example.nl\/wp-json\/wc\/v2\/products\/attributes\/(?P<attribute_id>[\\d]+)\/terms\/25483"}],"collection":[{"href":"https:\/\/wordpress.example.nl\/wp-json\/wc\/v2\/products\/attributes\/(?P<attribute_id>[\\d]+)\/terms"}]}}
,{"id":25482,"name":"Ja","slug":"ja","description":"","menu_order":0,"count":195,"_links":{"self":[{"href":"https:\/\/wordpress.example.nl\/wp-json\/wc\/v2\/products\/attributes\/(?P<attribute_id>[\\d]+)\/terms\/25482"}],"collection":[{"href":"https:\/\/wordpress.example.nl\/wp-json\/wc\/v2\/products\/attributes\/(?P<attribute_id>[\\d]+)\/terms"}]}}]}

and  T = BatchObject<ProductAttributeTerm>
({Name = "BatchObject`1" FullName = "WooCommerceNET.Base.BatchObject`1[[WooCommerceNET.WooCommerce.v2.ProductAttributeTerm, WooCommerceNET, Version=0.7.3.0, Culture=neutral, PublicKeyToken=null]]"})

The error I GET after Line 301.
System.ServiceModel.FaultException`1[[Example.Services.WCF.ErrorReportResult, Example.Services.WCF]]: One of more Errors occured. (There was an error deserializing the object of type WooCommerceNET.Base.BatchObject`1[[WooCommerceNET.WooCommerce.v2.ProductAttributeTerm, WooCommerceNET, Version=0.7.3.0, Culture=neutral, PublicKeyToken=null]]. The value '' cannot be parsed as the type 'Int32'.)

**Comment by XiaoFaye** [comment]
Has the ProductAttributeTerms been deleted ?

**Comment by XiaoFaye** [comment]
Then it should be fine, as they have been deleted, it doesn't matter if the return value can be deserialized or not.

**Comment by Aldwoni** [comment]
How do I know if the ids have been removed without a user checking the database?

**Comment by Talented-Business** [comment]
Hello
var result = await service.Attribute.Terms.UpdateRange(row.Key, batch).ConfigureAwait(false);
Can you inform the class of second param batch above code?
I can't find BatchObject of ProductAttributeTerm in current package.
