### ISSUE TITLE
Can't upgrade beyond version 0.7.3 

### ISSUE THREAD

**Issue by smashed2bitz** [XiaoFaye/WooCommerce.NET#294]
Greetings,

I'm using Visual Studio 2015 Pro, and have WooCommerce.NET 0.7.3 installed using NuGet.  I am targeting .NET 4.6.1 to be compatible with another library I need as well.  

I am unable to upgrade to the later versions of 0.7.4 or 0.7.5,   What changed in 0.7.4 to prevent upgrading on this .NET version?  Anything I can do to override this?

Here's the output from the log:

Attempting to gather dependency information for package 'WooCommerceNET.0.7.4' with respect to project 'BackofficeManager', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'WooCommerceNET.0.7.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'WooCommerceNET.0.7.4'
Resolved actions to install package 'WooCommerceNET.0.7.4'
Removed package 'WooCommerceNET.0.7.3' from 'packages.config'
Successfully uninstalled 'WooCommerceNET.0.7.3' from BackofficeManager
  GET https://api.nuget.org/v3-flatcontainer/woocommercenet/0.7.4/woocommercenet.0.7.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/woocommercenet/0.7.4/woocommercenet.0.7.4.nupkg 354ms
Installing WooCommerceNET 0.7.4.
Install failed. Rolling back...
Package 'WooCommerceNET.0.7.4' does not exist in project 'BackofficeManager'
Package 'WooCommerceNET.0.7.3' already exists in folder 'C:\Git\WAABackofficeManager\packages'
Added package 'WooCommerceNET.0.7.3' to 'packages.config'
Package 'WooCommerceNET.0.7.4' does not exist in folder 'C:\Git\WAABackofficeManager\packages'
Could not install package 'WooCommerceNET 0.7.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by XiaoFaye** [comment]
The library has targeted .net core 2.0 since 0.7.4.

**Comment by pilotkid** [comment]
@XiaoFaye How do we get around that to update? I have tried dropping my project's .NET version to 2.0 and I still cannot update to 0.7.5

**Comment by XiaoFaye** [comment]
@pilotkid  It's .NET Core 2.0, NOT .NET Framework 2.0
