### ISSUE TITLE
Registering Media

### ISSUE THREAD

**Issue by Anooshmoosh** [XiaoFaye/WooCommerce.NET#295]
This API works great.  One thing that is missing is ability to register Media for products.  We need the image id for attaching images to the product/variations.  I am using FTP to send images over to the site but can't get the images registered to obtain an ID.  Any ideas how best to achieve this?

**Comment by Anooshmoosh** [comment]
I now realize that I have to set the src parameter of the image to the URL of the image.  I am doing an FTP of the image to the  directory and then setting the src as such:
  WCProductImage = new ProductImage();
                    WCProductImage.src = "https://mydomain//wp-content/uploads/2018/06/StoreTestMask_img8.jpg";
                    WCProductImage.name = Path.GetFileNameWithoutExtension(MediaURL);
                    WCProductImage.position = 0;
                    Images.Add(WCProductImage);

but still get errors.  In fact I get the same error for any call with issue.   Yes I have tried using http as well but did not help.

Error:  An exception of type 'System.AggregateException' occurred in mscorlib.dll but was not handled in user code

 I realize this is due to a JSON serialization problem but have not seen a resolution in my searches.  This is frustrating as I have to debug my code with no clue on what caused the error!  Any help appriciated.

**Comment by XiaoFaye** [comment]
You can hook into jsonSerializeFilter and jsonDeserializeFilter to see the actual errors. Are you sure the image url is accessiable?

**Comment by Anooshmoosh** [comment]
Yes, typing in the URL in browser shows the image.  I am downloading in WP directory which is local to Woocommerce such as:
http://mydomain.com//wp-content/uploads/ProductMedia/StoreTestMask_img4.jpg

Also thanks for the pointer on hooking jsonDeserializeFilter.  Puting a break point on the first line of this function and it is not hit:
 public virtual T DeserializeJSon<T>(string jsonString)
{
   ....

**Comment by XiaoFaye** [comment]
Are you using Json.NET for serialize and deserialize?

**Comment by Anooshmoosh** [comment]
I think so.  Isnt it the default?  In my environment, I have downloaded the WooCommerce project from am building it as a sub project of of my application.  Nuget package manager says JSON.Net is already installed.  Do I have to do anything else?

**Comment by XiaoFaye** [comment]
No, it's not the default, you can check the wiki here: https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-JSON.NET-in-WooCommerce.NET

**Comment by Anooshmoosh** [comment]
Thank you for your pointing this out to me.  I am now using the following code:
  public class MyRestAPI : WooCommerceNET.RestAPI
        {
            public MyRestAPI(string url, string key, string secret, bool authorizedHeader = true,
                Func<string, string> jsonSerializeFilter = null,
                Func<string, string> jsonDeserializeFilter = null,
                Action<System.Net.HttpWebRequest> requestFilter = null)
                : base(url, key, secret, authorizedHeader, jsonSerializeFilter, jsonDeserializeFilter, requestFilter)
            {
            }

            public override T DeserializeJSon<T>(string jsonString)
            {
                return JsonConvert.DeserializeObject<T>(jsonString);
            }

            public override string SerializeJSon<T>(T t)
            {
                return JsonConvert.SerializeObject(t);
            }
        }

        public static string DeserializeFilter(string S)
        {
            return S;
        }

I am putting a breakpoint in above line "return S;" and it never hits it when throwing the System.AggregateException.  The inner exception is blank, so, no clue!

In any case, I verified that even with exception, the image makes it to the woocommerce media library. It even says "Uploaded To  Store test product"  which is the test product I am using.  The image however does not show in the product page.  This is a variable product with no image for the variation.  For now I only have loaded one variation.

**Comment by Anooshmoosh** [comment]
Forgot to include the way I instantiate the rest api:
 bool bSendAuthInHeader = true;
 WooCommerceNET.RestAPI rest = new MyRestAPI("https://MyDomain.com/wp-json/wc/v2/", WooCommerceKey, WooCommerceSecret, bSendAuthInHeader, null, DeserializeFilter); 

 WCObject WC = new WCObject(rest);

**Comment by Anooshmoosh** [comment]
There was an issue with WC renaming same product loaded more than once in my trials as duplicates and appending _0x to them.  Manually deleting those when testing allows me to get around that.  Now  the image gets transferred, attached to the product but the call still throws an exceptinon, this time a WebException on line 192 of RestAPI.cs.  Debugging this I see the response is   {"The remote server returned an error: (500) Internal Server Error."}.  Because of this I do not get the id of the newly created product and image which i need to keep synchronized with my DB.

**Comment by XiaoFaye** [comment]
You can use webResponseFilter to see what it actually responses.

**Comment by Anooshmoosh** [comment]
I looked at it via break point and the response content is "The remote server returned an error: (500) Internal Server Error."}

**Comment by Anooshmoosh** [comment]
The fact that the image is created on WP just fine and is even attached but the call does not get completed with the return object is preplexing.  I just tested with setting the image.id of an existing image (one that I uploaded earlier)  and porduct.update() worked.   I used to set the image.id for upload images to null.  I also tried with not setting it at all in the hope that image.id setting is the culprit

**Comment by XiaoFaye** [comment]
It seems WooCommerce has errors after setting up the image, please check the debug info from WordPress and WooCommerce. Or you can use Postman to manually call the API and see how it goes.

**Comment by Anooshmoosh** [comment]
Yes, I am on the same hunt!  Found this in debug logs:

[03-Aug-2018 00:37:32 UTC] PHP Fatal error:  Out of memory (allocated 95158272) (tried to allocate 86 bytes) in /home2/myname/apnemed.com/wp-includes/option.php on line 382

Tried to increase the limit in php.ini and .htaccess but server may need to be restarted. I'll contact the provider. Thanks for chasing this with me!

**Comment by XiaoFaye** [comment]
In SerializeJSon, you should get the json string for updating image, in webRequestFilter, you will get the correct url to post the json string.

**Comment by Anooshmoosh** [comment]
This is finally fixed! There were several layers of problems that complicated things but the one creating the WebException was php running out of memory.  It was not sufficient to add php.ini with higher thresholds to Woocommerce.  Had to also update .htaccess to point to it.  All works now.  Thanks for all the help to get to the bottom of this.
