### ISSUE TITLE
401 Error - woocommerce_rest_cannot_view

### ISSUE THREAD

**Issue by dave92220** [XiaoFaye/WooCommerce.NET#296]
**Woo commerce** 3.4.4
**WordPress** 4.9.8
**.net** 4.6.1 with version 0.7.5.0 (Also occurred on 0.7.3.0)

I am setting up a new client on our .net appication, so created the API key as required, however when I come to do a call (for example below), it returns a Status 401 - woocommerce_rest_cannot_view. 

**Full Error**
_Message={"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}_

Code to make the call
RestAPI rest = new RestAPI("http://website.co.uk/wp-json/wc/v2/", "key", "secret");
WCObject = new WCObject(rest);
var products = await wc.Product.GetAll();

This code does work with 2 difference wordpress / woocommerce sites.  One of them being on matching versions to the new setup above (see versions above).

Can you please advise what would be causing this error?

I have tried this on wc.Orders.GetAll(); , and got the same response.
I have also set the True / False for the authorizedHeader and got the same result.
message if there is any

**Comment by XiaoFaye** [comment]
Please check #211

**Comment by dave92220** [comment]
I will get them to check the Web Server permissions, as I attempted adding false as a 4th Parameter, but got the same response.

What kind of permissions would you expect to return this error?

**Comment by dave92220** [comment]
Hi, will get the logs checked.  To confirm I did use the correct prefix for the endpoint url.  It is http://
