### ISSUE TITLE
Get all brands

### ISSUE THREAD

**Issue by leandroalves2014** [XiaoFaye/WooCommerce.NET#297]
Hello,

You can get all the brands and associate them with the products?

I have no option to get this information from the api.

Thank you.
Leandro Alves

**Comment by XiaoFaye** [comment]
Is the brands comes with WooCommerce by default?

**Comment by leandroalves2014** [comment]
Hello, really the brands are not native to the woocommerce platform.

A plugin was used to create this functionality, is it possible to perform some updating of the brands and update the products through api?

Thank you
Leandro Alves

**Comment by XiaoFaye** [comment]
You can check if this plugins provides Restful API, some of them might.

If not, you will need to create your own API for it.

**Comment by doommaker79** [comment]
Hi,
can you help me implementing the brands? the office link is here:
https://woocommerce.com/document/woocommerce-brands/#rest-api-support
but I'm stuck. thanks.
