### ISSUE TITLE
product.getall() return only 10 items 

### ISSUE THREAD

**Issue by mickeymarko** [XiaoFaye/WooCommerce.NET#298]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
WP 4.9.8 WC  3.4.4 WC.net 0.75

- Steps to replicate the issue
do get all
- Details of the error message if there is any
no error

**Comment by XiaoFaye** [comment]
This is default behavior, please see #88

**Comment by efimomax** [comment]
please meke a per_page parameter in RestApi or WCObject as property
and than result will be from 0 to 100 
http://woocommerce.github.io/woocommerce-rest-api-docs/#pagination

**Comment by mickeymarko** [comment]
thanks
