### ISSUE TITLE
Update attribute option on Product[0].attributes[0].options[0]

### ISSUE THREAD

**Issue by grobekelle** [XiaoFaye/WooCommerce.NET#300]
Hi there,

I would like to update the attribute options on Product[0].attributes[0].options[0], but i don`t have an idea how to. Is there an code example or could anybody help me out?

Thanks in advance

WooCommerce.NET 0.7.5
WordPress 4.9.8
WooCommerce 3.4.4

**Comment by XiaoFaye** [comment]
1. Get the product,
2. Make change to the product object
3. Update the product
