### ISSUE TITLE
Clear the value of Sale_Price and update the variation product from the API

### ISSUE THREAD

**Issue by leandroalves2014** [XiaoFaye/WooCommerce.NET#302]
I'm trying to update the value of Sale_Price to NULL but in the site the value always gets the orginal.

Example code:

updVariation.sale_price = updStoreProduct.OnlineSalePrice <= 0? (decimal?) null: Convert.ToDecimal (updStoreProduct.OnlineSalePrice);

Is it possible to clear this value through the API?

Thank you for your help

**Comment by XiaoFaye** [comment]
Have you checked this?

![image](https://user-images.githubusercontent.com/6334728/44883840-bd2f3300-ad0c-11e8-9d8c-82d17ef9a062.png)

**Comment by leandroalves2014** [comment]
Yes I saw but I need to update the product variation and this method does not exist.

Is it possible to add to the variation of the product?

Example code

await _storeService.WcObject (). Product.Variations.Update (variation_id, updVariation, parent_id);

Thank you

**Comment by XiaoFaye** [comment]
Yes, it seems UpdateWithNull is missing for variation, I will add it ASAP.

**Comment by christechno25** [comment]
Hello. How do you clear the sale price of a variation? Like this?

Await wc.Product.Variations.UpdateWithNull(......................)?

I can't seem to find the UpdateWithNull method under Variations. Thank you very much.
