### ISSUE TITLE
null trying to getAll()

### ISSUE THREAD

**Issue by carloscarniato** [XiaoFaye/WooCommerce.NET#305]
Wordpress : 4,9,8
Woocommerce: 3.4.4 with SSL
Woocommerce.NET: 0.7.3

Sorry for the question, i am new to ASP.NET and cant get this to work properly.
iam trying to get products in this method. the RestApi and WCObject was create propely but when trying to get products, null is returned.

[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<string> Create(SolicitacaoViewModel model, ProdutoSolicitacaoViewModel[] produtos, int? id, VendaFormaPagamentoViewModel[] formaPagamento)
        {
 RestAPI rest = new RestAPI(url, key, secret);
WCObject wc = new WCObject(rest);
var products = await wc.Product.GetAll();
}

**Comment by XiaoFaye** [comment]
Did it give you any error message? Have you try other like Category?

**Comment by carloscarniato** [comment]
> Did it give you any error message? Have you try other like Category?
I am getting this error in first line RestAPI
Exception thrown: 'System.FormatException' in mscorlib.dll

i managed to work in a new application, but cant in this project

**Comment by XiaoFaye** [comment]
@carloscarniato maybe your existing application is not compatible with the library.
