### ISSUE TITLE
Invalid parameter line_items, fee_lines

### ISSUE THREAD

**Issue by pavelekNET** [XiaoFaye/WooCommerce.NET#306]
when I call 

> return await _wc.Order.Update(order.id.Value, order);

I get error:

> line_items:line_items[0][subtotal] is not string
> fee_lines[0][total_tax] is not string

after checking newest Woocommerce REST API v2 documentation, there is:

> attribute: total_tax, type: string
> attribute: subtotal, type: string

C# Order properties are decimal or object when I look at DataMember attribute.

Woocommerce version: 3.4.5
WoocommerceNET version: 0.7.5

**Comment by XiaoFaye** [comment]
did you use Json.NET for serialize?

**Comment by pavelekNET** [comment]
Yes I am using Newtonsoft.Json. Before I updated Woocommerce to the latest version (there was really old version) it worked fine but after the update, this happend. I did a workaround that in JsonSerializationFilter I am setting line_items[x][subtotal] = line_items[x][subtotal].ToString()  for other invalid fields its same process.

**Comment by XiaoFaye** [comment]
Woocommerce only recognizes decimals in string, but Json.NET won't know that. That's why the error is happening. JsonSerializationFilter is a good workaround for this issue.

**Comment by OscarLate** [comment]
I'm trying do the same with JsonSerializationFilter, can you show me example for it? I feel lost.
