### ISSUE TITLE
403 Forbidden on any request.

### ISSUE THREAD

**Issue by topherZa** [XiaoFaye/WooCommerce.NET#307]
Hi,

I'm getting the below error on any request I make to one site. I don't have any other sites to test against, however I can make the same requests with the WooCommerce python module successfully. I'm using the same consumer key/secret for both. I've included both requests below:

**.net:**
> GET /wp-json/wc/v2/products/categories?oauth_consumer_key=<consumer_key>&oauth_nonce=90655125f652493f8ecf2181c2eba2d8&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1537440585&oauth_signature=StjADqLoacMkAJFIFWN3R5712SbbpsUeGLKW8azwv1w%3D HTTP/1.1
> Connection: Keep-Alive
> Host: test.host.com
> 

**python:**
> GET /wp-json/wc/v2/products/categories?oauth_consumer_key=<consumer_key>&oauth_timestamp=1537440659&oauth_nonce=2d8b26a1a93c231edb0636ed8fdcf4a46b2dfc1f&oauth_signature_method=HMAC-SHA256&oauth_signature=D29jgUareTxDvrhNfpzRihmHKrHRxithmhPPJuwj438%3D HTTP/1.1
> Host: test.host.com
> user-agent: WooCommerce API Client-Python/1.2.1
> Accept-Encoding: gzip, deflate
> accept: application/json
> Connection: keep-alive

I'm using the .net library as follows and I have tried putting ```false``` as the fourth parameter as well without luck: 
```
rest = new RestAPI("http://test.host.com/wp-json/wc/v2", consumerKey, consumerSecret); 
wc = new WCObject(rest);
var request =  await wc.Attribute.GetAll();
```

- Wordpress version, WooCommerce version and WooCommerce.NET version

> WP Version: 4.9.8
> WooCommerce version: 3.4.5
> WooCommerce.NET version: 0.7.5

**Error Message:**
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>403 Forbidden</title>
> </head><body>
> <h1>Forbidden</h1>
> <p>You don't have permission to access /wp-json/wc/v2/products/categories
> on this server.<br />
> </p>
> <p>Additionally, a 403 Forbidden
> error was encountered while trying to use an ErrorDocument to handle the request.</p>
> </body></html>

Any help would be appreciated.

**Comment by topherZa** [comment]
Okay, I found a thread on WP support where a plugin was causing the request to always be thrown out with a 403 due to the user-agent being blank with reasons described in the link: Link [here](https://wordpress.org/support/topic/403-forbidden-with-woocommerce-rest-api-v2/)

I think a user-agent should be included probably by default?

**Comment by XiaoFaye** [comment]
@topherZa  Great finding! 
Since we can use requestFilter to add UserAgent, I wouldn't put a default user agent.

**Comment by topherZa** [comment]
Ah of course. Thank you. I've been rushing to complete this project so haven't taken more time to explore your library. Thanks for all your hard work in putting this together.

**Comment by robkite** [comment]
I just ran up against this issue and wasted a lot of time trying to understand why requests in anything else (such as Postman) were successful.

The requestFilter is great for resolving the issue but could this at least be highlighted in the documentation? Lots of hosts seem to like to reject anything without a user agent string and while the fix is trivial, it's only easy once you have identified what the issue is.

**Comment by XiaoFaye** [comment]
@robkite Sorry for the confusion, I have highlighted the wiki link on the project home page.
