### ISSUE TITLE
Get products with filter

### ISSUE THREAD

**Issue by mauriciosouza** [XiaoFaye/WooCommerce.NET#308]
How can I get all products with the filter limit? When I have brackets I get an exception.

`RestAPI rest = new RestAPI("http://url.com.br/store/wc-api/v3/", "", "");
            WCObject wc = new WCObject(rest);
            var products = await wc.GetProducts(new Dictionary<string, string>() {
                { "filter[limit]", "15" }
            }
            );`

- Wordpress version:4.8.7 , WooCommerce version: 2.6.14 and WooCommerce.NET version: 0.7.5

**Comment by XiaoFaye** [comment]
Please try ` { "per_page", "15" }`

**Comment by mauriciosouza** [comment]
per_page does not work

**Comment by XiaoFaye** [comment]
What do you mean it doesn't work? did you get an error message or it returns something unexpected?

**Comment by simonemarra** [comment]
In my case, I have a default behaviour of "per_page" of 10. Using the Dictionary string
{ "per_page", "100"} is accepted, but increasing it result in error from REST API.

I'm not a wordpress or woocommerce expert, so I don't know if it is a standard behaviour. What I need to understand is if I can access the  X-WP-Total and X-WP-TotalPages headers using your library, just to know how many HTTP call I should execute to get all data.

**Comment by XiaoFaye** [comment]
Setting the page size to a big value might cause heavy database load and sql query time out.

Sure you can access the X-WP-Total and X-WP-TotalPages headers, see #196
