### ISSUE TITLE
Adding items in order gives NullReferenceException

### ISSUE THREAD

**Issue by marinak13** [XiaoFaye/WooCommerce.NET#309]
I am trying to use this code for making an order in Woocommerce: 
          
            var order = new Order() { status = "pending" };
            order.currency = "EUR";
            order.line_items.Add(new OrderLineItem()
            {
                id=44,
                product_id = 44,
                quantity=2
            }
              );
            order.customer_id = 1;
      
           Task ord = wc.Order.Add(order);
           ord.Wait();

But everytime it gives me this exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

I have tried everything but no success....

**Comment by XiaoFaye** [comment]
Have you try `order.line_items = new ...` first?

**Comment by marinak13** [comment]
Yes! This was the solution! Thank you so much for your help!
