### ISSUE TITLE
Error: 500 internal error.

### ISSUE THREAD

**Issue by mathandsciencechannel** [XiaoFaye/WooCommerce.NET#31]
This seems like a consistent error, so i will post it.
I can post a product normally and it will work fine, the first time. The second time, it will return an error containing the html of the website where it has a 500 internal error.

**Comment by mathandsciencechannel** [comment]
`An exception of type 'System.Exception' occurred in mscorlib.dll but was not handled in user code

Additional information: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

<html><head>

<title>500 Internal Server Error</title>

</head><body>

<h1>Internal Server Error</h1>

<p>The server encountered an internal error or

misconfiguration and was unable to complete

your request.</p>

<p>Please contact the server administrator at 

 webmaster@datlu.org to inform them of the time this error occurred,

 and the actions you performed just before this error.</p>

<p>More information about this error may be available

in the server error log.</p>

<p>Additionally, a 500 Internal Server Error

error was encountered while trying to use an ErrorDocument to handle the request.</p>

</body></html>`

**Comment by XiaoFaye** [comment]
I have tried to post product twice, didn't get any error, Could you please look into the details and see what the actual error is?

![image](https://cloud.githubusercontent.com/assets/6334728/18929677/eb590b84-8621-11e6-88d8-92147b68e7d7.png)
