### ISSUE TITLE
Error adding ProductImage

### ISSUE THREAD

**Issue by malkurwi2** [XiaoFaye/WooCommerce.NET#310]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version **4.9.8**, WooCommerce version **3.4.5** and WooCommerce.NET version **is it PHP? if yes => 7.2.10?**

**- Steps to replicate the issue**

    Dim products As Object
    Dim NewProduct As Object
    Dim OnLineProduct As New Product

    Private Sub InsertNewItemToOnlineStore()
        Try
            OnLineProduct = New Product
            OnLineProduct.name = CellValue("Name")
            OnLineProduct.description = CellValue("Description")
            OnLineProduct.regular_price = CellValue("Price")
            OnLineProduct.type = "simple"
            OnLineProduct.stock_quantity = 1
            If IO.File.Exists(Application.StartupPath & "\images\" & ImgFolder & "\" & (CellValue("Name")) & ".Tiff") Then
                Dim lstImges As New List(Of ProductImage)
                Dim blog As New WordPressWrapper(_Website & "/xmlrpc.php", _AdminUserName, _AdminPassword)
                Dim MyOnlineImg = Image.FromFile(Application.StartupPath & "\images\" & ImgFolder & "\" & (CellValue("Name")) & ".Tiff")
                Dim ms As New MemoryStream()
                Dim myImageCodecInfo As ImageCodecInfo
                Dim myEncoder As System.Drawing.Imaging.Encoder
                Dim myEncoderParameter As EncoderParameter
                Dim myEncoderParameters As EncoderParameters
                myImageCodecInfo = GetEncoderInfo(ImageFormat.Png)
                myEncoderParameters = New EncoderParameters(1)
                myEncoder = System.Drawing.Imaging.Encoder.Quality
                myEncoderParameter = New EncoderParameter(myEncoder, CType(50L, Int32))
                myEncoderParameters.Param(0) = myEncoderParameter
                MyOnlineImg.Save(ms, myImageCodecInfo, myEncoderParameters)
                Dim imgdata() As Byte = ms.GetBuffer
                Dim ReceivedOnlineImg = blog.NewMediaObject(New MediaObject With {.Bits = imgdata, .Name = (OnLineProduct.name) & ".Png", .Type = "image/Png"})
                Dim OnlineImg As New ProductImage
                OnlineImg.name = (OnLineProduct.name) & ".Png"
                OnlineImg.alt = (OnLineProduct.name) & ".Png"
                OnlineImg.src = ReceivedOnlineImg.URL
                OnlineImg.position = 0
                OnlineImg.date_created = Now
                OnlineImg.date_modified = Now
                lstImges.Add(OnlineImg)
                OnLineProduct.images = lstImges
                MyOnlineImg.Dispose()
                ms.Close()
            End If
            OnLineProduct.categories = New List(Of ProductCategoryLine) From {New ProductCategoryLine() With {.id = 1}}
            NewProduct = wc.Product.Add(OnLineProduct)
            Dim tmrNewProduct As New Timer With {.Interval = 500, .Enabled = True}
            AddHandler tmrNewProduct.Tick, AddressOf tmrNewProductTick
        Catch ex As Exception
            XtraMessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub tmrNewProductTick(sender As Object, e As EventArgs)
        If NewProduct IsNot Nothing AndAlso NewProduct.status <> TaskStatus.WaitingForActivation Then

            sender.stop
            If NewProduct Is Nothing OrElse NewProduct.status = System.Threading.Tasks.TaskStatus.Faulted Then
                _OnlineItemID = -1
            Else
                _OnlineItemID = NewProduct.Result.id
            End If

           End If

    End Sub

    Public Function GetEncoderInfo(ByVal format As Imaging.ImageFormat) As Imaging.ImageCodecInfo
        Dim j As Integer
        Dim encoders() As ImageCodecInfo
        encoders = ImageCodecInfo.GetImageEncoders()
        j = 0
        While j < encoders.Length
            If encoders(j).FormatDescription.ToLower.Contains(format.ToString.ToLower) Then
                Return encoders(j)
            End If
            j += 1
        End While
        Return encoders(j)
    End Function

**- Details of the error message if there is any**

So from code above the **ReceivedOnlineImg**  has a **URL** = "http://pointofsalestore2.jeffcomputers.com/point_of_sale_store/wp-content/uploads/2018/09/Name.png"

That is valid and I can go to it, works fine!

But then the on the **timer Tick event**, I get **NewProduct Status = Faulted**. With this exception **message**:
 {"code":"woocommerce_product_image_upload_error","message":"Error getting remote image http:\/\/pointofsalestore2.jeffcomputers.com\/point_of_sale_store\/wp-content\/uploads\/2018\/09\/1-Order-3-eggs-7.png. Error: cURL error 6: Could not resolve host: pointofsalestore2.jeffcomputers.com.","data":{"status":400}}

**Comment by XiaoFaye** [comment]
Have you tried images from other places? outside this domain.
