### ISSUE TITLE
I can not call rest Api because i use this plugin : "Login to See Add to Cart and Prices in WooCommerce"

### ISSUE THREAD

**Issue by alialinia** [XiaoFaye/WooCommerce.NET#311]
- Wordpress 4.9.8, WooCommerce 3.4.3 and WooCommerce.NET 0.7.5

- when i active the plugin , then i get error  and when i deactive the plugin i do not get any error

- Details of the error message 
{
"code": "woocommerce_rest_cannot_view",
"message": "Sorry, you cannot list resources.",
"data": {
    "status": 401
   }
}

**Comment by XiaoFaye** [comment]
This plugin conflict with the WooCommerce RESTFUL API, you might want to check with the author.
