### ISSUE TITLE
How do you attach an image to a variation?

### ISSUE THREAD

**Issue by christechno25** [XiaoFaye/WooCommerce.NET#317]
Hello everybody. I have been working on a Windows form application that can create update delete products on Woocommerce. I am now able to create/update/delete products even with variations. However, I cannot seem to get how to attach an image to a variation. I am able to attach images to a Parent Product but not on a variation. Basically I upload the images first and retrieve their IDs. That's what I do on parent products and I did a similar way on variations but it didn't work. 

I have this code...

           `Dim product_image As New VariationImage
            product_image.id = ds.Tables("info").Rows(x).Item("image")
            var = New Variation() With {
                .sku = ds.Tables("info").Rows(x).Item("CSKU"),
                .description = ds.Tables("info").Rows(x).Item("CDescription"),
                .regular_price = CDec(ds.Tables("info").Rows(x).Item("CRegular_Price")),
                .visible = True,
                .attributes = vatribs,
                .in_stock = ds.Tables("info").Rows(x).Item("CIn_Stock"),
                .manage_stock = ds.Tables("info").Rows(x).Item("CManage_Stock"),
                .stock_quantity = CInt(ds.Tables("info").Rows(x).Item("CStock_Quantity")),
                .image = product_image
                }`

On `product_image.id = ds.Tables("info").Rows(x).Item("image")`, an error would occur and it would say...

![untitled](https://user-images.githubusercontent.com/13817176/47613842-08797e00-dad1-11e8-8213-15dccf3a228a.png)

What is the correct way to do this? Thank you so much everybody.

Wordpress version - 4.9.8
WooCommerce version - 3.4.5
WooCommerce.NET version - 0.7.5

**Comment by XiaoFaye** [comment]
id is Integer, I think you will need to convert the value type.

**Comment by christechno25** [comment]
Hi Sir. Thank you so much for this. It's actually an integer value but somehow it needed me to add CInt() even if it's already an integer. This is solved. Thank you so much for this.
