### ISSUE TITLE
PRODUCT.UPDATERANGE DOES NOT UPDATE

### ISSUE THREAD

**Issue by Henry6to** [XiaoFaye/WooCommerce.NET#318]
PRODUCT.UPDATERANGE DOES NOT UPDATE

ESTIMATED, FIRST THANK YOU FOR THE API BECAUSE IT IS OF MUCH UTILITY!

I AM WANTING TO UPDATE PRODUCTS MASSIVE (TO RAISE I DO NOT HAVE PROBLEMS, I UPLOAD IT OK AND I EVEN TAKE THE ID AND I CAN KEEP IT IN MY OWN DB)

THE PROBLEM IS WHEN IT SENDS UPDATE PRODUCTS MASSIVE, IT DOES NOT ABSOLUTELY DO NOTHING AND IT DOES NOT GIVE ME ANY ERROR. IF I UPDATE ONE ONLY DOES IT OK. USSING PRODUCTO.UPDATE(ID, NEW PRODUCTS) I DO NOT KNOW THAT I CAN BE DOING EVIL, I PASS THE PART OF THE CODE WHERE I COMMAND TO UPDATE ...

Dim mListWooCommerceProductUpdate As New List(Of List(Of WooCommerce.v2.Product))

   Dim mRest As New WooCommerceNET.RestAPI(mSitioWeb, Cliente, ClienteSecreto)
            Dim Wc As New WooCommerce.v2.WCObject(mRest)

            Dim mListaWC As New WooCommerceNET.Base.BatchObject(Of WooCommerce.v2.Product)

            For Each mListaDeProductoWC In mListWooCommerceProductUpdate
                mListaWC.update = mListaDeProductoWC
                Await Wc.Product.UpdateRange(mListaWC)
            Next

PD: FORGIVE FOR ENGLISH BUT USE THE TRANSLATOR,

Wordpress  4.9.8
Woocommerce 3.5
api woocommercenet.0.7.5

**Comment by XiaoFaye** [comment]
There might be a limitation of products you can update at the same time. Please try small amount first, like 10, and see how it goes.

**Comment by Henry6to** [comment]
Dear thank you very much, try with only 1 product and although it does not give an error, it does not update the price nor the stock.

if I do it with the update.product (id, product.v2.woocommerce) command if it works

I'm going to continue testing and if I achieve any progress I would like to thank you!
