### ISSUE TITLE
Product ID is not int when updating a product

### ISSUE THREAD

**Issue by Kismet64** [XiaoFaye/WooCommerce.NET#319]
Hi, sorry quite new to this but struggling getting this basic bit of code to update an existing product, its telling me the id is not an integer.
The only thing I can think of is the version of JSON I have used "Newtonsoft.Json.Net20.dll"
Any suggestions to where I am going wrong.

**the following code results in an exception**

> System.Net.WebException
>   HResult=0x80131509
>   Message={"code":"rest_invalid_param","message":"Invalid parameter(s): id","data":{"status":400,"params":{"id":"id is not of type integer."}}}
>   Source=WooCommerce.NET

  

 private async void button2_Click(object sender, EventArgs e)
        {
            MyRestAPI rest = new MyRestAPI("http:/xxxx.co.uk/shop/wp-json/wc/v2", "ckxxxx", "csxxxx");
            WCObject wc = new WCObject(rest);
          
            //Update products with new values
            Int wid = 1163;
            await wc.Product.Update(id: wid, new Product {name = "xxxxxxxxxxxx" });
        }

**Comment by Kismet64** [comment]
Hi, yes tried without the id and get the same error.
thanks for the suggestion 


Hola, sí intenté sin el id y obtendré el mismo error.
Gracias por la sugerencia
saludos

**Comment by Kismet64** [comment]
Closed in error, re-opened

**Comment by XiaoFaye** [comment]
WooCommerce returns all decimal data as string, if you are using Newtonsoft.Json, you will need to handle this manually.

**Comment by Kismet64** [comment]
Thanks again, sorry really daft question, how do I use it without  Newtonsoft.Json
I read this but not sure how to add Json.NET reference

Make sure you get WooCommerce.NET version 0.7.1 or higher from NuGet.org.
Add Json.NET reference to your project.
Define your own RESTAPI class as below:
