### ISSUE TITLE
Meta Filter

### ISSUE THREAD

**Issue by suhomlineugene** [XiaoFaye/WooCommerce.NET#32]
Hello. I try to set meta filter , because I don't see `meta` fields

I try to do it like this

`var orders = await wc.GetOrders(new Dictionary<string, string>() {
                { "per_page", "100" }, { "meta","true"} });`

But filter not work.

How I can set meta filter?

**Comment by XiaoFaye** [comment]
Hi, meta is only avaliable in Legacy api.
In the latest API, you might want to try **filter** parameter, as **it Use WP Query arguments to modify the response**.

**Comment by suhomlineugene** [comment]
How I can do this?


Can you write sample code?

**Comment by XiaoFaye** [comment]
I don't have a sample code, you can check the links below for full details of WP Query:

http://wordpress.stackexchange.com/questions/67141/can-i-query-custom-meta-data-through-wp-query
https://codex.wordpress.org/Class_Reference/WP_Query#Custom_Field_Parameters

**Comment by suhomlineugene** [comment]
so i need to write filter like this?

var orders = await wc.GetOrders(new Dictionary<string, string>() { { "per_page", "100" }, { "meta","meta_query"} });

**Comment by XiaoFaye** [comment]
I'm afraid I don't know the answer to your question, you will need to figure it out by yourself.
