### ISSUE TITLE
How can I get woocommerce_rest_authentication_error error immediately

### ISSUE THREAD

**Issue by bretbas** [XiaoFaye/WooCommerce.NET#321]
Hello. How can I get **woocommerce_rest_authentication_error** error immediately? When I try to transfer the domain key and code to RestAPI. 
`try
{
	var uri = new Uri(siteDomain, "wp-json/wc/v2");
	var restAPI = new RestAPI(uri.AbsoluteUri, keyAPI, codeAPI, false);
	wooObject = new WCObject(restAPI);
}
catch (Exception e)
{
	// Here I want catch unsuccessful connection
}`
The problem is that WooCommerce.NET tries to connect to the store when a specific request is already being made. And I need to check whether the authorization was successful or not

**Comment by bretbas** [comment]
@XiaoFaye , I don't have any exception when authentication is doing with wrong data.
For example:
![without_exception](https://user-images.githubusercontent.com/26548549/47927942-bc19ae00-ded5-11e8-9f81-29e738318627.gif)
But I get an exception when I already request data, for example products:
![within_exception](https://user-images.githubusercontent.com/26548549/47928231-a8227c00-ded6-11e8-9c3f-8221d42b4de9.gif)

**Comment by bretbas** [comment]
@XiaoFaye , 

> I will suggest you to make a simple request after creating the WCObject.
What is the simple request to do after creating a WCObject?

**Comment by XiaoFaye** [comment]
Request for Reports or Settings maybe
