### ISSUE TITLE
Is there a wc.Product.Variations.AddRange(....) method?

### ISSUE THREAD

**Issue by christechno25** [XiaoFaye/WooCommerce.NET#322]
Hello Sir. I can see that Woocommerce.NET has wc.Product.Variations.UpdateRange(...). Is it possible to create multiple variations at the same time and not just update existing variations? Possibly something that goes like...  

`wc.Product.Variations.AddRange(....)`

Thank you so much.

**Comment by XiaoFaye** [comment]
Actually you can create multiple variations in UpdateRange.
