### ISSUE TITLE
wc.Product.GetAll with "sku" parameter return only first product

### ISSUE THREAD

**Issue by marjanoh2** [XiaoFaye/WooCommerce.NET#324]
I have this code : 
 var start = wc.Product.GetAll(new Dictionary<string, string> { { "sku", "1014, 1015, 1016, 1017" } });

This method returns only first product(with sku 1014).

**Comment by XiaoFaye** [comment]
Looks like it only accepts a single SKU.

![image](https://user-images.githubusercontent.com/6334728/48165732-5bfa9000-e34b-11e8-9da0-51bab594bdf3.png)
