### ISSUE TITLE
How to get a currency of my shop?

### ISSUE THREAD

**Issue by bretbas** [XiaoFaye/WooCommerce.NET#325]
Hi. How can I get a currency of my shop? I see, that the currency I can get in Setting Options, but I don't find this.
![default](https://user-images.githubusercontent.com/26548549/48299024-11f2e500-e4d8-11e8-883e-b385b153d01f.jpg)
WooCommerce.NET 0.7.3

**Comment by bretbas** [comment]
@XiaoFaye , Can you help me?

**Comment by XiaoFaye** [comment]
You can get it on WooCommerce API V3, but I'm still working on it, should be released in the next version.

**Comment by bretbas** [comment]
@XiaoFaye , How long it takes?

**Comment by XiaoFaye** [comment]
All I can say is before Christmas.

**Comment by bretbas** [comment]
Ok, thanks

**Comment by negapo** [comment]
> All I can say is before Christmas.

Thank you very much for working on this.

**Comment by XiaoFaye** [comment]
@negapo  version 0.7.6 beta is out, you should be able to get the currency now.
