### ISSUE TITLE
Is it possible to Limit fields returned in GetAll (Products)

### ISSUE THREAD

**Issue by Kismet64** [XiaoFaye/WooCommerce.NET#326]
Wordpress Version 4.9.8
WooCommerce version 3.5.1
WooCommerce.NET version 0.7.5
Visual Studio community 2017 

I am trying to retrieve all products using the following code.
the code works fine in general but I have one product with a long complex description that causes an exception in the Newtonsoft.Json DeserializeJSon
This is the error I get from the product with the complex description. is there another way without using json or can point me at some examples

Newtonsoft.Json.JsonReaderException: 'After parsing a value an unexpected character was encountered: ". Path '[47].description', line 1, position 131895.'

or is there a way to limit what fields are requested so the description is not returned at all ie   { "fields", "sku,name.regular_price" },

           while (active)
            {
                var products = await wc.Product.GetAll(new Dictionary<string, string>() {
                    { "fields", "orderby.id" },
                    { "page", Cur_page.ToString() },
                    { "per_page", "100" } });

                if (products.Count == 0)
                {
                    break;
                }

PS, thanks for the support, great wrapper

**Comment by Kismet64** [comment]
Spent a few more hours and I believe I will have to handle the Deserialisation of the JSON string

**Comment by XiaoFaye** [comment]
I think it's possible in legacy api.

**Comment by Kismet64** [comment]
Found the issue, it was a plugin that alters the alt text of images to match the product, must have an issue with the API, still a bit wasteful of bandwidth pulling description back so will look at the legacy API for this.
Thanks again for the help,
