### ISSUE TITLE
How to use woocommerce multilingual

### ISSUE THREAD

**Issue by JannikWorkAccount** [XiaoFaye/WooCommerce.NET#329]
How can i use the WooCommerce.NET with WooCommerce Multilingual? 

I'm planning to use the WooCommerce.NET for my webpage. The problem without the mulilingual support it's useless. Have a look at this: [https://wpml.org/documentation/related-projects/woocommerce-multilingual/using-wordpress-rest-api-woocommerce-multilingual/](url)

Any suggestions?

**Comment by XiaoFaye** [comment]
Have you tried using parameters to pass the lang ?

**Comment by gitgiangalbe** [comment]
doesn't work or i'm doing something wrong.
i've modified model for this project, introducing "lang" and "translation_of" for Product DataContract.
So i send two request, the first one for product in default language (IT) and second one for english traslation. But result is two product without traslation and relation ...
Before start my test i read: https://wpml.org/documentation/related-projects/woocommerce-multilingual/using-wordpress-rest-api-woocommerce-multilingual/

Wordpress 5.0
WPML Multilingual CMS 4.1.1

Request JSON for traslation:

{"attributes":[{"id":367,"name":"CALZ. DONNA 34-42 CON ½  ","options":["36","37","38","39"],"position":0,"variation":true,"visible":true},{"id":367,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":367,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":381,"name":"COLORE","options":["NERO","NERO","NERO","NERO"],"position":0,"variation":true,"visible":true},{"id":381,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true},{"id":381,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true}],"backorders":"no","button_text":"","catalog_visibility":"visible","categories":[{"id":1955,"name":"FALL\/WINTER","slug":"FALL\/WINTER"},{"id":1962,"name":"APEPAZZA                 ","slug":"APEPAZZA                 "}],"cross_sell_ids":[],"default_attributes":[],"description":"English Descr","dimensions":{},"download_expiry":-1,"download_limit":-1,"downloadable":false,"downloads":[],"external_url":"","featured":true,"grouped_products":[],"images":[{"alt":"APEPAZZA SNEAKERS TENNIS  LACES VELLUTO","name":"DSE_3490jpg","position":0,"src":"http:\/\/192.168.0.200\/wptestsite\/wp-content\/uploads\/2018\/12\/DSE_3490.jpg"}],"in_stock":true,"lang":"en","manage_stock":false,"menu_order":0,"meta_data":[{"key":"hwp_product_gtin","value":""}],"name":"English Traslation APEPAZZA SNEAKERS TENNIS  LACES VELLUTO","purchase_note":"","regular_price":"109","reviews_allowed":true,"short_description":"English Short Descr","sku":"000042_en","slug":"APEPAZZA SNEAKERS TENNIS  LACES VELLUTO","sold_individually":false,"status":"publish","stock_quantity":0,"tags":[],"tax_class":"standard","tax_status":"taxable","translation_of":"4020","type":"variable","upsell_ids":[],"virtual":false,"weight":"0"}

Any suggestions?
Thanks in advance.

**Comment by JannikWorkAccount** [comment]
I´ve tried around and this worked:

1. Create new Class:
`    public class IProduct : Product
    {
        public string lang { get; set; }
        public string translation_of { get; set; }
    }`

2. Create the Product:
`            IProduct p1 = new IProduct()
            {
                name = ...
                lang = "en",
                translation_of = "82568"
            };`

3. Fire API Call:
`await wc.Product.Add(p1);`

**Comment by gitgiangalbe** [comment]
Solved.
I was not registered yet WPML plugin so i havent seen that was necessary to install also WooCommerce Multilingual. 
At the beginning i hope it was necessary to install WPML Multilingual CMS Only.
Now all works fine.
Thanks.
