### ISSUE TITLE
Product object taking in has the category object

### ISSUE THREAD

**Issue by frodijo** [XiaoFaye/WooCommerce.NET#33]
WooCommerceNET.WooCommerce.Product

```
    /// <summary>
    /// List of categories. See Categories properties.
    /// </summary>
    [DataMember(EmitDefaultValue = false)]
    public CategoryList categories { get; set; }
```

this should be ProductCategoryList

the categorylist works until you need to add something more than the name and slug, the other fields like parent are not required

**Comment by XiaoFaye** [comment]
It seems Category only has the basic information, if you want to do more, you will need to use ProductCategory. In product object, it only returns basic information of category.

What did you want to achieve in here?
