### ISSUE TITLE
How to sort products by properties from the shop?

### ISSUE THREAD

**Issue by bretbas** [XiaoFaye/WooCommerce.NET#330]
@XiaoFaye , Hello. In my shop I can order products by popularity, rated, novelty, prices: desc, and prices: asc:
![2](https://user-images.githubusercontent.com/26548549/48722629-898de600-ec35-11e8-8f4e-f4b0b7425ac2.jpg)
But I can't find these properties in the WooCommerce API. 
Woocommerce API has two properties that are responsible for sorting. Here there are:
![2](https://user-images.githubusercontent.com/26548549/48722779-ea1d2300-ec35-11e8-8af1-dcce11f001a6.jpg)

> date, id, include, title and slug

These properties are not related to the sorting properties on my site.

How can I order my products by properies from my site?

**Comment by XiaoFaye** [comment]
Have you tried using parameters?

**Comment by bretbas** [comment]
@XiaoFaye, Of course. I tried that. Here there are:
```
var parameters = new Dictionary<string, string>();
parameters["page"] = currentPage.ToString();
parameters["orderby"] = "title";
```

But I asked about something else. How can I sort my products by popularity, rated, novelty, prices: desc, and prices?

**Comment by bretbas** [comment]
@XiaoFaye , But the theme is a standard WooCommerce theme and no plug-ins other than WooCommerce installed. 
Where does this type of sorting come from?

**Comment by XiaoFaye** [comment]
@bretbas  Even it's a standard WooCommerce theme, the API won't support all of them. I'm planning to develop a WooCommerce plugins which provides enhance API calls, which are missing in the official API.

**Comment by bretbas** [comment]
@XiaoFaye, So, I can’t create a sorting by the same keys as in the Woocommerce theme? Quickly and efficiently

**Comment by XiaoFaye** [comment]
@bretbas Not as far as I know.
