### ISSUE TITLE
Question: I can use parameters to reduce the amount of info is downloaded from the website?

### ISSUE THREAD

**Issue by Shivansps** [XiaoFaye/WooCommerce.NET#331]
I dont think it can be done, but im trying to optimise to reduce the amount of traffic to the website.

I need to check every 30mins that the products are updated with my own internal DB, but i only need the id, price, stock and sku for that, but when i use GetAll() i do get everything from the items, incluiding the list of images and categories.

There is any way i could avoid this?

**Comment by XiaoFaye** [comment]
You might want to try the legacy V3 api.

![image](https://user-images.githubusercontent.com/6334728/48742026-1bdbcb80-ecc2-11e8-952c-880728903e63.png)

**Comment by Shivansps** [comment]
i cant belive they deprecated that.
OK, it works, so now im using the legacy V3 to read products, then i convert them to v2 products so i can keep using V2 for everything else.

BTW, in legacy V3 "per_page" changes to "filter[limit]", you may want to note that in the intro.

**Comment by XiaoFaye** [comment]
@Shivansps  Thanks for the tips, will update the Intro.
