### ISSUE TITLE
How can I cancel my request?

### ISSUE THREAD

**Issue by bretbas** [XiaoFaye/WooCommerce.NET#332]
@XiaoFaye , Hi. How can I cancel a request like this:
`var settings = await wooObject.Setting.GetAll();`
I don't see anything about `CancEllationToken` and `CancellationTokenSource`.

**Comment by XiaoFaye** [comment]
Seems there are lots need to be updated, I will see what I can do.

**Comment by bretbas** [comment]
So, Is cancel functionality not implemented in Woocommerce .NET?

Sorry for my English. I'm from Russia

**Comment by XiaoFaye** [comment]
@bretbas That's right

**Comment by bretbas** [comment]
@XiaoFaye , I can't cancel not cancelable task. But I can not wait for it to complete, thereby simulating the cancellation. I resolve this with `TaskCompletionSource<T>`. I create a task extensions methods:
`
public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken) 
{ 
	var tcs = new TaskCompletionSource<bool>(); 
	using(cancellationToken.Register(() => tcs.TrySetResult(true))) 
		if (task != await Task.WhenAny(task, tcs.Task)) 
			throw new OperationCanceledException(cancellationToken); 
	return await task; 
}

public static async Task WithCancellation(this Task task, CancellationToken cancellationToken) 
{ 
	var tcs = new TaskCompletionSource<bool>(); 
	using(cancellationToken.Register(() => tcs.TrySetResult(true)))  
		if (task != await Task.WhenAny(task, tcs.Task)) 
			throw new OperationCanceledException(cancellationToken); 
	await task; 
}
`
And when I want to cancel any not cancelable task, I write:
`var settings = await wooObject.Setting.GetAll().WithCancellation(cts.Token);`

**Comment by XiaoFaye** [comment]
@bretbas  That's great! Do you mind to create a pull request so I can merge?

**Comment by XiaoFaye** [comment]
@bretbas Hi, your suggestion has been merged in the latest version 0.7.7, thanks!
