### ISSUE TITLE
How can Get a Product's Attribute?

### ISSUE THREAD

**Issue by Umar3399** [XiaoFaye/WooCommerce.NET#333]
I'm trying to get Product's Attribute, like here I am getting variations of a specific product:

`var variation = await wC.Product.Variations.Get((12,0);

int? x = variation.stock_quantity;`

How I will get that? 
Thank You!

**Comment by PoliSafety** [comment]
You need to first load the product and then use a For Each loop to get its attributes.
Example:
```
Dim prd as Product = Await wc.Product.Get(product_id)
For Each attrb In prd.attributes
     'Read the attributes
Next
```
Hope this helped you out.

**Comment by Umar3399** [comment]
Thank you very much! that really helped. God bless you!
` var product = await wC.Product.Get(product_id);
            ProductAttributeLine list = new ProductAttributeLine();
            foreach( var items in product.attributes)
            {
                list = items;
            }
            var name = list.name;`
