### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path

### ISSUE THREAD

**Issue by hopdl** [XiaoFaye/WooCommerce.NET#335]
WooCommerce.NET version 2

When i run my function:
```
MyRestAPI rest = new MyRestAPI(@"http://myproduct.club/wp-json/wc/v2/", "key", "secret");
WCObject wcObject = new WCObject(rest);

 public async Task<List<Product>> GetAllProduct()
        {
            return await wcObject.Product.GetAll();
        }

```

I tried to use JSON.NET in WooCommerce.NET as in issue https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-JSON.NET-in-WooCommerce.NET 
but the result return is:
"	<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="UTF-8" />
	
	<title>locagroup.club | Just another WordPress site</title>

	
			
						<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
		
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="http://locagroup.club/xmlrpc.php" />
	<link rel="shortcut icon" type="image/x-icon" href="http://locagroup.club/wp-content/themes/bridge/img/favicon.ico">
	<link rel="apple-touch-icon" href="http://locagroup.club/wp-content/themes/bridge/img/favicon.ico"/>
	<script type="application/javascript">var QodeListingAjaxUrl = "http://locagroup.club/wp-admin/admin-ajax.php"</script><link href='//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic|Open+Sans:100,200,300,400,500,600,700,800,900,300italic,400italic|Gentium+Basic:100,200,300,400,500,600,700,800,900,300italic,400italic|Pacifico:100,200,300,400,500,600,700,800,900,300italic,400italic|Raleway:100,200,300,400,500,600,700,800,900,300italic,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<script type="application/javascript">var QodeAjaxUrl = "http://locagroup.club/wp-admin/admin-ajax.php"</script><link rel='dns-prefetch' href='//apis.google.com' />
<link rel='dns-prefetch' href='//maps.googleapis.com' />
<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link rel='dns-prefetch' href='//s.w.org' />..."

![image](https://user-images.githubusercontent.com/35034800/49159009-16335500-f356-11e8-9de6-9af13e91f986.png)

It cannot parse the result to json
Please give me some clues, solutions to fix. Thanks!

**Comment by rtmrodrigues** [comment]
Try to remove JetPack PlugIN...
