### ISSUE TITLE
OrderCouponLine discount and discount_taxes type

### ISSUE THREAD

**Issue by simonemarra** [XiaoFaye/WooCommerce.NET#339]
Wordpress version 4.9.8, WooCommerce version 3.4.6 and WooCommerce.NET version 0.7.5

I'm using the OrderCouponLine class to add some coupons on an order. 
The problem seems to be related to the type of decimal property:
OrderCouponLines discount type is decimal, but my Woocommerce returns errors expecting string values. If I copy the Order content (as Json string) and change such value using a string formatted number ("1234" instead of 1234) the order is correctly accepted.

- Details of the error message if there is any
```json
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): coupon_lines",
    "data": {
        "status": 400,
        "params": {
            "coupon_lines": "coupon_lines[0][discount] is not of type string.."
        }
    }
}
```

I read issue #292 and the problem seems to be similar.

To solve the issue at the moment I avoid to use the WooCommerce.NET libs classes for Order and OrderLineItem, but I'm using some custom classes:

```cs
public class OrderCouponLine_Custom : OrderCouponLine
{
    [DataMember]
    [JsonProperty(PropertyName = "discount")]
    public string discount_string
    {
        [CompilerGenerated]
        get;
        [CompilerGenerated]
        set;
    }

    [DataMember]
    [JsonProperty(PropertyName = "discount_tax")]
    public string discount_tax_string
    {
        [CompilerGenerated]
        get;
        [CompilerGenerated]
        set;
    }
}

public class Order_Custom : Order
{
    [DataMember]
    [JsonProperty(PropertyName = "coupon_lines")]
    public List<OrderCouponLine_Custom> coupon_lines_custom
    {
        [CompilerGenerated]
        get;
        [CompilerGenerated]
        set;
    }
}
```

In this way I can override the default behaviour of JsonConvert.

I'm missing something or the issue is real?

**Comment by XiaoFaye** [comment]
Yes, we do have this issue when working with json strings that returns by WooCommerce RESTful API.
