### ISSUE TITLE
Placeholder Image

### ISSUE THREAD

**Issue by OscarLate** [XiaoFaye/WooCommerce.NET#341]
WooCommerce.Net  7.3

For each product with variations that I upload to the web, upload a blank placeholder image.Then I have in the section MEDIA thousands of blank images.Any trick to solve this?

Regards,

**Comment by XiaoFaye** [comment]
Is the image link from your website? or third-party?

**Comment by OscarLate** [comment]
I write wc.PostProduct(product ) with product.images = null; and then WooCommerce API create this image in my website  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI9c-96JB3gE6ZnLrLWezDlismv6k37wbLF71pFqobSVyvxUhJ for each product uploaded

**Comment by XiaoFaye** [comment]
I think this is a WooCommerce behavior and can't control from the Rest API.

**Comment by OscarLate** [comment]
I think so, but you know about something to remove all images of variants?  When I did variation.image.clear() returned  woocommerce_product_invalid_image_id

**Comment by XiaoFaye** [comment]
After you cleared the images, what was the request json looks like?
