### ISSUE TITLE
How to assign value to Non-variation attributes

### ISSUE THREAD

**Issue by Anooshmoosh** [XiaoFaye/WooCommerce.NET#342]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by Anooshmoosh** [comment]
Hi, I am successfully adding variation attributes to my products.  However, not sure how to add non variations attribute values?  I associate these attributes by creating 
`ProductAttributeLine ProductAttributeLine = new ProductAttributeLine()
                {
                    id = 9, 
                    name = "Manufacturer",
                    options = DALUtils.GetProductManufacturerList(DC).ToList(), 
                    variation = false,
                    visible = true
                };`
But there is no place to associate the "option" value.
I know how to association the value for variation attributes for variations by populating VariationAttribute structure for the variation and specifying the "option" value there but in the case of non-variation attributes  we don't have different value for each variation, hence the specification of  variation = false.
Thank you for your help

**Comment by XiaoFaye** [comment]
Have you checked the WooCommerce RESTful API document?

**Comment by Anooshmoosh** [comment]
Yes, but I was hoping that the .NET API provides the hook for specifying the option value for non variations attributes.  Is that not supported and I need to use the WooCommerce  REST API directly?

**Comment by XiaoFaye** [comment]
@Anooshmoosh It will require some extra work, this API only supports basic api calls.

**Comment by Anooshmoosh** [comment]
Thank you.
