### ISSUE TITLE
WPML - Unable to Save Product in Another Language

### ISSUE THREAD

**Issue by gitgiangalbe** [XiaoFaye/WooCommerce.NET#343]
- Related To "How to use woocommerce multilingual **#329**", closed too soon.

- WordPress v. 5.0.2 with storefront theme 
- WooCommerce v. 3.5.3 
- W.Net v. 0.7.6
- WPML Multilingual CMS v. 4.1.1

![image](https://user-images.githubusercontent.com/29622873/50478142-ee282780-09cf-11e9-9635-29675e864add.png)

I expect two product with own language traslation as show in the first 2 line of db, but i obtain two distinct products withount language correlation.
Why.
below JSON request and Response:

**Italian Language Request:**
{"attributes":[{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true}],"backorders":"no","button_text":"","catalog_visibility":"visible","categories":[{"id":2921,"name":"FALL\/WINTER","slug":"FALL\/WINTER"}],"cross_sell_ids":[],"default_attributes":[],"description":"","dimensions":{},"download_expiry":-1,"download_limit":-1,"downloadable":false,"downloads":[],"external_url":"","featured":true,"grouped_products":[],"images":[],"in_stock":true,"manage_stock":false,"menu_order":0,"meta_data":[{"key":"hwp_product_gtin","value":""}],"name":"ABITO DONNA","purchase_note":"","regular_price":"108","reviews_allowed":true,"short_description":"","sku":"000002","slug":"ABITO DONNA","sold_individually":false,"status":"publish","stock_quantity":0,"tags":[],"tax_class":"standard","tax_status":"taxable","type":"variable","upsell_ids":[],"virtual":false,"weight":"0","lang":"it","translation_of":null}

**Italian Language Response:**
853
{"id":4281,"name":"ABITO DONNA","slug":"abito-donna","permalink":"http:\/\/192.168.0.200\/wptestsite\/prodotto\/abito-donna\/","date_created":"2018-12-27T12:05:15","date_created_gmt":"2018-12-27T11:05:15","date_modified":"2018-12-27T12:05:15","date_modified_gmt":"2018-12-27T11:05:15","type":"variable","status":"publish","featured":true,"catalog_visibility":"visible","description":"","short_description":"","sku":"000002","price":"","regular_price":"","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"price_html":"","on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"in_stock":false,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"0","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":2921,"name":"FALL\/WINTER","slug":"fallwinter-anno-2018"}],"tags":[],"images":[{"id":0,"date_created":"2018-12-27T13:05:15","date_created_gmt":"2018-12-27T11:05:15","date_modified":"2018-12-27T13:05:15","date_modified_gmt":"2018-12-27T11:05:15","src":"http:\/\/192.168.0.200\/wptestsite\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","name":"Segnaposto","alt":"Segnaposto","position":0}],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"meta_data":[{"id":49144,"key":"_wpml_word_count","value":"{\"total\":0,\"to_translate\":{\"en\":4,\"it\":4}}"},{"id":49178,"key":"hwp_product_gtin","value":""}],"_links":{"self":[{"href":"http:\/\/192.168.0.200\/wptestsite\/wp-json\/wc\/v2\/products\/4281"}],"collection":[{"href":"http:\/\/192.168.0.200\/wptestsite\/wp-json\/wc\/v2\/products"}]}}
0

**Request Language English**
{"attributes":[{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":445,"name":"CALZ. DONNA 34-42 CON ½  ","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true},{"id":459,"name":"COLORE","options":[],"position":0,"variation":true,"visible":true}],"backorders":"no","button_text":"","catalog_visibility":"visible","categories":[{"id":2921,"name":"FALL\/WINTER","slug":"FALL\/WINTER"}],"cross_sell_ids":[],"default_attributes":[],"description":"English Descr","dimensions":{},"download_expiry":-1,"download_limit":-1,"downloadable":false,"downloads":[],"external_url":"","featured":true,"grouped_products":[],"images":[],"in_stock":true,"manage_stock":false,"menu_order":0,"meta_data":[{"key":"hwp_product_gtin","value":""}],"name":"English Traslation ABITO DONNA","purchase_note":"","regular_price":"108","reviews_allowed":true,"short_description":"English Short Descr","sku":"000002_en","slug":"ABITO DONNA","sold_individually":false,"status":"publish","stock_quantity":0,"tags":[],"tax_class":"standard","tax_status":"taxable","type":"variable","upsell_ids":[],"virtual":false,"weight":"0","lang":"en","translation_of":"4281"}

**Response Language English:**
893
{"id":4282,"name":"English Traslation ABITO DONNA","slug":"abito-donna-2","permalink":"http:\/\/192.168.0.200\/wptestsite\/prodotto\/abito-donna-2\/","date_created":"2018-12-27T12:05:30","date_created_gmt":"2018-12-27T11:05:30","date_modified":"2018-12-27T12:05:30","date_modified_gmt":"2018-12-27T11:05:30","type":"variable","status":"publish","featured":true,"catalog_visibility":"visible","description":"English Descr","short_description":"English Short Descr","sku":"000002_en","price":"","regular_price":"","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"price_html":"","on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"in_stock":false,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"0","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0","rating_count":0,"related_ids":[4281],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":2921,"name":"FALL\/WINTER","slug":"fallwinter-anno-2018"}],"tags":[],"images":[{"id":0,"date_created":"2018-12-27T13:05:31","date_created_gmt":"2018-12-27T11:05:31","date_modified":"2018-12-27T13:05:31","date_modified_gmt":"2018-12-27T11:05:31","src":"http:\/\/192.168.0.200\/wptestsite\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","name":"Segnaposto","alt":"Segnaposto","position":0}],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"meta_data":[{"id":49179,"key":"_wpml_word_count","value":"{\"total\":0,\"to_translate\":{\"en\":12,\"it\":12}}"},{"id":49213,"key":"hwp_product_gtin","value":""}],"_links":{"self":[{"href":"http:\/\/192.168.0.200\/wptestsite\/wp-json\/wc\/v2\/products\/4282"}],"collection":[{"href":"http:\/\/192.168.0.200\/wptestsite\/wp-json\/wc\/v2\/products"}]}}
0

**Comment by gitgiangalbe** [comment]
In the Above JSON Request (par. "Request Language English") you can see:

![image](https://user-images.githubusercontent.com/29622873/50478713-f7ff5a00-09d2-11e9-9fd4-1afd92c82e05.png)

**Comment by XiaoFaye** [comment]
May be WooCommerce  doesn't accept your request with "translation_of"?

**Comment by ajayak** [comment]
Hi @gitgiangalbe, sorry to bother you here but I see that you are using latest version of WooCommerce i.e. 3.5.3. Are you facing this issue?
https://github.com/XiaoFaye/WooCommerce.NET/issues/344

**Comment by gitgiangalbe** [comment]
Hi @ajayak. I'm still facing this iussue without success ... have you any suggestion for me ?

**Comment by gitgiangalbe** [comment]
> May be WooCommerce doesn't accept your request with "translation_of"?

Hi @XiaoFaye . How can i understand if my WooCommerce does not accept "translation_of"?

**Comment by XiaoFaye** [comment]
@gitgiangalbe I don't think it will support, you will need to check WPML support regarding Restful API: https://wpml.org/forums/topic/rest-api-posts/
