### ISSUE TITLE
woocommerce_rest_authentication_error (Invalid signature - provided signature does not match.)

### ISSUE THREAD

**Issue by ajayak** [XiaoFaye/WooCommerce.NET#344]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
WooCommerce - 3.5.3
WooCommerce.NET Version - 0.7.6-beta and 0.7.5

- Steps to replicate the issue
```cs
var request = new RestAPI(url, consumerKey, consumerSecret, false);
var wc = new WCObject(request);
var r = await wc.Report.GetAll();
```
No effect of adding `false` paramenter in RestApi.

- Details of the error message if there is any

```json
{
    "code": "woocommerce_rest_authentication_error",
    "message": "Invalid signature - provided signature does not match.",
    "data": {
        "status": 401
    }
}
```
![image](https://user-images.githubusercontent.com/5102208/50558646-14bec900-0d16-11e9-9a56-78f9f4841cc8.png)

Additional Details:
Protocol: HTTP
WCObject: v3 (same error with v2 as well)

**Comment by XiaoFaye** [comment]
What is the URL settings in your Wordpress?

**Comment by ajayak** [comment]
@XiaoFaye I created a new instance again with the previous version of WP and got this issue again.

**Url Settings**

WordPress Address (URL): http://ec2-13-233-105-236.ap-south-1.compute.amazonaws.com
Site Address (URL): http://ec2-13-233-105-236.ap-south-1.compute.amazonaws.com

WP: WordPress 4.9.9

**Comment by ajayak** [comment]
Yes @XiaoFaye. The basic Authorization passes with these url. But when I make the API calls as shown in the screenshot above, I get error.

**Comment by ajayak** [comment]
Any possible fix @XiaoFaye ? 😄

**Comment by XiaoFaye** [comment]
@ajayak Try to disable unnecessary plugins and see how it goes.

**Comment by ajayak** [comment]
@XiaoFaye I only have Wordpress and Wordpress paypal plugin installed. Should I share the credentials with you for the testing woocommerce instance?

**Comment by ajayak** [comment]
@XiaoFaye I created a new woocommerce instance:
https://ec2-13-127-91-66.ap-south-1.compute.amazonaws.com

When using Postman, I can make REST API as show in screenshot:
![image](https://user-images.githubusercontent.com/5102208/50902449-ea20ee80-1440-11e9-82f1-6d783152bc77.png)

I get the error mentioned above when using WooCommerce.Net package.

For your testing, here are WP credentials:
u: user
p: RyWn1J445aPr

This is a disposable woocommerce instance 😃

**Comment by XiaoFaye** [comment]
@ajayak I have edited your post and removed some sensitive information. For your issue, can you try to use the authorizedHeader parameter in RestAPI? set it to True and see how it goes.

**Comment by XiaoFaye** [comment]
@ajayak How is this going?

**Comment by ajayak** [comment]
Hi @XiaoFaye, I can't understand the exact cause of the issue. Only happens with apps running on AWS. But it works fine on new AWS instances.

I think you can mark this as closed.
