### ISSUE TITLE
How to Add a new Product with Existing Image In WordPress Without duplicate the same image on the server with another name?

### ISSUE THREAD

**Issue by vadimneta** [XiaoFaye/WooCommerce.NET#345]
Hello,
How to Add a new Product with Existing Image In WordPress Without duplicate the same image on the server with another name?

**This way adding a duplicated images with another name on the server :)**

```
for(int i=0;i<4;i++)
{
       Product simpleProduct = new Product()
                {
                    name = currProd.Title,
                    short_description = currProd.Description,  
                    src = "http://somedomain/uploads/images/image1.jpeg",
                };
              simpleProduct = await wc.Product.Add(simpleProduct);
}

The above code, create 5 new images with different names.
http://somedomain/uploads/images/image1.jpeg
http://somedomain/uploads/images/image1-2.jpeg
http://somedomain/uploads/images/image1-3.jpeg
http://somedomain/uploads/images/image1-4.jpeg

```
Still, I stuck with the same problem
**How to Add a new Product with Existing Image In WordPress Without duplicate the same image on the server with another name?**

Thanks a lot!

**Comment by topherZa** [comment]
@XiaoFaye  Is the only way to get the ids of the image from the wordpress plugin and query media?

**Comment by XiaoFaye** [comment]
@topherZa Yes
