### ISSUE TITLE
Filter Order Customer Wise

### ISSUE THREAD

**Issue by Manthan2611** [XiaoFaye/WooCommerce.NET#346]
Hi,

I am trying to retrieve the order using "customer_id" filter by writing
`var parms = new Dictionary<string, string>() { { "customer_id", "1" } };
            var order = wc.Order.GetAll(parms);`

After executing the same i am getting all customer order list rather than getting for specific order for that customer id. 
Referring to the API document of the Woocommerce customer_id is an int value so i have changed the dictionary param to 
`var parms = new Dictionary<string, int>() { { "customer_id", 1 } };
            var order = wc.Order.GetAll(parms);`
But now i am getting cannot convert exception from Dictionary<string,string> to Dictionary<string,int>.

Is there any way from where i can retrieve order customer wise? 

Using Wordpress version =4.9.9.
Using WooCommerce version = 3.5.3.
Using WooCommerce.NET version =0.7.5.

Thanks & Regards,
Manthan Patel

**Comment by Manthan2611** [comment]
Hi XiaoFaye,

Thanks for your super fast reply. Changing that made the program work, Thank you.

I am been referring he below document where it was showing customer_id
[woocommerce api](https://woocommerce.github.io/woocommerce-rest-api-docs/wp-api-v2.html#order-properties)

Can you please provide me the doc which you have attached as image that will be a great help.

Thanks

**Comment by XiaoFaye** [comment]
@Manthan2611  You need to check the Available parameters section. https://woocommerce.github.io/woocommerce-rest-api-docs/wp-api-v2.html#list-all-orders
