### ISSUE TITLE
Unknow woocommerce restapi version

### ISSUE THREAD

**Issue by yy1015** [XiaoFaye/WooCommerce.NET#347]
Hi XiaoFaye,
I got one exception said
System.Exception: 'Unknow WooCommerce Restful API version.'

  var result = new Result();
             var rest = new RestAPI("http://localhost:8080/WP/wp-json/wc/v3/orders", _appSettings.WooCommerceSettings.Key, _appSettings.WooCommerceSettings.Secret);
             WCObject wc = new WCObject(rest);
            var orderDto = await _orderDetailQuery.ExecuteAsync(new OrderDetailQueryCriteria()
            {
                UserId = request.UserId,
                OrderId = request.OrderId
               
            });

My code is kind of like this
Thanks

**Comment by SeanoNET** [comment]
Hi yy1015,

It looks like you have included the order endpoint when initializing the REST API class. 

Please remove the
>/orders
and try
> http://localhost:8080/WP/wp-json/wc/v3

**Comment by yy1015** [comment]
> Hi yy1015,
> 
> It looks like you have included the order endpoint when initializing the REST API class.
> 
> Please remove the
> 
> > /orders
> 
> and try
> 
> > http://localhost:8080/WP/wp-json/wc/v3

Thanks SeanoNET,
I have tried but still got that exception.

Thanks for your help

**Comment by XiaoFaye** [comment]
try `http://localhost:8080/WP/wp-json/wc/v3/`

**Comment by yy1015** [comment]
> try `http://localhost:8080/WP/wp-json/wc/v3/`

Thanks XiaoFaye,
But still not working. Maybe i need different ways to write this string?

Thanks
