### ISSUE TITLE
ProductCategoryBatch missing?

### ISSUE THREAD

**Issue by richardaubin** [XiaoFaye/WooCommerce.NET#348]
Was just cross referencing the WC api docs and working with your API in VS2017 and noticed there is no ProductCategoryBatch object.

**Comment by XiaoFaye** [comment]
Oh, you are right, it's missing, will be added in the next release.

For now you can easily define it with: 
`public class ProductCategoryBatch : BatchObject<ProductCategory> { }`

**Comment by richardaubin** [comment]
That is what I ended up doing. Thanks!
