### ISSUE TITLE
Unknown WooCommerce API version

### ISSUE THREAD

**Issue by WillyBilly90** [XiaoFaye/WooCommerce.NET#349]
- Wordpress version : 4.9.9
- WooCommerce version: 3.5.0
- WooCommerce.NET version: 0.7.6

- Steps to replicate the issue
I can not use this url: http://www.mywebsite.nl/wp-json/wc/v2/ because that ends on the normal startpage of the shop.

When I use http://www.mywebsite.nl/index.php?rest_route=/wc/v2  then I get the normal json webpage, but WooCommerce.Net says Unknown WooCommerce API version

Does somebody know what I have to change to fix this problem?

**Comment by XiaoFaye** [comment]
If you use rest_route, the request will be handled by Wordpress first, not WooCommerce.

**Comment by WillyBilly90** [comment]
Is there another way to directly access the WooCommerce api then /wp-json/wc/v2/ ?

**Comment by richardaubin** [comment]
Have you tried using the v3 url?

**Comment by WillyBilly90** [comment]
I just tried it, but same result.

**Comment by richardaubin** [comment]
Can you share the entire code block?

**Comment by WillyBilly90** [comment]
This is the entire code block to retreive the products:

public static async Task<List<Product>> GetProductInfoAsync(string SearchTerm) //Search with searchterm
        {
            //Get info for api connection from saved properties
            Website = Application.Current.Properties["website"] as string;
            WooCommerceKey = Application.Current.Properties["consumerkey"] as string;
            WooCommerceSecret = Application.Current.Properties["consumersecret"] as string;
            //create api connector
            RestAPI rest = new RestAPI(Website, WooCommerceKey, WooCommerceSecret);
            WCObject wc = new WCObject(rest);
            //search searchterm in WooCommerce and create a list of products with the found products
            List<Product> products = await wc.Product.GetAll(new Dictionary<string, string>() { { "name", SearchTerm } });
            return products;
        }

**Comment by richardaubin** [comment]
"name" is not a recognized parameter.
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by richardaubin** [comment]
Try...
List products = await wc.Product.GetAll(new Dictionary<string, string>() { { "**search**", SearchTerm } });

**Comment by WillyBilly90** [comment]
That does not work too.

**Comment by richardaubin** [comment]
Are you able to retrieve a product by it's id.... using wc.Product.Get(); ?

**Comment by WillyBilly90** [comment]
No, it gives the same error

**Comment by XiaoFaye** [comment]
The problem is that Woocommerce doesn't accept rest_route

**Comment by WillyBilly90** [comment]
I do not use the rest_route , I changed the permalink settings and I use /wp-json/wc/v3/ but that give the probleem with: Value cannot be null. Parameter name: src

**Comment by XiaoFaye** [comment]
@WillyBilly90 I see, the problem is in the returned json string, which can't be deserilized. Please use jsonDeserializeFilter to get the json string and check the src property.

**Comment by WillyBilly90** [comment]
Finally found it, the answer from WooCommerce API was a 403 error instead of a json string.
Why the error was: _Value cannot be null. Parameter name: src,_ I really don't know.

**Comment by XiaoFaye** [comment]
@WillyBilly90 it tried to desalinize the error string to product object, which sure will fail.

**Comment by XiaoFaye** [comment]
@WillyBilly90 The latest version 0.7.9 has a Debug flag, set it to true will give you more details on the exception.
