### ISSUE TITLE
Delete Response Message is JSON string.

### ISSUE THREAD

**Issue by richardaubin** [XiaoFaye/WooCommerce.NET#350]
Wordpress version: 5.03
WooCommerce version: 3.5.4
WooCommerce.NET version: 0.76beta

I'm unit testing a bunch of functions and noticed this...

...var result = await wc.Product.Delete((int)(product.id)); // always casting int??

produces a JSON string response, Maybe create a response object of some type?

**Comment by XiaoFaye** [comment]
Sure, I will change it to a corresponding object in the next version.

**Comment by XiaoFaye** [comment]
@richardaubin  Hi, the Delete function will return a corresponding object in the latest version 0.7.7, thanks!
