### ISSUE TITLE
The bare minimums to create a product variation...

### ISSUE THREAD

**Issue by richardaubin** [XiaoFaye/WooCommerce.NET#351]
For anyone who might be interested, here's the code I wrote to create a product variation from scratch... Hopefully someone finds it useful.
`
            // Woo.Commerce = static WCobject

            var Attributes = Woo.Commerce.Attribute; 
            var Products = Woo.Commerce.Product;
            var Variations = Products.Variations;

            var attribute =
                await Attributes.Add(
                    new ProductAttribute()
                    {
                        name = "ProductAttribute"
                    });

            var product = 
                await Products.Add(
                    new Product()
                    {
                        type = "variable",

                        attributes = new List<ProductAttributeLine>()
                        {
                            new ProductAttributeLine()
                            {
                                id = attribute.id,
                                variation = true,

                                options = new List<string>()
                                {
                                    { "Term" }
                                }
                            }
                        }
                    });

            var variation =
                new Variation()
                {
                    attributes = new List<VariationAttribute>()
                    {
                        {
                            new VariationAttribute()
                            {
                                id = attribute.id,
                                option = "Term"
                            }
                        }
                    }
                };

            await Variations.Add(variation, (int)product.id);
`

**Comment by gmorken** [comment]
great!
