### ISSUE TITLE
Search product with part of name

### ISSUE THREAD

**Issue by WillyBilly90** [XiaoFaye/WooCommerce.NET#352]
If I use this:  _List<Product> products = await wc.Product.GetAll(new Dictionary<string, string>() { { "name", SearchTerm } })_; the product is not found.
If SearchTerm is _canon_ I would like to retrieve all products with _canon, Canon, CANON_ in their name.
Is that possible ?

**Comment by richardaubin** [comment]
If I'm right, "name" is not a recognized parameter.
Check the woocommerce api documentation.

**Comment by WillyBilly90** [comment]
I checked the documentation and it seems that you can only search with "id" and "sku".
Isn't that weird, that you can not search by name or title?

**Comment by richardaubin** [comment]
That is incorrect.

Look at the api documentation here.  Create your dictionary<string, string> with the parameters found here: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

On 2019-02-19 2:17:42 AM, WillyBilly <notifications@github.com> wrote:

I checked the documentation and it seems that you can only search with "id" and "sku".
Isn't that weird, that you can not search by name or title?

**Comment by richardaubin** [comment]
new Dictionary<string, string>() { { "search", "text to search" } };

**Comment by WillyBilly90** [comment]
That works, thanks for that. The API-documentation is not really clear to me.

**Comment by richardaubin** [comment]
It was unclear to me as well. I decided to take a couple of hours to look at the entire api documentation with the examples given for other languages.  Then I compare the WooCommerc.NET classes in a test project.

I strive to "touch" everything when I get my hands on something like this library.

Enjoy!  By the way what are you working on?  I'm creating an application to interface data from a niche market-desktop catalog app that has 10s of thousands of products wilth multiple categories, multiple attributes, multiple interlinked cross-sells, and multiple variations. The website when done will give users a Touch Screen product filtering system (highly configurable 3rd party plugin).

This is my first serious application and I'm teaching myself C# programming at the same time.

On 2019-02-19 4:05:01 PM, WillyBilly <notifications@github.com> wrote:

That works, thanks for that. The API-documentation is not really clear to me.

**Comment by WillyBilly90** [comment]
richardaubin, I'm working on an app with Xamarin.Forms, scan a barcode of a product with camera or search it by typing a search term. Then select the product and quickly change the stock quantity or price.
