### ISSUE TITLE
How can I change order status in V3

### ISSUE THREAD

**Issue by thomaseb1** [XiaoFaye/WooCommerce.NET#356]
Hi,

how can I update the order status in woocommerce.net.

orders,getall() works but I'm not able to update the status.

Pleas can give me anyone a Code example.

I tried this code:

  public async Task<List<Order>> GetOrders()
        {
                RestAPI rest = new RestAPI(Url, Key, Secret);
                WCObject wc = new WCObject(rest);
                List<Order> orders = await wc.Order.GetAll();
                return orders;  
        }

        public async Task UpdateOrders(int id, Order item )
        {
          
            RestAPI rest = new RestAPI(Url, Key, Secret);
            WCObject wc = new WCObject(rest);
            await wc.Order.Update(id, item);

        }

Best regards.

**Comment by XiaoFaye** [comment]
@thomaseb1  If you have updated to the latest version 0.7.7, please try below code:

`await wc.Order.UpdateWithNull(128, new { status = "pending" });`
