### ISSUE TITLE
Using version 7.3 issue with adding product variations

### ISSUE THREAD

**Issue by StasenOnline** [XiaoFaye/WooCommerce.NET#359]
I am using the latest wordpress, woocommerce version, and when I am trying to add product Using  variations it didn't ad the regular price and sale price as well. ! 

I am using Woocommerce.NetX version 7.3 with Visual Studio 2015 .. C# 

is there any solution for that?>

**Comment by StasenOnline** [comment]
Woocommerce.NET version 0.7.3 With visual Studio 2015 C#

**Comment by XiaoFaye** [comment]
@StasenOnline Have you tried version 0.7.5?

**Comment by StasenOnline** [comment]
@XiaoFaye
 
When I try to install version 0.7.5 , it gives me this message: 
" Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'WooCommerceNET 0.7.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
"

Can you help me fix this issue ! 

Thanks !

**Comment by StasenOnline** [comment]
@XiaoFaye  
Just updated to 0.7.5 and still not adding the Variation price!  would you let me know what I should do !
