### ISSUE TITLE
Price property lacks decimal separator

### ISSUE THREAD

**Issue by dandersson79** [XiaoFaye/WooCommerce.NET#36]
When fetching a WooCommerce product over the API, the price property (as well as the regular_price and sale_price) misses a decimal separator. It's however not possible for me to just divide by 100 to ge the correct price. For example, the price stored in the db as 5.1 comes out as 51 through the API, similarily 39 comes out as 39. 
In the database, all price values are stored with a point (.), but in the front-end I use a comma (,) as the decimal separator. I haven't had any problems with this in the frontend, nor with storing a price using the API (using UpdateProduct). It's only when fetching products this occurs. 
Specifically, I have this problem when I'm updating product information form an external source. I fetch the product from the API, update something (usually) and then send the whole product back over the API. This then results in the price being changed in the database...
Could the problem be related to my frontend setting of the decimal separator, or is this a general issue?

**Comment by XiaoFaye** [comment]
Hi, could you please have a look at this issue? #24 
As I can remember, the api should always return the decimal numbers in standard format whatever separator you have set for the front-end.
Please let me know if you have more information regarding this issue.

**Comment by dandersson79** [comment]
I have changed the decimal separator in the WooCommerce frontend, but still I receive price values without decimals when fetching products over the API.
I'm not entirely sure how his relates to #24, as I don't understand the error reported there, but like yourself, I was able to change the decimal separator in the frontend without any issue.

**Comment by dandersson79** [comment]
A screenshot of the product properties while debugging
![product_properties](https://cloud.githubusercontent.com/assets/20773344/19597728/9b3c3802-9796-11e6-958d-5d066a547a41.png)

**Comment by XiaoFaye** [comment]
As you can see in the screenshot, there are 2 fields regarding prices, the first one is "price", which only has the number without any separator; the second one is "price_html", which has the price with separator.

As far as I know, field "price", "regular_price" and "sale_price" will always return the un-formatted price, which will not have the separator and will never affect by the separator settings.

**Comment by dandersson79** [comment]
Yes, I noticed that too. My problem is that for the price properties (without parsing the price_html), there's no way of knowing if the actual price is 0.51€, 5.10€ or 51.00€.
I've built a workaround in the meanwhile, but I just wanted to flag this and find out if it's intentional or indeed a bug

**Comment by XiaoFaye** [comment]
In the adding product page, if you put a price 12 dollar as below:
![image](https://cloud.githubusercontent.com/assets/6334728/19678668/2f6fa40c-9afb-11e6-9c67-df1ceb8e14ef.png)

You will get the price as "12" in the return json string. you will not get "12.00".

So in your screenshot, your price 51 means 51 dollar, I guess you had put "51" in the product page, instead of "51.00", that's why you can't see the separator. This is a WooCommerce REST API behavior.

**Comment by dandersson79** [comment]
No, the price according to both the WooCommerce frontend and the database in this case is actually "5.1"
But like I said, perhaps this is an issue with the WC API as such, and not in the .Net part

**Comment by dandersson79** [comment]
I did some further testing and I believe the problems are due to local settings in my Visual Studio. When the .Net-wrapper tries to parse the string received from the API to a Decimal, it cannot parse the delimiter '.' (dot) as it expects a comma (as per my local settings). I'm not to sure how to change this somewhere in VS, but also I'm not sure if I should, as a comma is the correct delimiter for my applications.
In any case I'm closing the issue now as I believe it's due to local settings and has nothing to do with WooCommerce.Net as such.
Thanks for your help!

**Comment by XiaoFaye** [comment]
Thanks for the information, now I have a full picture in my head:
1. The WooCommerce REST API will return decimal number with the default delimiter '.' (dot) regardless your woocommerce setting and local settings.
2. When C# parsing a decimal number, it always respect the local setting.

This should be the reason to your issue.

I also found a MSDN page that relate to this: https://msdn.microsoft.com/en-us/library/system.globalization.numberformatinfo.numberdecimalseparator(v=vs.110).aspx

I will try to add a fix for this.

Thanks again for your information. :)
