### ISSUE TITLE
delegate requestFilter is not working

### ISSUE THREAD

**Issue by gocasals** [XiaoFaye/WooCommerce.NET#360]
In my Wordpress i'm using JWT for security and I'm trying to use this token with the following code:
    //Create delegate function
    Action<HttpWebRequest> webRequestFilter = CreateWebRequest;
    RestAPI rest = new RestAPI(Url,"", "", true, null, null, webRequestFilter, null);

     public void CreateWebRequest(HttpWebRequest httpWebRequest)
        {
            httpWebRequest.Headers["Authorization"] = "Bearer "+ wp.Token;
            httpWebRequest.Method = "Post";
        }

In RestAPI.cs in the class in the line number 141 invoke the "requestFilter" passed as parameter in the constructor, but "httpWebRequest" is not as reference, and any change in into the function is not reflected into SendHttpClientRequest function

**Comment by XiaoFaye** [comment]
Can you try this: `RestAPI rest = new RestAPI(Url,"", "", true, null, null, CreateWebRequest, null);`

**Comment by gocasals** [comment]
yes, i tried but the problem is when call the delegate any change is returned because the parameter is not a ref.
     if (webRequestFilter != null)
                    webRequestFilter.Invoke(httpWebRequest);

**Comment by XiaoFaye** [comment]
Below is what I did and I get the changes:
![image](https://user-images.githubusercontent.com/6334728/54874364-c91c4700-4e4e-11e9-9952-2956a71e8210.png)

![image](https://user-images.githubusercontent.com/6334728/54874369-e4875200-4e4e-11e9-98b1-a1e4fb25da67.png)

**Comment by gocasals** [comment]
thanks for you help, finally work. we close this issue.
