### ISSUE TITLE
500 (Internal Server)

### ISSUE THREAD

**Issue by haseebmukhtar** [XiaoFaye/WooCommerce.NET#363]
Hi
Probably this is not WooCommerce.NET issue, but may be some one can help me. 

On all the post methods (adding product, adding tags, etc) I am getting 500 error (exception message : The remote server returned an error: (500) Internal Server Error.) and exception response is godaddy default 500 error page html code, but the task is successfully executed on server.

I mean if I am adding a new product from code its giving error but actually product is posted on website.
Tried deactivating all plugins but still same issue.

All get methods is working all good.

WooCommerce version 3.5.6 
WordPress 5.0.3
WooCommerce.NET version 0.7.4.0

Thanks

**Comment by XiaoFaye** [comment]
It's always good to check your web server logs.

**Comment by haseebmukhtar** [comment]
Thanks XiaoFaye, yes got the issue.

Actually hosted on godaddy and the php version is 5.6 (can not upgrade) and there is a php 5.6 bug which gives warning;

"PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0"

Because of the warning, all the post methods throw exception in WooCommerce.Net and wp-api

php bug: https://bugs.php.net/bug.php?id=66763

It took me a while to get the exact error because when I set wordpress to debug true, start getting so many deprecated errors (theme using old methods).

Thanks

**Comment by haseebmukhtar** [comment]
was php version issue
