### ISSUE TITLE
Auth SignIn error

### ISSUE THREAD

**Issue by zhaozhao2018** [XiaoFaye/WooCommerce.NET#364]
WooCommerce.NET: 0.730, vs2017, .netframework 4.5.1
I build a auth signin url, below this:
`http://myshopname.ca/wc-auth/v1/authorize?app_name=myshop&scope=read&user_id=123&return_url=http://localhost:66666/Home/AuthResult&callback_url=https://localhost:66666/Home/AuthResult`
When I click "Approve" button, it show the error: 
`Error: A valid URL was not provided..`
The return url and callback url direct to the get key and SecretKey method. 
Is the URL correct? Thanks.

**Comment by haseebmukhtar** [comment]
Hi

Return URL should be valid URL, may be return url and callback can not be same,  try your website address for return url;

Return url is just to show a specific page after user click "Approve"
The auth details send to Callback URL (which should be https)

**Comment by zhaozhao2018** [comment]
> Hi
> 
> Return URL should be valid URL, may be return url and callback can not be same, try your website address for return url;
> 
> Return url is just to show a specific page after user click "Approve"
> The auth details send to Callback URL (which should be https)

Hi haseebmukhtar,
Thanks. I found it can't use the local url. It need use the valid url. Such as:
`http://myshopname.ca/wc-auth/v1/authorize?app_name=myshop&scope=read&user_id=123&return_url=http://appname/Home/AuthResult&callback_url=https://appname/Home/AuthResult`
But this will make it impossible for me to debug. And how can I get the key and SecretKey?

**Comment by XiaoFaye** [comment]
@zhaozhao2018 try to use JWT in the latest version, which is much easier.
