### ISSUE TITLE
regular_price is not of type string in v3

### ISSUE THREAD

**Issue by haseebmukhtar** [XiaoFaye/WooCommerce.NET#366]
Hi

I am getting error "regular_price is not of type string" when adding product, i know this issue was solved for v2 but seems now its still a problem in v3.

Any suggestions.

**Comment by XiaoFaye** [comment]
Hi, have you tried the latest version 0.7.7?

**Comment by haseebmukhtar** [comment]
let me try, thanks
was using 0.7.4

**Comment by haseebmukhtar** [comment]
Thanks, its fine in 0.7.7

separate issue in 0.7.7, I was getting error on signing, missing public key file sn.key.snk, on project properties I have unchecked "sign the assembly" and all good now.
