### ISSUE TITLE
Problem adding cross_sell_ids

### ISSUE THREAD

**Issue by piotrgulbis** [XiaoFaye/WooCommerce.NET#367]
I know this is not a support forum, but I am not sure where to add this... it might be a problem with WooCommerce.NET.

I am trying to add a List<int> of ids to a product's cross_sells property. I see the ids when debugging but it doesn't seem to get set..

p is of type Product, optionalProducts is of type List<int>

`
p.cross_sell_ids = new List<int>();
p.cross_sell_ids.AddRange(optionalProducts);
`

Am I doing something wrong?

**Comment by XiaoFaye** [comment]
I can't see anything wrong from your code, do you have detail error message?

**Comment by piotrgulbis** [comment]
Nope, no errors. It does doesn't do anything. I check the post_meta table in the wordpress db for the id of the product and the crosssell_id's field is empty.

**Comment by piotrgulbis** [comment]
I tried using Postman by adding cross_sell_ids[0] with a value of 152 for example and it worked, so it must be either my code or yours :)

**Comment by piotrgulbis** [comment]
I found the problem, not sure I understand why it happens...

in your BaseObject.cs you have:
```
public async Task<BatchObject<T>> UpdateRange(int parentId, BatchObject<T> items,   Dictionary<string, string> parms = null)
{
    return API.DeserializeJSon<BatchObject<T>>(await API.PostRestful(APIParentEndpoint + "/" + parentId.ToString() + "/" + APIEndpoint + "/batch", items, parms).ConfigureAwait(false));
}
```

changing this to:
```
public async Task<string> UpdateRange(int parentId, BatchObject<T> items, Dictionary<string, string> parms = null)
{
    return await API.PostRestful(APIParentEndpoint + "/" + parentId.ToString() + "/" + APIEndpoint + "/batch", items, parms).ConfigureAwait(false);
}
```

now the ids get updated...

**Comment by piotrgulbis** [comment]
Switching over to using JSON.net seems to work...

**Comment by XiaoFaye** [comment]
Can you set the SerializeJSon filter and check what's the difference?

**Comment by piotrgulbis** [comment]
> SerializeJSon

Sorry, not sure what you mean...
