### ISSUE TITLE
Attribute terms

### ISSUE THREAD

**Issue by haseebmukhtar** [XiaoFaye/WooCommerce.NET#369]
Hi
I am having a problem, I am getting attribute terms but its only returning 10 (not all). Is there is filter some where or settings to limit to 10?

wc.Attribute.Terms.GetAll(1); // attribute id is 1

returning only 10 terms, not all .

Thanks

**Comment by XiaoFaye** [comment]
By default is always 10, you can use per_page parameter to change the limit.

**Comment by haseebmukhtar** [comment]
Thanks, used per_page param and all good now.
Thanks
