### ISSUE TITLE
Null reference exception while add pic with good

### ISSUE THREAD

**Issue by vromashin** [XiaoFaye/WooCommerce.NET#37]
Hi,
Probably I'm do womething wrong, but when I'll try to add link to picture together with new good, I have the follofing:
![null-ref-woo](https://cloud.githubusercontent.com/assets/6556197/19528989/713336aa-962e-11e6-865e-70c9037c15f1.PNG)

This is issue or I do ot wrong way? Please give a path to fix that. Thanx in advance.

**Comment by XiaoFaye** [comment]
Hi, Could you please add the below line before adding images?

p.images = new ImageList();

Let me know if it works, this seems to be a bug.

**Comment by vromashin** [comment]
Thanks. It's help - this problem disappear.

**Comment by XiaoFaye** [comment]
That's good. I will keep it that way, users should initialize the images object if they want to add a image, and the images object will not be serialized if no images are added.
