### ISSUE TITLE
Attribute Terms Create / Add to Product

### ISSUE THREAD

**Issue by jmead** [XiaoFaye/WooCommerce.NET#370]
Does anyone have the steps to create a product with attributes? 

When I create a product object there are two objects(Attributes and Attirbute Defaults) under the product object. I defined both for the product but get duplicate terms under each attribute.

Do you need to provide Attributes and Attribute Defaults or just Attribute Defaults?

**Comment by haseebmukhtar** [comment]
Hi
I am using attributes only and its working all good.

```
 ProductAttributeLine brand = new ProductAttributeLine();
            brand.name = "Brand";
            brand.visible = true;
            brand.options = new List<string>();
            brand.options.Add(cboBrands.Text);

            item.attributes.Add(brand); //item is Product
```

Thanks

**Comment by jmead** [comment]
Ok but how do you set a term from the Options.Add

**Comment by jmead** [comment]
All sorted, thanks man

 List<ProductAttributeLine> productAttributeLines = new List<ProductAttributeLine>();

            List<ProductAttribute> productAttributes = await wc.Attribute.GetAll();


            foreach (TechSpec techSpec in hpProduct.TechSpecs)
            {
                if (!productAttributes.Exists(x => x.name == techSpec.Name))
                {
                    ProductAttribute productAttribute = new ProductAttribute();
                    productAttribute.name = techSpec.Name;
                    productAttribute.type = "select";
                    productAttribute.slug = ToUrlSlug(techSpec.Name);
                    productAttribute = await wc.Attribute.Add(productAttribute);
                }
                
                List<string> productAttributeOption = new List<string>();
                productAttributeOption.Add(techSpec.Value);

                ProductAttributeLine productAttributeLine = new ProductAttributeLine()
                {
                    name = techSpec.Name,
                    options = productAttributeOption,
                    visible = true,
                    variation = false
                };

                try
                { 
                    productAttributeLines.Add(productAttributeLine);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error when adding product attribute line" + ex.Message);
                    Console.ReadKey();
                }

**Comment by jmead** [comment]
The following method 

 ProductAttributeLine brand = new ProductAttributeLine();
            brand.name = "Brand";
            brand.visible = true;
            brand.options = new List<string>();
            brand.options.Add(cboBrands.Text);

            item.attributes.Add(brand); //item is Product

Does not create an Attribute or Attribute Term. Additionally it doesn’t increase the attribute term count.

I have been able to create an Attribute and Attribute Term to match the option string selected however it doesn’t link to the term.

**Comment by jmead** [comment]
Found the following article
https://rudrastyh.com/woocommerce/rest-api-create-product-with-attributes.html
