### ISSUE TITLE
Order Shipping Tracking

### ISSUE THREAD

**Issue by dannifielding** [XiaoFaye/WooCommerce.NET#371]
I'm not sure if this is the right place to post this, I don't think it is but I'm not sure where else to post.

I'd like to be able to add Shipping Tracking to an order. Is this possible through the current version of this library? I've got the most up-to-date NuGet package as well as the latest WooCommerce (it just updated this morning).

Thanks for any help.

**Comment by XiaoFaye** [comment]
Is your shipping tracking coming from a plugin?

**Comment by dannifielding** [comment]
Ah, it appears so. I didn't even think of that!

It's coming from the WooCommerce Advanced Shipment Tracking plugin, which is probably why I couldn't find it in the Orders object!

**Comment by Magnetize** [comment]
> Ah, it appears so. I didn't even think of that!
> 
> It's coming from the WooCommerce Advanced Shipment Tracking plugin, which is probably why I couldn't find it in the Orders object!

If the tracking number is saved as an order meta field, it is possible to update it via Woo.NET, I am using it for exactly that myself. I am not running the current version though and Woo is not 3.5 I think, but still, should be possible. :)

**Comment by XiaoFaye** [comment]
@dannifielding  @Magnetize is right, you can go for this direction.
