### ISSUE TITLE
GetOrders - The value '' cannot be parsed as the type 'Int32'

### ISSUE THREAD

**Issue by zhaozhao2018** [XiaoFaye/WooCommerce.NET#372]
WooCommerceNET 0.7.3, vs2017, MVC, C#
When I calling WCObject.Order.GetAll(parameters), it throw the exception "The value '' cannot be parsed as the type 'Int32'. But I use the:
```
 string trimstr(string json)
        {
            return json.Trim(new char[] { '\uFEFF', '\u200B' });
        }
```
and 
```
RestAPI rest = new RestAPI("https://mystore.com/wp-json/wc/v2/",
                                    WooAccessKey,
                                    WooSecretKey, jsonDeserializeFilter: trimstr);
```
The problem still exists. What have I lost? Thanks.

**Comment by zhaozhao2018** [comment]
Does anybody know？？？

**Comment by XiaoFaye** [comment]
can you upload the detail json string so I can check? Please remove sensitive information.

**Comment by zhaozhao2018** [comment]
> can you upload the detail json string so I can check? Please remove sensitive information.

I use the other method. I modify the value "tax_class". Before is "", changed to "0", and the value"taxes" is too. 
By the way, Why I only download 10 records each one time, instead of downloading records based on start and end date? Thanks.

**Comment by haseebmukhtar** [comment]
Hi
Check the PHP version on server.
Default data size is 10 items, you can manually define if you requires more than 10

**Comment by zhaozhao2018** [comment]
> Hi
> Check the PHP version on server.
> Default data size is 10 items, you can manually define if you requires more than 10

Hi,
I can't find the php version on server. Would you like tell me how to define the number of items? Thanks.
