### ISSUE TITLE
CustomerId type on Order is too small

### ISSUE THREAD

**Issue by lxalln** [XiaoFaye/WooCommerce.NET#373]
WooCommerce can return Orders with a `customer_id` that is larger than an Int32.
This causes a crash `JsonReaderException: JSON integer 100000000089 is too large or small for an Int32. Path 'customer_id'…`

Example: 
```json
{
    "customer_id": 100000000089,
}
```
_note: extra data left out for brevity_

**Comment by XiaoFaye** [comment]
Hi, the customer_id is defined as integer in WooCommerce as well, do you know why it can become a value like 100000000089? In your case, it's more like a string to me.

![image](https://user-images.githubusercontent.com/6334728/56856289-8862a100-69ab-11e9-82c9-f5a99fac794e.png)

**Comment by lxalln** [comment]
I agree that it looks like a string, but it has been returned as a number in the JSON. Not as a string.

We provide a platform where people connect to their WooCommerce instances, so this is not an instance that we control.

Unfortunately the [`integer` definition](https://www.php.net/manual/en/language.types.integer.php#language.types.integer.overflow) in PHP can mean `long` on a 64-bit system. So I still believe the library should be using `long` instead of `int` wherever WooCommerce specifies an `integer`.

**Comment by XiaoFaye** [comment]
I can see the ID is defined as 64 bit integer in wordpress database as well, I will update this in the next release.

**Comment by XiaoFaye** [comment]
@lxalln Hi, this has been fixed in version 0.7.8
