### ISSUE TITLE
Final element 'display' from the namespace ''. Found item 'item' from the namespace ''.

### ISSUE THREAD

**Issue by LBoschi87** [XiaoFaye/WooCommerce.NET#374]
Good Evening,

I'm working with Visual Studio 2017, VB.Net

Wordpress version: 5.1.1, 
WooCommerce version: 3.6.1
WooCommerce.NET version: 0.7.7

for some days I have been having problems with the product categories. probably due to some wordpress or woocommerce updates.
when I try to read the product categories it gives me the following error:

ex.Message:
---------------------
"Error during deserialization of the object of type System.Collections.Generic.List`1 [[WooCommerceNET.WooCommerce.v3.ProductCategory, WooCommerce.NET, Version = 0.7.7.0, Culture = neutral, PublicKeyToken = ff41d0b6c937438d]]. final element 'display' from the namespace ''. Found item 'item' from the namespace ''. "

ex.StackTrace:
--------------------------
   in System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions (XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   in System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject (XmlDictionaryReader reader)
   in System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject (Stream stream)
   in WooCommerceNET.RestAPI.DeserializeJSon [T] (String jsonString)
   in WooCommerceNET.Base.WCItem`1. <GetAll> d__11.MoveNext ()
--- End stack trace from previous location where the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult ()
   in SyncWC_GGW.frmImportaSuWC.VB $ StateMachine_185_ControlCategoryArticleAsync.MoveNext () in C: Sorg_VBNET_2017 SyncWC_GGW frmImportaSuWC.vb: row 555

Function performed:
--------------------------------
myCategoryAllCateg = Await wc.Category.GetAll (New Dictionary (Of String, String) () From {
                {"per_page", "45"}
            })

I never had this problem before, this command has always worked.

I noticed that if I try to create a new category, it always gives me the same message (Error during the deserialization of the object of type WooCommerceNET.WooCommerce.v3.ProductCategory. Expected final element 'display' from the namespace ''. Found element 'item' from the namespace ''.) but then it is created correctly.

What could it depend on?

Thanks in advance

I apologize for any errors, my English is not perfect

Luca

**Comment by Progytech** [comment]
Hi Luca,
Your English is very good, so nothing to worry.
I am new to WordPress and the library, but I noticed that you said, you are working with VB.NET and the sample code you posted is in C#, can you post the exact code you are using?

I am also using VB.NET and here is a sample of the code I am using to read all categories from WC and synch them with my own data.

```
               Using tempbizItemsCategories As New bizItemsCategories
                    tempbizItemsCategories.FillAllRecords()

                    While nextPageNumber > 0
                        Dim allProductsList As List(Of ProductCategory) = Await wc.Category.GetAll(New Dictionary(Of String, String)() From {
                                                                                          {"page", nextPageNumber.ToString},
                                                                                          {"per_page", "100"}})

                        If allProductsList IsNot Nothing AndAlso allProductsList.Count > 0 Then

                            For Each webItem As ProductCategory In allProductsList
                                With webItem
                                    If Not String.IsNullOrEmpty(.id) Then
                                        If tempbizItemsCategories.Seek($"{NameOf(tempbizItemsCategories.CategoryWebID)}={ .id}") Then
                                            If tempbizItemsCategories.CategoryWebID <> .id Then
                                                tempbizItemsCategories.CategoryWebID = .id
                                            End If
                                        End If
                                    End If
                                End With
                            Next webItem

                            nextPageNumber += 1
                        Else
                            nextPageNumber = -1
                        End If
                    End While

                    If tempbizItemsCategories.IsDirty Then
                        tempbizItemsCategories.Save()
                    End If

                End Using ' tempbizItemsCategories
```
Hope this help.

**Comment by LBoschi87** [comment]
Hi @Progytech ,

Thanks for your answer.
i'm doing similar operations, but every time when i try to call the function "Await wc.Category.GetAll" the function fail and go into the catch exception with the message:
"Final element 'display' from the namespace ''. Found item 'item' from the namespace ''."
i don't know why, it worked fine since 2 weeks ago.

`
     Dim myCategoryAllCateg As New List(Of ProductCategory)

    Async Function ControlloCategoriaArticoloAsync() As Task(Of Integer)

        'i parametri sono case sensitive

        Dim bEsito As Integer = 0
        Dim sAppSuffissoSlug As String = ""

        Try

            Dim url As String = ConfigurationManager.AppSettings("url")
            Dim key As String = ConfigurationManager.AppSettings("key")
            Dim secret As String = ConfigurationManager.AppSettings("secret")

            Dim myRestAPI = New RestAPI(url, key, secret, False)
            Dim wc As WCObject = New WCObject(myRestAPI)

            Dim myCategoryGenere As New List(Of ProductCategory)
            Dim myCategoryLnGenere As New ProductCategoryLine

            Dim myCategoryRepartoGGW As New List(Of ProductCategory)
            Dim myCategoryLnRepartoGGW As New ProductCategoryLine

            Dim myCategoryFornitore As New List(Of ProductCategory)
            Dim myCategoryLnFornitore As New ProductCategoryLine

            'la gerarchia della categoria è
            'Genere -> RepartoGGW -> Fornitore

            Dim sSlugGenere As String = strDatiArticoloLocale.Genere.ToLower.Replace(" ", "-")
            Dim sSlugRepartoGGW As String = strDatiArticoloLocale.RepartoGGW.ToLower.Replace(" ", "-")
            Dim sSlugFornitore As String = strDatiArticoloLocale.Fornitore.ToLower.Replace(" ", "-")

            'solo per test poi è da cancellare
            '----------------------------------
            myCategoryAllCateg = Await wc.Category.GetAll(New Dictionary(Of String, String)() From {
                {"per_page", "45"}
            })
            '----------------------------------


            sAppSuffissoSlug = "-" & strDatiArticoloLocale.Genere.ToLower

            '-------------------------------------------------------------------------------------------------------
            'controllo se esiste su WooCommerce la Categoria Genere
            '-------------------------------------------------------------------------------------------------------
            If strDatiArticoloLocale.Genere.Trim.Length > 0 Then

                myCategoryGenere = Await wc.Category.GetAll(New Dictionary(Of String, String)() From {
                    {"slug", sSlugGenere}
               })

                If myCategoryGenere.Count = 0 Then

                    Dim c As ProductCategory = New ProductCategory With {
                    .name = strDatiArticoloLocale.Genere,
                    .slug = sSlugGenere
                    }
                    Dim r1 As ProductCategory = Await wc.Category.Add(c)
                    myCategoryLnGenere.id = r1.id
                    strDatiArticoloWC.category = myCategoryLnGenere

                Else

                    myCategoryLnGenere.id = myCategoryGenere(0).id
                    'myCategoryLnGenere.name = myCategoryGenere(0).name
                    'myCategoryLnGenere.slug = myCategoryGenere(0).slug
                    strDatiArticoloWC.category = myCategoryLnGenere

                End If

            End If

            '-------------------------------------------------------------------------------------------------------
            'controllo se esiste su WooCommerce la Categoria RepartoGGW
            '-------------------------------------------------------------------------------------------------------
            If strDatiArticoloLocale.RepartoGGW.Trim.Length > 0 Then

                myCategoryRepartoGGW = Await wc.Category.GetAll(New Dictionary(Of String, String)() From {
                    {"slug", sSlugRepartoGGW & sAppSuffissoSlug},
                    {"parent", CStr(myCategoryGenere(0).id)}
                })
                '{"parent", CStr(If(sSlugGenere.Trim = "", "0", CStr(strDatiArticoloWC.category.id)))}

                If myCategoryRepartoGGW.Count = 0 Then

                    Dim c As ProductCategory = New ProductCategory With {
                    .name = strDatiArticoloLocale.RepartoGGW,
                    .slug = sSlugRepartoGGW & sAppSuffissoSlug,
                    .parent = If(myCategoryGenere(0).id > 0, myCategoryGenere(0).id, 0)
                    }
                    '.parent = If(strDatiArticoloLocale.Genere.Trim.Length = 0, 0, myCategoryGenere(0).parent)
                    Dim r1 As ProductCategory = Await wc.Category.Add(c)
                    myCategoryLnRepartoGGW.id = r1.id
                    strDatiArticoloWC.category = myCategoryLnRepartoGGW

                Else

                    myCategoryLnRepartoGGW.id = myCategoryRepartoGGW(0).id
                    strDatiArticoloWC.category = myCategoryLnRepartoGGW

                End If

            End If

            '-------------------------------------------------------------------------------------------------------
            'controllo se esiste su WooCommerce la Categoria Fornitore
            '-------------------------------------------------------------------------------------------------------
            If strDatiArticoloLocale.Fornitore.Trim.Length > 0 Then

                myCategoryFornitore = Await wc.Category.GetAll(New Dictionary(Of String, String)() From {
                    {"slug", sSlugFornitore & sAppSuffissoSlug},
                    {"parent", CStr(myCategoryRepartoGGW(0).id)}
                })
                '{"parent", CStr(If(sSlugRepartoGGW.Trim = "", "0", CStr(strDatiArticoloWC.category.id)))}

                If myCategoryFornitore.Count = 0 Then

                    Dim c As ProductCategory = New ProductCategory With {
                    .name = strDatiArticoloLocale.Fornitore,
                    .slug = sSlugFornitore & sAppSuffissoSlug,
                    .parent = If(strDatiArticoloLocale.Fornitore.Trim.Length = 0, 0, myCategoryRepartoGGW(0).id)
                    }
                    Dim r1 As ProductCategory = Await wc.Category.Add(c)
                    myCategoryLnFornitore.id = r1.id
                    strDatiArticoloWC.category = myCategoryLnFornitore

                Else

                    myCategoryLnFornitore.id = myCategoryFornitore(0).id
                    strDatiArticoloWC.category = myCategoryLnFornitore

                End If

            End If

            bEsito = 1

            Return bEsito

        Catch ex As Exception
            MessageBox.Show(ex.Message, System.Reflection.MethodInfo.GetCurrentMethod.Name)
            Return -1
        End Try

    End Function
`

**Comment by Progytech** [comment]
Hi Luca,
Thanks for posting the details of your code.
The only thing that caught my attention is that you are calling the wc.Category.GetAll() with a "per_page" parameter of 45 items, do you have less than 45 categories created in WC?

Also, have you manually look at all your Categories in the website to see if there is anything unusual with their names that may be throwing the errir in the GetAll() call.

Edhy!

**Comment by LBoschi87** [comment]
> Hi Luca,
> Thanks for posting the details of your code.
> The only thing that caught my attention is that you are calling the wc.Category.GetAll() with a "per_page" parameter of 45 items, do you have less than 45 categories created in WC?

I've tried to reduce items to search at 15, but the message are the same (i've 28 product category on woo-commerce)

> Also, have you manually look at all your Categories in the website to see if there is anything unusual with their names that may be throwing the errir in the GetAll() call.

i've looked for it but apparently its all ok
If i use the command:

https://www.gioielleriamichini.it/wp-json/wc/v3/products/categories/?consumer_key=mykey&consumer_secret=mysecret

website answer this:

--------------------------------------------------------------------------------------
[{"id":54,"name":"ANELLO ARGENTO","slug":"anello-argento","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":27,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/54"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":63,"name":"ANELLO ORO","slug":"anello-oro","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":1,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/63"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":58,"name":"ANELLO ORO 9CT","slug":"anello-oro-9ct","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":8,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/58"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":55,"name":"BRACCIALE ARGENTO","slug":"bracciale-argento","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":8,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/55"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":57,"name":"BRACCIALE ORO","slug":"bracciale-oro","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":1,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/57"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":59,"name":"BRACCIALE ORO 9CT","slug":"bracciale-oro-9ct","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":13,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/59"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}},{"id":84,"name":"CALVIN KLEIN","slug":"calvin-klein-uomo","parent":74,"description":"","display":[""],"image":null,"menu_order":0,"count":33,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/84"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}],"up":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/74"}]}},{"id":85,"name":"CALVIN KLEIN","slug":"calvin-klein-donna","parent":83,"description":"","display":[""],"image":{"id":1,"date_created":null,"date_created_gmt":null,"date_modified":null,"date_modified_gmt":null,"src":false,"name":"","alt":false},"menu_order":0,"count":36,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/85"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}],"up":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/83"}]}},{"id":87,"name":"CALVIN KLEIN","slug":"calvin-klein-unisex","parent":86,"description":"","display":[""],"image":null,"menu_order":0,"count":1,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/87"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}],"up":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/86"}]}},{"id":64,"name":"CIONDOLO ARGENTO","slug":"ciondolo-argento","parent":0,"description":"","display":[""],"image":null,"menu_order":0,"count":2,"_links":{"self":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories\/64"}],"collection":[{"href":"https:\/\/www.gioielleriamichini.it\/wp-json\/wc\/v3\/products\/categories"}]}}]
--------------------------------------------------------------------------------------

if i create a new product category i've the same message:

"Errore durante la deserializzazione dell'oggetto di tipo WooCommerceNET.WooCommerce.v3.ProductCategory. Previsto elemento finale 'display' dallo spazio dei nomi ''. Trovato elemento 'item' dallo spazio dei nomi ''."

**Comment by XiaoFaye** [comment]
@LBoschi87 The problem is here: `display":[""]` , please use jsonDeserializeFilter  and replace all `[""]` to `[]`.

**Comment by LBoschi87** [comment]
Thanks for your answer @XiaoFaye ,

i've tried with your example:

`        string trimstr(string json)
        {
            return json.Trim(new char[] { '\uFEFF', '\u200B' });
        }
`

But i can't replace string with this, only one character.

What can i modify to it for solve my problem?

Thanks for the help.

Luca

**Comment by XiaoFaye** [comment]
Shouldn't it be:

Private Function Trimstr(Optional ByVal json As String = "") As String
    Dim sApp As String = "[" & Chr(34) & Chr(34) & "]"
    Return json.Replace(sApp, "​[]")
End Function

**Comment by LBoschi87** [comment]
Hi @XiaoFaye ,

Probably i've written wrong.
My ask was if you can give to me an example for create an jsonDeserializeFilter who can replace all [""] to [].

My test isn't good because the function:

Dim myRestAPI = New **RestAPI**(url, key, secret, False) want as optional parameter jsonDeserializeFilter like Func(Of String, String).

![2019-05-03 09 18 43](https://user-images.githubusercontent.com/46675046/57124093-abfb6200-6d84-11e9-8319-89d8dc0e5e81.jpg)

How can i do one correct filter who can correctly replace all [""] to [] for solve the problem in description?
Final element 'display' from the namespace ''. Found item 'item' from the namespace ''.

Thanks for the help

Luca

**Comment by XiaoFaye** [comment]
The function in my code is Func(Of String, String), have you tried the code as I said?

**Comment by LBoschi87** [comment]
Hi XiaoFaye,

Excuse me if i've don't written to you those days but i went out of city
for work.
i've tried to create an  jsonDeserializeFilter without success.
It's first time for me, i never worked with json and wordpress/woocommerce
using API. its all new for me.
Probably my questions in these things can be banal, i'm sorry for this.
If you could show me a code snippet for create this filter or some example
for quickly solve this issue, I would be very grateful.

Thanks a lot for the help

Luca

Il giorno ven 3 mag 2019 alle ore 13:35 James Yang <notifications@github.com>
ha scritto:

**Comment by LBoschi87** [comment]
"The function in my code is Func(Of String, String), have you tried the
code as I said?"

I can't find it :(

Il giorno ven 3 mag 2019 alle ore 13:35 James Yang <notifications@github.com>
ha scritto:

**Comment by XiaoFaye** [comment]
@LBoschi87 Hi, please see my example code below:

![image](https://user-images.githubusercontent.com/6334728/57614867-66356980-75ce-11e9-8eb6-6a2ced322101.png)

**Comment by LBoschi87** [comment]
Hi XiaoFaye,

Thanks a lot for the help!
It works fine!!

Good Evening
Luca
