### ISSUE TITLE
stock_quantity serialization in v3

### ISSUE THREAD

**Issue by qwertio** [XiaoFaye/WooCommerce.NET#375]
issue #288 fixed serialization for v2, but need to do the same changes for v3.Product and v3.Variation:

change 
private object stock_quantityValue { get; set; }

to protected

**Comment by XiaoFaye** [comment]
Thanks for raising this issue, it will be fixed in the next release.

**Comment by XiaoFaye** [comment]
@qwertio Hi, this has been fixed in version 0.7.8
