### ISSUE TITLE
Lock User/Customer account

### ISSUE THREAD

**Issue by Progytech** [XiaoFaye/WooCommerce.NET#376]
Hi All,
What would it be the best way to lock, block a user/customer account in WordPress that can be done via an API call?
I have looked at several plug-ins but none seems to work via API.
I also read that changing the "Role" to none, would prevent user from log in, but in my tests with WP 5.2 this does not work.
I am looking for a simple way to block a user from my .Net application with an API call.

Any hints, suggestions are welcome.

Thanks!

Edhy Rijo

**Comment by XiaoFaye** [comment]
There is a plugins called Disable User Login, if the data is in wp_usermate table, you should be able to use WC API to make changes.

**Comment by Progytech** [comment]
Hi James,

Thanks I will take a look of this plugin.
