### ISSUE TITLE
Error 401 

### ISSUE THREAD

**Issue by athsk** [XiaoFaye/WooCommerce.NET#377]
Wordpress version: 5.2
Woocommerce version: 3.6.2
Woocommerce.NET version: 0.7.7

I am trying to update batch categories and i get the 401 error, also i get the 401 error when i try to list products. The api key and secret is working in browser and lists the orders like this
https://mysite.com/wp-json/wc/v2/orders?per_page=100&consumer_key=ck_XXXXXXXXXXXXXXXXX&consumer_secret=cs_cXXXXXXXXXXXXXXXXX

I get the results i am expecting but from the code below

ProductCategoryBatch catBatch = new ProductCategoryBatch();
List<ProductCategory> newcats = new List<ProductCategory>();
[The list is populated with categories]
 catB.create = newcats;
 var c = await wc3.Category.UpdateRange(catB);

I get this error
{"code":"woocommerce_rest_cannot_batch","message":"Sorry, you are not allowed to batch manipulate this resource.","data":{"status":401}}

I created a new key and secret and again i get the same error.

**Comment by XiaoFaye** [comment]
If you are sure that you have the right permission, please check this #357

**Comment by athsk** [comment]
hi, i added the RequestFilter option but i still get the same response.

//added this in the restapi constructor
rest = new RestAPI(myEndpoint.GetEndpointUrl(), myEndpoint.ApiKey, myEndpoint.ApiSecret, requestFilter: RequestFilter);

//and this in form1.cs where i have the button that uploads the categories
private void RequestFilter(System.Net.HttpWebRequest request)
{  request.UserAgent = "WooCommerce.NET";   }

**Comment by XiaoFaye** [comment]
Can you try to use other API tools like Postman and see if you get the same error?

**Comment by athsk** [comment]
Hi, it turns out that the account assosiated with the api key was customer and not shop manager. So when this was changed it worked. 
thank you for your reply.

**Comment by athsk** [comment]
Something weird happened, it seems like after the excecution of the code all categories were removed. Does the batch deletes all previeus categories?

**Comment by XiaoFaye** [comment]
No, it shouldn't delete anything, can you reproduce this issue?

**Comment by Progytech** [comment]
Hi James,
 
Yes, I can still reproduce the issue.  Keep getting the same error message when trying to update anything, customer, product, category, etc.
 
Edhy Rijo
Phone: 718-884-8679

**Comment by athsk** [comment]
I had 4 categories Woman [id 64], Man [id 65], Girl [id 66], Boy [id 67] (it is for clothes)
Then i had a list with 3 new ProductCategory and then 

ProductCategoryBatch catBatch = new ProductCategoryBatch();
List newcats = new List();
/*these are loaded dynamically but the result is the same*/
newcats.add({ name='woman subcategory', parent =64, slug='woman_subcategory'});
newcats.add({  name='man subcategory', parent =65, slug='man_subcategory'});
newcats.add({ name='boy subcategory', parent =67, slug='boy_subcategory'});
catB.create = newcats;
var c = await wc3.Category.UpdateRange(catB);

this returned a list with 3 blank categories. And when i looked in the admin panel of wordpress in products-> product categories everything was blank.

then i run again the code creating the 4 initial categories and run again the batch creation and it worked. But still the response i get is a list with 3 blank categories how will I know if the batch completed sucessfully or not?

@Progytech What error did you get?

**Comment by Progytech** [comment]
Sorry athsk, my previous message was posted in this thread by mistake.  I deleted it.

**Comment by XiaoFaye** [comment]
@athsk I have tried your code, not getting the same issue. Can you try this on a blank database?
