### ISSUE TITLE
Can't add variations with attribute

### ISSUE THREAD

**Issue by kokorambo** [XiaoFaye/WooCommerce.NET#378]
Hi Xiao, 
I has tried to add variations with attribute but when I checked it in backend admin, it haven't any attribute I add. All of attribute has active in my site. Can you help me to add variations with attribute. Thanks! Here is my test code.

WCObject wc = new WCObject(rest);
                VariationImage vrIamge = new VariationImage
                {
                    src = "https://ae01.alicdn.com/kf/HLB1TwwxaTjxK1Rjy0Fnq6yBaFXaZ/Free-Fast-Shipping-1-1-Arc-Reactor-DIY-Modle-Led-Light-Mark-Two-Remote-Light-Arc.jpg_640x640.jpg"
                };
                VariationAttribute variationAttribute = new VariationAttribute
                {
                    name = "Color",
                    option = "Black",
                };
                VariationAttribute variationAttribute1 = new VariationAttribute
                {
                    name = "Size",
                    option = "Extra Large",
                };
                var listVariationAttribute = new List<VariationAttribute>();
                listVariationAttribute.Add(variationAttribute);
                listVariationAttribute.Add(variationAttribute1);
                Variation variations = new Variation();
                variations.image = vrIamge;
                variations.regular_price = Convert.ToDecimal(10.29);
                variations.sale_price = Convert.ToDecimal(6.99);
                variations.stock_quantity = 100;
                variations.attributes = listVariationAttribute;
                variations.visible = true;
                variations.sku = "797979";
                var response = await wc.Product.Variations.Add(variations, 1239, null);

**Comment by XiaoFaye** [comment]
Are those attributes already exists?

**Comment by kokorambo** [comment]
> Are those attributes already exists?

Yes, I has config it in backend and used for my site. When I added new variant with exists attributes, it has added new variants with no attributes option like image below. 
[https://imgur.com/IPYr59q](url)

**Comment by Alessandro-4EYES** [comment]
@kokorambo Were you able to solve this issue?
