### ISSUE TITLE
backorders_allowed for new product does not work

### ISSUE THREAD

**Issue by SolvITnow** [XiaoFaye/WooCommerce.NET#379]
Wordpress: 5.1.1
WooCommerce: 3.5.8
WooCommerce.NET version 0.7.5

When i create a product (simple or variations on a variable) and i set the : 'backorders_allowed = true' it does not work. It's always "Do not Allow".

The documentation of the WooCommerce API say it is a readonly field. I was expecting it can be set on creating a product. Can anybody confirm it is not possible to set this setting when creating a product?

Is there an other way to set this setting?

http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**Comment by XiaoFaye** [comment]
Try UpdateWithNull , if this doesn't work either, that means this field is for viewing only.

**Comment by SolvITnow** [comment]
Thank you for the fast reply. But it is not working. I am going to ask WooCommerce why this is not possible.

I would also like to thank you for creating and maintaining the WooCommerce.NET project. It works great.
