### ISSUE TITLE
What is different between ProductAttributeLine and ProductAttribute? 

### ISSUE THREAD

**Issue by kokorambo** [XiaoFaye/WooCommerce.NET#380]
As a title above, I have confused when adding product attribute. What is different between ProductAttributeLine and ProductAttribute?

**Comment by XiaoFaye** [comment]
ProductAttributeLine - https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes-properties

ProductAttribute - https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes

**Comment by kokorambo** [comment]
> ProductAttributeLine - https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes-properties
> 
> ProductAttribute - https://woocommerce.github.io/woocommerce-rest-api-docs/#product-attributes

I have read doc api before implement your lib. But the key of problem is I don't understand the relation of 2 properties when adding to product. Are they two distinc attributes?

**Comment by XiaoFaye** [comment]
ProductAttributeLine is shown as a property of a product, ProductAttribute is the actual product attribute itself.
