### ISSUE TITLE
Retrieving all resources and implementing GetTotalPages method

### ISSUE THREAD

**Issue by SeanoNET** [XiaoFaye/WooCommerce.NET#381]
Hi,

As a follow up to #83, rather than paging a request in a while loop until no more resources are returned - Could we instead implement a GetTotalPages method that will return the total number of pages via the `X-WP-TotalPages` header?

For example:
```vb
Dim productCategories As New List(Of ProductCategory)
Dim totalPages As Integer = wc.GetProductCategoriesCount.Result
For i As Integer = 1 To totalPages
	Dim page As New Dictionary(Of String, String) From {
	  {"page", i.ToString}
  }

	productCategories = wc.GetProductCategories(page).Result

	For Each category As ProductCategory In productCategories
		'...
	Next
Next
```

Thanks

**Comment by SeanoNET** [comment]
After further investigation [webResponseFilters](https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET) may solve this

**Comment by XiaoFaye** [comment]
@SeanoNET  Yes, see here: https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET

**Comment by SeanoNET** [comment]
I have built an extensions method that will allow me to call `GetTotalPages()` on WooCommerce resources, however it's not a very clean solution as i have to initialize a new `RestAPI` and `WCObject` to parse the delegate function for the `responseFilter` (I will need different delegates when calling `GetAll()` when retrieving product pages).

```vb
Module Extensions
    Dim pages As Integer = 1
    Private Sub ResponseFilter(obj As HttpWebResponse)
        pages = If(obj.Headers("X-WP-TotalPages"), 0)
    End Sub

    <Extension()>
    Public Function GetTotalPages(ByVal obj As WCObject.WCProductItem) As Integer
        Dim api As New RestAPI("http://www.yourstore.co.nz/wp-json/wc/v3/", "<WooCommerce Key>", "<WooCommerce Secret", responseFilter:=AddressOf ResponseFilter)
        Dim wc As New WCObject.WCProductItem(api)
        Dim products = wc.GetAll().Result
        Return pages
    End Function

    <Extension()>
    Public Function GetTotalPages(ByVal obj As WCItem(Of ProductCategory)) As Integer
        Dim api As New RestAPI("http://www.yourstore.co.nz/wp-json/wc/v3/", "<WooCommerce Key>", "<WooCommerce Secret", responseFilter:=AddressOf ResponseFilter)
        Dim wc As New WCItem(Of ProductCategory)(api)
        Dim products = wc.GetAll().Result
        Return pages
    End Function

End Module
```

Usage:
`Dim pageCount as Integer = wc.Product.GetTotalPages()`

Possibly adding an optional `responseFilter` on the `GetAll()` method might make this solution a little more cleaner, what do you think?

**Comment by XiaoFaye** [comment]
You don't need to create a new RestAPI object, the existing one will do.
![image](https://user-images.githubusercontent.com/6334728/58315724-2e4be300-7e66-11e9-9678-ca7f05912e8a.png)

**Comment by SeanoNET** [comment]
@XiaoFaye , the existing `RestAPI` (The same one i use to cycle through the pages of products outside of the `Extensions` module) does not have the delegates for `ResponseFilter`. Otherwise the pageCount will increment when making a call to get the product nth page.

I will also need different delegates when calling `GetAll()` when retrieving product pages.

I will keep working on a better solution, thanks again.

**Comment by HammacheAbir** [comment]
Thanks @SeanoNET it works for me! you saved me

**Comment by amirvenus** [comment]
Is it possible to get the Total count in something like await wc.Product.GetAll rather than relying on the ResponseFilter delegate? 

Thanks!
