### ISSUE TITLE
Web request filter is being invoked before content has been added into the the web request stream

### ISSUE THREAD

**Issue by SeanoNET** [XiaoFaye/WooCommerce.NET#383]
Is it possible to move the invocation of the `webRequestFilter.Invoke(httpWebRequest);` to just before the actual request has been made in 

```csharp
                // asynchronously get a response
                WebResponse wr = await httpWebRequest.GetResponseAsync().ConfigureAwait(false);
```

rather than before the content has been added into the request stream?

**Comment by XiaoFaye** [comment]
May I ask what was the reason for this change?

**Comment by SeanoNET** [comment]
By using overrides for `SerializeJson` and request filters i am able to see the request content from the last request - this is needed for audit logging.

if the invocation of `webRequestFilter` is done before serializing the request body this will not be set in `MyRestAPI` derived from `RestAPI`.

I could not find any solution around reading a [HttpWebRequest Request Stream](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.getrequeststream?view=netframework-4.8#System_Net_HttpWebRequest_GetRequestStream) when `CanSeek` is false (can't reset the position after reading the content request before actually making the request inside of WooCommerce.NET.

```vbnet
Public Class MyRestAPI
    Inherits RestAPI

    Private _lastRequest As String
    Public Property LastRequest() As String
        Get
            Return _lastRequest
        End Get
        Private Set(ByVal value As String)
            _lastRequest = value
        End Set
    End Property

    Public Sub New(ByVal url As String,
                   ByVal key As String,
                   ByVal secret As String,
                   ByVal Optional authorizedHeader As Boolean = True,
                   ByVal Optional jsonSerializeFilter As Func(Of String, String) = Nothing,
                   ByVal Optional jsonDeserializeFilter As Func(Of String, String) = Nothing,
                   ByVal Optional requestFilter As Action(Of HttpWebRequest) = Nothing,
                   ByVal Optional responseFilter As Action(Of HttpWebResponse) = Nothing)
        MyBase.New(url, key, secret, authorizedHeader, jsonSerializeFilter, jsonDeserializeFilter, requestFilter, responseFilter)
    End Sub

    Public Overrides Function DeserializeJSon(Of T)(ByVal jsonString As String) As T
        Return MyBase.DeserializeJSon(Of T)(jsonString)
    End Function

    Public Overrides Function SerializeJSon(Of T)(ByVal o As T) As String
        Dim json As String = MyBase.SerializeJSon(Of T)(o)
        LastRequest = json
        Return json
    End Function
End Class
```

```vbnet
 Dim api As New MyRestAPI(...)
 Private Sub RequestFilter(obj As HttpWebRequest)
        'Can't read request stream because it doesnt exist when invoked and because CanSeek is false
        Console.WriteLine(api.LastRequest)
 End Sub
```

**Comment by XiaoFaye** [comment]
Maybe you can set requestBody to null while calling SendHttpClientRequest, and then process the actual requestBody in RequestFilter method. 

This is not a good workaround, I'm thinking of making SendHttpClientRequest a virtual method so it can be overridden.

**Comment by SeanoNET** [comment]
Thanks for the suggestion, this could be a possible work around

**Comment by XiaoFaye** [comment]
@SeanoNET Hi, this has been done in version 0.7.9.
