### ISSUE TITLE
How to add category to product?

### ISSUE THREAD

**Issue by kokorambo** [XiaoFaye/WooCommerce.NET#384]
How can I create new and add category to my product. I have tried add ProductCategoryLine like this:
 _List<ProductCategoryLine> productCategoryLines = new List<ProductCategoryLine>();
                ProductCategoryLine productCategoryLine = new ProductCategoryLine();
                if(productData.ProductCategory != null)
                {
                    productCategoryLine.name = productData.ProductCategory[0].CategoryName;
                    productCategoryLines.Add(productCategoryLine);
                }
                else
                {
                    return null;
                }
                var response = await wc.Product.Update(1234, new Product { categories = productCategoryLines});_

but nothing happen. Can you help me fix this? Thanks a lot!

**Comment by kokorambo** [comment]
Maybe I have already find method to add this. I will try and notify to you if successfull. Thanks!

**Comment by kokorambo** [comment]
Sorry but after all, I couldn't add category to my product. Can you help me to fix this?

**Comment by XiaoFaye** [comment]
Use ProductCategory to create new category first, then assign it to product.

**Comment by kokorambo** [comment]
> Use ProductCategory to create new category first, then assign it to product.

Tks for quick reply. I 've tried create category but in your Product model, it using ProductCategoryLine instead of ProductCategory. So, how to add newly created category to Product model? Using ProductCategory's id for ProductCategoryLine's id? 
One more question, if I add 2 category with the same name, it will return only one unique id? Tks!

**Comment by XiaoFaye** [comment]
ProductCategoryLine only for assigning category, it won't create a new one.

Not sure what happen if you add 2 categories with the same name.

**Comment by vishal-parmar** [comment]
@kokorambo You can't add 2 categories with the same name. if you can try to add maybe Generate error occured

**Comment by franknesse** [comment]
> ProductCategoryLine only for assigning category, it won't create a new one.

I don't understand this reply. Is it possible to supply an example how to link a Product to a ProdutCategory?

**Comment by franknesse** [comment]
@kokorambo Did you manage to get a ProductCategory linked to a Product? If so, how?

**Comment by Progytech** [comment]
Hi all,
You need to first add the ProductCategory, store the ID somewhere and then assign it to the ProductCategoryLine collection.

`Dim wcProductCategory As New ProductCategory() With {.name = categoryRecord.CategoryName}`

**Comment by Progytech** [comment]
Sorry, the code above is not a completed code, just enough to give you an idea on how to add the category.
The Product Categories as well as Product Images records must exist before you can assign them to the product.

**Comment by franknesse** [comment]
Thank @Progytech. In the meantime I managed to get thi sto  work. Below my C# code which more or less confirms yours:

```
MyRestAPI rest = new MyRestAPI("xxxxxxxxxxxxxxxxxxxxxxxxx", consumerKey, consumerSecret);
WCObject wc = new WCObject(rest);

ProductCategory pc = await GetProductCategory(130);   //Loads an existing ProductCategory

Product p = new Product();
p.name = name;			
p.categories = new List<ProductCategoryLine>();
p.categories.Add(new ProductCategoryLine() { id = pc.id, name = pc.name });

await wc.Product.Add(p);
```

**Comment by Progytech** [comment]
Hi Frank, @franknesse 
I am glad you made it work and moving forward!

**Comment by FabPari** [comment]
Hi, dear is there anyone who can help me to understand how to add an existing category to an existing article?
I don't understand what kind of parameter I need to update on the product, I create a category list but how to update the product? Can any one write me an example?
thanks a lo
Fabio
