### ISSUE TITLE
Cannot deserialize the current JSON array when calling wc.Category.GetAll()

### ISSUE THREAD

**Issue by kokorambo** [XiaoFaye/WooCommerce.NET#385]
I have problem when I tried getting list of category like issue #200. I also changed ProductCategory model like this post but it's still not working? Can you check it, please?
This is my error I get: 
"There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.ProductCategory, WooCommerce.NET, Version=0.7.7.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character 'V'."
Sorry about more question in a short time :D. Tks a lot!

**Comment by XiaoFaye** [comment]
After upgrading to version 0.7.9, you can set DEBUG to true to get more details on the return json string.

**Comment by GitHubYou** [comment]
i'm getting error "Encountered unexpected character 'ï'"
setted "Rest.Debug = True" but how can i see "debug" output in vb.net (uwp) or c#

[WooCommerceNET.WooCommerce.v2]
