### ISSUE TITLE
The underlying connection was closed: The connection was closed unexpectedly.

### ISSUE THREAD

**Issue by kokorambo** [XiaoFaye/WooCommerce.NET#387]
Hi, have a good day! I have problem when tried delete product. Here is my code:
                RestAPI rest = new RestAPI(url, clientKey, clientSecret);
                WCObject wc = new WCObject(rest);

                var response = await wc.Product.Delete(wooProductID, true, null);
It's response a exception like issue title above. I also read #206 issue and try this but it's not working. Can you help me to fix this?

**Comment by XiaoFaye** [comment]
Please check your web server logs and see the detail error message.

**Comment by kokorambo** [comment]
> Please check your web server logs and see the detail error message.

Thanks for your quick support. After check my server, my sys admin told me that he have blocked DELETE request. After unblocked, everything is ok :D.
