### ISSUE TITLE
ImageId type on ProductImages is too small

### ISSUE THREAD

**Issue by marekkajta** [XiaoFaye/WooCommerce.NET#388]
Hi, I'm getting an error msg from woocommerce with image_id that is larger than an Int32.  The woocommerce placeholder image id is 6009686620154 and when there is no image the placeholder is used.

{JSON integer 6009686620154 is too large or small for an Int32. Path '[0].id', line 1, position 20.}

Any ideas on how to fix it?

**Comment by XiaoFaye** [comment]
I think this is similar to the issue #373, should be fixed in the next release.

**Comment by marekkajta** [comment]
Fantastic, any idea on an ETA of the next release?

**Comment by XiaoFaye** [comment]
No later than then end of July, as I'm working on some new features as well.

**Comment by XiaoFaye** [comment]
@marekkajta Hi, this has been fixed in version 0.7.8
