### ISSUE TITLE
How to install 0.7.7 in .NET Framework 4.6.1 ? Wich version is compatible ?

### ISSUE THREAD

**Issue by RafalRRR** [XiaoFaye/WooCommerce.NET#389]
I can not install WoocommerceNET in the WPF .Net Framework 4.61 project or in 4.5. Only WoocommerceNET 0.7.3 in the .NET Framework 4.0 and 0.7.4 in the .NET Framework 4.5 works for me.
What version of the .Net Framework is compatible version 0.7.7 ??

-.Net Framework 4.6.1,  Wordpress 5.1, WooCommerce 3.6.3 and WooCommerce.NET 0.7.7

**Comment by XiaoFaye** [comment]
Hi, version 0.7.7 should be working with .NET Framework 4.6.1, see below screenshot. For .NET Framework 4.5, version 0.7.3 is the last support version.

![image](https://user-images.githubusercontent.com/6334728/60628212-83571d80-9e44-11e9-8eb1-aff00769c076.png)

**Comment by Talented-Business** [comment]
![image](https://user-images.githubusercontent.com/2536597/61025362-72ca1880-a3eb-11e9-98c8-ac3c1b1d1e9b.png)
I can't execute the woocommerce package.

**Comment by kudusrl** [comment]
Hello! We've the same problem on our console application project on .NET Framework 4.6.1.
When try to install your package, we have this error:
![image](https://user-images.githubusercontent.com/53183850/61640092-07aafc80-ac9d-11e9-8cee-23c953b32ec4.png)

The project is on the righ version of .NET Framework:
![image](https://user-images.githubusercontent.com/53183850/61640161-214c4400-ac9d-11e9-92ab-0a03db85bcbe.png)

Can you help me please?

Thank you

**Comment by XiaoFaye** [comment]
@kudusrl which version of Visual Studio are you using? BTW: I'm using VS2019.
