### ISSUE TITLE
Mange_stock and price

### ISSUE THREAD

**Issue by drikqlis** [XiaoFaye/WooCommerce.NET#39]
manage_stock property of variation has a type of string and is not working correctly for me. When I changed it in your code to bool it started working.

I can't get regular_price of variation to work - it is not going through, and fiddler is not even showing it in request JSON. Can you check if it is working for you?

**Comment by drikqlis** [comment]
Here is code sample of how I try to add price to a variation:
```
Variation variation = new Variation();
variation.regular_price = 15.55M;
variation.stock_quantity = Convert.ToInt32(wariant["ILOSC"].InnerText);
variation.attributes = val;
variation.manage_stock = true;
vl.Add(variation);

create.Add(new Product()
    {
        categories = cl,
        name = produkt["NAZWA"].InnerText,
        type = "variable",
        sku = zmien(produkt["KOD"].InnerText),
        description = produkt["OPIS"].InnerText,
        variations = vl,
        attributes = al,
     };

pb.create = update;
await wc.UpdateProducts(pb);
```
However it is not going through and it is not shown in JSON response.

**Comment by XiaoFaye** [comment]
does it give you any error message?

**Comment by drikqlis** [comment]
No, it creates a product, with attributes and variation, but without a variation price.

**Comment by XiaoFaye** [comment]
There is a bug in the code, you can change it as blew to make it work:

Line 716 in Product.cs file

Before: `public class Variation`
After: `public class Variation : JsonObject`

**Comment by drikqlis** [comment]
It is working now, thanks for your help!
