### ISSUE TITLE
I can't install on .net 4.7.3190.0

### ISSUE THREAD

**Issue by Talented-Business** [XiaoFaye/WooCommerce.NET#390]
I tried to install your package.
but I couldn't install.
The following message is the error.

Install failed. Rolling back...
Could not install package 'WooCommerceNET 0.7.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references that are compatible with that framework. For more information, contact the package author.

What is wrong?

**Comment by XiaoFaye** [comment]
Hi, please see issue #389

**Comment by Talented-Business** [comment]
I don't understand.
How can I install your package?
![image](https://user-images.githubusercontent.com/2536597/61013720-d1c56880-a3be-11e9-9dee-2bf20a5cad82.png)

**Comment by XiaoFaye** [comment]
Is your project targeting .NET 4.5?

**Comment by Talented-Business** [comment]
no

**Comment by XiaoFaye** [comment]
Can you confirm by checking the Project properties? If you have a solution with multiple projects, please make sure you select the right project to install the package.

![image](https://user-images.githubusercontent.com/6334728/61014434-7f467500-a3db-11e9-99b2-407802f840e7.png)

**Comment by Talented-Business** [comment]
![image](https://user-images.githubusercontent.com/2536597/61014513-bbb9a700-a3c2-11e9-8bc2-0ac51ede401d.png)
My .net version is 4.5
How can I install?

**Comment by XiaoFaye** [comment]
You can change Target framework to .NET 4.6.1 or higher. If you don't want to change this, you can still install WooCommerce.NET version 0.7.3

**Comment by Talented-Business** [comment]
then how can I install 0.7.3 woocommerce.net?

**Comment by XiaoFaye** [comment]
![image](https://user-images.githubusercontent.com/6334728/61014853-95553500-a3dd-11e9-9aed-735de58f8f9b.png)

**Comment by Talented-Business** [comment]
![image](https://user-images.githubusercontent.com/2536597/61015207-7cd92080-a3c5-11e9-99d3-5352d290682d.png)
I installed 4.6.1 .net, 4.7.2 net framework.
But I can't install still

**Comment by XiaoFaye** [comment]
Not sure what is the problem, I have tested on my side and it works.
If you can please zip a minimum project and send it to me so I can test it.

![image](https://user-images.githubusercontent.com/6334728/61015442-be76c500-a3df-11e9-9698-292ce89f695b.png)

**Comment by Talented-Business** [comment]
[woocommerce.zip](https://github.com/XiaoFaye/WooCommerce.NET/files/3379900/woocommerce.zip)

**Comment by XiaoFaye** [comment]
I can install it without making any changes to your project. I have zipped it and uploaded. 
[woocommerce-Updated.zip](https://github.com/XiaoFaye/WooCommerce.NET/files/3379907/woocommerce-Updated.zip)

BTW: I'm using VS2019

![image](https://user-images.githubusercontent.com/6334728/61015677-bcf9cc80-a3e0-11e9-9b5a-32296bbabd44.png)

**Comment by Talented-Business** [comment]
![image](https://user-images.githubusercontent.com/2536597/61025431-ac028880-a3eb-11e9-9d26-75b0597d3b11.png)
I can't execute the project.
Please help me.

**Comment by kudusrl** [comment]
Hello! We've the same problem on our console application project on .NET Framework 4.6.1.
When try to install your package, we have this error:
![image](https://user-images.githubusercontent.com/53183850/61640092-07aafc80-ac9d-11e9-8cee-23c953b32ec4.png)

The project is on the righ version of .NET Framework:
![image](https://user-images.githubusercontent.com/53183850/61640161-214c4400-ac9d-11e9-92ab-0a03db85bcbe.png)

Can you help me please?

Thank you
