### ISSUE TITLE
When I am using delete of Product Category Batch, it generates System.Runtime.Serialization.SerializationException.

### ISSUE THREAD

**Issue by Talented-Business** [XiaoFaye/WooCommerce.NET#394]
Woocommerce.Net version is 0.7.7, wordpress version is 3.6.5

ProductCategoryBatch productCategoryBatch = new ProductCategoryBatch();
List<int> deleteCategories = new List<int>();
List<ProductCategory> updateCategories = new List<ProductCategory>();
deleteCategories.Add(30);
deleteCategories.Add(31);

...(add updateCategories )

productCategoryBatch.update = updateCategories;
productCategoryBatch.delete = deleteCategories;

var result = await wc.Category.UpdateRange(productCategoryBatch);

Then the system shows following error.
Exception thrown: 'System.Runtime.Serialization.SerializationException' in mscorlib.dll
But the code deletes product categories in woocommerce.
What is wrong?

**Comment by XiaoFaye** [comment]
I think this is just a deserilize error with return json. After upgrading to version 0.7.9, you can set DEBUG to true to get more details on the return json string.
