### ISSUE TITLE
Blank product or variant sale_price doesn't get deserialized in Legacy v3

### ISSUE THREAD

**Issue by maxim-skuvault** [XiaoFaye/WooCommerce.NET#395]
WordPress 4.1.26 | WooCommerce 2.4.0 | WooCommerce.NET 0.7.7

- Steps to replicate the issue
Call WooCommerceNET.WooCommerce.Legacy.WCObject.GetProduct or GetProducts for a product that has a blank sale price, either in the product or variation

- Details of the error message if there is any
System.Runtime.Serialization.SerializationException : There was an error deserializing the object of type WooCommerceNET.WooCommerce.Legacy.ProductList. The value '' cannot be parsed as the type 'Int32'.

**Comment by XiaoFaye** [comment]
Hi, the woocommerce legacy api is not supported anymore, please try to use the latest api version.
