### ISSUE TITLE
Unable to send HTML "<select>options</select>" to short description

### ISSUE THREAD

**Issue by Shivansps** [XiaoFaye/WooCommerce.NET#396]
Hi,
ive been able to send HTML code to short description to add images and text using the api, but for some reson when i send a html code containing a select it does not accept it, the update request do pass, but all HTML tags are removed ending in plain text.

Something as simple as this code:
Product p = new Product();
p.short_description="select option  option1 /option  option option 2 /option /select";
wc.Product.Update (ID,p);

edit: i removed the <> from the tags as it was causing problems to post here.
This results in plain text "option 1 option 2" being written. Keep in mind i can write the select code on a product using the GUI and it does work.

**Comment by XiaoFaye** [comment]
Please check this: https://github.com/woocommerce/woocommerce/issues/8090

**Comment by Shivansps** [comment]
And how i do enable html short description? because this is not working for me

                    Product p2 = new Product();
                    p2.short_description = AgregarInformacionAhora12(p);
                    Dictionary<string, string> param = new Dictionary<string, string>();
                    param.Add("enable_html_short_description", "true");
                    wc.Product.Update(p.id.Value,p2, param);

**Comment by XiaoFaye** [comment]
After the product is added, do following to update short description with html:

await wc.Product.UpdateWithNull(product_id, new { short_description = "<h1>abc test</h1>", enable_html_short_description = true });

**Comment by XiaoFaye** [comment]
@Shivansps Hi, this has been done in version 0.7.9.
