### ISSUE TITLE
Load Variation with qty = 0 and hide it from Front End

### ISSUE THREAD

**Issue by gitgiangalbe** [XiaoFaye/WooCommerce.NET#397]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

WordPress 5.2.2 With G5Plus April theme

WooCommerce 3.6.5

WooCommerce.NET 0.7.8

- Steps to replicate the issue

I need to upload Product Variation to WooCommerce with qty  = 0 but i wouldn't see this option in shop. How i can do? Which fields and relative data values have i to set to obtain it ?

- Details of the error message if there is any

I Still see Option Variations with Zero quantity. 
Inventory configurations seems all ok.

**Comment by XiaoFaye** [comment]
Will it show if the qty > 0 ?

**Comment by gitgiangalbe** [comment]
of course.

The products and variants sent to woocommerce have the exact same JSON
[json_non_vis.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/3485236/json_non_vis.txt)
[json_vis.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/3485237/json_vis.txt)

, unfortunately some products show all the options of size and color even if the stock is equal to zero, other products instead show only the available combinations.

what am I doing wrong ? could it be a problem related to the theme?

**Comment by XiaoFaye** [comment]
maybe relate to this https://github.com/woocommerce/woocommerce/issues/15484
