### ISSUE TITLE
JWT auth

### ISSUE THREAD

**Issue by igitur** [XiaoFaye/WooCommerce.NET#399]
## Versions
- Wordpress version 5.2.2
- WooCommerce version 3.7.0 
- WooCommerce.NET version: latest commit from GitHub https://github.com/XiaoFaye/WooCommerce.NET/commit/f892c81e2a0786dced6c6a93c56e6fb9224791b5

## Replication
- Install JWT auth as per https://en-nz.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
- Run code below

```c#
RestAPI rest = new RestAPI("http://www.mydomain.com/wp/wp-json/jwt-auth/v1/token", "", "");
WCObject wc = new WCObject(rest);
```

## Details of the error message if there is any
Exception is thrown:
```
System.Exception: Please use WooCommerce Restful API Version 2 url for this WCObject. e.g.: http://www.yourstore.co.nz/wp-json/wc/v2/
   at WooCommerceNET.WooCommerce.v2.WCObject`15..ctor(RestAPI api) in C:\dev\WooCommerce.NET\WooCommerce\v2\WCObject.cs:line 23
   at WooCommerceNET.WooCommerce.v2.WCObject..ctor(RestAPI api) in C:\dev\WooCommerce.NET\WooCommerce\v2\WCObject.cs:line 178
   at ConsoleApp1.Program.Main(String[] args) in C:\temp\ConsoleApp1\Program.cs:line 29
```

Exception is thrown at https://github.com/XiaoFaye/WooCommerce.NET/blob/master/WooCommerce/v2/WCObject.cs#L21 because `api.Version == APIVersion.WordPressAPIJWT`, not `APIVersion.Version2`.

I see recent changes have been made to https://github.com/XiaoFaye/WooCommerce.NET/blob/master/RestAPI.cs#L81 to set the url and `.Version` for JWT

**Comment by XiaoFaye** [comment]
It should be `WPObject wp = new WPObject(rest);`

`WCObject` is for WooCommerce, `WPObject` is for WordPress

**Comment by igitur** [comment]
Ah, thanks, I misunderstood. 

So how can I access WooCommerce objects using JWT auth?

**Comment by igitur** [comment]
Sorry to say this, but the documentation is really poor. I can't figure out what the prerequisites to do just a normal set up. For example, I also realised that https is required for basic auth. This is a WooCommerce requirement, but I would have expected this to be explicitly listed in this repo's README.

Are the JWT or OAuth plugins a prerequisite or are they an optional alternative way of authenticating?

And many more questions....

Dude, I promise I will [buy you a coffee](https://www.buymeacoffee.com/YU0SqVyrR):coffee: if you set up clear, understandable documentation with a full work client project. Even your code samples on the README page can't compile (you're declare the `p` variable twice).

**Comment by XiaoFaye** [comment]
Hi, sorry if the document got you confused.

- WooCommerce ONLY supports OAuth for now, no plugins needed.
- WooCommerce.NET will use basic auth for WooCommerce API if you pass https URL, this is done automatically.
- JWT and OAuth plugins is for WordPress API authentication ONLY.
- The code samples is for usage demonstration ONLY, it's NOT a demo project.

Thanks for your suggestions, I will try to improve the documents and make it more user-friendly.

**Comment by igitur** [comment]
Thanks. I eventually succeeded with https + basic auth. Once I get everything working, I'll make a pull request to improve the documentation.
