### ISSUE TITLE
V3 OrderLineItem and  OrderMeta

### ISSUE THREAD

**Issue by negapo** [XiaoFaye/WooCommerce.NET#402]
Wordpress (5.2.2), WooCommerce (3.7.0), WooCommerce.NET 

Hi, when using the Order object with the V3 library the OrderLineItem and  OrderMeta properties have to be declared as WooCommerceNET.WooCommerce.v2.OrderLineItem and WooCommerceNET.WooCommerce.v2.OrderMeta, apparently Visual Studio doesn't seem to identify this two properties. I can see that the whole order object is inherited by the V2.Order but cant understand why the other Object properties don't have this problem. Any help would be appreciated. Ty

**Comment by XiaoFaye** [comment]
What do you mean Visual Studio doesn't seem to identify this two properties? Do you have more details?

**Comment by geraldosalazar16** [comment]
Hi
I experimented the same behavior.
Right now I am using
using OrderLineItem = WooCommerceNET.WooCommerce.v2.OrderLineItem;

Because
using OrderLineItem = WooCommerceNET.WooCommerce.v3.OrderLineItem;
trows an error that says OrderLineItem does not exist in WooCommerceNET.WooCommerce.v3
