### ISSUE TITLE
int / Int32 -> Int64 (v2/product for total_sales)

### ISSUE THREAD

**Issue by Hw0xEEhqtb** [XiaoFaye/WooCommerce.NET#403]
Hey there,

first of all: Thanks for that great library, I found it very helpful!

I found an issue with pulling products on v2, changed to the latest version and still had this issue using this lib (0.7.8).

total_sales is declared as int(Int32) in row 183 of "WooCommerce/v2/Product.cs".
I had a Woocommerce shop exceeding this int. It would be great if you can change it in your main branch to Int64 since i'd like to stay up to date :) That change worked for me and could help others  #aswell.

- I tried to link this issue to the other product int32 issues... I had problems with it, sorry for opening a new issue :)

Best Regards

**Comment by XiaoFaye** [comment]
Thanks for letting me know, I will fix this one in the next release.

**Comment by XiaoFaye** [comment]
@Hw0xEEhqtb Hi, this has been fixed in version 0.7.9.
