### ISSUE TITLE
SET Shipping Costs at existing

### ISSUE THREAD

**Issue by daGregs** [XiaoFaye/WooCommerce.NET#405]
Hi Dudes, 
How set new costs for existing Shipping? In ShippingMethod.GetAll i see the ID, Name, Order but not Settings
Is there an example?

- Wordpress version = 5.2.3
- WooCommerce version = 3.7.0
- WooCommerce.NET = 0.7.9

**Comment by XiaoFaye** [comment]
Have you tried shipping zone methods?
