### ISSUE TITLE
issues with serialization object to json

### ISSUE THREAD

**Issue by VanchoDimitrov** [XiaoFaye/WooCommerce.NET#408]
### Make sure you have included the below details when open an issue. Thank you.

- I am using latest Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

`var p = new Product
                        {
                            sku = "1",
                            name = "Display Monitor",
                            description = a.
![Screenshot_1](https://user-images.githubusercontent.com/22734456/66109995-1b8cac00-e5c6-11e9-9e9d-c37b02e2cbe9.png)
ITEM_DESC,
                            tax_class = "18",
                            stock_quantity = Convert.ToInt32(a.QTY_OH),
                            price = a.UNIT_PRICE,
                            images = new ProductImage
                            {
                                src = "eftpos.jpeg",
                                position = 0
                            }
                        };`

- Details of the error message if there is any
The error happens when I do the images = new ProductImage object. It's not working, and I get a generic error that ProductImage is not part of List<ProductImage> which in fact is not the truth.

Please if you would comment on it.

Cheers,
Vancho

**Comment by XiaoFaye** [comment]
images is a list of ProductImage, in your code, you tried to assign it to a single ProductImage.

**Comment by VanchoDimitrov** [comment]
Would you share a simple code usage please? Whatever I try on my side is not working.

**Comment by VanchoDimitrov** [comment]
Actually, please don't waste your time.. Here it is for others.

await wc.Product.Add(new Product
                {
                    name = "test 9",
                    images = new List<ProductImage>
                    {
                        new ProductImage{
                        src = "pos.jpeg"
                        }
                    }
                });

Thanks for the great work!
