### ISSUE TITLE
Pulling specific attributes/properties of Products during GetAll()

### ISSUE THREAD

**Issue by andre-idrive** [XiaoFaye/WooCommerce.NET#409]
I am getting an error when I pull all the products because, for some of the products, the price has a string value instead of an int. However, I don't need the price attribute. Is there a way the pull a few attributes from all the products instead, say just the sku, the id, and the amount of inventory?

**Comment by XiaoFaye** [comment]
If you are using the Legacy API, it's possible. Check **Fields Parameter**  here: https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#parameters
