### ISSUE TITLE
How to add Category and Tags with the product?

### ISSUE THREAD

**Issue by vromashin** [XiaoFaye/WooCommerce.NET#41]
Hi!
Here is example a code:
... <create product object (pr) >

```
        pr.categories = new CategoryList();
        WooCommerceNET.WooCommerce.Category cat = new Category();
        cat.name=gd.goodType.name.ToString() + "/" + gd.goodKind.name.ToString() + "/" + gd.goodKindValue.name.ToString();
        pr.categories.Add(cat);

        pr.tags = new TagList();
        Tag tg1 = new WooCommerceNET.WooCommerce.Tag();
        tg1.name= gd.goodType.name.ToString();
        pr.tags.Add(tg1);

        Tag tg2 = new WooCommerceNET.WooCommerce.Tag();
        tg2.name = gd.goodKind.name.ToString();
        pr.tags.Add(tg2);

        Tag tg3 = new WooCommerceNET.WooCommerce.Tag();
        tg3.name = gd.goodKindValue.name.ToString();
        pr.tags.Add(tg3);
```

...<post product below>

No tags and no categories appear with the product after publish in WooCommerce. Probably I do something wrong?
Thanks in advance.

**Comment by XiaoFaye** [comment]
Tags and categories must be already exist, you can't create new tag or category while creating a new product. There are functions for creating tags and categories in the wrapper.

**Comment by vromashin** [comment]
OK, then another q.
I have create ProductCategory:

            ProductCategory cat = new  ProductCategory();
            cat.name = gd.goodType.name.ToString() + "/" + gd.goodKind.name.ToString() + "/" + gd.goodKindValue.name.ToString();

            wc.PostProductCategory(cat);


but in Product object I see only CategoryList type, not ProductCategory. How connect Product to category?

**Comment by XiaoFaye** [comment]
In Product object, it only uses Category, not ProductCategory, You can create a Category object with the basic information from ProductCategory and connect to the Product.

**Comment by vromashin** [comment]
OK, but I did't see any ws.PostCategory() method in wrapper,,,, only ws.PostProductCategory (I have updated to last version).

**Comment by XiaoFaye** [comment]
You don't need to post a Category, it's just a lightweight version of ProductCategory.
See below code on how to connect Product and Category:

`ProductCategory cat = new  ProductCategory();`
`Category cat2 = new Category();`
`cat.name = "test";`
`cat2.name = cat.name;`

`CategoryList cl = new CategoryList();`
`cl.Add(cat2);`

`Product pr = new Product();`
`pr.categories = cl;  //This is how you connect the category to product.`

**Comment by vromashin** [comment]
Thanks a lot, will try tomorrow.
You make a gread job, thanks!

**Comment by vromashin** [comment]
Sorry, it did not work. I create product category and post it, then create category and set it to product. But unfortunately category did not connect to product.

            ProductCategory cat = new  ProductCategory();
            cat.name = gd.goodType.name.ToString() + "/" + gd.goodKind.name.ToString() + "/" + gd.goodKindValue.name.ToString();

            wc.PostProductCategory(cat);

            Category cat2 = new Category();
            cat2.name = cat.name;

            CategoryList cl = new CategoryList();
            cl.Add(cat2);
                        
            Product pr = new Product();
            pr.name = gShow.name;
            pr.sku = gd.sku;
            pr.in_stock = true;
            pr.purchasable = true;
            pr.short_description = gShow.shortDescription;
            pr.description = gShow.description;
            pr.weight = gd.weight;
            pr.price = gShow.regularPrice;
            pr.regular_price = gShow.regularPrice;
            pr.sale_price = gShow.salePrice;

            pr.categories = cl;

**Comment by beatngu** [comment]
Any news on this?
I have the same problem,i just can't add a product to a category.
Making a category is working fine but when i want to assign a product to a category it does not work.

**Comment by XiaoFaye** [comment]
Hi, you will need to use PostProductCategory to create the product category first, then assign the Category object to Product with the ID. Product Category can't be created on the fly.

This should work for Product Tags as well.

example:
```
ProductCategory pc = new ProductCategory() { name = "test cat", slug = "testcat", description = "aa hello", display = "default" };
await wc1.PostProductCategory(pc);
await wc1.UpdateProduct(productID, new Product() { categories = new List<Category>() { new Category() { id = 25 } } });
```

**Comment by beatngu** [comment]
Hi there,
Thanks for a quick reply!
After some testing i got your example to work however not as i want.

This is working and the product is added to the category:

` await wc.UpdateProduct(314, new WooCommerceNET.WooCommerce.Product(){categories = new CategoryList() { new Category() { id = 9 } }});
`
However if i change it to this it's not working:

` await wc.UpdateProduct(314, new WooCommerceNET.WooCommerce.Product(){categories = new CategoryList() { new Category() { name = "home" } }});
`
I see it's only working on category id and not if i want to select from category name and it's also not working when i try to select from slug.

But what i do not understand is why something as this does not work:

 ```
WCObject wc = CallApi();
//Add categories
            WooCommerceNET.WooCommerce.ProductCategory cat = new WooCommerceNET.WooCommerce.ProductCategory();
            WooCommerceNET.WooCommerce.Category cat2 = new WooCommerceNET.WooCommerce.Category();
            cat.name = "home";
            cat2.name = cat.name;
            WooCommerceNET.WooCommerce.CategoryList cl = new WooCommerceNET.WooCommerce.CategoryList();
            cl.Add(cat2);
//Add product
            WooCommerceNET.WooCommerce.Product p = new WooCommerceNET.WooCommerce.Product()
            {
                name = "test product 9",
                description = "test product 9",
                price = 5.0M,
                categories = cl
            };
        await wc.PostProduct(p);
```
Should it not be possible to post the product to the categories instead of your way with updating the product?

**Comment by XiaoFaye** [comment]
Let's say this is just a WooCommerce behavior. Even if you want to add a new product with new categories in the WooCommerce admin page, you still can't add categories on the fly, you have to add the new categories first, then the product.

![image](https://cloud.githubusercontent.com/assets/6334728/20939607/55a5b4f2-bc54-11e6-918b-38c14a682d9f.png)
