### ISSUE TITLE
How to update Variation Stock QTY

### ISSUE THREAD

**Issue by andre-idrive** [XiaoFaye/WooCommerce.NET#411]
I am having trouble trying to update the variation `stock_quantity` of my products. Can you please take a look to make sure my code is accurate?

    public async void PushInventory(bool toZero = false)
    {
            // Get list of variations from WooCommerce
            var variants = PullVariants().Result;

            // Filtering variant SKUs that are in our system
            var variantsInOurSystem = variants.FindAll(_variant => SKUAPI.GetSKUByCustomerSKU(_companyId, _variant.sku) != null).ToList();

        foreach (var item in variantsInOurSystem )
        {
            if (item is Variation)
            {
                var variant = item as Variation;
                // Retrieve current quantity in stock for specific product sku
                string currentQty = VirtualWarehouseAPI.CurrentInStockNumber(variant.sku, _virtualWarehouseID).ToString();
                // Retrive stock status. This is a method containing a simple switch case
                string stockStatus = InStockStatus(currentQty);

                // Create dictionary as a parameter for Update method below. This will tell the system which product parameter on WordPress to update.
                Dictionary<string, string> itemParameters = GetParams(currentQty, stockStatus);

                // Finding the parent id of the current variant
                var parentId = products.Find(_product => _product.variations.Contains((int)variant.id)).id;

                // Updating the product quantity in WordPress
                Console.WriteLine($"Updating product variant: {variant.id} of variation {variant.attributes[0].option}.");
                await wc.Product.Variations.Update((int)variant.id, variant, (int)parentId, parms: itemParameters);
            }
        }
    }

    private Dictionary<string, string> GetParams(string currentQty, string stockStatus)
    {
        Dictionary<string, string> itemParameters = new Dictionary<string, string>() { { "stock_quantity", currentQty }, { "stock_status", stockStatus }, { "manage_stock", "true" } };
        return itemParameters;
    }

When I step through the code, `variant` ends up being `null` for some reason. However, when I hover over `item` it shows that it's not `null`. The methods that get passed properties of the `item` as parameters return an actual value.

I hope all this makes sense.

**Comment by XiaoFaye** [comment]
Can you try this:
`await wc.Product.Variations.UpdateWithNull(variationID, productID, new { stock_quantity = 2 });`

**Comment by andre-idrive** [comment]
Sure. What's the difference between `Update` and `UpdateWithNull`?

**Comment by andre-idrive** [comment]
I did `await wc.Product.Variations.UpdateWithNull((int)variant.id, (int)parentId, variant, parms: productParameter);` but now I'm getting a `System.Net.WebException` when it starts looping through the `variantsInOurSystem` list. When I step through it, the error occurs right after ln 257 is processed in the `RestAPI` file: `WebResponse wr = await httpWebRequest.GetResponseAsync().ConfigureAwait(false);`

**Comment by XiaoFaye** [comment]
No, not like that, just pass `new { stock_quantity = 2 } `, not the variant object.
