### ISSUE TITLE
Separating Variable Products and Single's

### ISSUE THREAD

**Issue by Vliesie** [XiaoFaye/WooCommerce.NET#413]
I Found the get method to use to pull a single product but im confused about how to get the Variable products when the Query is Products <ID> <Variations> Someone know how to achieve this?

And maybe have any idea how id check to see so  I can use different view methods

I was thinking of using type maybe?
But I still cant load variants that why

**Comment by XiaoFaye** [comment]
Try `wc.Product.Variations.GetAll()`

**Comment by Vliesie** [comment]
While I have you Could you show me how to get ahold of the Product Image src When i'm generating E.G Im binding to images but I don't think I can bind to a list for 1 element in Xaml
       ```
 WCObject wc = new WCObject(rest);
       
            var p = await wc.Product.GetAll(new Dictionary<string, string>() {
                    {"tag", Suppliers.tagid },
                    { "per_page", "80" } }); ;

            productsListView.ItemsSource = p;
```

**Comment by XiaoFaye** [comment]
It can be done, but need some customized code to bind to the right image property.

**Comment by Vliesie** [comment]
Could you possibly add the Featured_Image_src to the Products model?

**Comment by XiaoFaye** [comment]
@Vliesie Featured_Image_src is not a property of WooCommerce product. If this is for binding purpose, I would suggest not to bind to the product object directly, create your own binding object from the products is a much easier way for XAML application.
