### ISSUE TITLE
Stuck with Invalid signature - provided signature does not match

### ISSUE THREAD

**Issue by franknesse** [XiaoFaye/WooCommerce.NET#414]
Wordpress version 5.2.4
WooCommerce 3.7.1
WooCommerce.NET 0.7.9

Hello guys/girls,

I am really stuck with the famous error:

WebException: {"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}

FYI: 

- I have two wordpress instance running. One on my local machine and one on a remote server. The remote server is, as my local machine, in our company's LAN

- The error ONLY occurs when trying to call the Rest api on the remote server. Connecting to the local rest api, the Rest Api/WooCommerceNet is working like a charm :-)

- From my local browser I can login to the remote WooCommerce instance without any problem

- On the remote server I have defined WP_SITEURL and WP_HOME in wp-config.php
    define('WP_SITEURL', 'http://[ip address]/webshop/'); 
    define('WP_HOME', 'http://[ip address]/webshop');

- I am running WAMP on both machines to run Apache and host Wordpress

- Calling the api url (http://[ip address]/webshop/wp-json/wc/v3/) from my local browser works OK. I get the normal JSON response

- I am sure I am using the right consumer key and secret

Is there anybody that can point me into the direction of a solution?

Your help will be much appreciated!

Frank Nesse

- Details of the error message if there is any

**Comment by XiaoFaye** [comment]
Have you tried to change the value of authorizedHeader parameter?

**Comment by franknesse** [comment]
Thanks for the reply @XiaoFaye .How and where should I do that?

**Comment by XiaoFaye** [comment]
It's a parameter in RestAPI constructor, https://github.com/XiaoFaye/WooCommerce.NET/blob/83601f494938ba4084bbddfa489bab2b8b31cecb/RestAPI.cs#L73

**Comment by franknesse** [comment]
Nope. Same error occurs. I guess it is not releated to the wrapper. Therefore I posted the same issue on Stackoverflow. 

https://stackoverflow.com/questions/58554329/stuck-with-woocommerce-rest-authentication-error-invalid-signature-provided-s

Any valuable replies overthere will be posted here by me

**Comment by HoesLeaguesharp** [comment]
Currently facing the same issue, my url and the keys are correct, error occurs with authorizedHeader being true or false, i would say that the relevant API is down but can't be certain as there is no API status available.

**Comment by IcuScc** [comment]
Hi. I have the same problem.
in my case, now, i'm using a local wordpress...

**Comment by XiaoFaye** [comment]
Hi @HoesLeaguesharp @IcuScc , I will suggest you to use [Postman](https://www.getpostman.com/) to check if the API itself working.

**Comment by IcuScc** [comment]
Hi.. Thanks for your comments. Xiao.
In my case works ok. My problem was an extra / at the end of my URL... :-)
