### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by Tall-Paul** [XiaoFaye/WooCommerce.NET#416]
Should / does this package run on a .Net Core application?

Trying to use it, installs fine using NuGet, but when trying to launch my application I get:

"ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'WooCommerce.NET, Version=0.7.7.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d'. The system cannot find the file specified."

I suspect because there isn't a .Net Core version available.

**Comment by XiaoFaye** [comment]
WooCommerce.NET is built on .NET Core 2.0, and Yes, it will run on a .NET Core application.

**Comment by Tall-Paul** [comment]
Okay, so the problem I had seems like this one: https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

I had to clone your repo, change the 'targetframework' from 'netstandard2.0' to 'netcoreapp2.2', build it and then include the assembly in my project.

**Comment by XiaoFaye** [comment]
Which framework is your project targeting?

**Comment by Tall-Paul** [comment]
netcoreapp2.2

It's 'grandNode' ecommerce framework.

**Comment by XiaoFaye** [comment]
I just created a console project which targeting netcoreapp2.2, runs with WooCommerce.NET without this issue. 

![image](https://user-images.githubusercontent.com/6334728/67755261-b7fa7f00-fa9c-11e9-8ada-cb8b84fbc478.png)

**Comment by Tall-Paul** [comment]
Maybe it's something to do with my project being a class library?

**Comment by XiaoFaye** [comment]
Unless any of your project's framework doesn't match the compatible of .NET Standard 2.0

![image](https://user-images.githubusercontent.com/6334728/67755860-cdbc7400-fa9d-11e9-803c-6dcdc2f485f1.png)
