### ISSUE TITLE
Get Product Variation

### ISSUE THREAD

**Issue by IcuScc** [XiaoFaye/WooCommerce.NET#417]
Hi friends.
i want to know if is it possible to get a product variation with sku.
in my case, i want to update the stock of my variations and i have only the sku.
i have tried several methods but i dont get it.

i want to avoid to get all variations for after search the sku

Thanks.

**Comment by XiaoFaye** [comment]
Please use WCObject.Product.Variation.GetAll() function with sku parameter.

**Comment by IcuScc** [comment]
Thanks Xiao.
my best sample is that
            var oIcu = await wc.Product.Variations.GetAll(97,new Dictionary<string, string>()
                        {
                            { "sku", "CAMIS004102" }
                         });

but without id product, i dont get it.
is for this reason i ask in this foro.
thanks.

**Comment by XiaoFaye** [comment]
If you don't have the product id, that will be tricky. Have you tried wc.Product.GetAll() with sku parameter?

**Comment by IcuScc** [comment]
Wooowwww...Xiao... perfect....
It had not occurred to me to do so.
with this sample, i think solves my case.
           
            var oIca = await wc.Product.GetAll(new Dictionary<string, string>()
                        {
                            { "sku", "CAMIS004102" }
                         });

Thanks for your help... 
Fantastic :-)
