### ISSUE TITLE
GetProducts() paging sometimes returns duplicate SKU in stead of the correct one.

### ISSUE THREAD

**Issue by code54nl** [XiaoFaye/WooCommerce.NET#418]
We are running:
- WordPress 5.2.4
- WooCommerce Versie: 3.7.1
- WooCommerce.NET 0.8.0.0 (originally I used 0.7.4.0 but because of this problem I upgraded)
- **API v1** (http://shop.xxx.nl/wp-json/wc/v1/)

We use this to retrieve products from the shop:

```
public async Task<List<Product>> ReadAsync()
{
	wooProducts = new List<Product>();

	int page = 1;
	int nRetrieved = 0;

	//Load Products
	do
	{
		var retrievedProducts = await wc.GetProducts(new Dictionary<string, string>()
		{
			{  "page", page.ToString() },
			{  "per_page", "100" }  //100 is maximum 
		});
		nRetrieved = retrievedProducts.Count();		

		//check for duplicates See Ticket #16692
		List<Product> duplicates = new List<Product>();
		foreach (var product in retrievedProducts)
		{
			if (wooProducts.Any(p => p.sku == product.sku))
			{
				duplicates.Add(product);
				string log = "***************** WARNING: duplicate SKU  *****************\n";
				log += string.Format("SKU:{0}\nCreated:{1}\nModified:{2}\n\nDescription:{3}\n",
					product.sku, product.date_created, product.date_modified, product.description);
				log += "*****************\n";
				this.log.Info(log);
			}
		}

		wooProducts.AddRange(retrievedProducts.Except(duplicates));
		page++;
	}
	while (nRetrieved > 0);
	return wooProducts;
}
```
Sometimes this returns a duplicate SKU. The last one on a page is the same as the first on the next page.  **I found out that this second (duplicate) SKU, is retrieved in stead of the actual one.** So we receive duplicates, but this also means we are missing one. The total amount of items returned is correct. And the duplicate SKU is not in de WooCommerce database (checked that too).

We sync the shop every night and it happens almost every night, but only with a single product. It's always another product, but always the last on a page and the first of the next page. So it's not with every page, it's not with the same product, it's not always.

I was able to replicate the problem by restoring the Wordpress-database after a night that went wrong. With that it kept going wrong with the same product time after time. I changed the number of items per page from 100 to 90 and is was solved. So to sure I changed it to 50 and left it like that. Next couple of days it went wrong again. Same problem, but now with 50 items per page.

The problem, of course is, that we are missing one product. So in our sync we try to add that to the shop and then get an error that the SKU already sexists.

Is this a known problem?

**Comment by XiaoFaye** [comment]
No, I never heard of this problem.

- You mention duplicate sku, do you mean getting 2 exactly same products in the query? Or a product comes with other product's sku?
- The problem happens randomly?
- Have you tried to use API V3?
- If getting products by the sku, will you get 2 products?

**Comment by code54nl** [comment]
Hi @XiaoFaye , Yes both duplicates ara identical. Same SKU, same name, description, timestamp, etc.
If I read with pagesize 100, it's the 100th on one page and then the first on the next. And this duplicate is returned in stead of an actual SKU. So I get one duplicate and I miss one.

Yes it's quite randomly, however at the moment I have a backup restored that gives this error every time, with the same SKU and the same page. So I can test it now.

I have tried to migrate to API V3 but that caused quite a lot of code-changes. So we paused that.

I haven't tried to get products by SKU, only by page. I do have the URL and username and secret in a test-environment. I was thinking, maybe I can check the result when I access the API V1 and V3 with Postman or something. Just to see if that would give me the same duplicates on the same pages. Or is there another easy way to test paging without changing our application too much?

Thanks for your support.

**Comment by XiaoFaye** [comment]
Do you mind sending me the api token for the test-environment, which gives this error every time?
So I can do some testing on this issue.

Email:  xiaofaye#msn.com

**Comment by code54nl** [comment]
Thanks @XiaoFaye , I will try to send it to you within a couple of days. I have to ask someone to restore the database again.

**Comment by code54nl** [comment]
@XiaoFaye , I have a working test-environment now. I will sent you the details by mail.

**Comment by XiaoFaye** [comment]
I can now confirm that this is a bug in WooCommerce v1 API, and since v2 it had been fixed.

**Comment by code54nl** [comment]
@XiaoFaye , Thank you for confirming this bug!

To be clear: this is a bug in WooCommerce itself. Not in WooCommerce.NET?
The obvious solution it to upgrade to V3, but since a customer is paying for that: do you know a work-around? It worked fine for about a year. Or can't I ask you questions about WooCommerce itself?
Thanks again.

**Comment by XiaoFaye** [comment]
Yes, the bug is in the WooCommerce plugin itself.

As you are saying this wasn't happen before, the bug might ONLY present when it comes to a number of products in the database, or some products data might be corrupt in the database.
