### ISSUE TITLE
Product Upload Image

### ISSUE THREAD

**Issue by IcuScc** [XiaoFaye/WooCommerce.NET#419]
Hi, friends.
I want to make a question.

Is it posible to upload the image of produtc with Wocommerce.net?
or
I have to upload the images to a web folder and after attach to product with ProductImage object.

Thanks... :-)

**Comment by XiaoFaye** [comment]
There are two ways of uploading images:
1. Use WooCommerce API and assign a valid image URL.
2. Use Wordpress API and select a local image.

**Comment by IcuScc** [comment]
Thanks Xiao.
I dont have very clear the correct way to upload the product image...
I will try it, and comment my results

**Comment by franknesse** [comment]
If you want to have control over how images are uploaded to  the WP media library I would recommend using the Wordpress API. With control I mean things like preventing that the same images are uploaded multiple times. This API will let you search for an aimge after which you can take the ID and eg assign it to a product as product image. To use the WP Rest API I have installed the WP Rest API v2 plugin and the JWT Authentication plugin (required for WP REST API v2)

**Comment by IcuScc** [comment]
Hi  friend.. One small question..
I have installed these two plugins. but, is good practice use WordPressPCL library from nuget?
I don't got it, yet...

**Comment by XiaoFaye** [comment]
@IcuScc WooCommerce.NET already has the ability to make WordPress Restful API calls, you won't need WordPressPCL.

**Comment by IcuScc** [comment]
Thanks Xiao, i go to investigate how to do.
i'm lost with this topic.
in my case, after to assing an image to product or variation, i need to comprobe if this image exist in wordpress for upload it or not.

With my advances, after i write here my solution for the rest of people.
Thanks.

**Comment by IcuScc** [comment]
Xiao. I Got it.
Very simple. I want to put here my code example.

- I used JWT Authentication. So it is necesary to install the plugin JWT Authentication for WP REST.

- After i put in my wp-config.php the secret key.
        define( 'JWT_AUTH_SECRET_KEY', '5BejYXqifmYjhqTSPfZBQGd8RiASKTODDgurnTRg9Zp3Fxf9pXR8hqudNqzi7wF' );

- After i put in my .htaccess at the end before  </IfModule>
        RewriteCond %{HTTP:Authorization} ^(.*)
        RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

- After i put in my .htaccess at the end before  # END WordPress
        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

- Now in my c# code, simple example for get if the image exist and upload.
           RestAPI restwp = new RestAPI("http://localhost:8080/wordpress/wp-json/jwt-auth/v1/token", "myuser wordpress", "mypassword wordpress");
           WPObject wp = new WPObject(restwp);
           var oicu = await wp.Media.GetAll() ;    // i get all media records
           var overo = await wp.Media.GetAll(new Dictionary<string, string> { { "slug", "bobesponjaheroe"} });   // i get my file and i know if exists.
// upload the file
           await wp.Media.Add("granturismo.jpg", @"C:\WgSql\images\granturismo.jpg");


Thanks  Xiao for you patient. and thanks to all
I will continue...

**Comment by fredoche1810** [comment]
Hello @IcuScc , @XiaoFaye 

I tried your solution to upload a local image to a product but without any success
I receive the following error : System.Runtime.Serialization.SerializationException : 'There was an error deserializing the object of type WooCommerce.NET.WordPress.v2.Media. Encountered unexpected character 'o'.'

Do you have an idea ?

Thanks,

**Comment by omadawnx** [comment]
> Hello @IcuScc , @XiaoFaye
> 
> I tried your solution to upload a local image to a product but without any success I receive the following error : System.Runtime.Serialization.SerializationException : 'There was an error deserializing the object of type WooCommerce.NET.WordPress.v2.Media. Encountered unexpected character 'o'.'
> 
> Do you have an idea ?
> 
> Thanks,

Try going to settings -> permalinks, set it to slug mode (post name).

**Comment by IcuScc** [comment]
Hi.
I dont know. Sorry.
If i can i will try after again

**Comment by olivierp9** [comment]
I'm also having the `Encountered unexpected character 'o'.'`

I'm already in slug mode (post name)

WooCommerceNET 0.8.6
