### ISSUE TITLE
Update Order Error

### ISSUE THREAD

**Issue by eflowUser** [XiaoFaye/WooCommerce.NET#42]
Hi again!

I'm trying to Update  an Order state using the code below:

`             RestAPI restapi = new RestAPI(ApiUrl, ConsumerKey, ConsumerSecret);
             WCObject wc = new WCObject(restapi);
             string result = await wc.UpdateOrder (oid, new Order { id= oid , status= "cancelled", updated_at = DateTime.Now });`

Oid is an existing order Id. As you see I use a similar code like the Update Product Example in the Usage section (await wc.UpdateProduct(128, new Product { name = "test 9" });)

I also tried this other version

`              
            Dictionary<string, string> parametros = parametros = new Dictionary<string, string>();
            parametros.Add("status", "cancelled");
            RestAPI restapi = new RestAPI(ApiUrl, ConsumerKey, ConsumerSecret);
            WCObject wc = new WCObject(restapi);
            string result = await wc.UpdateOrder (oid, new Order { id= oid }, parametros);
            `
In both cases the result is the same: the order isn't update and I get the result below:

> "<br />\n<b>Warning</b>:  urldecode() expects parameter 1 to be string, array given in <b>/homepages/24/d582332844/htdocs/clickandbuilds/jolieboutique/wp-content/plugins/woocommerce/includes/api/legacy/v1/class-wc-api-server.php</b> on line <b>401</b><br />\n{\"order\":{\"id\":959,\"order_number\":959,\"created_at\":\"2016-10-26T11:36:00Z\",\"updated_at\":\"2016-10-26T13:31:14Z\",\"completed_at\":\"2016-10-26T12:31:14Z\",\"status\":\"trash\",\"currency\":\"EUR\",\"total\":\"151.60\",\"subtotal\":\"143.70\",\"total_line_items_quantity\":3,\"total_tax\":\"0.00\",\"total_shipping\":\"7.90\",\"cart_tax\":\"0.00\",\"shipping_tax\":\"0.00\",\"total_discount\":\"0.00\",\"cart_discount\":\"0.00\",\"order_discount\":\"0.00\",\"shipping_methods\":\"Env\\u00edo\",\"payment_details\":{\"method_id\":\"\",\"method_title\":\"\",\"paid\":false},\"billing_address\":{\"first_name\":\"\",\"last_name\":\"\",\"company\":\"\",\"address_1\":\"\",\"address_2\":\"\",\"city\":\"\",\"state\":\"\",\"postcode\":\"\",\"country\":\"\",\"email\":\"\",\"phone\":\"\"},\"shipping_address\":{\"first_name\":\"a\",\"last_name\":\"b\",\"company\":\"c\",\"address_1\":\"\",\"address_2\":\"\",\"city\":\"\",\"state\":\"\",\"postcode\":\"\",\"country\":\"ES\"},\"note\":\"test notes here\",\"customer_ip\":\"\",\"customer_user_agent\":\"\",\"customer_id\":\"0\",\"view_order_url\":\"http:\\/\\/jolie-boutique.es\\/my-account\\/view-order\\/959\",\"line_items\":[{\"id\":35,\"subtotal\":\"45.90\",\"total\":\"45.90\",\"total_tax\":\"0.00\",\"price\":\"45.90\",\"quantity\":1,\"tax_class\":null,\"name\":\"Camiseta Blanca de Lentejuelas\",\"product_id\":519,\"sku\":\"camisetablancalentuejuelasS\"},{\"id\":36,\"subtotal\":\"34.90\",\"total\":\"34.90\",\"total_tax\":\"0.00\",\"price\":\"34.90\",\"quantity\":1,\"tax_class\":null,\"name\":\"Pantal\\u00f3n Negro\",\"product_id\":464,\"sku\":\"pantanegro\"},{\"id\":37,\"subtotal\":\"62.90\",\"total\":\"62.90\",\"total_tax\":\"0.00\",\"price\":\"62.90\",\"quantity\":1,\"tax_class\":null,\"name\":\"Vestido de flores rojas\",\"product_id\":593,\"sku\":\"Vestido de flores rojas XL\"}],\"shipping_lines\":[{\"id\":38,\"method_id\":\"flat_rate\",\"method_title\":\"\",\"total\":\"7.90\"}],\"tax_lines\":[],\"fee_lines\":[],\"coupon_lines\":[],\"customer\":{\"id\":0,\"email\":\"\",\"first_name\":\"\",\"last_name\":\"\",\"billing_address\":{\"first_name\":\"\",\"last_name\":\"\",\"company\":\"\",\"address_1\":\"\",\"address_2\":\"\",\"city\":\"\",\"state\":\"\",\"postcode\":\"\",\"country\":\"\",\"email\":\"\",\"phone\":\"\"},\"shipping_address\":{\"first_name\":\"a\",\"last_name\":\"b\",\"company\":\"c\",\"address_1\":\"\",\"address_2\":\"\",\"city\":\"\",\"state\":\"\",\"postcode\":\"\",\"country\":\"ES\"}}}}"

Please, could you tell me what's wrong ?
Thanks in advance.

**Comment by XiaoFaye** [comment]
In your code: `string result = await wc.UpdateOrder (oid, new Order { id= oid , status= "cancelled", updated_at = DateTime.Now })`

1. You don't need to specific the order id twice in the new Order object.
2. updated_at should be updated automatically,

please try below code:
`string result = await wc.UpdateOrder (oid, new Order { status= "cancelled" })`

**Comment by eflowUser** [comment]
I tryed it with the same result (Warning urldecode()...) :-(

PD: I'm using WooCommerceNET.WooCommerce.Legacy, because if don't I get an Exception "You need to use the legacy WCObject on the legacy version of WooCommerce Restful API."

PD2: I'm adding "wc-api/v1/" to my shop Url as basic endpoint

**Comment by eflowUser** [comment]
Yeah, I got it!

The mistake was in Legacy Lib. now I'm NOT USING Legacy and change the endpoint to "wp-json/wc/v1/" and it has updated my order.

Thanks.

**Comment by XiaoFaye** [comment]
is the order filter working now?

**Comment by eflowUser** [comment]
not at all, i answer on the #40 topic :-)
