### ISSUE TITLE
How to set custom fields on Product level?

### ISSUE THREAD

**Issue by franknesse** [XiaoFaye/WooCommerce.NET#420]
Wordpress version 5.2.4
WooCommerce 3.7.1
WooCommerce.NET 0.8.0 

using WooCommerceNET.WooCommerce.v3;

Hello all,

I am looking for an example how to set values for custom fields that we have defined on Product level. For example we have defined a custom field called 'introduction_number'. When loading a product via WooComerceNET I can see this field (using the VS debugger) in the meta data collection of the product as 

id = 3424
key="introduction_number"
value = "some value"

Now I would like to change the value of this field via WooCommerceNET. Can anybody point me to a solution?

Thanks in advance!

Frank

**Comment by franknesse** [comment]
In the meantime I have found a way to (at least initially) set the value for a new product. It seems that ProductMeta is in the v2 namespace....
```
product.meta_data = new List<WooCommerceNET.WooCommerce.v2.ProductMeta>()
{
	new WooCommerceNET.WooCommerce.v2.ProductMeta()
	{
		id = 13774,
		key = "introduction_number",
		value = productBo.IntroductionNumber
	}
};
```
Still figuring out if and how I can update it for existing products. Will post it here if as soon as I have come that far ;-)

**Comment by XiaoFaye** [comment]
The ProductMeta object has no difference between v2 and v3, so you can use the ProductMeta object in v2 namespace while using v3 api.
