### ISSUE TITLE
Example of Order 

### ISSUE THREAD

**Issue by Lirian21** [XiaoFaye/WooCommerce.NET#421]
Hi 

Could you Provide me with an Example of how i'd Place & Update a Order using a single product or something of the likes.

I cant seem to find anything threw out the directory 

Would be of great help Thank you.

**Comment by XiaoFaye** [comment]
Check here: #226

**Comment by Lirian21** [comment]
var order = new Order(){status="pending"}; order.line_items.Add(new OrderLineIItem() { product_id=product.id, quantity = 1 }); wc.Order.Add(order);

So just tell me if im understanding this correctly 

You have to pass in status Then the Product
But my qeustion is

How do I specify Who's placing it along with the Status? So 
status="pending"
email=$"{User.Email}"  
As an example

And then for Variable products If I just want to Pass threw a Specific Variable product and not the whole product is that just a slug or hows this work?

Sorry the order things confusing me.

**Comment by XiaoFaye** [comment]
I would suggest you to read the WooCommerce Restful API document first, or you are not getting anywhere. 

https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by Lirian21** [comment]
I have read it yes, 

I'm for the most part
 aware of how the API works at this point.
I'm just confused as to how with the wrapper

I'd add a product to be added to a order and then add another and another and so on

Do I create a Orders list to pass into the line_Items wich im assuming is for More then 1 Product ordering. 

And how am I keeping orders for the same "Customer" Do I make the first order then
A order ID is created on the API side and I pull that then

every order afterwords I give the Parent Id to add onto that order.

That is the extent of what I can understand from the Documents, The rest is a little confusing thus the hope for an example.

**Comment by XiaoFaye** [comment]
What you are looking for is create and update of the order.
If you want to add multiple items in one go, sure you can do it when creating and order.
or if you want to update an order from time to time, you can always update the order with order id.

Working with orders has not much difference than working with product, so the example on the project home page is good for you to go ahead.

Go ahead, build a test environment, try few lines of code, look into methods and properties of the wrapper, I'm sure you will get much more out of this than just thinking about it. :)

**Comment by Lirian21** [comment]
xD I get what your saying but, I think your trolling me?

I'm not theorizing a app over here. 
I'm building a Application I wouldn't be asking if I understood the methods and properties I'm seeing in the wrapper i'm Obviously new to this. 

And yes its not much different But adding a orders not the problem its adding more then one, 

 ```
Order z = new Order()
            {
                status = "pending",
                billing = { email = Custemail }
            };

            foreach (var item in cart)
            {
                foreach (var x in p)
                {
                    if (x.id == item.variation_id)
                    {
                        var yup = x.id;
                        varID = Convert.ToInt32(yup);
                       
                    }
                }
                z.line_items.Add(new WooCommerceNET.WooCommerce.v2.OrderLineItem()
                {
                    product_id = z.id,
                    quantity = Convert.ToDecimal(productQuantity),
                    variation_id = varID,
                });
            }

            await wc.Order.Add(z);
```
If you want to add multiple items in one go, sure you can do it when creating and order- I figured as much but again im not sitting here xD asking over and over again because I like annoying people.
 
I'm Obviously messing around with the Methods, As I mentioned 

var order = new Order()
{status="pending"};

order.line_items.Add(new OrderLineIItem() 
{ product_id=something.id,
 quantity = something.Q }, //Cant add a Second One here?{
}

}); 

   Order z = new Order()
            {
                status = "pending",
                line_items = cart//List ,
            };

I'm not getting the right returns on the site thus the Question's .

**Comment by simontrice** [comment]
@Lirian21, you should create a list of OrderLineItems ( var mylist = new List<OrderLineItems>(); )

populate that from your cart list
for each( x in cart) {
    mylist.add( product_id = someint, quantity = anotherint, vatiation = yetanotherint, etc...);
    }

and then add it to the order when you create it

order z = new order();
order.status = "pending";
order.line_items.AddRange(mylist);
