### ISSUE TITLE
Can't seem to get attribute from a placed order

### ISSUE THREAD

**Issue by cslak** [XiaoFaye/WooCommerce.NET#422]
Some of the orders from woocommerce carry important information after order was placed under attribute in order page, i have no problem to retrieve the order, but i can't pull it's attribute out, any ideas?
my code is:

```
 Dim gorder = wc.Order.Get(OrderN)

   For Each item In gorder.Result.line_items
            OrderDetails.RichTextBox1.Text = OrderDetails.RichTextBox1.Text & item.quantity & " | " & item.name.ToString & vbNewLine



            
        Next
```

**Comment by XiaoFaye** [comment]
Have you checked the `meta_data` property?

**Comment by cslak** [comment]
Yup, got it, thank you!
