### ISSUE TITLE
Any way if Checking if a Product is updated on the site?

### ISSUE THREAD

**Issue by Vliesie** [XiaoFaye/WooCommerce.NET#423]
Is there any way to check weather let's say, A product's Price is updated on Woocommerece to then Refresh the Product on the app?

**Comment by XiaoFaye** [comment]
Yes, there is always a way, just need lots of coding.

**Comment by simontrice** [comment]
If you catch the return from the update task you can verify if it has updated (this is how I do it).  By default it will either return the updated product where you can check the date_modified field or will return an error, which should show in the output window if you are running in debug.
