### ISSUE TITLE
Can not get product

### ISSUE THREAD

**Issue by tuanta1996** [XiaoFaye/WooCommerce.NET#424]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

I got this error:
"System.Runtime.Serialization.SerializationException: 'There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.0.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Encountered unexpected character '<'.'" when running wc.Product.GetAll().
Any idea???

**Comment by XiaoFaye** [comment]
Set DEBUG to true and see what actually json string has returned
