### ISSUE TITLE
Is there any ways to see paid amount for order by customer?

### ISSUE THREAD

**Issue by hank-dohwankim** [XiaoFaye/WooCommerce.NET#425]
Hello Xiao. I really appreciate your awesome Library.

I'm currently developing integration system with WooCommerce.NET and local POS system.

I'm wondering is there any ways to check how much customer paid for their order and change that paid amount with API. 

I know there is "set_paid" , "status" properties in Order method but couldn't find anywhere about indicating paid amount by customer. Include WooCommerce API doc. 

My scenario is, If someone order items through WooCommerce, and store owner wants to customer pay deposit(this part, I need to check how much customer paid and need to pay more).

**Comment by XiaoFaye** [comment]
It seems you will need this plugins: https://docs.woocommerce.com/document/woocommerce-deposits/

**Comment by hank-dohwankim** [comment]
@XiaoFaye  Thank you very much

**Comment by hendrik-kim** [comment]
Hello XiaoFaye. Could you please delete this issue? my account is hacked and I'm trying to delete all my logs in github. Thank you.
