### ISSUE TITLE
Error in intial RestAPI call

### ISSUE THREAD

**Issue by yonahs** [XiaoFaye/WooCommerce.NET#427]
I am running a VB.NET empty website in 4.7.2

I have called:

`rest = New RestAPI("http://www.myStore.com/wp-json/wc/v3/", WooCommerceKey, WooCommerceSecret)`

I get the following error:
`BC30652: Reference required to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' containing the type 'Func(Of ,)'. Add one to your project.`

I have seen another issue where the solution was to run as a Web Application, unfortunately, that is not an option for me as I am adding this to an existing site

**Comment by XiaoFaye** [comment]
Which version of Visual Studio are you using? Some old version doesn't support adding .NET Standard reference.

**Comment by yonahs** [comment]
2019.

I solved the problem by adding the assembly in the web.config file


Is there any way for the wrapper to be modified to add a plug-in that uses
the woocommerce rest API?

**Comment by XiaoFaye** [comment]
You mean calling restful api for woocommerce plug-ins?

**Comment by yonahs** [comment]
yes, other endpoints..

**Comment by XiaoFaye** [comment]
Go here: https://github.com/XiaoFaye/WooCommerce.NET/commit/aa4d6522c09e9052ab9197b80260637f3f1b2933#diff-305fc9103a9925b6de1cf994f7e33a7f

and look for PluginsExtension, once you put other endpoints, you can access them from the Plugins property in WCObject.

**Comment by yonahs** [comment]
cool, thanks
