### ISSUE TITLE
 Operator '&' is not defined for string "" and type 'Object'.'

### ISSUE THREAD

**Issue by cslak** [XiaoFaye/WooCommerce.NET#428]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version(5.32), WooCommerce version(3.8.1) and WooCommerce.NET version(0.8.0)

- I tried to pull meta.data.
Error: Operator '&' is not defined for string "" and type 'Object'.'
From website, lets say someone ordered Pizza
From meta data it said Toppings: Pepperoni, now i get this error "Operator '&' is not defined for string "" and type 'Object'.'"

`
            For Each md In item.meta_data

              
                Try
                    OrderDetails.RichTextBox1.Text = OrderDetails.RichTextBox1.Text & md.key.ToString & ": " & md.value.ToString & "" & vbNewLine

                Catch ex As Exception
                    MsgBox(ex.Message)
                End Try
             
            Next`
Result of the string is:
product_extras: System.Object
_WCPA_order_meta_data: 

Just started happening recently, never came accross this issue, any idea why this is happening?

**Comment by XiaoFaye** [comment]
Please set a break point in here: `OrderDetails.RichTextBox1.Text = OrderDetails.RichTextBox1.Text & md.key.ToString & ": " & md.value.ToString & "" & vbNewLine` and check what is the meta_data. meta_data values are not always as string.

**Comment by cslak** [comment]
It's not a string, it's an object in my case. Problem is coming from md.value 
Not sure why it's not a string, in order details it's a string, but it's showing as an object, i tried converting it to string with no luck.

**Comment by cslak** [comment]
I don't understand why the values in this particular meta_data are not strings, and how can i view this particular object?

**Comment by XiaoFaye** [comment]
Please check this wiki page: https://github.com/XiaoFaye/WooCommerce.NET/wiki/Handle-different-types-of-Meta-Value-in-WC-Restful-API-V2

**Comment by cslak** [comment]
I set the break point, it showed 
MD.Key = "product_addons"
MD.Value = {Object}

That's where mistake is.

**Comment by XiaoFaye** [comment]
That means it's a complex meta value, you will need to follow the wiki page to extract the value.

**Comment by cslak** [comment]
Can I use JSON.NET just for md.value?

**Comment by XiaoFaye** [comment]
No, I don't think so, but you can intercept the json string using DeserializeJSon, which will contain all information, and do whatever you want with it.
