### ISSUE TITLE
WooCommerceNET says error deserializing OrderList: Value can not be parsed as a decimal value.

### ISSUE THREAD

**Issue by wkaper1** [XiaoFaye/WooCommerce.NET#43]
My WooCommerce shop (version 2.6.4), when I use the GetOrders API call, it often sends me an OrderList (JSON) that contains "shipping_lines" that look like:
"shipping_lines":[{"id":4,"method_title":"Flat Rate","method_id":"flat_rate:2","total":"0.00","total_tax":"0.00","taxes":[{"id":1,"total":""}]}]

It contains a "taxes" array that has a total value written like an empty string. This gives an exception saying that the value cannot be parsed as a decimal value.
If I repair the total manually by typing "0.00" then the exception disappears.
I am using the newest 0.5.5 version of the WooCommerceNET library.
What's wrong? Is WooCommerce 2.6.4 having a bug, or is WooCommerceNET too restrictive in not allowing a "". Or am I using a wrong mix of versions...? How can I get rid of the exception?

**Comment by XiaoFaye** [comment]
There is a bug in the code, I will fix it in the next release.
Meanwhile, if you can make changes as below, the exception should go away:

1. line 404 in Order.cs
Before:
`public class TaxItem`
After:
`public class TaxItem : JsonObject`

2. line 415 in Order.cs
Before:
`[DataMember(EmitDefaultValue = false)]`
After:
`[DataMember(EmitDefaultValue = false, Name = "total")]`
`private object totalValue { get; set; }`

**Comment by wkaper1** [comment]
Thank you! I tried it on the same case, and indeed, the exception was gone.
