### ISSUE TITLE
how to update stock status of a variand of product ?

### ISSUE THREAD

**Issue by akatsifos** [XiaoFaye/WooCommerce.NET#430]
Hello.
Is It possible to update a stock status of a variand of product ?
Regards
Aris

**Comment by akatsifos** [comment]
I founded how it works !
THanks.
But how is it possible to get   a variation   that has an attribute meta_key = _wpm_gtin_code  and 'xxx' in metavalue ?

**Comment by XiaoFaye** [comment]
Hi, please check this Wiki page: https://github.com/XiaoFaye/WooCommerce.NET/wiki/Handle-different-types-of-Meta-Value-in-WC-Restful-API-V2
