### ISSUE TITLE
Order Get All Raise Exception : The value 'total' cannot be parsed as the type 'Int32'

### ISSUE THREAD

**Issue by adelhoss** [XiaoFaye/WooCommerce.NET#431]
Worpress ver is :5.2, WooCommerce version: 3.5.5 WooCommerce.NET version:0.8.0

I Use Method GetAll from Object Wcobject To get all Order.
but raise Exception : The value 'total' cannot be parsed as the type 'Int32'
My Version is WooCommerce version : 3.5.5
[Screenshot WooCommerce version ](https://www.mediafire.com/convkey/094b/mxk7rk7oi2ld7xqzg.jpg?size_id=5)

also i check All Previous Issues :1 plase see screen shot
[Previous Issues check by me](https://www.mediafire.com/convkey/48b8/82hnkidd7nxng24zg.jpg)

this problem for 2017 year !
but now check all wc-order-*.php in my host all deleted and insertion good and new
no problem
please help me
thx

**Comment by adelhoss** [comment]
I set True the Property Debug And Get Json 
I use validator online : https://jsonformatter.org/
and my json is Valid .
download my json file from this link :
[Download My Json Debug Txt File](https://www.mediafire.com/file/9pnotni9yadozgm/json.txt/file)

**Comment by adelhoss** [comment]
I Used : jsonDeserializeFilter
```
        string trimstr(string json)
        {
            string deb= json.Replace("\"total:\"\"\"", "\"total:\"\"0\"");
            return deb;
        }
```

`                RestAPI rest = new RestAPI("https://XXXXXXXXX/wp-json/wc/v3/", "XXXXXXX", "XXXXX",requestFilter:request,jsonDeserializeFilter:trimstr);`

but no Change .
please Help Thx .

**Comment by adelhoss** [comment]
Please help i can not solve this problem 
. Thx .

**Comment by XiaoFaye** [comment]
Please give me some time, I'm working on it.

**Comment by XiaoFaye** [comment]
This value in your json string:
![image](https://user-images.githubusercontent.com/6334728/74111567-6f557480-4bfa-11ea-8fa2-6707de2b769e.png)
doesn't match the definition of TaxItem:
![image](https://user-images.githubusercontent.com/6334728/74111574-8ac07f80-4bfa-11ea-9755-b969ef59f0bf.png)

In the trimstr function, just replace `{"id":"total","total":[],"subtotal":""}` with empty string and then it will work.
![image](https://user-images.githubusercontent.com/6334728/74111590-c0656880-4bfa-11ea-9af2-3cfb7f04e896.png)

**Comment by adelhoss** [comment]
I Test And Post Result .
Thank you very Much .

**Comment by adelhoss** [comment]
Problem Solved . Thankssssss .
God bless you .
