### ISSUE TITLE
Product Variations

### ISSUE THREAD

**Issue by jmargel74** [XiaoFaye/WooCommerce.NET#432]
Using vb.net to create a master-child datagrid to list all the products.  I have it listing all the products, however I need the variations to be a child of the parent and along with the description, price, etc.. 

The variations only show the id number.  How would I first be able to put this as a child of a parent and second obtain all the other information related to that variation?
`Dim baseUrl = My.Settings.URL
            Dim key = My.Settings.WC_Key
            Dim secret = My.Settings.WC_Secret

            Dim rest As RestAPI = New RestAPI(baseUrl, key, secret, False)
            Dim wc As WCObject = New WCObject(rest)
            Dim tableSummaryRow1 As New GridTableSummaryRow()
            Dim summaryColumn1 As New GridSummaryColumn()
            gridType = "Products"
            SfDataGrid1.DataSource = Nothing
            SfDataGrid1.Refresh()

            lblStatus.Text = "Checking Orders.."

            clearGrid()
            childGrid.Columns.Clear()

            SfDataGrid1.AutoGenerateColumns = False

            Dim dic As Dictionary(Of String, String) = New Dictionary(Of String, String)()
            dic.Add("per_page", "100")
            Dim pageNumber As Integer = 1
            dic.Add("page", pageNumber.ToString())

            Dim products As List(Of Product) = New List(Of Product)()
            Dim endWhile As Boolean = False

            While Not endWhile
                Dim productsTemp = Await wc.Product.GetAll(dic)

                If productsTemp.Count > 0 Then
                    products.AddRange(productsTemp)
                    pageNumber += 1
                    dic("page") = pageNumber.ToString()
                Else
                    endWhile = True
                End If
            End While

            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.MappingName = "name", .HeaderText = "Item Name"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.MappingName = "sku", .HeaderText = "SKU"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.MappingName = "stock_quantity", .HeaderText = "Stock Quantity"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.MappingName = "price", .HeaderText = "Price"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.MappingName = "categories[0].name", .HeaderText = "Categories"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.HeaderText = "Length", .MappingName = "dimensions.length"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.HeaderText = "Height", .MappingName = "dimensions.height"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.HeaderText = "Width", .MappingName = "dimensions.width"})
            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.HeaderText = "Weight (oz.)", .MappingName = "weight"})

            Me.SfDataGrid1.Columns.Add(New GridTextColumn() With {.HeaderText = "ID", .MappingName = "id"})

            SfDataGrid1.AutoSizeColumnsMode = AutoSizeColumnsMode.Fill

            Me.SfDataGrid1.DataSource = products`

**Comment by XiaoFaye** [comment]
You will need to call `Product.Variations.Get(id)` to get the details of variations .
