### ISSUE TITLE
Coupon is lost on Order.Update()

### ISSUE THREAD

**Issue by bomyras** [XiaoFaye/WooCommerce.NET#433]
Wordpress version: 5.3.2
WooCommerce version: 3.9.2 
WooCommerce.NET version: 0.8.0.0
Relevant plugins: WooCommerce Smart Coupons 4.5.5

1) I have a pending order with a coupon of type percentage discount, with a value of 40%.
![image](https://user-images.githubusercontent.com/2385184/74998078-0f5f9900-5458-11ea-8521-961c04774a3c.png)

2) I load the order using WooCommerce.NET:
![image](https://user-images.githubusercontent.com/2385184/74998164-4766dc00-5458-11ea-865e-78d3388a5291.png)

After loading the order, I can see the coupon is loaded:
![image](https://user-images.githubusercontent.com/2385184/74998340-c825d800-5458-11ea-8180-e0228adaf141.png)

Coupon data:
`{{
  "id": 988,
  "code": "ritas40",
  "amount": "40",
  "date_created": {
    "date": "2019-10-16 17:32:23.000000",
    "timezone_type": 1,
    "timezone": "+00:00"
  },
  "date_modified": {
    "date": "2019-10-16 17:32:23.000000",
    "timezone_type": 1,
    "timezone": "+00:00"
  },
  "date_expires": null,
  "discount_type": "percent",
  "description": "",
  "usage_count": 23,
  "individual_use": false,
  "product_ids": [],
  "excluded_product_ids": [],
  "usage_limit": 0,
  "usage_limit_per_user": 0,
  "limit_usage_to_x_items": null,
  "free_shipping": false,
  "product_categories": [],
  "excluded_product_categories": [],
  "exclude_sale_items": false,
  "minimum_amount": "",
  "maximum_amount": "",
  "email_restrictions": [],
  "virtual": false,
  "meta_data": []
}}`

3) I set the order status to "complete":
![image](https://user-images.githubusercontent.com/2385184/74998209-6b2a2200-5458-11ea-9e44-134ea0036a16.png)

4) I add some meta data on the order:
![image](https://user-images.githubusercontent.com/2385184/74998259-9a409380-5458-11ea-80bd-a71df4ff12f0.png)

5) I update the order:
![image](https://user-images.githubusercontent.com/2385184/74998635-89dce880-5459-11ea-88be-96a4a50998b3.png)

6) The order is updated successfully, but when inspecting wo = ot.Result, I can see the _coupon_lines_ is empty:
![image](https://user-images.githubusercontent.com/2385184/74998675-a711b700-5459-11ea-8705-e101dd9fd3e9.png)
The WooCommerce order no longer have the coupon, and in woocommerce the order is with full value without any discount.

**Comment by bomyras** [comment]
When WooCommerceNET.WooCommerce.v2 it works fine.

**Comment by XiaoFaye** [comment]
If you only update the order status, without the meta data, will that happen?

**Comment by IcuScc** [comment]
Hi to all. 
I have the same problem. I will try using V2...
but i think it is need to review V3 this bug.

Thanks to all.

**Comment by IcuScc** [comment]
Hi. I try to using V2 and works OK.
I hope in V3 are solved soon.
