### ISSUE TITLE
Error add media file

### ISSUE THREAD

**Issue by hptung** [XiaoFaye/WooCommerce.NET#435]
Hi there
- Wordpress version: 5.3.2
- WooCommerce version 3.9.2
- WooCommerce.NET version 0.8.1

I have problem when i upload media file with code.
Media media = await wp.Media.Add("testimage.jpeg", @"D:\Document\Source.SVN\ConnectWoocommerce\ConnectWoocommerce\bin\Debug\image\1.jpeg");
Then I get error '{"code":"json_oauth1_signature_mismatch","message":"OAuth signature does not match","data":{"status":401}}'
I use WP REST API - OAuth 1.0a Server.
Do you have any way for fix that problem.
Thank you.

**Comment by XiaoFaye** [comment]
Can you try JWT Auth? I think OAuth has issue with upload.

**Comment by hptung** [comment]
@XiaoFaye thanks for your respone.
I fixed it with change header request. httpWebRequest.Headers["Authorization"] = "Bearer " + JWT_Object.token;
