### ISSUE TITLE
Adding Variations to existing product (v3)

### ISSUE THREAD

**Issue by Alessandro-4EYES** [XiaoFaye/WooCommerce.NET#436]
Hi,

I'm trying to add new variations to an existing variable product (using WooCommerceNET.WooCommerce.v3), but when the variation is added, it is not linked to the attribute (size).
Same issue as #378 (but no solution posted).

![image](https://user-images.githubusercontent.com/60977153/76146559-18757a80-6094-11ea-8024-44fe93a21343.png)

I followed the examples that were given in [#114 ](https://github.com/XiaoFaye/WooCommerce.NET/issues/114) and other posts, but no success.

Here is the used code:

               // Add Attribute
               List<ProductAttributeLine> attribsList = product.attributes;
               var sizeoptions = new List<string>();
               sizeoptions.Add("36");

                attribsList.Add(new ProductAttributeLine()
                {
                    name = "size",
                    id = 2,
                    variation = true,
                    visible = true,
                    options = sizeoptions
                });
                product.attributes = newattribsList;
                await wc.Product.Update(product.id.Value, product);

                // Add Variation
                List<VariationAttribute> vatrib = new List<VariationAttribute>()
                {
                    new VariationAttribute() {  name="size", option= "36" }
                };

                Variation var1 = new Variation()
                {
                        regular_price = "130",
                        attributes = vatrib,
                        stock_quantity = 5,
                        manage_stock = true,
                        sku = "variationsku00001"
                };
                    
                Variation vr = await wc.Product.Variations.Add(var1, prodWrite.id.Value);
                product.variations.Add(vr.id.Value);
                
                await wc.Product.Update(product.id.Value, product);

**Comment by XiaoFaye** [comment]
I think you need to pass attribute ID in vatrib.

**Comment by Alessandro-4EYES** [comment]
Thanks! That was indeed the issue.

**Comment by mcupryk** [comment]
Hi @Alessandro-4EYES m can you paste your solution here?
Thanks.

**Comment by dmainmon** [comment]
> attribute

Can you please post a solution?

**Comment by dmainmon** [comment]
> I think you need to pass attribute ID in vatrib.

Anytime I specify an id when adding a Variation Attribute (or anything really), nothing gets added. If I use 0 or omit the id, It gets added. 
The code below doesn't work (no error message, just doesn't add the Variation Attribute).
```
Variation newVariation = variant;
newVariation.attributes = new List<VariationAttribute>()
 {
      new VariationAttribute()
       {            
            id=99,          // THIS DOES NOT WORK          
           name="Options",
           option= Variants[count]
       }
 };
 var upVar = wc.Product.Variations.Update((ulong)variant.id, newVariation, Convert.ToUInt32(RecID));
```
        
The next section code adds works but there's no id or it's 0. Anything else and it never get's added.

```
Variation newVariation = variant;
newVariation.attributes = new List<VariationAttribute>()
 {
      new VariationAttribute()
       {                                
           name="Options",
           option= Variants[count]
       }
 };
 var upVar = wc.Product.Variations.Update((ulong)variant.id, newVariation, Convert.ToUInt32(RecID));
```
