### ISSUE TITLE
Could not create SSL/TLS secure channel .Net FrameWork 4.6.1 SecurityProtocolType.Tls12 not work

### ISSUE THREAD

**Issue by adelhoss** [XiaoFaye/WooCommerce.NET#437]
Hello My Friend I Use Latest Version Library : WooCommerce.NET 0.8.1
Wordpress Version Is : 5.2.5
WooCommerce Version Is : 3.7.1

I Wrote Simple Code To Test :
```
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ServicePointManager.DefaultConnectionLimit = 9999;
            try
            {
                RestAPI rest = new RestAPI("https://www.kharidketab24.ir/wp-json/wc/v3/", "ck_XXXXXXXXXXXXX00a6129a59b956c92f23b28", "cs_XXXXXXXXXXX1e1eea6e6bcdd3a6380a41619");
                WCObject wc = new WCObject(rest);
                List<Product> products = wc.Product.GetAll().GetAwaiter().GetResult();
                int y = 0;
            }
            catch(Exception ex)
            {
                string i = ex.ToString();
            }
```
Please See Screen Shot My Exception 
[Exception RunTime ScreenShot](https://www.mediafire.com/convkey/2a20/qu3rueirjftpwhxzg.jpg)

**Comment by adelhoss** [comment]
My sslab Teest 
https://www.ssllabs.com/ssltest/analyze.html?d=www.kharidketab24.ir
My WebSite Support Tls 1.2 .
But Expection raise why ?

**Comment by geri1983** [comment]
Same probleme for me.
I've modified my code version:
In WooCommerceNet.RestAPI

public async Task<string> SendHttpClientRequest<T>(string endpoint, RequestMethod method, T requestBody, Dictionary<string, string> parms = null)
        {
            HttpWebRequest httpWebRequest = null;
            try
            {
ADDED THIS LINE:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;


recompiled, and now it's working again
Hope helps.

**Comment by XiaoFaye** [comment]
@geri1983 @adelhoss , you might be able to use webRequestFilter to add the extra line for TLS 1.2, no need to recompile the source code.

https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET

**Comment by adelhoss** [comment]
@XiaoFaye Please Guide For Your Description ...
thx

**Comment by adelhoss** [comment]
I change My Code To :
```
        private void RequestFilter(HttpWebRequest request)
        {
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            }
            catch (Exception)
            {

                throw;
            }
        }

        private void ResponseFilter(HttpWebResponse response)
        {
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            }
            catch (Exception)
            {

                throw;
            }
        }
                RestAPI rest = new RestAPI("https://kharidketab24.ir/wp-json/wc/v3/", "ck_5XXXXXXXXXXXXXXXXXXX956cXXXXXX23b28", "cs_XXXXXXXXXXXXXXXXX6e6XXXX80aX9",requestFilter:RequestFilter,responseFilter:ResponseFilter);
```
But No Change . Still Exception : Could not create SSL/TLS secure channel

**Comment by adelhoss** [comment]
Oh no after nine hour without reply 
😑😑😑

**Comment by geri1983** [comment]
We have got this information from our server hosting company:
(google translated text from hungarian to english)

"As of March 1, encryption under TLSv1.2 is not officially supported and poses a security risk, so software developers, browser developers, if they see encryption older than TLSv1.2 on a given server, will warn the user that the server is not secure.
Even if the old ciphers are active, they will not allow many times to connect.
In the last month we have received a lot of such notifications, in the light of which we have to manually change our servers where necessary.
We would like to apologize for any inconvenience this may cause and please upgrade your API to TLSv1.2 encryption.
Thank you for your understanding."


In my case, forced TLS1.2 code line solved this problem. As I mentioned above, in older post.

**Comment by adelhoss** [comment]
Thanks friend 
I tested with ssllab my server use tls 1.2
I see you post and tested and changed cide to tls 1.2 in my case no change .
Still exception ....
Could not create secure ....

**Comment by geri1983** [comment]
If you want / can, send me in private message your shop address and create for me a temporary key pair to test the communication with my software. Read only access is enough of corse.
igaz.gergo@gmail.com
You can delete the key after the test.

**Comment by adelhoss** [comment]
Please Check Your Email I Sended Read Api Key For You ...
I am Wating For you ...

**Comment by adelhoss** [comment]
@XiaoFaye Please Support an guide Me .........
I Need You Friend

**Comment by adelhoss** [comment]
I Solved This Problem ....
I Test My Application On Windows Server 2012 R2 Successfully Run .
But Exception When Run in Windows 7 : Could not create SSL/TLS secure channel
Solution Is :
1-First Setup Download and Install the Windows 7 SP1 Convenience Rollup :
https://www.catalog.update.microsoft.com/search.aspx?q=3177467
Download Package Based On Artitecture architecture x86 or x64
Install And Restart Then go to step 2
2-Download Convenience rollup update for Windows 7 SP1 and Windows Server 2008 R2 SP1
https://www.catalog.update.microsoft.com/Search.aspx?q=3125574
Enjoy .

**Comment by geri1983** [comment]
Thank you for sharing the information

best regards:
Igaz Gergely


adelhoss <notifications@github.com> ezt írta (időpont: 2020. márc. 12., Cs,
14:56):

**Comment by lonwabontsinde** [comment]
Error: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__44`1.MoveNext()


Getting above error

            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ServicePointManager.DefaultConnectionLimit = 9999;

            RestAPI rest = new RestAPI("https://www.site.co.za/wp-json/wc/v3/", WebConfigurationManager.AppSettings["consumerkey"], WebConfigurationManager.AppSettings["consumersecret"]);
                WCObject wc = new WCObject(rest);
