### ISSUE TITLE
Microsoft CSharp Runtime Binder

### ISSUE THREAD

**Issue by suhomlineugene** [XiaoFaye/WooCommerce.NET#44]
Hello. I have Microsoft CSharp Runtime Binder exception when try to get orders. Any thoughts how to fix this?

![image](https://cloud.githubusercontent.com/assets/13189289/19839138/8732b5d8-9ee5-11e6-8b99-f58ce611906d.png)

**Comment by XiaoFaye** [comment]
I don't think this has anything to do with the Wrapper or Woocommerce. You should be able to find an answer in Stackoverflow.

**Comment by suhomlineugene** [comment]
It highlight lines of GetOrders.

**Comment by suhomlineugene** [comment]
It crashes in Release mode. In debug all ok

**Comment by XiaoFaye** [comment]
what about other API like GetProducts?

**Comment by suhomlineugene** [comment]
Will try now.

**Comment by suhomlineugene** [comment]
Same thing with GetProducts

**Comment by XiaoFaye** [comment]
May have a look at few lines of your code?

**Comment by suhomlineugene** [comment]
yes

` public async void Inwork_down()
        {

            RestAPI rest = new RestAPI("http://simplegames.com.ua/wp-json/wc/v1/", "ck_9d64c027d2c5f81b8bed3342eeccc6d337be813d", "cs_60697b1e6cbdeb8d62d19e0765e339f8e3334754");
            WCObject wc = new WCObject(rest);
            //Get all products
            var orders = await wc.GetOrders(new Dictionary<string, string>() {
                          { "per_page", "100" }, { "status","processing"} }); // Dodelat filtr dlaya teh chto v  rabote


            string products = orders.ToFormattedJsonString();
            Debug.WriteLine(products);


            List<RootObject> rootObjectData = JsonConvert.DeserializeObject<List<RootObject>>(products);


            OrdersList = new List<RootObject>(rootObjectData);
            





        }`

**Comment by XiaoFaye** [comment]
can you try to comment the last 2 lines and see how it goes?

**Comment by suhomlineugene** [comment]
Will try now

**Comment by suhomlineugene** [comment]
Same thing

**Comment by XiaoFaye** [comment]
I recalled that you have been using the Wrapper for some time, how come the error appear now? Is there any environment change?

BTW:  I don't get this error on my side.

**Comment by suhomlineugene** [comment]
Is there any environment change?


Nope. 



Okay, maybe we will write php back-end for WooCommerce. And get JSON from it. Anyway, thank's.

You can close issue.
