### ISSUE TITLE
wc.Product.GetAll() Not Work

### ISSUE THREAD

**Issue by mirasolutions** [XiaoFaye/WooCommerce.NET#440]
Helloi have this code but not have any effect, no error and no product.
Any idea ?

static void Main(string[] args)
        {

            invio();

            
        }

private static async Task<string> invio()
        {
            RestAPI rest = new RestAPI("https://www.xxxx.com//wp-json/wc/v3/",   "xxxx", "xxxx");
            WCObject wc = new WCObject(rest);

            //Get all products
            try
            {
                var products = await wc.Product.GetAll();
            }
            catch (Exception)
            {

                throw;
            }

            return "ok";
        }

**Comment by jmargel74** [comment]
your url should only have one slash after .com  and here is an example of how I do it.  You need to use a list.

` 
 Dim productslist As List(Of Product) = New List(Of Product)()
Dim dic As Dictionary(Of String, String) = New Dictionary(Of String, String)()
            dic.Add("per_page", "100")
            Dim pageNumber As Integer = 1
            dic.Add("page", pageNumber.ToString())

            Dim endWhile As Boolean = False

            While Not endWhile
                Dim productsTemp = Await wc.Product.GetAll(dic)
                'Dim productsTemp = wc.Product.GetAll(dic)

                If productsTemp.Count > 0 Then
                    productslist.AddRange(productsTemp)
                    pageNumber += 1
                    dic("page") = pageNumber.ToString()
                Else
                    endWhile = True
                End If
            End While`

**Comment by mirasolutions** [comment]
Hello i have try with this code, but not work.
How i can verify if restapi work on my wordpress ?

private static async Task<string> invio()
        {
            RestAPI rest = new RestAPI("https://www.loriparostore.com/wp-json/wc/v3/",   "xxxx", "xxx");
            WCObject wc = new WCObject(rest);

            //Get all products
            try
            {
                List<Product> st = await wc.Product.GetAll();


            }
            catch (Exception)
            {

                throw;
            }

            return "ok";
        }

**Comment by XiaoFaye** [comment]
Are you sure you website has products?

**Comment by mirasolutions** [comment]
![api](https://user-images.githubusercontent.com/25934693/76688220-2b0b2900-662b-11ea-88d2-ddf1284c9117.jpg)
![prodotti](https://user-images.githubusercontent.com/25934693/76688221-2c3c5600-662b-11ea-9fa1-9f22da8674c3.jpg)

Yes i have, see in attachment

**Comment by XiaoFaye** [comment]
Could you please send me a pair of keys for testing?   xiaofaye(at)msn.com

**Comment by mirasolutions** [comment]
i have send you

**Comment by yarx1988** [comment]
Hello, everyone! I have a litle problem: var products = await wc.Product.GetAll() get only last 10 products, but i want to take all, What I must do?
With best regard, Evgeniy!

**Comment by giotab** [comment]
To pull all the products, you need to specify the page number. Or you increase the number of items per page.
I use the following code to pull all the orders, but it should also work for Product.
```c#
List<Order> allOrders = new List<Order>(); 
int page = 1, perPage = 20;
Dictionary<string, string> parameters = new Dictionary<string, string>
{
    { "per_page", perPage.ToString() }
};
bool hasResults = true;
while (hasResults)
{
    parameters["page"] = (page++).ToString();
    var orders = await wc.Order.GetAll(parameters);
    allOrders.AddRange(orders);
    hasResults = orders.Count == perPage;
}
