### ISSUE TITLE
Missing property in OrderShippingLine (instance_id)

### ISSUE THREAD

**Issue by daniel-andersson-ap** [XiaoFaye/WooCommerce.NET#441]
Wordpress version: 5.2.5
WooCommerce version: 3.7.0
WooCommerce.NET version: v0.8.1

WooCommerce made a change in 3.4 and splitted the method_id:instance_id that was previosly joined in same property with a : to separate them.
The have since "corrected" the issue with the missing instance_id and there is now an instance_id property so u can identify what instance of the method was used.

"shipping_lines": [   {
      "id": 3856,
      "method_title": "Local pickup",
      "method_id": "local_pickup",
      "instance_id": "8",
      "total": "0.00",
      "total_tax": "0.00",
      "taxes": [],
      "meta_data": [{ ... }]

Documentation is still missning it so its easy to miss:
https://woocommerce.github.io/woocommerce-rest-api-docs/#order-shipping-lines-properties

More information on the update here:
https://github.com/woocommerce/wc-api-dev/issues/113
https://github.com/woocommerce/woocommerce/issues/21116

// Regards Daniel

**Comment by XiaoFaye** [comment]
Thanks for letting me know, this will be fixed in the next release.

**Comment by daniel-andersson-ap** [comment]
Glad for any help i can provide.
Keep up the good work.

**Comment by XiaoFaye** [comment]
Hi, this has been fixed in the latest version 0.8.2.
