### ISSUE TITLE
datetime error on default category woocommerce 4.0

### ISSUE THREAD

**Issue by nturini-cascinanet** [XiaoFaye/WooCommerce.NET#442]
Hello i encounter this issue on my first woocommerce 4.0 installation

I think is a conversion problem by a wrong datetime in the images of default categories.

this is the errore that i received:
`Errore durante la deserializzazione dell'oggetto di tipo System.Collections.Generic.List 1[[WooCommerceNET.WooCommerce.v3.ProductCategory, WooCommerce.NET, Version=0.8.1.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Stringa non riconosciuta come valore DateTime valido.`

translation in english is something like that:
`Error during object deserializzation of type System.Collections.Generic.List 1[[WooCommerceNET.WooCommerce.v3.ProductCategory, WooCommerce.NET, Version=0.8.1.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. String not represents a valid DateTime value.`

This is a response from postman, you can see the wrong date_created_gmt and date_modified_gmt; all the default categories have this issue
![image](https://user-images.githubusercontent.com/62327651/76939821-66db1280-68f9-11ea-9126-69f2f19208e9.png)

**Comment by XiaoFaye** [comment]
Looks like this is a WooCommerce issue? In this case, you can implement DeserializeJSon and do a string replace to fix this issue manually.

**Comment by nturini-cascinanet** [comment]
Yes i think is a woocommerce issue but i can't manually deserialize because the reported error is generated by `wc.Category.GetAll()`

Is not a big problem in my case, deleting all the default categories it works, maybe you can catch this error on category deserialization
