### ISSUE TITLE
Attaching products to images

### ISSUE THREAD

**Issue by jmargel74** [XiaoFaye/WooCommerce.NET#443]
I don't know if I am doing this right and need some help.  I have the user select an image, which goes into a list and then upload to my website.  This works.  However the issue I am having is then attaching the product image to that product when I create it.  It creates the product but no image is associated with it.
Can you provide a small .NET example on how to attach that particular uploaded image to that product when it's created?

**Comment by XiaoFaye** [comment]
You just need to update the product with given image ids.
