### ISSUE TITLE
WooCommerceObject.Product.Reviews.GetAll(Product.Id) Gets 404

### ISSUE THREAD

**Issue by andyfmking** [XiaoFaye/WooCommerce.NET#444]
When I request for all reviews for a product by using 

`WooCommerceObject.Product.Reviews.GetAll(Product.Id)`

The request url gets wrong path which is unavailable.

- Wordpress version 5.3.2, WooCommerce version 3.9.3 and WooCommerce.NET version 0.8.1

- Steps to replicate the issue
Get Reviews by Product Id with method such as below
WooCommerceObject.Product.Reviews.GetAll(Product.Id) 

- Details of the error message
Gets 404 not found because its requesting at url /wp-json/wc/v3/products/{id}/reviews
instead I found this endpoint available at /wp-json/wc/v3/products/reviews?id={id}/

v2 has that endpoint structure available at url /wp-json/wc/v2/products/{id}/reviews but the library fails when using v2 endpoints.

Any work around this?

**Comment by XiaoFaye** [comment]
Hi, the API route of getting review has changed in WooCommerce API V3, I will need to make some changes, a new version will be released soon with this fix.

**Comment by XiaoFaye** [comment]
Hi, this has been fixed in the latest version 0.8.2.
