### ISSUE TITLE
401 Invalid timestamp

### ISSUE THREAD

**Issue by aunrela** [XiaoFaye/WooCommerce.NET#445]
Hi,

I just started getting the following error on a previously working setup. I believe Wordpress auto updated over the weekend and think this has brought on the problem.

> {'code': 'woocommerce_rest_authentication_error', 'data': {'status': 401}, 'message': 'Invalid timestamp.'}

WordPress version: 5.4
WooCommerce version: 4.0.1
WooCommerceNET version: 0.8.1

Rest documentation says caller and servers’ time zones must be the same.

Setting the PC’s clock to UTC resolves the issue. 
For a better fix I added the following Request Filter to the application

```
private void RequestFilter(System.Net.HttpWebRequest request)
        {
            request.Date = request.Date.ToUniversalTime();
        }
```
Not sure if this is an issue or just my own misconfiguration, but I figured I would post it incase anyone else has this problem.

**Comment by XiaoFaye** [comment]
Thanks for the information! This is very helpful for everyone.
