### ISSUE TITLE
401 oauth signature mismatch

### ISSUE THREAD

**Issue by markuznw** [XiaoFaye/WooCommerce.NET#448]
Hello, maybe it is a stupid question but just wanted to ask if someone is having issues out of nowhere on a working install where all that changed are maybe wordpress / plugins updates.

I'm using nginx 1.17 and since like a week I'm having issues with oauth1.0 signature not matching. I also tried to regenerate token and token secret more than 10 times using the link in the wiki but it still keeps giving me issues.

Got any idea on what it can be / i need to check?

Any help would be appreciated as I'm getting crazy on this. Woocommerce auth works completely fine so I can get / add / update items in woocommerce but cannot touch anything about media (because it's done by wordpress rest apis using oauth1.0). I also tried to switch to jwt, but that never worked giving malformed headers (i guess it's due to nginx maybe?)

**Comment by XiaoFaye** [comment]
Have you tried to change the AuthorizeHeader value?

**Comment by markuznw** [comment]
Thanks, I've tried setting it to false but the same issue occurs with both oauth1.0 and jwt :(

**Comment by markuznw** [comment]
@XiaoFaye Ok i found out the fix for jwt. I have to use authorizeheader set as false and also make sure that jwt secret is NOT at the end of wp-config file but before including settings as stated here:

https://github.com/Tmeister/wp-api-jwt-auth/issues/59

If you can add both things to docs i guess they will be useful to a lot of users!
Thanks for help <3

It's now working fine on jwt + nginx :)
