### ISSUE TITLE
added_by_user in OrderNote Object

### ISSUE THREAD

**Issue by negapo** [XiaoFaye/WooCommerce.NET#451]
Hi, there are two fields in the OrderNote object called added_by_user (boolean) and author (string). Any chance we can add them? Thanks

**Comment by XiaoFaye** [comment]
Hi, thanks for letting me know, this  will be added  in version 0.8.2.

**Comment by XiaoFaye** [comment]
Hi, this has been fixed in the latest version 0.8.2.
