### ISSUE TITLE
ProductCategory error on created with image

### ISSUE THREAD

**Issue by cbamultimedia** [XiaoFaye/WooCommerce.NET#452]
Test 1:
Create a productcategory within image its OK

Create a product within image its ok

Create a product with image its ok

Create a productcategory with image FAILED

`ProductCategoryImage CategoriaImagen = new ProductCategoryImage();

                            ResultadoSubirImagen = false;
                            //Si tenemos imagen la subimos
                            if (!string.IsNullOrWhiteSpace(Familia.Imgweb))
                            {
                                ResultadoSubirImagen = await ImagenSubirPorFTP(Familia.Imgweb);

                                if (ResultadoSubirImagen)
                                {
                                    //Obtenemos el nombre de la imagen
                                    NombreImagen = Familia.Imgweb.Substring(Familia.Imgweb.LastIndexOf(@"\") + 1);

                                    //Asignamos nombre
                                    CategoriaImagen.src = Configuracion.FTPUrl + NombreImagen;
                                    CategoriaImagen.alt = Familia.Nomfam;
                                }
                            }

                            //Campos de categoria
                            ProductCategory Categoria = new ProductCategory()
                            {
                                id = Familia.WooCommerceId,
                                display = "default",
                                parent = Familia.WooCommerceIdParent,
                                name = Familia.Nomfam,
                                description = Familia.Descr,
                                count = 0,
                                menu_order = 0,
                                slug = Familia.Slug
                            };

                            //Si hemos subido foto, la asignamos                            
                            if (ResultadoSubirImagen)
                                Categoria.image = CategoriaImagen;
                            

                            List<ProductCategory> categorias = await Woo.Category.GetAll();

                            //Creamos categoria
                            ProductCategory CategoriaCreada = await Woo.Category.Add(Categoria);`

I test more options of ProductCategoryImage , add id, name, etc and alwais failed

ERROR:
Se espera el estado 'Element'.. Se encontró 'Text' con el nombre '', espacio de nombres ''.
Expected status 'Element'. 'Text' found with name '', namespace ''.
WooCommerceNET.Base.WCItem`1.<Add>d__12.MoveNext()

**Comment by XiaoFaye** [comment]
Below code works fine for me:
![image](https://user-images.githubusercontent.com/6334728/79848007-9dcea780-8414-11ea-8426-146f43a011ea.png)

**Comment by cbamultimedia** [comment]
Thanks.

v2 it works

`WooCommerceNET.WooCommerce.v2.ProductCategoryImage();`

**Comment by andraschris** [comment]
thanks a lot.
