### ISSUE TITLE
Could not create SSL/TLS secure channel. Only Run from windows server 2008 r2

### ISSUE THREAD

**Issue by RBSystemService** [XiaoFaye/WooCommerce.NET#453]
Good Evening, 

i've create an vb.net application for sync my local db with a remote wordpress/woocommerce one.

All works fine if the application run under windows 10, if i try to execute the same application on windows server 2008 r2 foundation it don't work...

the remote wordpress/wc db are hosted on a web hosting, i haven't done any IIS configuration on the server.

what i can try to do for solve the problem ?

Thanks for the help

Luca

**Comment by XiaoFaye** [comment]
Windows Server 2008 R2 doesn't support new version of SSL/TLS secure channel, and your web server seems have the latest SSL/TLS version.
