### ISSUE TITLE
Getting all customers

### ISSUE THREAD

**Issue by carellot** [XiaoFaye/WooCommerce.NET#454]
- Wordpress version: 5.4
- Woocommerce.net version: 0.8.1

using:   
` var Customer = await wc.customer.GetAll();`

I do not receive all customers, only previously registered users. How can I also get those who have made a purchase without first identifying themselves?
Thanks!

**Comment by XiaoFaye** [comment]
You mean the customers that checkout as guest? Do you see them in Wordpress backend?

**Comment by carellot** [comment]
Exactly, purchases made by guest users.
when the order has been placed i can see this user in customers woocommerce section, but I can't get them through `var Customer = await wc.customer.GetAll();`
sorry for my torpidity with english.
Thanks !

**Comment by XiaoFaye** [comment]
Try to pass the role parameter as "all".

**Comment by carellot** [comment]
works perfectly with parameters, thank you very much.
```
   var param = new Dictionary<string, string>() {{"role","all"}};
   List<Customer> Lclient = Task.Run(() => v3.Customer.GetAll(param)).Result;
```
