### ISSUE TITLE
Create product in all shops

### ISSUE THREAD

**Issue by IcuScc** [XiaoFaye/WooCommerce.NET#458]
Hi friends.
I want create products in all shops with the same ID.
If i create the product by hand, i can get it. The same product, with the same ID in two shops.
but using the API i dont get it.

it is possible? How would it be?

Thanks a lot :-)

**Comment by XiaoFaye** [comment]
I think this is WooCommerce/Wordpress behavior, we don't have control over it.

**Comment by mirco261** [comment]
All products goes to wp_posts table in database.
To this table goes many others post types:
https://wordpress.org/support/article/post-types/

so if you want to have same ID for every product, you must have same ID for many others post types. And what would you do, when you get order from customer in one shop. Orders are in wp_posts table too.

So I think it is no possible.

**Comment by IcuScc** [comment]
Hi folks...
im so sorry. i'm confused. This topic is for prestashop not woocommerce.
Sorry
Best Regards
