### ISSUE TITLE
manage_stock and reviews_allowed not getting set

### ISSUE THREAD

**Issue by frodijo** [XiaoFaye/WooCommerce.NET#46]
version: 0.5.5.0

when i set those values:

wp.manage_stock = "true";
wp.reviews_allowed = false;

still the products get created with the default values in woocommerce.

![image](https://cloud.githubusercontent.com/assets/8365422/19944070/1019cb22-a132-11e6-99a5-8fa4f825efe6.png)

**Comment by XiaoFaye** [comment]
can you try to change the source code? change the data type of manage_stock from string to bool.
This is a known issue. #39

**Comment by frodijo** [comment]
that worked for me, thanks

**Comment by piotrgulbis** [comment]
Apologies for reviving this issue, but reviews_allowed is still not getting set... 

setting reviews_allowed = false; doesn't turn if off... is there something I'm missing?

**Comment by XiaoFaye** [comment]
It seems to be a WooCommerce issue, I have checked everywhere in the dll, can't find anything.

**Comment by piotrgulbis** [comment]
Thanks Xiao, I will have a look on the Woocommerce github if I can find anythere there.

**Comment by piotrgulbis** [comment]
FYI

Getting a fix in 2.6.10+
https://github.com/woocommerce/woocommerce/issues/12618

or you can just patch it yourself if you have access.
