### ISSUE TITLE
Website does't display of Variation

### ISSUE THREAD

**Issue by bungphe** [XiaoFaye/WooCommerce.NET#460]
I have created variation for the product as shown with my code:
           ` 
//Add product
            Product p = new Product()
            {
                name = "test product 26",
                description = "test product 26",
                price = 8.0M,
                sku = DateTime.Now.ToString("yyyyMMddHHmmss"),
                regular_price = 8.0M,
                type = "simple",
                short_description = "Make sure this fitsby entering your model number. HIGH - QUALITY FAN: 100 CFM exhaust fan quickly reduces humidity to prevent or eliminate fogged mirrors and manage moisture in bathrooms up to 95 sq.ft., so your vision will be clear and your surroundings will always be comfortable",
                //categories = productCategories,
                //images = productImages,
                //attributes = productAttributes,
                //default_attributes = default_attributes,

            };
            //assign to categories
            List<ProductCategoryLine> productCategories = new List<ProductCategoryLine>();
            productCategories.Add(new ProductCategoryLine
            {
                id = 16
            });
            p.categories = productCategories;
            //Add Images 
            List<ProductImage> productImages = new List<ProductImage>();
            productImages.Add(new ProductImage
            {
                src = "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg"
            });
            productImages.Add(new ProductImage
            {
                src = "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg"
            });

            productImages.Add(new ProductImage
            {
                src = "https://images-na.ssl-images-amazon.com/images/I/71kj0z2Cr0L._AC_SL1500_.jpg"
            });

            productImages.Add(new ProductImage
            {
                src = "https://images-na.ssl-images-amazon.com/images/I/61yhjB3BW0L._AC_SL1500_.jpg"
            });

            p.images = productImages;
            //create new product
            p = await wc.Product.Add(p);

            List<string> colors_options = new List<string>();
            colors_options.Add("Black");
            colors_options.Add("White");
            colors_options.Add("Red");
            colors_options.Add("Yellow");

            List<string> size_options = new List<string>();
            size_options.Add("X");
            size_options.Add("XS");
            size_options.Add("XM");
            size_options.Add("XL");

            List<ProductAttributeLine> productAttributes = new List<ProductAttributeLine>();
            productAttributes.Add(new ProductAttributeLine
            {
                id = 3,
                name = "color",
                position = 1,
                visible = true,
                variation = true,
                options = colors_options
            });
            productAttributes.Add(new ProductAttributeLine
            {
                id = 2,
                name = "size",
                position = 2,
                visible = true,
                variation = true,
                options = size_options
            });
            p.attributes = productAttributes;

            List<ProductDefaultAttribute> default_attributes = new List<ProductDefaultAttribute>();
            default_attributes.Add(new ProductDefaultAttribute
            {
                id = 3,
                name = "color",
                option = "Black",
            });

            default_attributes.Add(new ProductDefaultAttribute
            {
                id = 2,
                name = "size",
                option = "X",
            });
            p.default_attributes = default_attributes;

            p = await wc.Product.Update(p.id.Value, p);

            // Add Variation
            List<VariationAttribute> vatrib = new List<VariationAttribute>()
            {
                new VariationAttribute() { id= 3,  name="color", option= "Black" },
                new VariationAttribute() { id= 2,  name="size", option= "X" }
            };

            Variation var1 = new Variation()
            {
                regular_price = 8.0M,
                attributes = vatrib,
                stock_quantity = 5,
                manage_stock = true,
                sku = DateTime.Now.ToString("yyyyMMddHHmmss")
            };

            Variation vr = await wc.Product.Variations.Add(var1, p.id.Value);
            p.variations.Add(vr.id.Value);

            p= await wc.Product.Update(p.id.Value, p);
` 
![1](https://user-images.githubusercontent.com/4928996/81006758-3257f180-8e7a-11ea-9bd6-1b0ae0e49985.png)
But website does't show this:
![2](https://user-images.githubusercontent.com/4928996/81006823-561b3780-8e7a-11ea-8f45-782d7d754982.png)

Can everyone check for me if I'm wrong somewhere? Thanks everyone very much

**Comment by bungphe** [comment]
I checked and have found the reason is because the product does not update the variation.

This p= await wc.Product.Update(p.id.Value, p) command does't update variation for product.

**Comment by XiaoFaye** [comment]
`product.variations` is Read only, you shouldn't need the latest 2 lines of code.

Check #436

**Comment by bungphe** [comment]
> `product.variations` is Read only, you shouldn't need the last 2 lines of code.
> 
> Check #436

Thank XiaoFaye so much, I change type = "simple" -> variable, products was displayed. I also will try with your sugggest

**Comment by macupryk** [comment]
Hi Team. I am hitting the same issue. Can you please paste your solution. Much appreciated.
