### ISSUE TITLE
get Id Product with Id Variation?

### ISSUE THREAD

**Issue by OscarLate** [XiaoFaye/WooCommerce.NET#461]
Hi,

I need id of product but only have ID Of Variation. How can get Id Product with fast response ( with only id variation)? I know that can do products.getAll but this take several minuts.

Regards

**Comment by XiaoFaye** [comment]
You want to get IDs of all products?

**Comment by OscarLate** [comment]
For example, I have id_variant 303 and want know the id_product of this id_variant with one call to the api.

**Comment by XiaoFaye** [comment]
I don't see there is an easy way to do that.
