### ISSUE TITLE
Product DateTime Deserialization Issue

### ISSUE THREAD

**Issue by pradeep0102** [XiaoFaye/WooCommerce.NET#462]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
   Wordpress version : 5.4
   WooCommerce version : 4.0.1
   WooCommerce.NET : 0.8.2 and 0.7.9

- Steps to replicate the issue
   I hate synced the products already. Now to update the changes on WooCommerce when trying to get the product then getting deserialization issue.
  
   Code : 
   Task<Product> productTask = Task.Run(() => wc.Product.Get(item.WooCommerceId));
            productTask.Wait();
            var product = productTask.Result;   

- Details of the error message if there is any
   There was an error deserializing the object of type WooCommerceNET.WooCommerce.v3.Product. The DateTime represented by the string is not supported in calendar System.Globalization.GregorianCalendar.

at WooCommerceNET.RestAPI.DeserializeJSon[T](String jsonString)
   at WooCommerceNET.Base.WCItem`1.<Get>d__9.MoveNext()

Due to this my live website is down. Please help me to get this resolved.

**Comment by XiaoFaye** [comment]
Have you checked this #445 ?

**Comment by pradeep0102** [comment]
I have created a service to sync the data so not able to set that.
This is the data I am getting from api -
![image](https://user-images.githubusercontent.com/5467474/81274727-4fedac80-906e-11ea-8622-72bf508e563a.png)

Thanks.

**Comment by XiaoFaye** [comment]
I think it has something to do with your server Calendar setting, but I don't know what changes you have done that cause this issue.

**Comment by pradeep0102** [comment]
Yes.
It looks the date format issue is there on server side. This is fresh sync. I synced few days ago when no data was there. The it worked fine however now I want to update the details so it is giving issue.

For now I moved ahead by using workaround -

string trimstr(string json)
        {
            return json.Replace("0000-", "0001-");
        }

**Comment by XiaoFaye** [comment]
I see, that's a invalid date string, your solution should work fine.

**Comment by pradeep0102** [comment]
Yes. It did.

Thanks for your help.
