### ISSUE TITLE
Retrieve metadata complex json content

### ISSUE THREAD

**Issue by pablolp82** [XiaoFaye/WooCommerce.NET#464]
Hi XiaoFaye, 

Great work with this project!

I am using v0.8.0, over Wordpress 5.4.1 and WooCommerce 4.0.1.

I am trying to retrieve and create via RestApi coupons with a plugin metadata.

When I request a coupon, the json is like this:

`{"id":130678,
"code":"prueba_mm",
"amount":"0.00",
"date_created":"2020-05-08T06:50:51",
"date_created_gmt":"2020-05-08T05:50:51",
"date_modified":"2020-05-08T08:10:56",
"date_modified_gmt":"2020-05-08T07:10:56",
"discount_type":"fixed_cart",
"description":"",
"date_expires":"2020-08-20T23:00:00",
"date_expires_gmt":"2020-08-20T22:00:00",
"usage_count":0,
"individual_use":false,
"product_ids":[],
"excluded_product_ids":[],
"usage_limit":null,
"usage_limit_per_user":null,
"limit_usage_to_x_items":null,
"free_shipping":false,
"product_categories":[],
"excluded_product_categories":[],
"exclude_sale_items":false,
"minimum_amount":"0.00",
"maximum_amount":"0.00",
"email_restrictions":[],
"used_by":[],
"meta_data":[
	{"id":2291550,"key":"_acfw_excluded_coupons","value":[]},
	{"id":2291551,"key":"_acfw_schedule_start","value":"2020-05-08"},
	{"id":2291552,"key":"_acfw_schedule_start_error_msg","value":""},
	{"id":2291553,"key":"_acfw_schedule_expire_error_msg","value":""},
	{"id":2291554,"key":"_acfw_reset_usage_limit_period","value":"none"},
	{"id":2291555,"key":"_acfw_disable_url_coupon","value":""},
	{"id":2291556,"key":"_acfw_code_url_override","value":""},
	{"id":2291557,"key":"_acfw_success_message","value":""},
	{"id":2291558,"key":"_acfw_after_redirect_url","value":""},
	{"id":2291559,"key":"_acfw_enable_role_restriction","value":""},
	{"id":2291560,"key":"_acfw_usage_limit_reset_time","value":""},
	{"id":2291564,"key":"_acfw_bogo_deals","value":
		{"conditions":
			{"products":[
				{"product_id":"122674","label":"CALDO CASERO CARNE GALLINA BLANCA1 L (33934)"},
				{"product_id":"121961","label":"SOPA CREMA CHAMPI\u00d1ON GALLINA BLANCA 70 g (1169)"},
				{"product_id":"123920","label":"SOPA JARDINERA GALLINA BLANCA 77 g (5934)"},
				{"product_id":"122151","label":"SOPA SOPINSTANT COCID GALLINA BLANCA 45G (20506)"},
				{"product_id":"123928","label":"SOPA VERDURAS GALLINA BLANCA 56 g (5939)"}],
				"quantity":2},
		"deals":
			{"products":[
				{"product_id":"123920","label":"SOPA JARDINERA GALLINA BLANCA 77 g (5934)"},
				{"product_id":"123928","label":"SOPA VERDURAS GALLINA BLANCA 56 g (5939)"}],
			"quantity":1,
			"discount_type":"fixed",
			"discount_value":0.14},
			"conditions_type":"combination-products",
			"deals_type":"combination-products",
			"type":"repeat",
			"notice_settings":
				{"message":"",
				"button_text":"",
				"button_url":"",
				"notice_type":"global"}}},
	{"id":2291566,"key":"_acfw_apply_notification_message","value":""},
	{"id":2291567,"key":"_acfw_apply_notification_btn_text","value":""},
	{"id":2291568,"key":"_acfw_apply_notification_type","value":"notice"},
	{"id":2291570,"key":"slide_template","value":"default"},
	{"id":2291571,"key":"_wpb_vc_js_status","value":"false"},
	{"id":2291572,"key":"_acfw_cart_conditions","value":[]},
	{"id":2291573,"key":"_acfw_cart_condition_display_notice_auto_apply","value":""},
	{"id":2291574,"key":"_acfw_cart_condition_notice","value":
		{"message":"",
		"btn_text":"",
		"btn_url":""}},
	{"id":2291589,"key":"_thumbnail_id","value":"125765"}]`

But when I debug the generated Coupon object, the "_acfw_bogo_deals" metadata element don't have the json text, but I only get an {object} object, so, I can't do anything with that json metadata.

I am trying to recover it with a MetaValueProcessor method, but I don't know exactly how can I manage it.

Could you please show me how can I retrieve the json value of that metadata element?

**Comment by XiaoFaye** [comment]
I think the MetaValueProcessor document is clear enough, you might need help from senior developer.

**Comment by willherr** [comment]
I think the issue I closed is related to this one more closely. I have still having troubles after implementing MetaValueProcessor. I still get an empty {object} object value when I know the json is being returned correctly. I reference the MetaValueProcessor document, so I do not believe I missed a step. Shouldn't `value` be either a JArray or JObject so that I can do my "custom" MetaValue processing?

![image](https://user-images.githubusercontent.com/22281397/94990435-1a2fef80-054a-11eb-84ce-55c2c78c97e7.png)
