### ISSUE TITLE
Invalid signature message on second request (first request works fine)

### ISSUE THREAD

**Issue by audigex** [XiaoFaye/WooCommerce.NET#465]
- Wordpress version, WooCommerce version and WooCommerce.NET version
WP: 5.4.1
WC: 4.0.1
WC.NET: 0.8.2

- Steps to replicate the issue

            RestAPI rest = new RestAPI(apiUri, key, secret); // Confirmed to be working in Postman
            WCObject wc = new WCObject(rest);

    var productAttributes = await wc.Attribute.GetAll(); // This works
    var attributeID = productAttributes.Where(x => x.slug.ToLower() == "brand").First().id   
    var productAttributeTerms = await wc.Attribute.Terms.GetAll(attributeID); // This doesn't

- Details of the error message if there is any

'{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}'

What am I missing?

**Comment by XiaoFaye** [comment]
I can't replicate this issue. Could you try to skip the first line and hard-code attributeID, see how it goes?

**Comment by audigex** [comment]
Yeah the issue was that I wasn't passing a valid ID in - can I suggest that "invalid signature" probably isn't the right error to return here? It's confusing - I'd have expected something like a NullArgumentException to be thrown instead

**Comment by XiaoFaye** [comment]
The attributeID was passed as part of the request URL, checking if the id is valid is up to you.
