### ISSUE TITLE
'There was an error deserializing the object of type System.Collections.Generic.List.... Encountered unexpected character 'o'

### ISSUE THREAD

**Issue by audigex** [XiaoFaye/WooCommerce.NET#466]
There seems to be an issue when deserializing the request... but it appears to be valid JSON when I send a GET request to `/wp-json/wp/v2/media` using Postman and using the same key/secret

I've attached the Postman response (with references to my own website changed to mysite.com)

This only happens with Wordpress endpoints, WooCommerce endpoints are fine

Wordpress version, WooCommerce version and WooCommerce.NET version
WP: 5.4.1
WC: 4.0.1
WC.NET: 0.8.2

Steps to replicate the issue

```
var rest = new RestAPI(apiUri, key, secret);
var wp = new WPObject(rest);
var media = await wp.Media.GetAll();
// or
var media = await wp.Media.Get(54258);
```

I've also tried the below deserializefilter as suggested in another issue

```
new RestAPI(apiUri, key, secret, jsonDeserializeFilter: trimstr);
string trimstr(string json)
{
    return json.Trim(new char[] { '\uFEFF', '\u200B' });
}
```

Details of the error message if there is any

```
System.Runtime.Serialization.SerializationException: 'There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerce.NET.WordPress.v2.Media, WooCommerce.NET, Version=0.8.2.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. Encountered unexpected character 'o'.'

Inner exception:
XmlException: Encountered unexpected character 'o'.
```

[wp_response.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/4607175/wp_response.txt)

**Comment by XiaoFaye** [comment]
Is the attached json coming from Postman or your program?

**Comment by audigex** [comment]
The attached is from Postman, I’m not sure how I would retrieve it from my program

**Comment by audigex** [comment]
Apologies, I hadn't noticed the inner exception:

XmlException: Encountered unexpected character 'o'.

**Comment by XiaoFaye** [comment]
With jsonDeserializeFilter, you are able to set a break point and save the json string. Please attach that one.

**Comment by audigex** [comment]
"oauth_token and oauth_token_secret parameters are required when using WordPress REST API."

That explains it... the result is a string not a JSON object

However, I am definitely passing (valid) values for Key and Secret into the RestAPI constructor?

**Comment by XiaoFaye** [comment]
Have you checked this on the home page? Are you using JWT?

```cs

//using JWT
RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/jwt-auth/v1/token", "<UserName>", "<Password>");

//using OAuth
RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wp/v2/", "<Client_Key>", "<Client_Secret>");
rest.oauth_token = "<OAuth_Token>";
rest.oauth_token_secret = "<OAuth_Token_Secret>";

```

**Comment by audigex** [comment]
Ah, that's the issue - I missed that part: the WooCommerce part of the client works fine so it seemed that the authentication was okay with the key and secret
