### ISSUE TITLE
Consult for new created fields

### ISSUE THREAD

**Issue by siropa81** [XiaoFaye/WooCommerce.NET#467]
Good Morning,
I have created a new field, which is mandatory to enter when completing the order (it would be the tax identification number), but I do not know how to access it from the api and thus be able to search the client to know if it is created or not before manually entering an order from another application.

WooCommerceNET.0.8.1

Greetings and thank you

**Comment by XiaoFaye** [comment]
Try meta_data

**Comment by siropa81** [comment]
Thank you very much, I will try it.

**Comment by siropa81** [comment]
Good afternoon, I have been looking and that additional field is entered in the order metadata and not in the customer metadata, so in order to access this value, you would have to go through the customer's orders and take the data.
Wouldn't there be some way that that additional field (in my case tax information) was entered directly into the customer's metadata instead of the order's?

Sorry for my English.

a greeting

**Comment by siropa81** [comment]
Good,
I have been doing other tests and what I have verified is that in the metadata it appears as follows:

TPedido2.Result.meta_data | Count = 3 | 
TPedido2.Result.meta_data[2].id | 957
TPedido2.Result.meta_data[2].key | "_additional_wooccm0"
TPedido2.Result.meta_data[2].value | "22xxxyyy"

The name of the additional field that you had created does not appear as a key so it would be difficult to find. I have verified that the id, in this case 957, is different if another order is made, so I cannot use it for the field name

a greeting

**Comment by siropa81** [comment]
I just saw that really the id of the additional field is that key and the name that I put it is a tag that apparently I can't access.

In any case, since it cannot be accessed from the client but must be done from the orders, it would be all slower since first you would have to search for a client order and then take it from there the value of the additional field

I don't know if there will be a way to do it directly.
