### ISSUE TITLE
 Access to all clients

### ISSUE THREAD

**Issue by siropa81** [XiaoFaye/WooCommerce.NET#468]
Good afternoon,
I have multiple users / clients.
A user has placed an order but does not want to make a customer account, I also have an administrator and a customer who does not have any order.
Once I try to access all the clients, (in my case I have 3). I cannot get the administrator user (who has 2 orders) nor the client who did not want to become a user account. I can only get the user who is a customer and who does not have any orders.
Task<List<Customer>> clientesListado = wc.Customer.GetAll();

In the users section, only the administrator (who has 2 orders) and a customer who has no orders appear. In the woocommerce customers section if all 3 appear.

Thank you

**Comment by XiaoFaye** [comment]
Please check #454

**Comment by siropa81** [comment]
Ok, sorry, I haven't seen it.
I just looked at it and it is perfectly explained.
Regards, and thank you very much
