### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by frodijo** [XiaoFaye/WooCommerce.NET#47]
I am using this same solution on 3 different websites, and from the same method i randomly get:

{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

other times it is working fine,
i have verified that the url and keys are correct when this happens.

I cant reproduce this as it happens randomly

**Comment by frodijo** [comment]
seems to be when i call getproducts with sku parm for sku like this: CJ 120/130-190/220BL

**Comment by XiaoFaye** [comment]
all 3 websites are using http?

**Comment by frodijo** [comment]
Yes

Kv.
Fróði

On 3 Nov 2016, at 18:56, James Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


all 3 websites are using http?

-

**Comment by XiaoFaye** [comment]
Can you catch this error in your code and try to send your request again when getting this error?  I have the same issue when internet is slow, but try again will always work. Don't know why this is happening yet.

**Comment by frodijo** [comment]
i think the issue is always when i call a GetProducts

var parms = new Dictionary<string, string>();
parms.Add("sku", ProductSKU);

var prods = wc.GetProducts(parms).Result;


if i set ProductSKU to this sku: CJ 120/130-190/220BL it fails

**Comment by XiaoFaye** [comment]
try to HtmlEncode your ProductSKU.

**Comment by XiaoFaye** [comment]
Hi, there is a bug in the wrapper and I have released a beta version 0.5.6, could you please update and try again? Thanks.

**Comment by frodijo** [comment]
Hi thanks, but the beta version still has this line set to string when it should be bool
https://github.com/XiaoFaye/WooCommerce.NET/blob/master/WooCommerce/Product.cs#L244
