### ISSUE TITLE
Customers created via rest api are not shown in customers list in woocommerce

### ISSUE THREAD

**Issue by VeereshAngadi** [XiaoFaye/WooCommerce.NET#470]
WooCommerce version: V3
Steps to reproduce:
1. Create customer using WooCommerce.net library.
2. go to woocommerce store and login as admin.
3. navigate to woocommerce->customers.
4. Observe that it does not list any customers.

Note: i used woocommerce.net library to check existing customers, i can see the customers i created. Also the same customer is added in user with role as customer. Using same library i was able to create order also.

Am i missing any setting?

**Comment by XiaoFaye** [comment]
Please check #468
