### ISSUE TITLE
UpdateOrder causing meta data to be lost on order

### ISSUE THREAD

**Issue by Chris-Knowlson** [XiaoFaye/WooCommerce.NET#471]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version 4.9.13, WooCommerce version 3.5.1 and WooCommerce.NET version 0.8.1

- create variable product with selectable attributes. create an order containing the item. 
retrieve the item from woocommerce with 
Order order = wc.GetOrder(orderid).Result;
then use the retrieved order to Update with
string updateOrderResponse = wc.UpdateOrder((int)order.id, order).Result;
The selected variant attribute gets removed from the order. 

- no error message

**Comment by XiaoFaye** [comment]
Try to use UpdateWithNull

**Comment by Chris-Knowlson** [comment]
thanks for the fast response.

we are currently using the WooCommerceNET.WooCommerce.Legacy.WCObject. There isn't an UpdateWithNull on that.

Sorry for missing that in my first message i hadn't realised there were 4 versions of the wcobject

**Comment by XiaoFaye** [comment]
Sorry we don't support Legacy API anymore, please try to use the latest version.

**Comment by Chris-Knowlson** [comment]
ok. Thanks for your time.
