### ISSUE TITLE
Woocommerce API JWT

### ISSUE THREAD

**Issue by acerov** [XiaoFaye/WooCommerce.NET#478]
Is it possible to authenticate to Woocommerce API with JWT?

I am having problem to connect to Wordpress API and Woocommerce API with same .htaccess settings.

Both DO WORK but not at the same time with same .htaccess settings.
What settings I need for both APIs to work?

**Comment by XiaoFaye** [comment]
Woocommerce API will work when JWT is enabled, I have tested it without any problem, you might need to check your website/server configurations.

**Comment by acerov** [comment]
Can you please post your working .htaccess content, mine is:

`# BEGIN WordPress

RewriteEngine On

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]

# END WordPress`

When above .htaccess settings are in place WordPress API works, Woocomerce Api NOT.
When I comment these two lines, iti is the opposite.
`#RewriteCond %{HTTP:Authorization} ^(.*)
#RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`

**Comment by XiaoFaye** [comment]
I'm not using Apache, so I don't need this file. I think this issue ONLY happens when using Apache.

**Comment by XiaoFaye** [comment]
@acerov This link might be able to help you, https://wordpress.stackexchange.com/questions/283874/can-i-authenticate-with-both-woocommerce-consumer-key-and-jwt

**Comment by acerov** [comment]
> I'm not using Apache, so I don't need this file. I think this issue ONLY happens when using Apache.

after much frustration I switched from apache to nginx.
Result:
Wordpress API works as expected
Woocommerce API does NOT work, constantly giving error:
{"code":"jwt_auth_bad_auth_header","message":"Authorization header malformed.","data":{"status":403}}

Conclusion:
With Apache based on .htaccess settings I was able to alternate beetween Wordpress API and Woocommerce API, now under nginx just Wordpress API work.
I am unable to make Woocommerce API work with nginx

Pulling my hair out, please help

**Comment by XiaoFaye** [comment]
Hi, this is fixed in version 0.8.3.
