### ISSUE TITLE
Update product images

### ISSUE THREAD

**Issue by JM63** [XiaoFaye/WooCommerce.NET#48]
Hi,
I'm trying to update a product and in particular the images, using the following code:

               ImageList productImagesList = new ImageList();
               Image img = new Image()
               ...
               productImagesList.Add(img);
               img = new Image()
               ....
               productImagesList.Add(img);

                Product newP = new Product()
                {
                    sku = drArtigo["art"].ToString(),
                    slug = drArtigo["art"].ToString(),
                    name = drArtigo["Desig"].ToString(),
                    short_description = drArtigo["Desig"].ToString(),
                    description = drArtigo["Detalhes"].ToString(),
                    regular_price = drArtigo["PV"].toDecimal(),
                    sale_price = drArtigo["PV"].toDecimal(),
                    price_html = drArtigo["PV"].toDecimal().ToString("C2"),
                    in_stock = true,
                    categories = categoriesList,
                    images = productImagesList
                };
                int pid = (int)product.id;
                string json = await _wooObject.UpdateProduct(pid, newP);

But in the product remain the first images sent when the product creation. I take a look to the json string returned from the server and images source remains the old one, do not update to new source url send with product update.
What am I doing wrong?

**Comment by JM63** [comment]
Great confusion of mine, i was do get from remote server and post on localhost
Sorry...

**Comment by ironfly** [comment]
Do you happen to have the code you used to create the product, with an image?  I am struggling to make this work, really appreciate it.  THanks.

**Comment by sterenas** [comment]
@ironfly, did you manage to get the code to create a product with an image?  I've got it working just in case you still need it. 
Thanks,
Sergio

**Comment by cooltechgy** [comment]
@sterenas  please help me fix mind how do you add image?

**Comment by ironfly** [comment]
SUre, this is the function i ended up using - it is in VB.net.  you can yank out some of the extra stuff i have going on:

` 

Async Function addtowoo() As Threading.Tasks.Task


        Try
            
            Dim rest As RestAPI = New RestAPI("https://websiteaddress.com/wp-json/wc/v1/", "ck_d8eba14dc821d154c2ba51f8a6d80b7d5f037b67", "cs_5d87b9cb78213aee05794713a4701d898f9eeb73")
            '  consumer kjey first, then 
            Dim onsale As Boolean = False 'set to true to take 10%off

            Dim wc = New WooCommerce.WCObject(rest)
            Dim p As New WooCommerce.Product
            Dim sp As New specs
            Dim specs As String = sp.getspecs(buildid)
            Dim price As Decimal = sp.price
            Dim path As String = "https://bikebuilder.alliedcycleworks.com/buildimages/allied-" & buildid & ".jpg"
          
            p.name = "Product Name " & buildid
          
            Dim proddate As String = ""
            Dim saleprice As Decimal = 0.0
            Dim discount As Decimal = 0.0
            Dim productcategory As Integer = 142

          

            p.description = proddate & specs
            p.short_description = proddate & specs
            p.price = Decimal.Parse(price)
            p.regular_price = Decimal.Parse(price)

            p.sale_price = Decimal.Parse(saleprice)

           
            Dim catlist As New WooCommerce.CategoryList
            Dim c As New WooCommerce.Category
            c.id = productcategory
            catlist.Insert(0, c)
            p.categories = catlist



            Dim imagelist1 As New WooCommerce.ImageList
            Dim w As New WooCommerce.Image
            w.src = path
            w.position = 0

            imagelist1.Insert(0, w)
            p.images = imagelist1

            Dim r = Await wc.PostProduct(p)
            Dim s As String() = r.Split(":")
            s = s(3).Split(",")

            redir &= s(0).Replace("""", "")
           
        Catch ex As Exception
            Response.Write(ex.ToString)
        End Try
        'need to write to page in js to change href of parent page...
        js.Text = "<script>parent.location.href = '" & redir & "';</script>"
        '  Response.Redirect(redir)
    End Function
`

**Comment by cooltechgy** [comment]
Value of type 'ImageList' cannot be converted to 'List(Of
ProductImage)'.

**Comment by cooltechgy** [comment]
any help please

**Comment by sterenas** [comment]
Here's a quick sample:
        Dim rest As New WooCommerceNET.RestAPI(Web_BaseAddress, Web_CK, Web_CS)
        Dim wc As New WCObject(rest)

        Dim c As New List(Of ProductCategoryLine)
        Dim d As New ProductDimension With {.height = "10", .length = "11", .width = "12"}
        Dim img As New List(Of ProductImage)

        Dim cat0 As New ProductCategoryLine With {.name = "Category A"}
        c.Add(cat0)

        Dim atr As New ProductAttribute With {.name = "Size"}

        Dim img0 As New ProductImage With
            {
            .name = "WooDefaultImageName",
            .date_created = Now,
            .date_modified = Now,
            .src = "http://XXXXXX.com/images/DSC00204.jpg",
            .id = 0,
            .alt = "Alt Description for Image",
            .position = 0
            }
        img.Add(img0)

        Dim time As DateTime = Now()

        Try
            Dim p As New Product With
              {
                .sku = "SKU - " & time,
                .name = "Product - " & time,
                .description = "Description <b>Product</b> " & time,
                .short_description = "Short <I><B>Description</B></I> for Product " & time,
                .manage_stock = True,
                .backorders_allowed = False,
                .stock_quantity = 90,
                .date_on_sale_from = Today(),
                .date_on_sale_to = Today.AddDays(5),
                .weight = "800",
                .dimensions = d,
                .on_sale = True,
                .regular_price = 3000,
                .price = 100,
                .sale_price = 2470,
                .downloadable = False,
                .featured = True,
                .in_stock = True,
                .reviews_allowed = False,
                .images = img,
                .categories = c
            }

            Dim resp = Await wc.Product.Add(p)
            TextBox1.Text = "ID: " & resp.id & " - " & resp.description
        Catch ex As Exception
            Dim Data As Object = JsonConvert.DeserializeObject(ex.Message)
            TextBox11.Text = "Error coder - " & Data("code") & vbCrLf
            TextBox11.Text += "Message - " & Data("message") & vbCrLf
            TextBox11.Text += "Data - " & "Status: " & Data("data")("status") & " - " & "Resource ID: " & Data("data")("resource_id")
        End Try
