### ISSUE TITLE
Get all variations from all products 

### ISSUE THREAD

**Issue by NoamC1987** [XiaoFaye/WooCommerce.NET#481]
Hello,

First of all thank you very much for this great library. 

I would like to know  if there is a way to get all of the variations and product at once?. Instead of make loop for each product and get his variations. 

I appreciate if you can help me with that 

Thank you 🙏

**Comment by sterenas** [comment]
When you Get a product (by ID), the response has a collection called Variations that contains a list of all variations of that product Id.

**Comment by NoamC1987** [comment]
Thank you for your reply.

I would like to all of the details of the variation as well not only the id.

is there a way to get all variations at once without calling for each product variation separately? 

![image](https://user-images.githubusercontent.com/66224071/83386957-94adfe80-a3f4-11ea-8717-8acfb57fa832.png)

**Comment by XiaoFaye** [comment]
Try this: `wcObject.Product.Variations.GetAll(productID)`

**Comment by NoamC1987** [comment]
thank you for your reply, I did use the "GetAll". but only can be done for single product at once not all of the products together. 
is that correct?

thanks

**Comment by XiaoFaye** [comment]
With WooCommerce Rest API, Looping products is the only way.

**Comment by NoamC1987** [comment]
Ok got it thank you :).

and thanks again for this library
