### ISSUE TITLE
Add Category with image error

### ISSUE THREAD

**Issue by andraschris** [XiaoFaye/WooCommerce.NET#482]
First of all, Thanks for your library
I have this problem:
- Wordpress version:5.4.1, WooCommerce version: 4.1.0 and WooCommerce.NET version : 0.82

- Only when i am add category including image i am getting the error. The problem is image
[System.Runtime.Serialization He was met with an unexpected character 'Î'.]
The same code when i am adding product and image is ok!
When image missing all is ok.
This is data before call category.add
![Clipboard01](https://user-images.githubusercontent.com/32484308/83444249-cb673180-a453-11ea-8740-d56779a138f2.png)
And this is error
![Clipboard02](https://user-images.githubusercontent.com/32484308/83444342-ee91e100-a453-11ea-8e51-9d18e5e6c282.png)

**Comment by XiaoFaye** [comment]
Have you checked this ? #452

**Comment by andraschris** [comment]
I works! Thanks a lot.
