### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by hltyvz** [XiaoFaye/WooCommerce.NET#485]
Hello there. updating a product takes 8 seconds. this is a very long time. Is there a method to speed it up?

**Comment by XiaoFaye** [comment]
The speed depends on your network and webserver speed.

**Comment by hltyvz** [comment]
I am using 6x Cpu 8 Gb Ram vps. my wordpress and internet works fast. Is it normal to update the product in 8 seconds with this hardware?

**Comment by XiaoFaye** [comment]
Can you try to use Postman or other REST API tools and send the update request directly? See how is the speed with that.

**Comment by hltyvz** [comment]
It took 2.7 seconds to update a product with Postman.

**Comment by XiaoFaye** [comment]
It's better to post part of your code so we can identify the problem.

**Comment by hltyvz** [comment]
RestAPI rest = new RestAPI("***", "ck_***", "cs_***", false);
			WCObject wc = new WCObject(rest);
			Product p = new Product();
			p.name = item.İsim;
			p.sku = item.StokKodu;
			p.sale_price = item.İndirimliSatışFiyatı;
			p.regular_price = item.NormalFiyat;
			p.stock_status = "instock";
			p.status = "publish";
			p.stock_quantity = item.Stok;
			p.tax_status = "taxable";
			p.purchasable = true;
			List<ProductImage> productImages = new List<ProductImage>();
			productImages.Add(new ProductImage
			{
				src = item.Görseller
			});
			p.slug = item.ShopifyHead;
			p.images = productImages;
			var result = await wc.Product.Add(p);

**Comment by hltyvz** [comment]
I think the problem is related to my computer. After restarting, the product update fell to 2 seconds.
