### ISSUE TITLE
Product batch creation not returning errors

### ISSUE THREAD

**Issue by jacargentina** [XiaoFaye/WooCommerce.NET#489]
- Wordpress version, WooCommerce version and WooCommerce.NET version
wordpress: 5.4.2
woocommerce: 4.1.0
woocommerce.net: 0.8.2

- Steps to replicate the issue
1- Build a batch of 100 Products
2- Send the batch by calling `AddRange`
3- Resulting product.id are all 0 because of errors, which i cant get back!

There error is basically, duplicated sku's

Somehow the result should be a different structure for the errors. Look here.

https://github.com/woocommerce/woocommerce/blob/86f59dff09529c52beead45e01e4b59f014c6040/includes/legacy/api/v3/class-wc-api-products.php#L3087

**Comment by XiaoFaye** [comment]
Have you tried with less product?

**Comment by jacargentina** [comment]
@XiaoFaye all 23 products in that batch where already on WC, so all of them had `product.id = 0` and i (and final user too) have no indication of the problem.

I insist on this: ideally the result should be a different structure for the errors, or having some mechanism to get that error (actually WC returns errors, but i cant see them via the API)

**Comment by jacargentina** [comment]
@XiaoFaye Maybe #340 is the solution to this?
