### ISSUE TITLE
authentication_error when using "before" or "after" criterion on WC.GetOrders(...)

### ISSUE THREAD

**Issue by wkaper1** [XiaoFaye/WooCommerce.NET#49]
If I call the WCObjects "GetOrders" method with either the "after" parameter or the "before" parameter then I get an Authentication Exception that says the signature is not valid.
For instance if I do the following, I get the exception:

            OrderList ol = await WcObject.GetOrders(new Dictionary<string, string>()
            {
                ["after"] = new DateTime(2016, 9, 30).ToString("yyyy-MM-ddThh:mm:ss"),
            });

When I do this, I also get the exception:

            OrderList ol = await WcObject.GetOrders(new Dictionary<string, string>()
            {
                ["before"] =  new DateTime(2016, 10, 30).ToString("yyyy-MM-ddThh:mm:ss"),
            });

Many other combinations of parameters work correctly, for instance:

            OrderList ol = await WcObject.GetOrders(new Dictionary<string, string>()
            {
                ["status"] = "processing",
                ["context"] = "view",
                ["per_page"] = "100"
            });

This gives me a valid list of orders.
Therefore I think there cannnot be anything wrong with my credentials. If something was wrong, all requests should fail, I guess? 
How can I fix it? Being able to select on DateTime is a bit essential.
(I am on version 0.5.5)

**Comment by XiaoFaye** [comment]
Hi, there is a bug in the wrapper and I have released a beta version 0.5.6, could you please update and try again? Thanks.

**Comment by wkaper1** [comment]
Yes, the "before" and "after" parameters can be used now. Thanks!
