### ISSUE TITLE
Product.GetAll() returns only 10 last items

### ISSUE THREAD

**Issue by p1zza** [XiaoFaye/WooCommerce.NET#491]
hi! Func wc.Product.GetAll() returns 10 last items of the WooCommerce Products. How can i configure it? Code below: 

`List<Product> products = await wc.Product.GetAll();`

**Comment by XiaoFaye** [comment]
Check here: https://github.com/XiaoFaye/WooCommerce.NET/issues/440#issuecomment-614215024
