### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by hltyvz** [XiaoFaye/WooCommerce.NET#494]
Hello there.
I share my product installation code below. When I run this code, there is no response after the request is made. Is there anything wrong here? When I do it with Postman, the request is completed within 3-4 seconds and the response comes. When I look at the server logs, I see the error "(70007) The timeout specified has expired: AH01075: Error dispatching request to:". How can I fix this problem? It loaded 120,000 products without problems, but later began to cause problems.

public async Task<int> UrunYukle(WoModel item)
		{
			RestAPI rest = new RestAPI("https://..../wp-json/wc/v3/", "....", "....", true);
			WCObject wc = new WCObject(rest);
			Product p = new Product();
			p.name = item.İsim;
			p.sku = item.StokKodu;
			p.sale_price = item.İndirimliSatışFiyatı;
			p.regular_price = item.NormalFiyat;
			p.stock_status = "instock";
			p.manage_stock = true;
			p.status = "publish";
			p.stock_quantity = item.Stok < 4 ? 5 : item.Stok;
			p.tax_status = "taxable";
			p.purchasable = true;
			List<ProductImage> productImages = new List<ProductImage>();
			productImages.Add(new ProductImage
			{
				src = item.Görseller
			});		
			p.slug = item.ShopifyHead;
			p.images = productImages;
			p.reviews_allowed = false;
			var result = await wc.Product.Add(p);
			return Convert.ToInt32(result.id);
		}

**Comment by XiaoFaye** [comment]
Some web servers block post requests for security reason. Have you tried to get products?

**Comment by hltyvz** [comment]
getting product is working. I have tried something now. if images are null, the code works.

**Comment by XiaoFaye** [comment]
Maybe the image is too big to post to the web server? try a small image, like 5KB size, if still not working, your web server might be blocking file uploading.

**Comment by hltyvz** [comment]
I tried small size and it took 30 seconds. I think the problem is server-side but I don't know how to solve it.

**Comment by XiaoFaye** [comment]
I think it's better to contact your server provider.

**Comment by hltyvz** [comment]
You are right. Thank you for your interest.
