### ISSUE TITLE
WooCommerce.NET 0.8.2 Can not install on .net framework 4.5

### ISSUE THREAD

**Issue by HarshaMadu** [XiaoFaye/WooCommerce.NET#499]
### Make sure you have included the below details when open an issue. Thank you.

hi

I'm try add WooCommerce.NET 0.8.2  to visual studio 2015.
following error has occur please advice me

ould not install package 'WooCommerceNET 0.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.

you Immediate response is highly appreciate 
Thank you

**Comment by XiaoFaye** [comment]
Not, it does not support .NET Framework 4.5.

**Comment by HarshaMadu** [comment]
Can you please suggest me the support framework

**Comment by XiaoFaye** [comment]
Minimum is .NET Framework 4.6.1

**Comment by Rahim373** [comment]
Can you please downgrade the support for .NET Framewwork 4.5? I'm using this in a project and it's not possible to update the version.
