### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by Jen143** [XiaoFaye/WooCommerce.NET#50]
I am using v1 and when i tried to get orders, I have this error:

```
RestAPI rest = new RestAPI(_cred.Url, _cred.ConsumerKey, _cred.ConsumerSecret);
WooCommerceNET.WooCommerce.Legacy.WCObject wc = new WooCommerceNET.WooCommerce.Legacy.WCObject(rest);
Task<WooCommerceNET.WooCommerce.Legacy.OrderList> task = System.Threading.Tasks.Task.Run(() => wc.GetOrders());
 var response = task.GetAwaiter().GetResult();
```

> {"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

But i was able to get the orders using Postman with this URL: 
http://xxx.com/wc-api/v3/orders?oauth_consumer_key=ck_xxx41a3dd1d4b0b9b519c96d8fe621d783cd12xx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1478511461&oauth_nonce=Q68pPF&oauth_version=1.0&oauth_signature=9bdz2m6oCFiqoTIHU70PHdifKhU=

What could be the possible cause of this one? Thanks

**Comment by XiaoFaye** [comment]
You were saying that you are using v1, but in the Postman url, it is v3, am I missing anything here?

**Comment by Jen143** [comment]
The woocommerce version is 4.61 so it must be v1 but then when I tried to request through postman, I've always get error with I used this : http://www.xxxx.com.au/wc-api/v1/orders?oauth_consumer_key=ck_xxxxxa3dd1d4b0b9b519c96d8fe621d783cd1200&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1478573379&oauth_nonce=zOkF9o&oauth_version=1.0&oauth_signature=a5gbM1dJqmXZkvQTFHaxWuc7qkA=

"errors": [
    {
      "code": "woocommerce_api_authentication_error",
      "message": "Invalid Signature - provided signature does not match"
    }

But when I tried to v3, I can get the orders:

http://xxx.com.au/wc-api/v3/orders?oauth_consumer_key=ck_xxxxxa3dd1d4b0b9b519c96d8fe621d783cd1200&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1478573032&oauth_nonce=BQk8ZM&oauth_version=1.0&oauth_signature=t7orOe9ZYwmY1kGoDFlutBiGvDM=


In your wrapper, I have tried to use the v1 and  v3 but I still got same error. I have tried to remove the www and use the v3 but got same error.

**Comment by XiaoFaye** [comment]
Please try this: http://www.xxxx.com.au/wp-json/wc/v1/orders?xxxxxxxxxxxxxx

**Comment by XiaoFaye** [comment]
Hi @Jen143 ,

There is a new version 0.6.0 on the Nuget, could you please try the new version and see if the problem solved?
