### ISSUE TITLE
Add attributs in Product

### ISSUE THREAD

**Issue by hakimloup21** [XiaoFaye/WooCommerce.NET#501]
Hi , when I create the attribute for the product from the API, the attribute does not appear on the page, so I have to refresh the publication for the product manually please any help? 
![git1](https://user-images.githubusercontent.com/16979965/87807700-e0a7ec00-c858-11ea-985c-f7bd0f227937.png)
![git2](https://user-images.githubusercontent.com/16979965/87807702-e1d91900-c858-11ea-98d3-bfd5d5d45a9a.png)

**Comment by XiaoFaye** [comment]
So it shows up after you refresh?

**Comment by hakimloup21** [comment]
yes

**Comment by hakimloup21** [comment]
before refresh publication :
![image](https://user-images.githubusercontent.com/16979965/88174378-7b6f4480-cc24-11ea-915c-67a31c527b81.png)

After : 
![image](https://user-images.githubusercontent.com/16979965/88174551-c12c0d00-cc24-11ea-9900-1634a06bb4dd.png)
