### ISSUE TITLE
401 woocommerce_rest_cannot_create after change HTTP to HTTPS

### ISSUE THREAD

**Issue by igorryko** [XiaoFaye/WooCommerce.NET#503]
Hi all

A customer paid for us to develop integration with Woocommerce, and we use the Woocommerce.NET library with success.

But, when the e-commerce goes to production environment, our customer changes to HTTPS. 

After this, all requisition returns 401 with message: Sorry, You Are Not Allowed to Access This Page

We use like this to upload a category, for example:

`        public async Task<int> UploadCategory(CategoryModel categoryModel)
        {
            var rest = new RestAPI(configuration["woo_commerce:base_url"], configuration["woo_commerce:consumer_key"], configuration["woo_commerce:secret_key"]);
            var wc = new WCObject(rest);

            var category = await wc.Category.Add(new ProductCategory { name = categoryModel.name });
            return category.id.Value;

        }`

With Postman, works fine.

![image](https://user-images.githubusercontent.com/52142487/89365011-244c8380-d6aa-11ea-91af-3e93219acf75.png)

**Comment by XiaoFaye** [comment]
Have you tried to change the value of authorizedHeader in RestAPI?

**Comment by igorryko** [comment]
XiaoFaye, thank you so much!

I change to false and went back to working.
