### ISSUE TITLE
MetaData issue

### ISSUE THREAD

**Issue by nturini-cascinanet** [XiaoFaye/WooCommerce.NET#506]
hi, i've a big issue with metadata fields, during my soncronization i receive this error:

`There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.2.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. 
The value '9223372036854775807' cannot be parsed as the type 'Int32'.`

and looking in json file i found that the problem is the id of metadata field

![image](https://user-images.githubusercontent.com/62327651/90122605-d694e280-dd5d-11ea-904a-a43b7a21e0e8.png)

i think is a fast resolution to change the id field from int32 to long

Regards Nicola

**Comment by venoniq** [comment]
Hello, the MetaData is also giving me problems in my case it tells me

Invalid Parameter meta_data [49] [value] is not of type string

until a few days ago it worked correctly.

**Comment by mirco261** [comment]
wuehey, woocommerce made new version of his plugin.

4.3.3 – 2020-08-14
WooCommerce REST API 1.0.10-pl-2
* Fix – Fix regression and restore backward compatibility for date-time and mixed datatypes. #239

After update this plugin started works product update by this awesome WooCommerce.NET plugin ;)
