### ISSUE TITLE
Update meta_data

### ISSUE THREAD

**Issue by mirco261** [XiaoFaye/WooCommerce.NET#508]
I've get data from product, and here is deserialized Meta_data of product:
MetaData deserialized:
"meta_data":[
{"id":8382651,"key":"manufacturer","value":"SENSILLO"},{"id":8382652,"key":"_ean","value":"5902021524495"},{"id":9847094,"key":"rank_math_title","value":"Prebaľovacia podložka Sensillo zelená za 11,75EUR"},{"id":9847095,"key":"rank_math_description","value":"Prebaľovacia podložka Sensillo zelená"},{"id":9847096,"key":"rank_math_focus_keyword","value":"prebaľovacia podložka sensillo zelená"},
{"id":9847097,"key":"rank_math_robots","value":["index"]}
]

I've changes in rank_math_title (other meta_data are no changed) and when I make an api call to edit product, I get response:
{"code":"rest_invalid_param","message":"Neplatn\u00fd parameter: meta_data","data":{"status":400,"params":{"meta_data":"meta_data[5][value] nie je typ string,null."}}}

Do you have any idea why ?

**Comment by venoniq** [comment]
the exact same thing is happening to me

**Comment by mirco261** [comment]
I read your post but I dont know if it is the same... so I've made new post... 

I dont have any idea...

**Comment by mirco261** [comment]
wuehey, woocommerce made new version of his plugin.

4.3.3 – 2020-08-14
WooCommerce REST API 1.0.10-pl-2
* Fix – Fix regression and restore backward compatibility for date-time and mixed datatypes. #239

After update this plugin started works product update by this awesome WooCommerce.NET plugin ;)

**Comment by venoniq** [comment]
I just updated the plugin and everything is working correctly.
