### ISSUE TITLE
Images duplicate in product update 

### ISSUE THREAD

**Issue by baxi2990** [XiaoFaye/WooCommerce.NET#509]
Hello, I am using the most recent version of the library, I have seen the need to upload images from my computer to wordpress, for that I use the library to consume the wordpress api.

When I upload the image and assign it to the product, everything is fine, but when I apply the product update it duplicates the image.

`Stream s = File.OpenRead(url);
                                                if (await client.IsValidJWToken())
                                                {
                                                    var createdMedia = await client.Media.Create(s, item[0].ToString() + "_" + nombreImagen + "_" + randomNumber + .jpg");
                                                    if (createdMedia.Id != 0)
                                                        urlImgWP = createdMedia.SourceUrl;
                                                }`

`imagenes.Add(new ProductImage()
                                                {
                                                    name = "",
                                                    src = urlImgWP
                                                });
 producto.images = imagenes;
`
So far everything works fine, when I run the following line of code I duplicate the images that I already uploaded previously with the wordpress api, the names used for the duplicates are the same with the addition of a number that is the one that wordpress puts when detects an image with the same name.

`await wc.Product.Update(Convert.ToInt32(producto.id), producto); `

Thanks for the help

**Comment by XiaoFaye** [comment]
If you already upload the image, please only pass image id to the product, do NOT pass the image URL.

**Comment by baxi2990** [comment]
Thanks, indeed, trying to do it, but assign the id and url, thanks for the answer, it is very valuable for me.
