### ISSUE TITLE
Question: Error when try a getProducts in https

### ISSUE THREAD

**Issue by sjrm75** [XiaoFaye/WooCommerce.NET#51]
I'd like to know how to make a call when using https cause I'm not sure if  I'm missing somethig
I'm using the WooCommerce.NET wrapper in a console application to reatrieve the products in WooCommerce. I'm just doing a simple test for now, I've installed wordpress and woocommerce in my machine and I've tested the wrapper and everything works fine. this is my code:

string ApiUrl = "http://<local_site>/wp-json/wc/v1/";
string ApiKey = "local_site_api_key";
string ApiSecret = "local_site_api_secret";

RestAPI rest = new RestAPI(ApiUrl, ApiKey, ApiSecret);
WCObject wc = new WCObject(rest);

var myTask = wc.GetProducts(); 
var products = myTask.Result; 

But when I try in the production site I recieve the error "The request was aborted: the connection was closed unexpectedly". I have not configured the production site so I don't know the details of the configuration, but I have de consumer key and consumer secret. I'm not making any change in my code, just the url, key and secret.

The main difference between both server is that the local server is "http" and the production server is "https" so I think there is the problem, but checking the code of the wrapper it's look like it handles this scenario (https).

The exception is thrown in the httpWebRequest.GetResponseAsync() on the wrapper.

Thank you in advance for your answer-

**Comment by XiaoFaye** [comment]
just put https://<local_site>/wp-json/wc/v1/ in your browser and press Enter, you should see store REST API details, Does the url matches the one you have put in your code?

**Comment by sjrm75** [comment]
I have done that test before and I have an answer, but I just made it again and I'm recieving a 404. I'll check that with the people in charge of the production server and let you know. 
Thank you!
