### ISSUE TITLE
How to login a user with Xamarin and WooCommerce.NET

### ISSUE THREAD

**Issue by Chandinipt** [XiaoFaye/WooCommerce.NET#512]
Using the current version of Xamarin (4.8) and WooCommerce.NET (0.82) 

I have used the WooCommerce consumer key and secret to get details from my Wordpress site.  and that is working fine.  

I now need to let users login to their accounts, so they can order stuff, check up on orders etc.  I can't find any documentation on how to do this using your plugin.  I installed the JWT Plugin on my WP site and have set the secret key.  Now I am stuck.  I tried doing this but I cannot actually get an authentication response or similar to check if the user has been logged in.  

            string endPoint = "/jwt-auth/v1/token";
            RestAPI rest = new RestAPI(baseUrl + endPoint, username, password);

            WPObject wp = new WPObject(rest);

Also, removing the above code and just doing below code (which worked before I installed JWT): 
UriBuilder builder = new UriBuilder(AppSettingsManager.Settings["BaseUrl"])
             { Path = ApiConstants.AuthenticateEndpoint };
             AuthenticationRequest authenticateRequest = new AuthenticationRequest()
             { UserName = userName,
             Password = password };

And I am hitting a 403.  I cannot find any documentation on how exactly you move ahead after installing the JWT plugin. 
Please can you point me in the right direction?  

Thank you

**Comment by XiaoFaye** [comment]
If you want to create an order, you will need to use WooCommerce REST API, not the Wordpress API.

**Comment by Chandinipt** [comment]
I am still struggling with this.  

I am breaking this down to just logging in a user to the app.  how would I do this using this plugin? I have got JWT installed on WP. And also have the WooCommerce Key/secret. But I don't know how to use these  

And what if it is a new user who wants to register on the app?  

Thank you for your help

**Comment by Chandinipt** [comment]
Further details: 

In the readme example, it shows this should work - as is calling the jwt-auth/v1/token api with the username and password.   : 

     RestAPI rest = new RestAPI(authenticationEndPoint, userName, password);

    However, although the above call returns back no problem, the jwt_object is null and so the following call does not give me the token.  How do I get the token for JWT?  

            Jwt_object = rest.JWT_Object;

   Am I supposed to sent the WooCommerce Key/secret instead of the username/password and then send the actual user details in the request?  
Thank you
