### ISSUE TITLE
Orders by Customer ID

### ISSUE THREAD

**Issue by hampton1122** [XiaoFaye/WooCommerce.NET#513]
- Wordpress version: 5.4.2, WooCommerce version: 4.3.1 and WooCommerce.NET version: 0.8.2

- I want to return a list of orders by customer_id, but I just get a list of orders for all users. How can I achieve this?

`
RestAPI rest = new RestAPI(_appSettings.WoocommerceEndpoint, _appSettings.WoocommerceKey, _appSettings.WoocommerceSecret, false);`
                `WCObject wc = new WCObject(rest);`
               ` orders = await wc.Order.GetAll(
                    new Dictionary<string, string>() {
                            { "customer_id", customerId },
                        }
                );`

**Comment by XiaoFaye** [comment]
Check here: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers
You can filter by email, but not customer id.
