### ISSUE TITLE
Updating product's featured property stopped working after upgrading to Woocomerce v 4.4.1

### ISSUE THREAD

**Issue by flydart** [XiaoFaye/WooCommerce.NET#517]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

Wordpress v5.5.1
Woocommerce v4.4.1
Woocommerce.NET v0.8.2

- Steps to replicate the issue

            var productBatch = new ProductBatch();
            productBatch.update = new List<Product>();

                productBatch.update.Add(new Product()
                {
                    id = product.id,
                    featured = false
                });

             var c = await wc.Product.UpdateRange(productBatch);

- Details of the error message if there is any

         No error returned, update no longer setting the featured properties. Everything used to work before the upgrade of Woocommerce v4.4.1

**Comment by XiaoFaye** [comment]
Try to do the update with Postman, if still not working, it's better to reports this to WooCommerce.
