### ISSUE TITLE
Establish productCategory ID manually

### ISSUE THREAD

**Issue by carellot** [XiaoFaye/WooCommerce.NET#519]
Hi, i'm Using:
    Wordpress version: 5.4
    Woocommerce.net version: 0.8.1
I'm trting to create new productCategory using this code:
```
        public async void AddCategory(WCObject rec)
        {
            ProductCategory categoria = new ProductCategory()
            {

                id = 02,
                name = "categoria de prova2",
                slug = "categoria-de-prova2"

            };
            await rec.Category.Add(categoria);
```
But this dosn't work because i can't set id,

There is no way I can establish the id manually?
Thanks

**Comment by XiaoFaye** [comment]
No, you can't set ID manually, it's managed by Wordpress.

**Comment by carellot** [comment]
> .

It would be a bad idea to use the "slug" field as an alternate id to sync with an ERP?
