### ISSUE TITLE
Legacy API variation product price show null

### ISSUE THREAD

**Issue by vip30** [XiaoFaye/WooCommerce.NET#52]
It seems sales price and regular_price are null too.
But if I use the wp-json/wc/v1/, it can show the value.
I am using 0.5.6 beta version
Thanks for help

**Comment by XiaoFaye** [comment]
Hi, I'm not maintaining the legacy API anymore, please try to use the latest v1. Thanks

**Comment by vip30** [comment]
I see, but I have trouble of using WPML with woocommerce API. It seems the filter language is not support on the latest v1 api. (Is it my misunderstanding?)
I understand it's not this project issue, but do you have any suggestion about that?

**Comment by XiaoFaye** [comment]
that shouldn't be the issue. What was the problem when using latest v1 api?

**Comment by vip30** [comment]
It seems the latest v1 api ignore the filter[lang] option (Actually I would like to get all the product of language)

And the wpml forum moderator expect we have to use lagacy api.
`https://localhost/WPML/wc-api/v3/products?filter[lang]=en&oauth_consumer_key=key&consumer_secret=key`
ref: https://wpml.org/forums/topic/woocommerce-api-no-language/

**Comment by XiaoFaye** [comment]
try this:

var p = await wc.GetProducts(new Dictionary<string, string>() {  { "lang", "en" }  });

**Comment by vip30** [comment]
I am using http api
This error is occurred in 0.5.5 and 0.5.6-beta
And I try to use postman to get the api, it's not work too.

{System.Exception: {"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}
   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.WooCommerce.WCObject.<GetProducts>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VizzShopConsole.Handler.POSSyncCommandHandlerAsync.<HandleCore>d__3.MoveNext()}

**Comment by XiaoFaye** [comment]
if postman is not working, then it should be a Woocommerce issue.

**Comment by vip30** [comment]
`Hi there,

Itamar is off today, so I will take care of this ticket, Hope that is OK.

It seems you are using the latest WooCommerce API which is not supported http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

Our developers are working on it for future version so currently it's not supported.

Thanks`

From WPML team.
So disappointed that I think I can only use the legacy one, 
Thanks for your help James
