### ISSUE TITLE
Error on Customer.Get(Email)

### ISSUE THREAD

**Issue by yonahs** [XiaoFaye/WooCommerce.NET#520]
I am runing updated version of Wordpress and WooCommerce and WooCommerceNet 0.8.2

When I try to use:
Dim custCheck As New WooCommerceNET.WooCommerce.v3.Customer
custCheck = Await wc.Customer.Get("Email@gmail.com")

I get:
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

**Comment by XiaoFaye** [comment]
If you want to get a customer by email address, please use parameters: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers

**Comment by yonahs** [comment]
Then why is there an overload with email as a parameter if it doesn't work?

**Comment by XiaoFaye** [comment]
It's just a general overload for all objects from legacy API, could be obsolete.
