### ISSUE TITLE
403 Forbidden when I try to access with key and secret

### ISSUE THREAD

**Issue by mmacneill123** [XiaoFaye/WooCommerce.NET#526]
### Make sure you have included the below details when open an issue. Thank you.

- Current WP version, Current WooCommerce version and WooCommerce.NET version compatible with .NET 4.6.1

Problem steps:
Created keys ck_ and cs_ combination from the WooCommerce admin screen with read/write access
Attempting to execute with the credentials always produces the same error:

RestAPI rest = new RestAPI("https://kcm.org.uk/wp-json/wc/v3/", 
                    "ck_...", 
                    "cs_...",
                    requestFilter: RequestFilter);
                WCObject wc = new WCObject(rest);

Request filter just adds the user-agent.
Permalinks use post-name and shop base is /product/.

I get this response back for any url:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/wc/v3/products
on this server.</p>
</body></html>

Is there a prerequisite that the web-server needs to allow access to the API, i.e. do I need to ask the server/firewall to be configured?

The reason I ask is that I get the same response if I just type {website}/wp-json/wc/v3 in a browser which I thought from the WooCommerce docs should return a response as it does not need authentication (see below)?

******
By default, the API provides information about all available endpoints on the site. Authentication is not required to access the API index.

HTTP request
GET /wp-json/wc/v3
*******

**Comment by XiaoFaye** [comment]
Change the authorizedHeader value in RestAPI and try again?

**Comment by mmacneill123** [comment]
Thanks James for the reply, tried both true and false – the same message!

**Comment by XiaoFaye** [comment]
Some plugins or web-server security settings can cause such error, I will suggest you to check the web-server first, then try to disable optional plugins.

**Comment by mmacneill123** [comment]
Thanks James

It was a server issue, everything was locked down – I am now getting data back but not what I expect!!

I used the Products.GetAll() call expecting to get around 150 and only got 10 and cannot see any specific reason why it would only return those 10.  Is there a configuration option that controls how many items you can return in one call?

Thanks

Michael

**Comment by XiaoFaye** [comment]
Check this one: https://github.com/XiaoFaye/WooCommerce.NET/issues/440#issuecomment-614215024

**Comment by mmacneill123** [comment]
Thanks James, looks good 😊

**Comment by JhonatanRamirezS** [comment]
Hi mmacneill123, I am facing the same issues, any advice on what I need to validate to avoid this kind of issue?

thanks a lot
