### ISSUE TITLE
getting error when trying to connect to WooCommerce API via HTTPS

### ISSUE THREAD

**Issue by mohamm4d** [XiaoFaye/WooCommerce.NET#528]
I got this error when trying to connect to WooCommerce API via HTTPS :

the request was aborted could not create ssl/tls secure channel

It is already working when using http but I got this error via HTTPS .

I use .net Framework 4.6.2 . 

I appreciate if you could help me in this issue

**Comment by XiaoFaye** [comment]
What is your operating system?

**Comment by mohamm4d** [comment]
windows 7

**Comment by XiaoFaye** [comment]
Please check here: https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

**Comment by mohamm4d** [comment]
Thank you .
After updating framework to 4.8 and changing to windows10 problem solved .
