### ISSUE TITLE
Json DeSerialize at release mode through exception

### ISSUE THREAD

**Issue by LuckySahu** [XiaoFaye/WooCommerce.NET#53]
Exception name :- System.RuntimeType doesn't contain a definition for Declared Properties`
Please remove dynamic keyword in next release of nuget package instead dynamic if we use 
`Type dt = typeof(T);
if (dT.Name.EndsWith("List"))
    dT = dT.GetTypeInfo().DeclaredProperties.First().PropertyType.GenericTypeArguments[0];`
its working fine
`public T DeserializeJSon<T>(string jsonString)
    {
        dynamic dT = typeof(T);

        if (dT.Name.EndsWith("List"))
            dT = dT.DeclaredProperties[0].PropertyType.GenericTypeArguments[0];//Throughing Exception at this point

        DataContractJsonSerializerSettings settings = new DataContractJsonSerializerSettings()
        {
            DateTimeFormat = new DateTimeFormat(DateTimeFormat),
            UseSimpleDictionaryFormat = true
        };
        DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(T), settings);
        MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes(jsonString));
        T obj = (T)ser.ReadObject(stream);
        stream.Dispose();

        return obj;
    }`
solution is

**Comment by XiaoFaye** [comment]
Can you tell me how to reproduce the exception so I can have a look? Thanks.

**Comment by LuckySahu** [comment]
In xamarin android project  i have used WooCommerce.NET dll from nuget package as well as i tried your class library project from github in both the way i am getting data in debug bode but in release mode  at dT = dT.DeclaredProperties[0].PropertyType.GenericTypeArguments[0] at this point i am getting the exception state that System.RuntimeType doesn't contain a definition for Declared Properties

but when i convert the dynamic keyword to Type dt = typeof(T); its working  in both debug and release mode because 
Dynamic will only shift the actual error (in your case access to a member that doesn´t exist) to runtime instead of to the compiler which makes it harder to find errors. Another reason here is that you already know the runtime-type of the expression typeof(T), which is allways System.Type. Why should you want to hide this information by using dynamic?

**Comment by XiaoFaye** [comment]
Good spot and thanks for the information, will update it in the next version.
