### ISSUE TITLE
Product meta_data attribute doesn't serialize when it is an object

### ISSUE THREAD

**Issue by willherr** [XiaoFaye/WooCommerce.NET#531]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
Woo Commerce version 3, WooCommerce.NET latest version

- Steps to replicate the issue
Set up a product with add-ons. Call Api.Product.GetAll(); Your product will not have the add-ons serialized correctly:

- Details of the error message if there is any
No error message.

**Comment by XiaoFaye** [comment]
Set Debug to true for RestAPI, check the returned json string.

**Comment by willherr** [comment]
I'm sorry I'm not sure what you mean exactly. Is this a flag somewhere that allows metadata values to always be returned as json string values instead?

I changed the code to `Api.Product.API.GetRestful(Api.Product.APIEndpoint)` which correctly shows that the object data is there:
![image](https://user-images.githubusercontent.com/22281397/94988707-3aa57d00-053d-11eb-8efb-c4692646c46a.png)

Running `Api.Product.GetAll()` returns:
![image](https://user-images.githubusercontent.com/22281397/94988806-f23a8f00-053d-11eb-923c-7fab9c396c8f.png)

**Comment by willherr** [comment]
It looks like I may be able to use `WCObject.MetaValueProcessor` to get the raw json for the value property, however I have a debug breakpoint in my func but it isn't getting hit on GetAll...

**Comment by XiaoFaye** [comment]
Have you checked this page? https://github.com/XiaoFaye/WooCommerce.NET/wiki/Handle-different-types-of-Meta-Value-in-WC-Restful-API-V2

**Comment by willherr** [comment]
Thank you! I have not come across this page yet. I will close my issue as I didn't have enough information to do so.
