### ISSUE TITLE
Product.Add woocommerce_rest_product_exists

### ISSUE THREAD

**Issue by Denoxph** [XiaoFaye/WooCommerce.NET#533]
WooCommerce version 4.5.2 and WooCommerce.NET version 0.8.2

async public void AddProduct(int pid, string pname, ProductCategory pcategorie, string pdescription, decimal pprice, bool pdownloadable, bool pvirtual)
        {

            RestAPI rest = new RestAPI(url, key, secret);
            WCObject wc = new WCObject(rest);

            List<ProductCategoryLine> productCategoryLines = new List<ProductCategoryLine>();
            productCategoryLines.Add(new ProductCategoryLine(){
                name = pcategorie.name,
                id = pcategorie.id,
                slug = pcategorie.slug
            });

            List<ProductAttributeLine> productAttributeLines = new List<ProductAttributeLine>();
            productAttributeLines.Add(new ProductAttributeLine()
            {
                id = pid,
                name = pname,
                visible = true
            });

            Product product = new Product()
            {
                name = pname,
                categories = productCategoryLines,
                type = "simple",
                date_created = DateTime.Now,
                description = pdescription,
                regular_price = pprice,
                id = pid,
                slug = pid + "_" + pname,
                downloadable = pdownloadable,
                _virtual = pvirtual,
                attributes = productAttributeLines,
                sku = Convert.ToString(pid),
                permalink = link + "/produkt/" + pname,
                catalog_visibility = "visible"
                
            };

            await wc.Product.Add(product);            
        }

Error Message:
"{"code":"woocommerce_rest_product_exists","message":"Kann keine existierende product anlegen.","data":{"status":400}}"

I was able to add one Product after that i couldn't add another one with different id, name etc.

**Comment by Albagape** [comment]
I think product.id is read only

**Comment by Denoxph** [comment]
> I think product.id is read only
> 
Thank you, that solved the problem. Should have looked more carefull.
