### ISSUE TITLE
Downloading image from URL wp-content/uploads/.... Results in 403. 

### ISSUE THREAD

**Issue by oeloe100** [XiaoFaye/WooCommerce.NET#534]
Hi there i got a quick question.

Im trying to download images from woocommerce url. Wich i find trough Product.Images.Src etc. Anyways if i open this url in browser or in postman i get to see the image. but when i try to download the image from my application i get 403.

I tried multiple methods. And created a new Httpclient with different headers. Also different get methods like 'GetStreamAsync'.

When i try to download a simple image from google. I get a successtatuscode. How can i download images from woocommerce using this WooCommerce.NET library?

**Comment by XiaoFaye** [comment]
You don't need WooCommerce.NET to download an image from URL, try WebClient.
