### ISSUE TITLE
Filtering Product.GetAll() using product attributes

### ISSUE THREAD

**Issue by Tatu100** [XiaoFaye/WooCommerce.NET#536]
Hi,

I've got some customized attributes in my product catalog, and i'll like to use them as filter in Product.GetAll() function.

For example:
* the attribute is: { id:2260, name: MyAttr, slug: pa_myattr }
* There're some products that have MyAttr="OK"

I don't know how to add the condition "MyAtt=OK" in  Product.GetAll() function. The condition "Products that have "MyAtt" attribute" would be also useful for me. 

Dictionary<string, string> myDict = new Dictionary<string, string>();
myDict.Add("consumer_key", this.customer_key);
myDict.Add("consumer_secret", this.customer_secret);
myDict.Add("per_page", 100);
myDict.Add("page", 1);
List<WC3.Product> result = await this.WC.Product.GetAll(_clsDict);

I've tried using the attribute's id, name, or slug, but the function returns all the products as well. 
myDict.Add("MyAttr", "OK");
myDict.Add("attribute", "MyAttr");
myDict.Add("slug", "pa_myattr");
None of these instructions work.

How can I do it? Any help would be much appreciated. 

Thanks

**Comment by negapo** [comment]
Hi, first find out the Attribute ID of the term "OK" then try this:

myDict.Add("attribute_term", "ID of OK");
