### ISSUE TITLE
Getting all customer metafields

### ISSUE THREAD

**Issue by hexoquinasa** [XiaoFaye/WooCommerce.NET#541]
Hello.

I'm not getting all metafields when using wc.Customer.Get(id);
Is this is the default behaviour, or am I missing something?
Thank you

Here is my code

```
//Manually getting the results
var client = new RestClient("https://www.mystore.com/wp-json/wc/v3/Customers/7?oauth_consumer_key=mykey&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1603118094&oauth_nonce=Gzr9ECammot&oauth_version=1.0&oauth_signature=mysecret");
client.Timeout = -1;
var request = new RestRequest(Method.GET);
request.AddParameter("text/plain", "", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);
var customer = JsonConvert.DeserializeObject<Customer>(response.Content); 
//It works: Customer has 4 metafields

//Using WooCommerceNet
MyRestAPI rest = new MyRestAPI("https://www.mystore.com/wp-json/wc/v3", "mykey", "mysecret",false);
WCObject wc = new WCObject(rest);
var customers2 = await wc.Customer.Get(7);
//Customer shows only 3 metafields

```

Seems to work when I add filters: page and per_page but don't get quite how it should be used...
Also when getting all customers wc.Customer.GetAll() it doesnt bring all the metafields for each one.
Thank you

**Comment by XiaoFaye** [comment]
Can you try to use WooCommerce.NET with Json.NET? See how it goes.

https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-JSON.NET-in-WooCommerce.NET

**Comment by hexoquinasa** [comment]
Hi James,
Thank you for the answer. Yes I'm using WooCommerce.NET with Json.NET.
What I found is that when I open two tabs in Postman and run the same payload using different auth types, 
one with the auth in the url like: https://www.mystore.com/wp-json/wc/v2/customers?page=1&per_page=10&consumer_key=myke&consumer_secret=mysecret

it doesnt return all the metadata. It just returns the preset by woocommerce: 
               "meta_data": [
                "id": 469,
                "key": "shipping_method",
                "value": [
                    "flat_rate:2"
                ]
            },
            {
                "id": 470,
                "key": "shipping_phone",
                "value": "4168888888"
            },
            {
                "id": 471,
                "key": "wc_last_active",
                "value": "1602892800"
            }
        ]...

When calling the api using postman and Oauth 1.0, HMAC-SHA1 it works
I get the extra metadata.

"meta_data": [
            {
                "id": 469,
                "key": "shipping_method",
                "value": [
                    "flat_rate:2"
                ]
            },
            {
                "id": 470,
                "key": "shipping_phone",
                "value": "4168888888"
            },
            {
                "id": 471,
                "key": "wc_last_active",
                "value": "1602892800"
            },
            {
                "id": 684,
                "key": "CustomerPrimaryCode",
                "value": "Woo_11"
            }
        ],

And the library seems to use the first method.

I tried puting AuthorizedHeader=true and it doesn't go through, I can't make basic auth work even from postman, I guess I would have to edit .htaccess to make it work, but I don't have access to it (I am using godaddy plesk)

Is it possible to use OAuth 1.0 with the library?

I see that there are two options 
```
if (AuthorizedHeader == true)
                    {
                        httpWebRequest = (HttpWebRequest)WebRequest.Create(wc_url + GetOAuthEndPoint(method.ToString(), endpoint, parms));
                        httpWebRequest.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(wc_key + ":" + wc_secret));
                    }
                    else
                    {
                        if (parms == null)
                            parms = new Dictionary<string, string>();

                        if (!parms.ContainsKey("consumer_key"))
                            parms.Add("consumer_key", wc_key);
                        if (!parms.ContainsKey("consumer_secret"))
                            parms.Add("consumer_secret", wc_secret);
```

Thank you

**Comment by XiaoFaye** [comment]
I guess your site is https? The library will default to method one if it's https. It seems this could be a WooCommerce bug?

**Comment by hexoquinasa** [comment]
Yes it is https, thank you James, I'll investigate if it's a WooCommerce bug ...

**Comment by hexoquinasa** [comment]
Hi James,
What I found is that if the oauth_signature_method is added to the parms collections it works
Right now if the request is https the following code is executed:

```
if (!parms.ContainsKey("consumer_key"))
                            parms.Add("consumer_key", wc_key);
                        if (!parms.ContainsKey("consumer_secret"))
                            parms.Add("consumer_secret", wc_secret);

```

Adding the code below brings all metafields: 

```
 if (!parms.ContainsKey("oauth_signature_method"))
                            parms.Add("oauth_signature_method", "HMAC-SHA1");

```

**Comment by XiaoFaye** [comment]
Hi, the way of authorization shouldn't affect the return data, have you checked with WooCommerce team if this is expected?

**Comment by hexoquinasa** [comment]
Hi, I posted an issue on their site: https://github.com/woocommerce/woocommerce/issues/28068

**Comment by XiaoFaye** [comment]
Thanks, let's see if they have any idea.
