### ISSUE TITLE
Coupon lines in orders, 'discount' and 'discount_tax' are null

### ISSUE THREAD

**Issue by kevinamorim** [XiaoFaye/WooCommerce.NET#548]
### Make sure you have included the below details when open an issue. Thank you.

When getting an order with coupons, the coupon lines have the 'discount' and 'discount_tax' as null.

This happens because the value is being assigned to 'discountValue' and discount_taxValue' fields, both protected. 

I don't know if there is a good reason for this to happen, but since they are protected, I cannot use them.

**Wordpress Version: ** 5.5.3
**WooCommerce.NET Version: ** 0.8.2

**Comment by gkverneland** [comment]
+1

**Comment by danieledignani** [comment]
It's still an issue

**Comment by KaoutharG** [comment]
It's still an issue. Always discount and discount_tax are null. And the 'discountValue' and discount_taxValue' fields are protected. How can I get the value of the coupon to display it?
Please Someone have another idea to get discount's value from the coupon?
