### ISSUE TITLE
How can I use it? - Error	CS4033

### ISSUE THREAD

**Issue by naugustijr** [XiaoFaye/WooCommerce.NET#55]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS4033	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.	TesteCETIINFO	E:\SVN\dotnetteste\trunk\Woocommerce\ConsoleApplication1\Program.cs	25	Active

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WooCommerceNET;
using WooCommerceNET.WooCommerce;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {

            //Legacy way of calling WooCommerce REST API
            //RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wc-api/v3/", "<WooCommerce Key>", "<WooCommerce Secret");
            //WooCommerceNET.WooCommerce.Legacy.WCObject wc = new WooCommerceNET.WooCommerce.Legacy.WCObject(rest);

            RestAPI rest = new RestAPI("http://www.xyz.com/wp-json/wc/v1/", "ck_1111", "cs_1111");
            WCObject wc = new WCObject(rest);

            //Get all products
            //var products = await wc.GetProducts();
            var products = await wc.GetProducts();
            Console.WriteLine(products); 
        }
    }
}

`

**Comment by XiaoFaye** [comment]
try this:

`Task t = wc.GetProducts();`
`t.Wait();`
`var products = t.result;`

**Comment by naugustijr** [comment]
var products = t.result;

Error	CS1061	'Task' does not contain a definition for 'result' and no extension method 'result' accepting a first argument of type 'Task' could be found (are you missing a using directive or an assembly reference?)

**Comment by naugustijr** [comment]
If I remove this code: var products = t.result;
I get this error (execution error):

System.AggregateException: Um ou mais erros. ---> System.Exception: {"code":"woo
commerce_rest_authentication_error","message":"Assinatura inv\u00e1lida - a assi
natura fornecida n\u00e3o confere.","data":{"status":401}}
   em WooCommerceNET.RestAPI.<SendHttpClientRequest>d__8`1.MoveNext() na E:\SVN\
dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\RestAPI.cs:linha 89
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em WooCommerceNET.WooCommerce.WCObject.<GetProducts>d__29.MoveNext() na E:\SV
N\dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\WooCommerce\WCObject.cs:l
inha 196
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   em System.Threading.Tasks.Task.Wait()
   em ConsoleApplication1.Program.Main(String[] args) na E:\SVN\dotnetteste\trun
k\Woocommerce\ConsoleApplication1\Program.cs:linha 31
---> (Exceção Interna N° 0) System.Exception: {"code":"woocommerce_rest_authenti
cation_error","message":"Assinatura inv\u00e1lida - a assinatura fornecida n\u00
e3o confere.","data":{"status":401}}
   em WooCommerceNET.RestAPI.<SendHttpClientRequest>d__8`1.MoveNext() na E:\SVN\
dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\RestAPI.cs:linha 89
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em WooCommerceNET.WooCommerce.WCObject.<GetProducts>d__29.MoveNext() na E:\SV
N\dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\WooCommerce\WCObject.cs:l
inha 196<---

**Comment by XiaoFaye** [comment]
are you using an IDE? it should tell you to use t.Result...

**Comment by naugustijr** [comment]
I am using Visual Studio 2015.

[image: Imagem inline 1]

Norival Augusti Junior
CETI Software <http://www.cetiinformatica.com.br/>
(14) 3762-1240


2016-11-18 9:18 GMT-02:00 James Yang <notifications@github.com>:

**Comment by XiaoFaye** [comment]
my mistake, should be as below:

![image](https://cloud.githubusercontent.com/assets/6334728/20428528/78f2b4e2-adee-11e6-8586-4e1769be71f3.png)

**Comment by naugustijr** [comment]
Error:

Invalid Signature


Um ou mais erros.
System.AggregateException: Um ou mais erros. ---> System.Exception:
{"code":"woo
commerce_rest_authentication_error","message":"Assinatura inv\u00e1lida - a
assi
natura fornecida n\u00e3o confere.","data":{"status":401}}
   em WooCommerceNET.RestAPI.<SendHttpClientRequest>d__8`1.MoveNext() na
E:\SVN\
dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\RestAPI.cs:linha 89
--- Fim do rastreamento de pilha do local anterior onde a exceção foi
gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   em
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em WooCommerceNET.WooCommerce.WCObject.<GetProducts>d__29.MoveNext() na
E:\SV
N\dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\WooCommerce\WCObject.cs:l
inha 196
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
includeTaskCanceled
Exceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,
CancellationTo
ken cancellationToken)
   em System.Threading.Tasks.Task.Wait()
   em ConsoleApplication1.Program.Main(String[] args) na
E:\SVN\dotnetteste\trun
k\Woocommerce\ConsoleApplication1\Program.cs:linha 31
---> (Exceção Interna N° 0) System.Exception:
{"code":"woocommerce_rest_authenti
cation_error","message":"Assinatura inv\u00e1lida - a assinatura fornecida
n\u00
e3o confere.","data":{"status":401}}
   em WooCommerceNET.RestAPI.<SendHttpClientRequest>d__8`1.MoveNext() na
E:\SVN\
dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\RestAPI.cs:linha 89
--- Fim do rastreamento de pilha do local anterior onde a exceção foi
gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   em
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em WooCommerceNET.WooCommerce.WCObject.<GetProducts>d__29.MoveNext() na
E:\SV
N\dotnetteste\trunk\Woocommerce\WooCommerce.NET-master\WooCommerce\WCObject.cs:l
inha 196<---

Norival Augusti Junior
CETI Software <http://www.cetiinformatica.com.br/>
(14) 3762-1240


2016-11-18 9:24 GMT-02:00 James Yang <notifications@github.com>:

**Comment by ironfly** [comment]
I am having the same issue with VS 2015

**Comment by XiaoFaye** [comment]
Hi @naugustijr , @ironfly 

There is a new version 0.6.0 on the Nuget, could you please try the new version and see if the problem still exist?

**Comment by naugustijr** [comment]
I will try.
Thanks.

Norival Augusti Junior
CETI Software <http://www.cetiinformatica.com.br/>
(14) 3762-1240


2016-12-14 23:53 GMT-02:00 James Yang <notifications@github.com>:

**Comment by aneggi** [comment]
Hello, 

I tryed the same but not working:

`RestAPI rest = new RestAPI("http://www.XXXXXX.com/wp-json/wc/v1/", "ck_XXXXXX", "cs_XXXXX");
            WooCommerceNET.WooCommerce.WCObject wc = new WooCommerceNET.WooCommerce.WCObject(rest);
            //Add new product

            

            Task<ProductList> t = wc.GetProducts();
            t.Wait();
            var products = t.Result;`

I have this as result:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<WooCommerceNET.WooCommerce.Product>>' to 'System.Threading.Tasks.Task<WooCommerceNET.WooCommerce.Legacy.ProductList>'	ConsoleApplication1	C:\Users\Ale\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	70	Active

Can you help me?

**Comment by XiaoFaye** [comment]
@aneggi  Do you have using WooCommerceNET.WooCommerce.Legacy; at the top of your code file? Please remove it if any.

**Comment by aneggi** [comment]
Yes removed. But in new version i think something change.
ProductList does not exist.
There is ProductBatch, but i not understand how to use it. Right?

**Comment by XiaoFaye** [comment]
@aneggi  **List<Product>** will work fine.

**Comment by aneggi** [comment]
with this code:
`Task<ProductList> t = wc.GetProducts();
            t.Wait();
            var products = t.Result;`
And without Legacy, the result is:

1)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ProductList' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApplication1	C:\Users\Ale\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	72	Active
2)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<WooCommerceNET.WooCommerce.Product>>' to 'System.Threading.Tasks.Task<ProductList>'	ConsoleApplication1	C:\Users\Ale\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	72	Active

**Comment by XiaoFaye** [comment]
@aneggi  `try Task<List<Product>> t = wc.GetProducts(); t.Wait(); var products = t.Result;`

**Comment by aneggi** [comment]
Yes, i don't know why I not think about it :-)

Now work fine.
