### ISSUE TITLE
Add or Update product: stock_quantity not set

### ISSUE THREAD

**Issue by Karl2893782** [XiaoFaye/WooCommerce.NET#550]
If I call Add or Update on a product with a stock_quantity set, then this doesn't get passed to WooCommerce.

The call completes successfully, and the product in WooCommerce shows "in stock" but doesn't show the available stock quantity.

I can see that the property stock_quantityValue on Product is marked up with a serialisation attribute, but the property stock_quantity doesn't have a serialisation attrubte, which is probably the cause of the issue. 

But I can't set the property stock_quantityValue because it is marked as protected.

WooCommerce.Net version: 0.8.2
WooCommerce version: 4.7.1
Wordpress version: 5.5.3–en_GB

**Comment by pwyszynski** [comment]
Does the product you're trying to set have `managed_stock` property set to true? Otherwise you won't be able to set the stock.
