### ISSUE TITLE
"manage_stock" on variation issue

### ISSUE THREAD

**Issue by chriseilander** [XiaoFaye/WooCommerce.NET#553]
So I'm using version 0.8.2, and I get the following:

> "The value 'parent' cannot be parsed as the type 'Boolean'".

Getting the product from the API using Insomnia, the only key with the value "parent" is "manage_stock". Looking in the issues it should have been fixed, right? #131 and #97.

But by looking at the code it seems it is only that way for v1, not for v2 and v3 (which I am using).

**Comment by XiaoFaye** [comment]
Fixed in the latest version.
