### ISSUE TITLE
How to get the list of the subcategories of a specific category?

### ISSUE THREAD

**Issue by hsn-hajjar** [XiaoFaye/WooCommerce.NET#556]
Hello, I am using Wordpress last version, WooCommerce last version and WooCommerce.NET v3.

I need to get all the subcategories of a category (parent category). Is there a way to do that with Woocommerce.NET v3 (C#)???

Thanks!

**Comment by RetailJEM** [comment]
Pretty sure this would work...
Refer to the WooCommerce API docs for which parameters to use.
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories

//Use parameters
var parentId = 1
var c = await wc.ProductCategory(new Dictionary<string, string>() 
{
	{ "parent", parentId.ToString() }
});
