### ISSUE TITLE
Add User-friendly Attribute Names and Values to Order Line Items Metadata

### ISSUE THREAD

**Issue by dartrax** [XiaoFaye/WooCommerce.NET#558]
WooCommerce 4.7.0 introduced User-friendly Attribute Names and Values to Order Line Items Metadata:
https://github.com/woocommerce/woocommerce/pull/27492

Looks like this:
```
"line_items": [
    {
        "id": 5,
        "name": "Variable Hoodie - Blue",

        "meta_data": [
            {
                "id": 51,
                "key": "pa_store-level-size",
                "value": "medium",
                "display_key": "Store Level Size",
                "display_value": "Medium"
            },
        ],

    }
```

Currently, it seems that I can't access display_key or display_value directly from this metadata, because the MetaData class doesn't have those properties: https://github.com/XiaoFaye/WooCommerce.NET/blob/10a4e08b43f9b088375e252771c3c6cbd4ef51ce/WooCommerce/v2/WCObject.cs#L82

Instead, I need to work around by iterating through WCObject.Attribute.GetAll (or at least I did not found an easier way to get the display names from the slugs of global attributes...)

**Comment by XiaoFaye** [comment]
Hi, this is done in version 0.8.3.
