### ISSUE TITLE
how get Some Specific Order Status

### ISSUE THREAD

**Issue by ciberfriends** [XiaoFaye/WooCommerce.NET#559]
Hello, How could you filter that shows some specific Order status Params, On-Hold, Processing, Pending, 
at the same time.

**Comment by ciberfriends** [comment]
In PHP I do it as follows:
`$orders=$woocommerce->get('orders', array('per_page'=>15, 'status'=>'pending,processing,on-hold,refunded,failed,cancelled'))`

**Comment by maaxelsson** [comment]
var wooparameters = new Dictionary<string, string>() { { "status", "processing" }, { "per_page", "100" } };
var ordersWithStatusProcessing = wc.Order.GetAll(wooparameters).Result;

Change processing to w/e status you want.
