### ISSUE TITLE
woocommerce_rest_authentication_error with v3 api and meta filter

### ISSUE THREAD

**Issue by DaviddH** [XiaoFaye/WooCommerce.NET#56]
Hello,

My goal is to retrieve an order, including the meta fields and line_items meta fields, I first used the new rest API (v1), but discovered that the new API doesn't return meta fields, so I am using the legacy v3 API now.

Sadly I am getting the following error when retrieving an order:
```
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}
```
My Code:
```C#
RestAPI rest = new RestAPI("http://xxxxx/wc-api/v3/", "xx", "xx");
WooCommerceNET.WooCommerce.Legacy.WCObject wc = new WooCommerceNET.WooCommerce.Legacy.WCObject(rest);

var orders = await wc.GetOrder(2867, new Dictionary<string, string>() { { "filter[meta]","true"} });
```

Site is on http, as soon as I remove the "filter[meta]","true" param, it works fine, but without the meta fields returned. (which I need)

Would for love to get some help here, so far your library has been in absolute time saver, thanks in advance!

**Comment by XiaoFaye** [comment]
Can you please try this in the latest v1 api:

`var orders = await wc.GetOrder(2867, new Dictionary<string, string>() { { "filter[meta_key]","xxx"} });`

The WC API doc says: 

> filter	->    Use WP Query arguments to modify the response; private query vars require appropriate authorization.

You can refer to Wordpress document for more details:
[https://codex.wordpress.org/Class_Reference/WP_Query](url)

**Comment by DaviddH** [comment]
Hello,

Thanks for your response.

Trying that with the new rest api gives the same oauth error, in the mean time i reverted to the RestApi.cs state before this commit: https://github.com/XiaoFaye/WooCommerce.NET/commit/87de8f62988b92c5e3a8ad848bd82f154e464d6d

Then it works fine (on the old api) without authorization error.

also your example on the new rest api will not work for me, since i need to retrieve the data, not filter on it.

The new rest api does not return meta fields (yet).

**Comment by XiaoFaye** [comment]
Hi,

You can get the order mate in Legacy API by using the parameter as below:

`parms.Add("meta", "true");`

**Comment by DaviddH** [comment]
Hi,

No that doesn't work...

With meta:
https://xxx/wc-api/v3/orders/2867?filter[meta]=true&consumer_key=xxx&consumer_secret=xxx

Without meta:
https://xxx/wc-api/v3/orders/2867?meta=true&consumer_key=xxx&consumer_secret=xxx

**Comment by XiaoFaye** [comment]
I can get the below data, is this what you expect?

![image](https://cloud.githubusercontent.com/assets/6334728/20537926/f14a35d8-b153-11e6-87e6-85d5f39d2252.png)

**Comment by XiaoFaye** [comment]
Hi @DaviddH , you can update the meta fields in this way #73

**Comment by DaviddH** [comment]
Hi,

Sorry for the late response.

I switched the site I am querying against to https to work around the issue with oauth, I suspect that had something to do with the server configuration, not this library.

Regarding the retrieval of the meta fields, I am still using the 'legacy' API since it returns a lot more data then the REST API, hopefully that changes in the further.

Thanks for your help, this issue can be closed.
