### ISSUE TITLE
A product id can overflow an int32

### ISSUE THREAD

**Issue by NicolaBizzoca** [XiaoFaye/WooCommerce.NET#560]
Hi,
A post id on WordPress is defined as: [bigint(20) unsigned](https://github.com/WordPress/WordPress/blob/d5fd3bd4529e5a6e17bfd857279ae47363e5be2a/wp-admin/includes/schema.php#L160) 
Which can overflow an int32, which is the type used by WooCommerce.NET for product id

It could be possible to change the type of the product id to fit the max size of a WordPress post id?

**Comment by XiaoFaye** [comment]
Hi, this is done in version 0.8.3.

**Comment by gaazkam** [comment]
@XiaoFaye  Varius `Delete` methods still accept `int` ids, not `uint`.

For example `WCObject.Order.Deleet` accepts the `int id` parameter. Likewise, `OrderBatch.delete` (and `BatchObject<T>.delete` in general) is also declared as `List<int>` rather than `List<uint>`.

**Comment by XiaoFaye** [comment]
Ops, forgot to change the parameter, will do it in the next version.

**Comment by richardaubin** [comment]
This is still not fixed in version 0.8.4.  Delete still accepting int instead of ulong....
![image](https://user-images.githubusercontent.com/37956997/204314209-f42d096e-ed6d-42c2-869a-8a3179d4fb6a.png)
