### ISSUE TITLE
Lose the iframe in the product description when adding a new product.

### ISSUE THREAD

**Issue by bungphe** [XiaoFaye/WooCommerce.NET#561]
I lose the iframe in the product description when adding a new product. Does anyone know the reason why?
Thank you so much!!!

**Comment by Bokkeman** [comment]
In my experience this is a WooCommerce limitation. We got around it by modifying the iframes into hidden div's with special attributes which could be sent to WooCommerce. Then we injected a site-wide page-level Javascript which looked for those divs after every page load and converted them into iframes.
