### ISSUE TITLE
Cannot Read Data on https site

### ISSUE THREAD

**Issue by andraschris** [XiaoFaye/WooCommerce.NET#563]
Hello
- Wordpress version:5.6 , WooCommerce version:4.9.2 , WooCommerce.NET version : 0.82

-  i am successfully connect to site
 https://testwooco.epsiloncomp.gr/wp-json/wc/v3/
using parameter [AuthorizedHeader]=False

But i cannot get data trying command such us
wc.Category.GetAll
or 
wc.Product.GetAll {parameters...}

In both cases the response is :
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>404 Not Found</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">404</div>
    <h2>Page Not Found</h2>
    <p class="lead">This page either doesn't exist, or it moved somewhere else.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>

The same code runs successfully on local site and the only difference is http

**Comment by XiaoFaye** [comment]
Can you turn the Debug on in Wordpress and then check the error log?

**Comment by andraschris** [comment]
Yes i turn it on, but after the error in the 4th line of this code
 1 Dim rest As WooCommerceNET.RestAPI = New WooCommerceNET.RestAPI(Me.Woo_Url.Text, Me.Woo_Key.Text, 
 Me.Woo_Secret.Text, AuthorizedHeader)
   2         Dim wc As WCObject = New WCObject(rest)
   3         Dim LsC As New List(Of ProductCategory)
   4         LsC = Await wc.Category.GetAll

the file debug.log is simply empty!

**Comment by andraschris** [comment]
ok
The problem related to site and wordpress and fixed!

**Comment by lavahasif** [comment]
@andraschris  how you fix this .I also face this error after changing domain to https .how you fix this could you elaborate what you did.

**Comment by andraschris** [comment]
Hello. The problem was related to the missing wordpress parameter file

.htaccess

in the root directory

![image](https://user-images.githubusercontent.com/32484308/107853386-54759b80-6e1e-11eb-80ba-ed25b7294d4c.png)

**Comment by lavahasif** [comment]
thank you .i coud'nt find any file like this
