### ISSUE TITLE
Unable to Download from Manage nugget package VS2012

### ISSUE THREAD

**Issue by Adeu** [XiaoFaye/WooCommerce.NET#564]
Error when trying to Install the WooCommerceNET using the Manage nugget package,
text:  El elemento 'metadata' en espacio de nombres 'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd'
 tiene un elemento secundario 'license' en espacio de nombres 
'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd' no válido.

The 'metadata' element in namespace 'http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd'
  has an invalid child element 'license' in namespace http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd

**Comment by XiaoFaye** [comment]
Can you upgrade to VS2019? seems to be a compatible issue.

**Comment by Adeu** [comment]
updated to VS2019 and fixed the issue, the nugget works prety well. 
thank you very much for the fast response.
