### ISSUE TITLE
Issues after WooCommerce update to 5.0.0

### ISSUE THREAD

**Issue by pwyszynski** [XiaoFaye/WooCommerce.NET#566]
Hi,

Yesterday WooCommerce updated to 5.0.0, and probably there are breaking changes to the Rest API part as well. I'm trying to retrieve Orders from WooCommerce, but the service hangs on calling the `GetAll()` method. Do you (or anyone else) maybe know if it's a huge thing to fix? I can provide more details if you tell me what else you need.

As a side note - a regular GET call through VS Code RestClient extension (think Postman or Fiddler) works properly. I'd rather not rewrite my whole integration using HTTP calls, though :)

- Wordpress version, WooCommerce version and WooCommerce.NET version
**WordPress version**: 5.6.1
**WooCommerce version**: 5.0.0
**WooCommerce.NET version**: 0.8.2

- Steps to replicate the issue
Simply connect to WooCommerce and try to get all Orders. The call is awaited and never succeeds.

- Details of the error message if there is any
No error message.

**Comment by Yoonwoo** [comment]
I have same problem, it just hangs forever with no error.

**Comment by Yoonwoo** [comment]
Wait.. nevermind I'm retarded, I did this:

GetProducts();

Instead of this:

Task.Run(() => this.GetProducts()).Wait();
