### ISSUE TITLE
Unit Test: I need to create Unit test, for this I need to mock up several methods, but I need them to be marked as virtual

### ISSUE THREAD

**Issue by gocasals** [XiaoFaye/WooCommerce.NET#568]
Error:
System.NotSupportedException: 'Unsupported expression: ... => ....Update(It.IsAny<int>(), It.IsAny<Product>(), null)
Non-overridable members (here: WCItem<**Product**>.Update) may not be used in setup / verification expressions.'

Example code:
 _wooWC.Setup(x => x.Product.Update(It.IsAny<int>(), It.IsAny< WooCommerceNET.WooCommerce.v2.Product>(), null))
                .Returns(Task.FromResult(item));
_wooWC.Setup(x => x.Product.Variations.Update(It.IsAny<int>(), 
                 It.IsAny< WooCommerceNET.WooCommerce.v2.Variation>(), It.IsAny<int>(), null))
                .Returns(Task.FromResult(itemV));
Thanks in advance.

**Comment by XiaoFaye** [comment]
Hi, this is done in version 0.8.3.
