### ISSUE TITLE
It is possible to customize the "Customer" class

### ISSUE THREAD

**Issue by jacargentina** [XiaoFaye/WooCommerce.NET#57]
Hi! In my use case here in Argentina, our website has some special extra fields for the Woocommerce "Customer" which are "CategoriaIVA" and "NumeroCUIT" which are needed to make legal invoices.

So far, now the json api is returning the extra fields, but WooCommerce .NET cant see them.

There is the possibility to somehow make WooCommerce .NET to read those values?

**Comment by XiaoFaye** [comment]
Sure, just create a sub class from Customer and add the extra fields. 
[https://msdn.microsoft.com/en-us/library/ebca9ah3.aspx](url)

PS: Don't forget to add the [DataContract] attribute for the extra fields.

**Comment by vankampenp** [comment]
Hi James, can you pleas update the link? It is no longer working.

Thanks, Pieter

**Comment by XiaoFaye** [comment]
updated, please try again.

**Comment by vankampenp** [comment]
Works!, thx Pieter

**Comment by jacargentina** [comment]
Hi again. I've in place tried with the "Order" class, i've created my own suclass "Order"  (my own namespace) like this:

```csharp
using System.Runtime.Serialization;

namespace CustomNamespace
{
    [DataContract]
    public class Order : WooCommerceNET.WooCommerce.Order
    {
        [DataMember(EmitDefaultValue = false)]
        public string numero_cuit { get; set; }

        [DataMember(EmitDefaultValue = false)]
        public string categoria_iva { get; set; }
    }
}
```


But then when i call the method from the API like this:

```csharp
 var wc = new WCObject(api);
 var task = wc.GetOrders();
 task.Wait();

var order = task.Result[0];

var myOrder = order as CustomNamespace.Order;
// myOrder is null
```

The returned orders are of type 'WooCommerceNET.WooCommerce.Order`. When i cast it to my own subclass, it returns null.

I dont understand how the `GetOrders` is supposed to instance my own subclass ?

**Comment by XiaoFaye** [comment]
if it's a casting problem, it should throw a casting exception instead of returning null. Could you please check what wc.GetOrders() had returned?

**Comment by jacargentina** [comment]
`wc.GetOrders()`correctly return 1 order (the test order i've saved) But it is of type `Order` from the library, not mine!

**Comment by vankampenp** [comment]
I am having the same problem. When you sub class a customer or an order, the library is still using its own class, not the one with the new fields. So it may be a simple thing, but it would help if you can give an example of how to extend customer or order with a field, without changing the library for ease of upgrading. See the code below. The OrderList is a list of Orders, not a list of the sub class My_Orders.

```
 public async Task<OrderList> GetOrders(Dictionary<string,string> parms = null)
        {
            string json = await API.SendHttpClientRequest("orders", RequestMethod.GET, string.Empty, parms);
            return API.DeserializeJSon<OrderList>(json);
        }
```

**Comment by XiaoFaye** [comment]
Please try the below code:

`  [DataContract] `
`    public class MyOrder : WooCommerceNET.WooCommerce.Order `
 `   {`
 `       [DataMember(EmitDefaultValue = false)]`
 `       public string numero_cuit { get; set; }`

`        [DataMember(EmitDefaultValue = false)]`
`        public string categoria_iva { get; set; }`
 `   }`

 `   [CollectionDataContract]`
`    public class MyOrderList : List<MyOrder>`
`    {`
 `       [DataMember]`
`        public List<MyOrder> orders { get; set; }`
 `   }`

`   string json = await API.SendHttpClientRequest("orders", RequestMethod.GET, string.Empty, parms);`
`   var myorders = API.DeserializeJSon<MyOrderList>(json);`

**Comment by vankampenp** [comment]
The last two lines mean changing WCObjects? I would have to do that for every method that returns or consumes an order or a customer.

Perhaps changing class Order to
  [DataContract]
    public class Order : MyOrder {
...
}

and then implement a MyOrder class with the additional custom fields
[DataContract]
    public  class mp_order: JsonObject  
    {
//custom field go here
}
Then the only change is the inheritance of MyOrder. My code consuming WCObjects, Customer, and Order works as before, but with this I can also use the extra fields on Customer and Order.
But I don't have enough knowledge to judge if this is the best way forward. It does still require me to make an update to your source code when you release a new version, albeit a minor one. Unless you build this in, with a skeleton MyOrder class that you never update.

**Comment by XiaoFaye** [comment]
I get what you mean, I will need to make some changes on my code to make it possible, will keep you updated.

**Comment by XiaoFaye** [comment]
Hi all, this functionality has been added in the latest commit: https://github.com/XiaoFaye/WooCommerce.NET/commit/70e4c567256f6297be60e593ddfbaf896cfad26b 

Thanks

**Comment by jacargentina** [comment]
I'm using the library through nuget. Can @XiaoFaye publish v0.6.0 to nuget please?

**Comment by XiaoFaye** [comment]
Hi @jacargentina , version 0.6.0 is on Nuget now.

**Comment by jacargentina** [comment]
@XiaoFaye I need to use this with v2 API. WCObject<T> is not available on v2, just the non-generic version?

**Comment by XiaoFaye** [comment]
@jacargentina it is available, you need to import the corresponding namespace.

**Comment by vinigarcia87** [comment]
@XiaoFaye I having the same problem than @jacargentina , but I didn't get the solution implemented here.
Can you please give me an example on how to extend a class to add some more properties?

**Comment by vinigarcia87** [comment]
I must say, I not from .NET world, so I'm kinda confused here...

What I'm doing:

I created a custom Order class, to add a new property called storms_receiptNumber.

```
namespace WoocommerceSharpClient
{
	[DataContract]
	class StormsOrder : WooCommerceNET.WooCommerce.v3.Order
	{
		[DataMember]
		public string storms_receiptNumber { get; set; }
	}
}
```

Then, I created a custom WCObject, where I pass my custom Order objetc instead of the original Order object:

```
namespace WoocommerceSharpClient.WooCommerce
{
	class StormsWCObject<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> : WooCommerceNET.WooCommerce.v3.WCObject
		where T1 : Coupon
		where T2 : Customer
		where T3 : Product
		where T4 : ProductReview
		where T5 : Variation
		where T6 : Order
		where T7 : OrderNote
		where T8 : OrderRefund
		where T9 : ProductAttribute
		where T10 : ProductAttributeTerm
		where T11 : ProductCategory
		where T12 : ShippingClass
		where T13 : ProductTag
		where T14 : TaxRate
		where T15 : TaxClass
		where T16 : Data
	{
		public StormsWCObject(RestAPI api) : base(api)
		{

		}
	}

	class StormsWCObject : StormsWCObject<Coupon, Customer, Product, ProductReview, Variation, Order, OrderNote, OrderRefund, ProductAttribute, ProductAttributeTerm, 
                                    ProductCategory, ShippingClass, ProductTag, TaxRate, TaxClass, Data>
	{
		public StormsWCObject(RestAPI api) : base(api)
		{

		}
	}

}
```

But still, my new parameter is not recognized:

```
public void GetOrderById()
{
	var order = wc.Order.Get(85).Result;
	Console.WriteLine(order.id + " - " + order.status);
	foreach (var orderMeta in order.meta_data)
	{
		Console.WriteLine(orderMeta.key + " = " + orderMeta.value);
	}

	Console.WriteLine(order.storms_receiptNumber); // <-- Error, property doesn't not exist!
}
```

var order is still an instance of WooCommerceNET.WooCommerce.v3.Order.

What I'm doing wrong here, guys? Thanks for the help!

**Comment by XiaoFaye** [comment]
You only need below code for **StormsWCObject** 

```
namespace WoocommerceSharpClient.WooCommerce
{
	class StormsWCObject : WCObject<Coupon, Customer, Product, ProductReview, Variation, StormsOrder, OrderNote, OrderRefund, ProductAttribute, ProductAttributeTerm, 
                                    ProductCategory, ShippingClass, ProductTag, TaxRate, TaxClass, Data>
	{
		public StormsWCObject(RestAPI api) : base(api)
		{

		}
	}

}
```

**Comment by vinigarcia87** [comment]
Hey, thanks for your answer!
I tried your code, but It return a NullPointException for some reason:

![image](https://user-images.githubusercontent.com/2436945/76483652-578a2f80-63f6-11ea-8846-42c1dd439a08.png)

**Comment by XiaoFaye** [comment]
Add this line to your Order class

![image](https://user-images.githubusercontent.com/6334728/76483904-29036780-647d-11ea-8542-039b87234339.png)

**Comment by vinigarcia87** [comment]
God! It worked! Thank you very much!
I spend a lot of time trying to do this! XD
Hava a good day man!

**Comment by vinigarcia87** [comment]
Hey, hello again!
I have one more question, my WC has many customizations that I need.
One of them that I not sure how to change, is that my CustomerBilling object has some new fields.
But I not able to change this object in the same way that I did on my last post.

What I have done so far is:

Create a new Customerilling class - FYI, cpf, rg, cnpj are brazilian personal documents:
```
namespace WoocommerceSharpClient.WooCommerce
{
	[DataContract]
	class StormsCustomerBilling : WooCommerceNET.WooCommerce.v3.CustomerBilling
	{
		[DataMember]
		public string cpf { get; set; }
		[DataMember]
		public string rg { get; set; }
		[DataMember]
		public string cnpj { get; set; }
	}
}
```
Create a new Customer class, that uses my custom CustomerBilling:

```
namespace WoocommerceSharpClient
{
	[DataContract]
	class StormsCustomer : WooCommerceNET.WooCommerce.v3.Customer
	{
		public new static string Endpoint { get { return "customers"; } }

		/// <summary>
		/// List of billing address data. See Customer - Billing properties
		/// </summary>
		[DataMember(EmitDefaultValue = false)]
		public StormsCustomerBilling billing { get; set; }
	}
}
```
And then, I use my new customer class on StormsWCObject.

The problem is that I get the following error:

> SerializationException: O tipo de contrato de dados 'WoocommerceSharpClient.StormsCustomer' não é serializável com DataContractJsonSerializer porque o membro de dados 'billing' está duplicado em sua hierarquia de tipos.

It says that StormsCustomer is not serializable because 'billing' is duplicated.

Do you have any hint on how can I customize this?
Thanks!

**Comment by vinigarcia87** [comment]
Maybe, mark `public **virtual** CustomerBilling billing { get; set; }` would be enough?

**Comment by vinigarcia87** [comment]
I also tried to extend directly from JsonObject:

```
	[DataContract]
	class StormsCustomer : JsonObject
	{

```

Recreating all the class from zero and using my own billing class... but this triggers an error on WCObject, that expects a Customer class

**Comment by XiaoFaye** [comment]
Remove **DataMember** attribute for **StormsCustomerBilling** seems working, I have tested on my local.
![image](https://user-images.githubusercontent.com/6334728/76589182-1ad14c00-654e-11ea-8f42-55f924b7e88d.png)

**Comment by vinigarcia87** [comment]
Hey, hello again.
Sorry taking so long to answer!
So I tested as you indicate but still, It doesn't work.

I end it up with two billing fields, and the custom one is always null:

![image](https://user-images.githubusercontent.com/2436945/76790492-b278a980-679d-11ea-88b8-e26f957a6607.png)

It doesn't get any error, but also no info on the property.

**Comment by XiaoFaye** [comment]
No, it won't work that way, you must hide the existing billing object. In your case, I would suggest you download the source code and make necessary changes.

**Comment by vinigarcia87** [comment]
Yeah, I started doing this yesterday... There's more modifications that I'll need to do anyways.
Thank you for your patience and all your help!
Also, thanks for this great code! :)
