### ISSUE TITLE
Variaton and product Batch

### ISSUE THREAD

**Issue by Miquel-agp** [XiaoFaye/WooCommerce.NET#571]
- Wordpress version: 5.6.2
- WooCommerce version :4.6.0
- WooCommerce.NET version: 0.8.2
Good morning.
I'm creating a method to update a store's stock, but from what I see, I can only update a batch of variations of a single product at a time, right?
Is there no way to create two batches, 1 of products and one of variations so as not to have to send a batch for each of the parent products?
I've been looking for info for hours and I can't find anything, can they help me?
Thank you very much.

**Comment by firestormza** [comment]
The WooCommerce REST API does not support variation batches for multiple products.
See [Batch Update Product Variations](https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-product-variations) on the Woo API Docs
