### ISSUE TITLE
doesnt work on user machine

### ISSUE THREAD

**Issue by jmurillor** [XiaoFaye/WooCommerce.NET#573]
Hi, sorry for my english.
Thank you for you plugin it works perfectly in my developer machine but when I install the exe with all the libraries it uses on users machine it doesnt works. I also installed the framework 4..7.2. Do I need to install another thing?
I jope you understand my question
Thank you
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by XiaoFaye** [comment]
Where error messages did you get?
