### ISSUE TITLE
How do I delete a tax class?

### ISSUE THREAD

**Issue by gaazkam** [XiaoFaye/WooCommerce.NET#576]
`WCObject.TaxClass.Delete` accepts an `int` parameter, but the `TaxClass` class has no such field. Instead there is the `string slug` field.

As per https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#delete-a-tax-class in order to delete a tax class we need to specify a slug, which is a string, and not an int.

**Comment by XiaoFaye** [comment]
Hi, this is fixed in version 0.8.3.
