### ISSUE TITLE
Catalog visibility hidden products are not returned by get all products

### ISSUE THREAD

**Issue by Yoonwoo** [XiaoFaye/WooCommerce.NET#579]
Wordpress latest Woocommere latest Woocommerce.NET latest

Products that are hidden dont get returned, but private products do.

**Comment by timeframederek** [comment]
Hi, I am not sure what you mean by "hidden" as this is not a normal WooCommerce product state. I suspect you are using a plug in or similar?

The normal product status's are ,,,,

All (1,110) | Published (1,083) | Drafts (2) | Private (25) | Trash (1) | Sorting
