### ISSUE TITLE
GetCustomerByEmail

### ISSUE THREAD

**Issue by vankampenp** [XiaoFaye/WooCommerce.NET#58]
Hi, GetCustomerByEmail was not working for me. So I experimented with Postman and found a solution I wanted to share. 
The code in GetCustomerByEmail is
```
string json = await API.SendHttpClientRequest("customers/email/" + email, RequestMethod.GET, string.Empty, parms);

return API.DeserializeJSon<Customer>(json);
```
           
It did not work, and this is confirmed if I try this in Postman
https://www.mysite.nl/wp-json/wc/v1/customers/email=pieter@mysite.nl

According to the WooCommerce documentation, it should be 
https://www.mysite.nl/wp-json/wc/v1/customers?email=pieter@mysite.nl
However, this returns
[]
For me, and a customer for other email addresses. This is maybe a WooCommerce or Wordpress bug.
This works consistently:
https://www.mysite.nl/wp-json/wc/v1/customers?role=all&email=pieter@mysite.nl
This returns a list of customers, in the exampe above without the role parameter, the result is an empty list

So I changed the code of GetCustomerByEmail to this:

```
string json = await API.SendHttpClientRequest("customers?role=all&email=" + email, RequestMethod.GET, string.Empty, parms);

if (json == "[]") return null;

return API.DeserializeJSon<CustomerList>(json)[0];

```
This code now works for me.

Thanks for making this library available.

Pieter

**Comment by XiaoFaye** [comment]
Thanks a lot!

**Comment by XiaoFaye** [comment]
Hi Pieter, this issue has been fixed in the latest commit: https://github.com/XiaoFaye/WooCommerce.NET/commit/70e4c567256f6297be60e593ddfbaf896cfad26b 

Thanks
