### ISSUE TITLE
Adding a ProductAttributeLine always appears as custom attribute for a product, not predefined

### ISSUE THREAD

**Issue by stevecurrey** [XiaoFaye/WooCommerce.NET#589]
Problem 252 was the same issue but was closed without response.

Adding an attribute line with the same name as a predefined attribute (eg. Capacity) does not link the attribute, it simply creates a custom attribute for that product.

The issues this creates is that variation values are not ordered correctly as per attribute terms on the back office. Also, the attributes are not filterable on the front office.

This is the correct appearance (product added manually)

![image](https://user-images.githubusercontent.com/43680706/112396393-f8911300-8cf7-11eb-8a95-5e65aa6e6c64.png)

This is the appearance using WooCommerceNet:

![image](https://user-images.githubusercontent.com/43680706/112396454-15c5e180-8cf8-11eb-9b29-d7dd445dcdec.png)

Code as follows:
```c#
WooCommerceNET.WooCommerce.v3.ProductAttributeLine productAttributeLine = new WooCommerceNET.WooCommerce.v3.ProductAttributeLine();  
productAttributeLine.variation = true;  
productAttributeLine.name = "Capacity";  
List<string> options = new List<string>();  
options.Add("64GB");  
productAttributeLine.options = options;
```

**Comment by stevecurrey** [comment]
I have just checked the rest of our products and they have all been created in this fashion.

I am assuming everyone else is having this problem?

Thank you

**Comment by XiaoFaye** [comment]
Blow is the correct way to add it. Attribute ID is the key, you must get it and link it with your product.

![image](https://user-images.githubusercontent.com/6334728/112615388-4c7e3200-8e87-11eb-9837-2a1e6e998243.png)

![image](https://user-images.githubusercontent.com/6334728/112615429-5a33b780-8e87-11eb-91d7-982e6c9667aa.png)

![image](https://user-images.githubusercontent.com/6334728/112615482-6ae42d80-8e87-11eb-9125-1c8b87626f0f.png)

**Comment by stevecurrey** [comment]
Thank you Xiao.

So I must first search for the attribute on the store so I get the ID to add to my attribute line.

Thank you

**Comment by stevecurrey** [comment]
I am trying to work through this but I cannot get a product attribute by searching by name. It always returns all of my attributes.

I have tried:

Dic.Add("name", "Capacity");
Dic.Add("search", "Capacity");

var wooCommerceVariationList = await wc.Attribute.GetAll(Dic);

**Comment by XiaoFaye** [comment]
I don't think there is a way you can filter it, get all of them should be fine.
