### ISSUE TITLE
Product addRange returns list with no data

### ISSUE THREAD

**Issue by dugi007** [XiaoFaye/WooCommerce.NET#599]
Hi,

if I understand correctly, product.addRange should return list with inserted data. For example if add list with 5 products, addRange returns list with 5 products, but product data is empty (no id, price etc).

Is this bug, or am I doing something wrong?

Tnx
Vedran

**Comment by firestormza** [comment]
This could be due to an error on the WooCommerce side.
I've submitted a pull request to fix this. #600
