### ISSUE TITLE
Deserialization error because of Windows culture

### ISSUE THREAD

**Issue by siavashgm** [XiaoFaye/WooCommerce.NET#60]
Hi,
- WooCommerce.NET version: 0.5.0.0 I guess

I got this error: " Input string was not in a correct format. " from JsonObject while I was running the software on Windows with Swedish culture! 

To fix this you may change it as bellow: 
JsonObject -> OnDeserialized => line of code:
pi.SetValue(this, decimal.Parse(value.ToString()));
change it to:
pi.SetValue(this, decimal.Parse(value.ToString(), CultureInfo.InvariantCulture));

I haven't seen any other problems, but you may add CultureInfo.InvariantCulture to all ToString functions so may prevent future errors or bugs.

Thank you very much,
Siavash

**Comment by XiaoFaye** [comment]
Hi Siavash, this issue has been fixed in the latest commit: https://github.com/XiaoFaye/WooCommerce.NET/commit/70e4c567256f6297be60e593ddfbaf896cfad26b 

Thanks
