### ISSUE TITLE
How do I prevent WooCommerce.NET from duplicating my image

### ISSUE THREAD

**Issue by audigex** [XiaoFaye/WooCommerce.NET#605]
- Wordpress version , WooCommerce version and WooCommerce.NET version:
All latest

- Steps to replicate the issue
1. Upload an image to Wordpress
2. Create a WooCommerce product, adding a new ProductImage with the URL of the uploaded image above

WooCommerce then seems to create a "filename-1.jpg" image which is a copy of the image just uploaded.

Is there a way to tell WooCommerce.NET NOT to copy the image locally, if I provide a URL for the product image?

- Details of the error message if there is any
None

**Comment by pricerc** [comment]
Doesn't WooCommerce do that if you add one manually?

If so, then this is a WooCommerce problem, not a WooCommerce.NET problem.

**Comment by mumartekhqs** [comment]
Same issue I am facing. My Images are duplicating how we can prevent. I want to create multiple products with Same Image but Images are creating as well.

**Comment by audigex** [comment]
@mumartekhqs I assume you're doing the same thing I did, where you upload the image using the Wordpress API, and then pass the image URL to the WC API?

The solution I found was not to pass the URL, but instead to pass the MediaItem ID that's returned when you upload the media item. That way WC uses the existing attachment, rather than creating a new attachment from the URL you pass
