### ISSUE TITLE
Woocommerce subscriptions .net API

### ISSUE THREAD

**Issue by hbrumfield** [XiaoFaye/WooCommerce.NET#61]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by hbrumfield** [comment]
I have a development group working on a project that needs to read/write to the subscriptions plugin for woocommerce.  I wanted to find out if it was possible to use the .net API perform functions within the woocommerce subscriptions plugin such as create or modify a subscriptions information.  I need it to be able create new subscriptions, modify the start date, put the subscription on hold, change pricing as well as a few other functions.  Any info would be greatly appreciated.

**Comment by XiaoFaye** [comment]
You will need to do some custom development on the WC REST API. If you want to discuss more, please contact me via xiaofaye(a)msn(dot)com . Cheers!
