### ISSUE TITLE
Product id is an uint but Product Delete and Update need a uint.

### ISSUE THREAD

**Issue by PuntoSistemi** [XiaoFaye/WooCommerce.NET#611]
Good Morning, I am using v3 of the WooCommerce.NET API and I can see inconsistencies in the type of the various id fields.

As stated in the title, there are inconsistencies in the parameters needed for the Product class, but also for other classes.

Can you please give a look at all the classes and make the paramtere types consistent? Otherwise a cast is always needed.

Ot let me know if I misunderstood something.

Thanks in advance

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.8.4, sorry for the delay.
