### ISSUE TITLE
Internal class objects need to be updated

### ISSUE THREAD

**Issue by giotabidze** [XiaoFaye/WooCommerce.NET#613]
In latest version, internal object classes need to be updated

v3.Order inherits from v2.Order, which has List<OrderMeta> property, when getting order by id,  tracking number item value can not be deserialized and has type of {object}

**Comment by firestormza** [comment]
There is no tracking number property in the Woo API. If using an external plugin you'll have to de-serialize the object yourself from meta_data. [See here](https://github.com/XiaoFaye/WooCommerce.NET/wiki/Handle-different-types-of-Meta-Value-in-WC-Restful-API-V2)
