### ISSUE TITLE
ID properties overflow

### ISSUE THREAD

**Issue by gkverneland** [XiaoFaye/WooCommerce.NET#615]
Referring to an issue that has not been solved correctly: https://github.com/XiaoFaye/WooCommerce.NET/issues/560

It fails for example when downloading an order with ID 61000150083 because of overflow when converting to a 32-bit unsigned integer. The ID propery should be changed to 64-bit.

**Comment by niikoo** [comment]
+1

**Comment by XiaoFaye** [comment]
Sorry for the confusion, all ID type will be changed to unsigned long in the next version.

**Comment by niikoo** [comment]
> Sorry for the confusion, all ID type will be changed to unsigned long in the next version.

When will the new version be released?

**Comment by nvsoares** [comment]
We are preparing a new release of our system and wanted to use version 0.8.3 because it already Allow authenticate Woocommerce API with JWT. It would be very helpful to have an idea When will the new version be released.

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.8.4, sorry for the delay.
