### ISSUE TITLE
Support ?rest_route=

### ISSUE THREAD

**Issue by niikoo** [XiaoFaye/WooCommerce.NET#616]
- Wordpress version, WooCommerce version and WooCommerce.NET version

Wordpress 5.7.2
WooCommerce 5.3.0
WooCommerce.NET 0.8.3

- Steps to replicate the issue

Using /?rest_route= instead of /wp-json throws an exception. /?rest_route=/wc/v3/ for example can be used when permalinks are disabled. 

- Details of the error message if there is any

**Comment by gkverneland** [comment]
+1

**Comment by niikoo** [comment]
Seems like it's only supported by WordPress, not WooCommerce.
