### ISSUE TITLE
Order Notes

### ISSUE THREAD

**Issue by ian-jeffery** [XiaoFaye/WooCommerce.NET#617]
Although I can see the OrderNote object, there is no OrderNote on teh WCObject class. How do i get the OrderNotes for an Order ?

**Comment by firestormza** [comment]
You need to retrieve the notes for each order using the Order Notes endpoint:
```
List<OrderNote> notes = await wc.Order.Notes.GetAll( orderId );
```
[See Woo Docs](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-notes)
