### ISSUE TITLE
Order.GetAll(Dictionary<string,string>) There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Order, WooCommerce.NET, Version=0.8.3.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. End element 'display_value' from namespace '' expected. Found element 'id' from namespace ''.

### ISSUE THREAD

**Issue by DoubleD82** [XiaoFaye/WooCommerce.NET#618]
Referring to https://github.com/XiaoFaye/WooCommerce.NET/issues/606#issue-874609717

I started getting the above mentioned error today and as far as I am aware, Wordpress and Woocommerce has not been updated.

My Wordpress version is: 5.5.3
My Woocommerce version is 4.9.1

If I just run Order.GetAll(), it runs, but only gets 10 orders.
This is quite an urgent issue. How do I go about resolving this error

**Comment by ac2894** [comment]
I exactly the same Issue @DoubleD82 have you resolved this for the moment? or still the issue persist?

**Comment by DoubleD82** [comment]
I still have this problem. My WooCommerce version is actually 5.3.0 and not 4.9.1 as previously stated

**Comment by ac2894** [comment]
Well I forked the repository and added this to my project dependencies, That was sufficient for me all Works fine

**Comment by DoubleD82** [comment]
Thanks. I forked it and added it to my references and now it's working.

**Comment by ian-jeffery** [comment]
added what to your references ?

**Comment by ac2894** [comment]
The Project, I just forked because I needed in my project organization but you can clone the project and add to your dependencies

**Comment by timeframederek** [comment]
All, we are not seeing this issue with the older WooCommerce.NET even with some of the causing plugins installed adding this data. this is only happening for us on the current WooCommerce.NET and with a bundling plugin adding to order data making the data unable to deserialise. Is this a duplicate of #606

**Comment by firestormza** [comment]
The issue has been fixed in PR #600 but is has not been released yet. That's why when you forked and built the source it worked.

**Comment by DoubleD82** [comment]
Thanks for everyone's assistance and input. I will close this issue now as it is a duplicate of others and for now, it has been resolved forking the source and building it.
