### ISSUE TITLE
wc.Customer.UpdateRange(cb).Result hanging without error

### ISSUE THREAD

**Issue by hdnhdn** [XiaoFaye/WooCommerce.NET#623]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
WooCommerce:  0.8.3 WooCommerce.NET
Wordpress: Version 5.7.2
WooCommerce: Version 5.4.1

- Steps to replicate the issue

if i make an update over update range is hanging no response no error no timeout. the application is hanging day and week on..

the problematic line ist the Result 
` Dim c = wc.Customer.UpdateRange(cb).Result`

work
` Dim c = wc.Customer.UpdateRange(cb)`

- Details of the error message if there is any
no error no timeout only hanging. its happend without update on booth side...

**Comment by hdnhdn** [comment]
The Problem are solved by deaktivate Polylang plugin in Woocommerce!

**Comment by hdnhdn** [comment]
The Probleme ist after installing Microsoft Update KB5003637
when i delete it it works perfekt..

after reinstalling KB5003637 the update is hanging..

**Comment by hdnhdn** [comment]
Anny News?

**Comment by gaazkam** [comment]
(Note that I don't know VisualBasic - I'm assuming it works more or less like the similar C# code would work, so I may be wrong)

Do you really need to use `.Result`? Doing so [is a recipe for deadlocks unless you know what you're doing](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

The general recommendation is to avoid `.Result` whenever possible, and instead always use `await`.

Please read this: https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/
