### ISSUE TITLE
Trying to update a meta_data > value field with an object, detects an unexpected character 'T'

### ISSUE THREAD

**Issue by MatisFl** [XiaoFaye/WooCommerce.NET#626]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

Latest WooCommerce.NET, it only affect the API

- Steps to replicate the issue

I would like to replicate this metadata = 

> {
id: 1
key: "_wc_shipment_tracking_items"
value: {
          test: "true"
          }
}

it's just an example, but i would like to achieve something similar.
the only problem is that when I try to compile, the command wc.Order.Update returns an exception

> XmlException : Encountered unexpected character 'T'.

source code : 

> RestAPI rest = new RestAPI(url, key, secret, false);
>             WCObject wc = new WCObject(rest);
>             
>             Order order = new Order();
> 
>             List<WooCommerceNET.WooCommerce.v2.OrderMeta> metadata = new List<WooCommerceNET.WooCommerce.v2.OrderMeta>
>             {
>                 new WooCommerceNET.WooCommerce.v2.OrderMeta
>                 {
>                     id = 1,
>                     key = "_wc_shipment_tracking_items",
>                     value = new
>                     {
>                         test = "true"
>                     }
>                 }
>             };
> 
>             order.meta_data = metadata;
> 
>             await wc.Order.Update(id, order);

The problem here is the value field, when I set the value to "true" for example, the field is correctly updated, but when i want to set the value to an object, to generate json, the error occurs

- Details of the error message if there is any

> System.Runtime.Serialization.SerializationException : 'There was an error deserializing the object of type WooCommerceNET.WooCommerce.v3.Order. Encountered unexpected character 'T'.'

**Comment by DarSitam** [comment]
Ok, so I found an alternative solution

```
public async Task CreateTracking(int order_id, string trk_provider, string trk_number)
        {
            string tracking_url = String.Format($"{url}orders/{order_id}/shipment-trackings");
            object post_object = new
            {
                tracking_number = trk_number,
                tracking_provider = trk_provider
            }; 

            using (var httpClient = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("POST"), tracking_url))
                {
                    var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes(key + ":" + secret));
                    request.Headers.TryAddWithoutValidation("Authorization", $"Basic {base64authorization}");

                    request.Content = new StringContent("JSON HERE");
                    request.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");

                    var response = await httpClient.SendAsync(request);
                }
            }
        }
```
