### ISSUE TITLE
User-friendly Attribute Names and Values to Order Line Items Metadata not Work - please add

### ISSUE THREAD

**Issue by hdnhdn** [XiaoFaye/WooCommerce.NET#627]
the new change & changes in Core version of Woocommerce 
look like this:
https://github.com/woocommerce/woocommerce-rest-api/pull/229

not worked with the version 0.83 please add the 2 fields to the wrapper..
if you need more information please contact me..

**Comment by XiaoFaye** [comment]
This has been fixed in version 0.8.4, sorry for the delay.
