### ISSUE TITLE
I can not get all products

### ISSUE THREAD

**Issue by halityilmaz1982** [XiaoFaye/WooCommerce.NET#628]
Hi,

I try to get all products with pagination with code below.
` RestAPI rest = new RestAPI(ClsWooCommerce.siteAdresi + "/wp-json/wc/v1/", ClsWooCommerce.apiAnahtari, ClsWooCommerce.apiGizliAnahtari);
                    WCObject wc = new WCObject(rest);
                    List<Product> urunListesi = new List<Product>();
                    Dictionary<string, string> parametreler = new Dictionary<string, string>();
                    parametreler.Add("per_page", "100");
                    parametreler.Add("status", "publish");
                    parametreler.Add("page", sayfa.ToString());
                    bool whileSonu = false;
                    while (!whileSonu)
                    {
                        var urunTemp = wc.GetProducts(parametreler);
                        if (urunTemp.Result.Count > 0)
                        {
                            urunListesi.AddRange(urunTemp.Result);
                            sayfa++;
                            parametreler["page"] = sayfa.ToString();
                        }
                        else
                        {
                            whileSonu = true;
                        }
                    }`

When I debugged the code it works fine till the last page. But at the end of process I have an error about retrieving products. 

The error code (inner exception message) is: System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v1.Product, WooCommerce.NET, Version=0.8.3.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]] türünde nesnesi serisini kaldırmada bir hata oluştu. '93.75' değeri, 'Int32' türü gibi ayrıştırılamaz. (this is in Turkish). 

The translated error message is: There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v1.Product, WooCommerce.NET, Version=0.8.3.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. The value '93.75' cannot be parsed like type 'Int32'.

I also tried the same code with v3. I got the incorrect type error message on it. 

Can you please tell me what I am doing wrong. Where is the error on my code?

Thank you.

**Comment by gaazkam** [comment]
What is the error message for v3 and do your orders use coupons?

**Comment by halityilmaz1982** [comment]
I get this message for v3:
`System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.3.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]] türünde nesnesi serisini kaldırmada bir hata oluştu. Giriş dizesi doğru biçimde değildi.`

in Eng.

`There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.Product, WooCommerce.NET, Version=0.8.3.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. The input string was not in the correct format.`

**Comment by halityilmaz1982** [comment]
I get theese messages on get product methodes not for orders.

**Comment by gaazkam** [comment]
Ah, sorry, my bad, apparently I cannot read :) Sorry for noise, please disregard what i wrote.

**Comment by halityilmaz1982** [comment]
I get this error message at the last page of product list.

**Comment by gaazkam** [comment]
What does this product have?

Because for example orders produce similar errors if they use coupons (I hope they finally fix this). I didn't read carefully and I assumed this was also your problem, but it's clearly not, since your problem are products and not coupons.

Still I would be very interested to know when will products fail to deserialize.

**Comment by halityilmaz1982** [comment]
I try to get the list of all products.

I will use my own code I think. Because I lost too much time.
