### ISSUE TITLE
Null User-Agent header gives error 403 Forbidden

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#63]
Wordpress version: 4.6.1
WooCommerce version: 2.6.8
WooCommerce.NET version: 0.5.3

I'm trying the code on the Readme.md to retrieve products:
```
     RestAPI rest = new RestAPI(ApiWoo, ComsumerKey, SecretKey);
     WCObject wc = new WCObject(rest);
     //Get all products
     var products = await wc.GetProducts();
```
 I get the http error code 403.
I found that the problem is that the HTTP Header User-Agent is null at RestAPI/SendHttpClientRequest.

I manage to get it to work using the following method to establish a UserAgent after the HttpWebRequest was created:
```
        public void SetHeader(HttpWebRequest Request, string Header, string Value)
        {
            PropertyInfo PropertyInfo = Request.GetType().GetRuntimeProperty(Header.Replace("-", string.Empty));
            if (PropertyInfo != null)
            {
                PropertyInfo.SetValue(Request, Value, null);
            }
            else
            {
                Request.Headers[Header] = Value;
            }
        }
```

Am I doing something wrong? Are there any workaround?

I tried to use the version 0.6.0 but it gives me an error becose BatchObject is not detected.
It also gives me an error at the SendHttpClientRequest Exception becouse it says that await shouldn't be used on catch body:` throw new Exception(await GetStreamContent(we.Response.GetResponseStream(), we.Response.ContentType.Split('=')[1]));`

**Comment by XiaoFaye** [comment]
Hi, could you mind sending me a set of API keys (read only) so I can have a look? please send to my email address xiaofaye(a)msn(dot)com

**Comment by goguvi** [comment]
Ok, i just sent them to you.
I also saw that the BatchObject problem was discussed in the issue 'Missing BatchObject??? #64'

Thanks for your help.

**Comment by XiaoFaye** [comment]
I have committed some new code, which will allows you to fix this issue easily. See below:
```
//Define a sub:
private void request(HttpWebRequest arg)
        {
            arg.UserAgent = "teset";
        }

//assign it to the requestFilter parameter in RestAPI constructor.
Var rest2 = new RestAPI("http://www.yourstore.com/wp-json/wc/v1/",
                                    "ck_1xxxxx5b4a236cdb9ce",
                                    "cs_1exxxxxxxx33ced5c27b", requestFilter: request);
```

**Comment by goguvi** [comment]
Thanks. I just check commit 2329d00 changes and apply them as you suggested to my tests, know it works pretty well.

**Comment by toddmillernyc** [comment]
Tried this wrapper today; got the same error with the v1 or v2 version.

Thanks,
-Todd
