### ISSUE TITLE
Using latest version 0.8.3.0 

### ISSUE THREAD

**Issue by bilpor** [XiaoFaye/WooCommerce.NET#630]
Following the code example to obtain orders peer page with the following code:

```
using WooCommerceNET.WooCommerce.v3;
using WooCommerceNET.WooCommerce.v3.Extension;

RestAPI rest = new RestAPI(endpoint, consumerkey, woosecret);
                WCObject wc = new WCObject(rest);

                var order = await wc.Order.GetAll(new Dictionary<string, string>()
                {
                    { "page", "1" },
                    { "per_page", "15" }
                });
```

Errors with: **Unknown WooCommerce Restful API version.**

**Comment by haseebmukhtar** [comment]
Hi
Can you tell us URL? Seem you are passing wrong url. 
e.g. URL for v3 should be .. https://youwebapplication.com/wp-json/wc/v3

**Comment by bilpor** [comment]
THe WooCommerce library i am referencing is runtime version v4.0.30319 with a Version 0.8.3.0 The link you have given above cannot be reached. I Installed via the Nuget Package Manager and selected 'WooCommerceNet' by JamesYang@NZ  and it says Latest Stable 0.8.3.

**Comment by XiaoFaye** [comment]
@bilpor How did you pass the endpoint? Can you give a screenshot with sensitive information blur?

**Comment by bilpor** [comment]
I passed the endpoint in the form "https://mywebsite.com/wp-json/wc/v3/"
