### ISSUE TITLE
Getting error while call the woocommerce endpoint

### ISSUE THREAD

**Issue by nithinak** [XiaoFaye/WooCommerce.NET#632]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

System.Net.WebException: '{"code":"jwt_auth_bad_auth_header","message":"Authorization header malformed.","data":{"status":403}}'

I am able to make requests with HTTPCLIENT with the same consumer_key and consumer secret

**Comment by haseebmukhtar** [comment]
Hi
Are you using Blazor or .Net6. They don't support HttpWebRequest. Adding support for HttpClient in this library.
