### ISSUE TITLE
Wonder if you're OK James

### ISSUE THREAD

**Issue by sterenas** [XiaoFaye/WooCommerce.NET#633]
Hi James,
Not really an issue, just noticed you haven't been around for a while and was wondering if you're doing ok.  Hopefully you're just busy at work  but we do miss your always helpful replies.
Greetings,
Sergio

**Comment by XiaoFaye** [comment]
@sterenas Hi, thanks for reach out, I'm all good. Sorry didn't have much time to maintain the project, as I'm crazy busy with my current job at the moment. Hopefully I can get some time to look at the issues later this month.
