### ISSUE TITLE
get id product

### ISSUE THREAD

**Issue by MorfeoIT** [XiaoFaye/WooCommerce.NET#635]
Hi,
how can I get product id when i add a new product?

 ### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by mirco261** [comment]
Hi, 

you can look here, how to add product ( PtrStruct head post):
[https://github.com/XiaoFaye/WooCommerce.NET/issues/488]

and on the last line of code you can return added product to variable... 
`Product newProduct = await wc.Product.Add(p);
`

and in newProduct.id is the id of added product.

**Comment by MorfeoIT** [comment]
thanks a lot
