### ISSUE TITLE
Add image in a product with vb.net

### ISSUE THREAD

**Issue by MorfeoIT** [XiaoFaye/WooCommerce.NET#636]
Hi all,
1. how can i add images in a product with vb.net using V3

2. how can i add category in a product with vb.net using V3

thanks.

 ### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by fredoche1810** [comment]
Hello @MorfeoIT,
Did you find the solution ?
I already checked #419 but I can't have it working with me
![image](https://user-images.githubusercontent.com/13088049/147935622-a4a4cd54-d5d1-48c5-b7f0-664f327b8e3a.png)

I receive the following error : System.Runtime.Serialization.SerializationException : 'There was an error deserializing the object of type WooCommerce.NET.WordPress.v2.Media. Encountered unexpected character 'o'.'

Thanks,
