### ISSUE TITLE
Multilanguage feature

### ISSUE THREAD

**Issue by fredoche1810** [XiaoFaye/WooCommerce.NET#648]
- Wordpress version : 5.8.1
- WooCommerce version : 5.6.0
- WooCommerce.NET version : 0.8.3

Hello,
First thanks for your project to connect Woocommerce to .net apps
I'm looking for the possibility to add different languages to my website.
If I'm right, I need to install an extension do add this function.
But after that, I need to be able to add or updates products and categories in different languages.
I saw an extension like WPML but will it work with your project ?
Did someone use it ? Is it possible to receive a sample of code ?
Thanks in advance,
Fredoche1810

**Comment by bulkasergei** [comment]
Yes it works fine, 
  It's very simple by using WooCommerce.NET.
Create a dictionary with products meta and assign to method.

 var dic = new Dictionary<string, string>();
            res.Add("lang", "en");
            WCObject wc = new WCObject(rest);  
var Products =  await wc.GetAll(rest,dic);

**Comment by fredoche1810** [comment]
@bulkasergei 
Thanks for you answer.
I suppose in your sample that lang is the meta field added with the module acf right?
Or is it an extra field you add manually in the database?
I already tried with the dictionary but even what I tried, it always return all the products in case of one product 
Thanks in advance,
