### ISSUE TITLE
How can get WooCommerce Software Licensing Activate

### ISSUE THREAD

**Issue by trungdh** [XiaoFaye/WooCommerce.NET#65]
Hello Mr Xiao Faye !
I'm sorry for disturb you again :) 
If Woocommerce system use **woocommerce-software-add-on plugin**. And the s**oftware license keys** will be stored in **wpnc_woocommerce_software_licences** table of Woocommerce's Database.
Do you know **any way** or **endpoint url** to provide API which help get all license string by a customer, Mr Xiao Faye ?
I've searched in Woocommerce API document, but I can not found any documents for that API.
Maybe I have to write an API on Woocommerce system by myself to provide that API, is it right ? Mr Xiao Faye.

**Comment by XiaoFaye** [comment]
Yes, you have to write your own API to get the data.
