### ISSUE TITLE
SSL expired error when certificate is not expired

### ISSUE THREAD

**Issue by audigex** [XiaoFaye/WooCommerce.NET#652]
When calling Product.Images.Add() followed by Product.Add(), I get an error 

    SSL certificate problem: certificate has expired

However, when requesting the URL that's throwing the error, the certificate doesn't expire for another 2 and a half months

    https://buildabundle.co.uk/wp-content/uploads/2021/10/B-0003-12434.jpg

Wordpress version: 5.8.1  
WooCommerce version: 5.7.1  
WooCommerce.NET version: 0.8.3  

- Steps to replicate the issue

1. Upload a file using wordpress's Media.Create()
2. Call product,images.Add() with the URL of the file created above
3. Call Product.Add()

On calling Product.Add in WooCommerce.NET, I get the SSL error, despite the domain's SSL certificate being fine

- Details of the error message if there is any
- 
{
  "code": "woocommerce_product_image_upload_error",
  "message": "Error getting remote image https://buildabundle.co.uk/wp-content/uploads/2021/10/B-0003-41242.jpg. Error: cURL error 60: SSL certificate problem: certificate has expired",
  "data": {
    "status": 400
  }
}

**Comment by CarlesFerrerBelda** [comment]
I have the same problem
