### ISSUE TITLE
REad Response Header for X-WP-Total and X-WP-TotalPages

### ISSUE THREAD

**Issue by gitgiangalbe** [XiaoFaye/WooCommerce.NET#653]
WP: 5.8
Woo.net:  0.8.3

i can't find how to read the response header.
i need to read two variable in header i.e. X-WP-Total and X-WP-TotalPages.
is it possible with this library ?
Thanks

**Comment by XiaoFaye** [comment]
Have you checked this?

![image](https://user-images.githubusercontent.com/6334728/142710358-4b943295-d3fa-45af-b255-44ddab9f3c76.png)
