### ISSUE TITLE
Create and get products Brans

### ISSUE THREAD

**Issue by soytomassr** [XiaoFaye/WooCommerce.NET#657]
Hellow

Why Is not possible to create and manage products Brands?

 
- WooCommerce.NET version 0.8.3.0

Thanks 
Tomás.

**Comment by zecurecode** [comment]
You can by adding and managing brand as product meta. You will then need a script that check for your added meta to convert it into brands based on your brand plugin, as brand is not a native woocommerce function. If you still need it, I can share a working script and code.
