### ISSUE TITLE
Authentication issue with HTTPS

### ISSUE THREAD

**Issue by vankampenp** [XiaoFaye/WooCommerce.NET#66]
Hi James,
I have an authentication issue on HTTP, using /wc/v1/.  "woocommerce_rest_cannot_view"
It is seems a server issue, I get it with Postman as well.
The WooCommerce documentation [https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https ](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https ) states:

**Occasionally some servers may not parse the Authorization header correctly (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters instead.**

Puting the key/secret as query strings works for me, so I changed SendHttpClientRequest to accomodate that. I had to add all parameters manually:
```

            StringBuilder sb = new StringBuilder();
                if (parms == null)
                {
                    parms = new Dictionary<string, string>();
                }
                parms.Add("consumer_key", wc_key);
                parms.Add("consumer_secret", wc_secret);
                foreach (var pair in parms)
                {  
                    sb.AppendFormat("{0}={1}&", HttpUtility.UrlEncode(pair.Key), HttpUtility.UrlEncode(pair.Value));
                }
                string url = "";
                url = (sb.Length > 0) ?  "?" + sb.ToString().Replace("%5b", "%5B").Replace("%5d", "%5D") : "";
                url = wc_url + endpoint + url;
               httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
               
              // start the stream immediately
                httpWebRequest.Method = method.ToString();
                 httpWebRequest.AllowReadStreamBuffering = false;
                
                //if (wc_Proxy)
                //    httpWebRequest.Proxy.Credentials = CredentialCache.DefaultCredentials;
                //else
                //    httpWebRequest.Proxy = null;
                
                if (requestBody.GetType() != typeof(string))
                {
                    var buffer = Encoding.UTF8.GetBytes(SerializeJSon(requestBody));
                    Stream dataStream = await httpWebRequest.GetRequestStreamAsync();
                    dataStream.Write(buffer, 0, buffer.Length);
                       httpWebRequest.ContentType = "application/json"; //moved as it does not work with query string when there is no body
           
                }
               ...

```

**Comment by XiaoFaye** [comment]
Could you please download the latest code from GitHub?
 
In version 0.6.0, there is a new argument “authorizedHeader” in the constructor of RestAPI. By default it’s true, which means the key/secret will be passed in the header, you can set it to False to it will be passed in query string.

**Comment by vankampenp** [comment]
mm, tried that, it also gives "woocommerce_rest_cannot_view". My assumption is that Woocommerce want the parameters with the keywords "consumer_key=" and "consumer_secret=" on the query string, and NetworkCredentials does not provide that. 

It works for me like this:

```

         if (AuthorizedHeader)
                    {
                        httpWebRequest = (HttpWebRequest)WebRequest.Create(wc_url + GetOAuthEndPoint(method.ToString(), endpoint, parms));

                        httpWebRequest.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(wc_key + ":" + wc_secret));
                    }
                    else
                    {
                        if (parms == null)
                        {
                            parms = new Dictionary<string, string>();
                        }
                        parms.Add("consumer_key", wc_key);
                        parms.Add("consumer_secret", wc_secret);

                        httpWebRequest = (HttpWebRequest)WebRequest.Create(wc_url + GetOAuthEndPoint(method.ToString(), endpoint, parms));

                    }


```


I also need to put the ContentType setting in the "if (requestBody.." block, otherwize I get a "rest_invalid_json" error from WooCommerce.

 ```
     if (requestBody.GetType() != typeof(string))
                {
                    var buffer = Encoding.UTF8.GetBytes(SerializeJSon(requestBody));
                    Stream dataStream = await httpWebRequest.GetRequestStreamAsync();
                    dataStream.Write(buffer, 0, buffer.Length);
                    httpWebRequest.ContentType = "application/json";

                }
```

Last and least, I need to add the role=all to the GetCustomerByEmail because WooCommerce does not return my user info without it. (It does not hurt for others as it returns one customer anyway).



```

public async Task<T2> GetCustomerByEmail(string email)
        {
            string json = await API.SendHttpClientRequest("customers", RequestMethod.GET, string.Empty, new Dictionary<string, string>() {
                {"email", email }, {"role","all" }
            });

            List<T2> c = API.DeserializeJSon<List<T2>>(json);
            if (c.Count == 0)
                return null;
            else
                return c[0];
        }


```


But I can also use GetCustomers and add the parameters my self.

If you think it should work with the NetworkCredentials, I am happy to provide you with a set of keys to test it with my WooCommerce shop.

**Comment by XiaoFaye** [comment]
Thanks for all the information, I will have a look ASAP.

**Comment by XiaoFaye** [comment]
Hi, I have made below changes to fix your issues:

1. When AuthorizedHeader = False, the key/secret are passed as query string.
2. The ContentType only be set when there is a request body, you should not get the error now.
3. For GetCustomerByEmail, you only need to pass {"role","all" } now.

**Comment by vankampenp** [comment]
That looks great! Thank you for all your work. I will incorporate this version, and experiment with the new set up to specify addition fields in Customer and Orders.

 

Pieter

 

 

 

Van: James Yang [mailto:notifications@github.com] 
Verzonden: zaterdag 10 december 2016 00:09
Aan: XiaoFaye/WooCommerce.NET <WooCommerce.NET@noreply.github.com>
CC: Pieter <pieter@datec.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [XiaoFaye/WooCommerce.NET] Authentication issue with HTTPS (#66)

 

Hi, I have made below changes to fix your issues:

1.	When AuthorizedHeader = False, the key/secret are passed as query string.
2.	The ContentType only be set when there is a request body, you should not get the error now.
3.	For GetCustomerByEmail, you only need to pass {"role","all" } now.

**Comment by XiaoFaye** [comment]
Hi @vankampenp , version 0.6.0 is on Nuget now.
