### ISSUE TITLE
wrong webResponse throw 403 forbiden

### ISSUE THREAD

**Issue by novinp** [XiaoFaye/WooCommerce.NET#660]
hi
when i call GetAll orders to receive last 10 orders
 *per_page=10
  *order=desc
  *orderby=date   

receive 403-forbiden
test with same parameteres on postman=>worked

my problem has been solved by add this line :

if (string.IsNullOrEmpty(httpWebRequest.UserAgent)) httpWebRequest.UserAgent = "my app name";
WebResponse wr = await httpWebRequest.GetResponseAsync().ConfigureAwait(false);

**Comment by XiaoFaye** [comment]
This could help: https://github.com/XiaoFaye/WooCommerce.NET/wiki/Specifiy-user-agent-when-making-requests-to-WooCommerce
