### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Marvinvdl** [XiaoFaye/WooCommerce.NET#665]
Hi, I'm getting this error 

System.AggregateException: 'One or more errors occurred. (<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
)'

and this is my code :

RestAPI rest = new RestAPI("http://www.sweetdigitalagency.com/wp-json/wc/v3/", "ck_*******", "cs_*******");
           
            WCObject wc = new WCObject(rest);

            //Get all products
            var products =  wc.Product.GetAll().Result;

Can you give me some advice?

Thanks

**Comment by XiaoFaye** [comment]
Please check your hosting environment, this could be a permission issue.

**Comment by JhonatanRamirezS** [comment]
Hi Marvinvdl, I am facing the same issue, Was you able to fix it?

all the best!

**Comment by Marvinvdl** [comment]
> Hi Marvinvdl, I am facing the same issue, Was you able to fix it?
> 
> all the best!

Hi JHonatanRamirezS,

Sorry for the late replay. I had a couple of times an error one was becouse the host didn't accept connections from outside. The other one's was because it was on a subdomain and woocommerce installation was not completed.

If you send your code I can look at it for you.

Good luck,

Marvin
