### ISSUE TITLE
The Get method takes a 32-bit integer, should be 64-bit

### ISSUE THREAD

**Issue by gkverneland** [XiaoFaye/WooCommerce.NET#666]
Referring to this issue: https://github.com/XiaoFaye/WooCommerce.NET/issues/615

This has not been fully fixed since the Get method still takes a 32-bit integer, while it should take a 64-bit integer since IDs can be for example 61000150083. Downloading a product with ID 61000150083 is still not possible.

**Comment by XiaoFaye** [comment]
Thanks, this will be fixed in the next version ASAP.😂

**Comment by RoeiKO** [comment]
@XiaoFaye Hi
related_ids on the Product class should also be an Int64
`{"JSON integer 50001672461251 is too large or small for an Int32. Path '[0].related_ids[0]', line 1, position 2561."}`

**Comment by XiaoFaye** [comment]
@RoeiKO Thanks for pointing out, will fix it in the next version.

**Comment by gkverneland** [comment]
@XiaoFaye when are you planning to release the next version?
