### ISSUE TITLE
Invalid Json body on requests with WP 4.7

### ISSUE THREAD

**Issue by dandersson79** [XiaoFaye/WooCommerce.NET#67]
I updated my WordPress (to 4.7) and WooCommerce (to 2.6.9) today in order to fix a problem with a shipping pluging. That plugin now works, but I have instead gotten a known problem with the API: any request I make using WooCommerce.NET throws an exception with the error "invalid JSON body".
This appears to be a WordPress issue https://github.com/woocommerce/wc-api-php/issues/68, but I wanted to mention it here in case someone else is struggling with this as well.
Also, if there is a quick fix for this in WooCommerce.NET, it would be much, much appreciated. But, like I said, it's a WordPress issue, so I don't mean to bother you with this.

**Comment by XiaoFaye** [comment]
Thanks for bringing this to my attention, will try to fix it ASAP!

**Comment by bryceadams** [comment]
You'll need to update to WordPress 4.7.1 when it's released - 4.7.0 was the version that introduced the issue.

**Comment by dandersson79** [comment]
Thanks for looking into it.
Is the fix already available through NuGet? Or will you wait until 0.6.0 is ready?

**Comment by XiaoFaye** [comment]
will wait until 0.6.0 is ready, should be in NuGet next week.

**Comment by XiaoFaye** [comment]
Hi @dandersson79 , version 0.6.0 is on Nuget now.

**Comment by dandersson79** [comment]
thanks @XiaoFaye. Unfortunately the fix didn't help me. I still get the same error. Is there perhaps something I need to change in my client/requests for it to work?

**Comment by XiaoFaye** [comment]
@dandersson79 , are you doing GET or POST? In version 0.6.0, it will only set the Content-Type when there is a request body like POST or PUT.

**Comment by XiaoFaye** [comment]
Sorry @dandersson79 , I had published the wrong DLL file in version 0.6.0, another version 0.6.1 has been created with the correct DLL, you should be able to see it in NuGet now.

**Comment by dandersson79** [comment]
@XiaoFaye I'm actually mostly in need of GETs at this point, I probably should have made that clear. thanks for clarifying though, I really appreciate how quickly you react and the great work you put in!
I will test POST and PUT though, as I'm using that from time to time
would you like me to create a separate issue for GET calls, just to keep track of things? as I said in my original post, I understand that this is a WordPress issue, so I don't mean to pile work on you

**Comment by Lavkushwaha** [comment]
I tried this for my Improper Json 

`try {
    // Array of response results.
    $results = $woocommerce->get('products'); //this will catch JSON
    // Example: ['products' => [[ 'id' => 8, 'created_at' => '2015-05-06T17:43:51Z', 'email' => ...
    
	$json_string = json_encode($results, JSON_UNESCAPED_SLASHES); //this will convert data into JSON
	
	
    \print_r($json_string);//print JSON
}
catch () {
    }`
