### ISSUE TITLE
406 Not Acceptable ( New product )

### ISSUE THREAD

**Issue by monxu88** [XiaoFaye/WooCommerce.NET#678]
- Wordpress version 5.8.3
- WooCommerce version 5.7.0 
- WooCommerce.NET version 0.8.4

Hi!
Use VB.Net, with framework 4.7.
I can list products, but when I want to register a product, this error appears:
![imagen](https://user-images.githubusercontent.com/73131709/148796876-47a454fb-b5cf-4ca3-bcab-3aae64cfe4eb.png)

**Comment by monxu88** [comment]
any ideas?

**Comment by monxu88** [comment]
If I do everything manually, without this API, it gives me the same error (406), but I can solve it by adding the Accept */* header, but with this API I don't know how I can add a header , any ideas?

**Comment by XiaoFaye** [comment]
https://github.com/XiaoFaye/WooCommerce.NET/wiki/How-to-use-webRequestFilter-and-webResponseFilter-in-WooCommerce.NET
