### ISSUE TITLE
Cannot Retrieve certain products using dictionary

### ISSUE THREAD

**Issue by chrisvell88** [XiaoFaye/WooCommerce.NET#688]
### Make sure you have included the below details when open an issue. Thank you.

Hi, 

I am using the code below to retrieve products. Strangely enough on certain items, searching by SKU returns the following error. I have compared these items to items which work using the same code and there is no evident difference between them. We are using the latest version of Wordpress & Woocommerce. 

 Dictionary<string, string> pDic = new Dictionary<string, string>();
                    pDic.Add("sku", txtBarcode.Text);

             
                    RestAPI rest = new RestAPI("https://URL/wp-json/wc/v2/", App.WooCons, App.WooSec);
                    WCObject wc = new WCObject(rest);
                    
                    App.wooProducts = await wc.Product.GetAll(pDic); //ERROR HAPPENING ON THIS LINE
                    
ERROR:

Fatal error</b>:  Uncaught Error: Call to a member function get_attributes() on bool in /public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php:463
                    
                    
I would appreciate your urgent assistance on the matter.

**Comment by chrisvell88** [comment]
Hi, any update on this issue please??

**Comment by FabPari** [comment]
Try to connect to
yourwebsite.com/wp-json/wc/v3/

**Comment by chrisvell88** [comment]
Hi Fabio,

Tried that but still the same

**Comment by XiaoFaye** [comment]
It's likely one of your plugins causing this problem.
