### ISSUE TITLE
Using ProductBatch to update more than 100 products.

### ISSUE THREAD

**Issue by piotrgulbis** [XiaoFaye/WooCommerce.NET#69]
Wordpress: 4.6.1
WooCommerce: 2.6.9
WooCommerce.NET: 0.6.0

When trying to update more than 100 Products using ProductBatch the following error occurs:

{"code":"woocommerce_rest_request_entity_too_large","message":"Unable to accept more than 100 items for this request.","data":{"status":413}}

What would be the correct way of handling this?

Splitting the ProductList into multiple ProductLists of 100 Products and then sending each ProductList seperately using ProductBatch?

Or is there a better way?

**Comment by XiaoFaye** [comment]
This is clearly a WooCommerce limitation and no better way.

**Comment by piotrgulbis** [comment]
In case anyone is interested, this is how I've solved it. There is probably a cleaner solution but this one works for me.

```
            var sortedProductList = pl.OrderBy(x => x.id).ToList();
            var productLists = new List<List<Product>>();
            for (int i = 0; i < sortedProductList.Count; i += 100)
            {
                productLists.Add(sortedProductList.GetRange(i, Math.Min(100, sortedProductList.Count - i)));
            }
            foreach (var productList in productLists)
            {
                var productBatch = new ProductBatch();
                productBatch.update = productList;
                await Wc.UpdateProducts(productBatch);
                Console.WriteLine("Updated " + productList.Count + " products");
            }
```

**Comment by XiaoFaye** [comment]
Thanks a lot!
