### ISSUE TITLE
SystemStatus.GetAll not returning any data

### ISSUE THREAD

**Issue by hillsydev** [XiaoFaye/WooCommerce.NET#693]
When executing the following call, an empty collection is being returned:

```
RestAPI rest = new RestAPI(_wooCommUrl, _consumerKey, _secretKey);
WCObject wc = new WCObject(rest);
var systemStatusResult = await wc.SystemStatus.GetAll(null);
```
There is no error being thrown, only systemStatusResult showing a count of 0.

I've tested the same v3 endpoint in Postman and get a complete system status JSON payload returned as expected.

Not sure if this is something that i'm doing incorrectly or a problem somewhere else.  Ideally, I would just like to get the environment information.

I will have to use a raw GET call as a workaround for this one.

- Wordpress version: 6.0
- WooCommerce version:  6.5.1
- WooCommerce.NET version:  0.8.4

**Comment by XiaoFaye** [comment]
You need to use the Get extension method.

![image](https://user-images.githubusercontent.com/6334728/229017222-32deca92-8dc6-4c2e-9f77-1806788ac01c.png)
