### ISSUE TITLE
Category GetAll only get 10 items no more

### ISSUE THREAD

**Issue by xplertor** [XiaoFaye/WooCommerce.NET#697]
When I try to obtain all the woo categories but I only get 10 items when there are actually 25 in the Woo.

- Wordpress 6.0, WooCommerce 6.6.1 and WooCommerce.NET 0.8.4

**Comment by matteozoni** [comment]
Try like this

```
                Dictionary<string, string> ParCall = new Dictionary<string, string>();
                ParCall.Add("per_page", "30");

                var lCategory = await wc.Category.GetAll(ParCall);
```

**Comment by xplertor** [comment]
Fine!! it's work, but does it mean that every GetAll query needs to send a Dic var as a parameter??

**Comment by matteozoni** [comment]
Yes, and if the elements are higher than 100 (maximum limit of the parameter) you have to read the following pages

**Comment by xplertor** [comment]
Thanks!!
