### ISSUE TITLE
Error deserializing when calling Product.GetAll

### ISSUE THREAD

**Issue by cdurham84** [XiaoFaye/WooCommerce.NET#699]
Using WooCommerceNet 0.8.4 for an integration with a client using WooCommerce. 

When I'm trying to pull products I'm getting an error during deserialization, Encountered unexpected character 'ï'. I'm using a dictionary to pass the page and per_page parameters. Here is the call being made:

`var products = await WooCommerce.Product.GetAll(dictParams);`

And here is the error message that I get:

2022/06/28 09:27:03 : Error -- There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.ProductCategory, WooCommerce.NET, Version=0.8.4.0, Culture=neutral, PublicKeyToken=XXXXXXXXX]]. Encountered unexpected character 'ï'.

I've seen similar issues on the board, but I've not seen any concrete solution. Any help is appreciated.

**Comment by kevinamorim** [comment]
Do you have the JSON response body returned by your WC API for get products?
