### ISSUE TITLE
no results returned

### ISSUE THREAD

**Issue by redwolf1630** [XiaoFaye/WooCommerce.NET#70]
So when i run the 'getproducts()' command i  never receive any results back.
 I dont know if there is supposed to be an error message or a reason, but if i do not use the '3000' timeout on the wait then the operation runs indefinitely. not sure what is going on or if i am doing something wrong.

- Wordpress version : 4.7,  WooCommerce version: 2.6.9 and WooCommerce.NET version : 6.01

sample code :

          clientConfig.BaseUrl = "https://<website>/"
 
![image](https://cloud.githubusercontent.com/assets/24610058/21270645/1d3d0c0c-c37d-11e6-9241-f5df5240b19f.png)

here is 't' when i use a break point after t.wait(3000)

![image](https://cloud.githubusercontent.com/assets/24610058/21270361/ef42b802-c37b-11e6-8a0b-b6aae7b5c698.png)

also code never goes beyond 'var products' it just hangs

**Comment by XiaoFaye** [comment]
@redwolf1630 thanks for telling me this, it has been updated.
