### ISSUE TITLE
Woocommerce WPML translations field

### ISSUE THREAD

**Issue by FabPari** [XiaoFaye/WooCommerce.NET#708]
Hi Dear
with wcommerce and WPML on REST api product request you have also variable named "translations" containing list id of products translated.
Possible for you to implement this on the product object?
Thanks
Fabio
![image](https://user-images.githubusercontent.com/66635441/195643954-7f6b8c8d-489c-4eaf-8dab-aa378fa5ba9c.png)

**Comment by XiaoFaye** [comment]
I think you can create a new object with new fields which inherits the product object

**Comment by FabPari** [comment]
Hi dear, tnks to much.
Have you an example to show me?
Tnks
Fabio

Il ven 14 ott 2022, 05:00 James Yang ***@***.***> ha scritto:

**Comment by FabPari** [comment]
I found a solution, and I hope can help some one.

Product object extension:
`namespace WoocommerceExtendedClient
{
    [DataContract]
    public class ProductExtended : WooCommerceNET.WooCommerce.v3.Product
    {
        public static string Endpoint { get { return "products"; } }

        [DataMember]
        public Translations translations { get; set; }
    }
}


namespace WoocommerceExtendedClient.WooCommerce
{
    class WCObjectExtended : WCObject<Coupon, Customer, ProductExtended, ProductReview, Variation, Order, OrderNote, OrderRefund, ProductAttribute, ProductAttributeTerm,
                                    ProductCategory, ShippingClass, ProductTag, TaxRate, TaxClass, Data>
    {
        public WCObjectExtended(RestAPI api) : base(api)
        {

        }
    }

}`

Declaration and usage

`WoocommerceExtendedClient.WooCommerce.WCObjectExtended wc = new WoocommerceExtendedClient.WooCommerce.WCObjectExtended(rest);

var products = new List<WoocommerceExtendedClient.ProductExtended>();
            Dictionary<string, string> pDic = new Dictionary<string, string>();
            pDic.Add("sku", SKU);
            pDic.Add("lang", "it");
 products = wc.Product.GetAll(pDic).Result;


`

thanks for support
Fabio
