### ISSUE TITLE
Application Closes on error 404

### ISSUE THREAD

**Issue by aliajboy** [XiaoFaye/WooCommerce.NET#718]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version 6.1, WooCommerce version 7.0.1 and WooCommerce.NET version 0.8.4

- I Do everything right and happy, but I want to make error for when user input a wrong Order Number and show to user that this order is not available or something like that. BUT, after 404, the application closes it self right after you input an Order number that doesn't exist. I don't want this. what shoud I do to make an if statement to check if this is 404 error or not? and make my action after that. I don't want the application to close!
-  thank you, you are the best

**Comment by richardaubin** [comment]
Can you share your code that is causing the 404.

**Comment by aliajboy** [comment]
Simply, put order number that does not exist and get a 404 error. then program will close itself without showing any error.
in debug mode you get webexception.
thank you

**Comment by richardaubin** [comment]
wrap the call in a try catch block and handle the exception directly to prevent your app from crashing... Return an appropriate error message.

**Comment by aliajboy** [comment]
I did that but need some exact error if that Order number doesn't exist. this try catch will get active even on no network, because if user has no access to internet, WebException will happen and the catch that is for Order number will run again. I think an update is nice for that.
tnx by the way

**Comment by XiaoFaye** [comment]
@aliajboy Try to check the Inner Exception of the exception you have catched.
