### ISSUE TITLE
Error in VB.NET

### ISSUE THREAD

**Issue by markldavison** [XiaoFaye/WooCommerce.NET#72]
Do you have any examples of calling your library from VB.net? I keep getting errors:

{"Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. "}

I am pretty sure I am doing something wrong but I cannot see what and I cannot find any examples using VB.NET. I am trying to call wc.GetOrders()

**Comment by markldavison** [comment]
Sorry, was a stupid mistake on my part.

**Comment by bensongwalker** [comment]
Mark I'm trying to use this wrapper as well with VB.net and am running into issues when trying to pull products? Mind if I pick your brain

**Comment by markldavison** [comment]
Hi,

I can try to help but please bear in mind that I am not started working with this yesterday! I have a console app reading orders but this is as far as I have got.

Please email me directly (mark@theidbandco.com<mailto:mark@theidbandco.com>) and I will try to help if I can as I will also need to work with products at some point. Christmas may slow my responses.

Kind Regards,

Mark Davison
The ID Band Company
http://www.theidbandco.com
0845 2694523

On 22 Dec 2016, at 15:56, bensongwalker <notifications@github.com<mailto:notifications@github.com>> wrote:


Mark I'm trying to use this wrapper as well with VB.net<http://VB.net> and am running into issues when trying to pull products? Mind if I pick your brain

-
