### ISSUE TITLE
Update order custom field

### ISSUE THREAD

**Issue by Magnetize** [XiaoFaye/WooCommerce.NET#73]
Hello and thank you for a great tool!

I have a question, I am doing some tests and I just now managed to update the order status by using `var response = await _wc.UpdateOrder(orderID, new Order { status = "completed" });`
I initially thought that I should call it like this:
`var order = await _woo.UpdateOrder(1034, new Dictionary<string, string> {
                {"status","completed" },
                {"postal_delivery_field","blabla"}
                 });`
I realized that the order did not update and found the correct way by looking through your older issues.
Would love to see an example on the first page with order updates as well. :)

However, now I am wondering how I could update a custom meta field that I added to all orders.
I tried like this (order meta field is called postal_delivery_field):
`var response = await _wc.UpdateOrder(orderID, new Order{ "postal_delivery_field" = "blabla" });`

Visual Studio 2015 tells me "Cannot initialize type 'Order' with a collection initializer because it does not implement 'System.Collections.Enumerable'
Invalid initializer member declarator
The left-hand side of an assignment must be a variable, property or indexer.

I am using WordPress 4.7 and Woocommerce 2.6.11 with .NET 4.5.2 and WooCommerceNET 0.6.1.
I am also using the standard API, i.e. not legacy.

Thanks in advance.

Regards,

**Comment by XiaoFaye** [comment]
There is no way to update custom meta field yet.

**Comment by Magnetize** [comment]
Hello!
Oh I see... Is this something you are planning to implement in the near future?
I am looking through the API code and I think it is prepared for this, if you pass an array called "meta_data" with key => value-pairs it should take care of this already, line 1055 of class-wc-rest-orders-controller.php.

I did some fast tests and shouldn't a structure like this work?
https://dotnetfiddle.net/tpZ6te
Or am I wrong in my assumptions? :)

Regards,

**Comment by XiaoFaye** [comment]
This is a WC REST API limitaion, not much we can do.

meta_data is not listed in the WooCommerce REST API docs, but you can give it a try.

**Comment by Magnetize** [comment]
Ok, I'll try. Think it would be easier if there was a property on the Order object called meta_data though. 
But I'll see what I can do. :)

**Comment by Magnetize** [comment]
Ok, so the problem is that I cannot create an array with field => value relation since "parms" is string,string only.
Managed to update my field by editing the Woocommerce API code, and run update_post_meta with $request['meta_data'].
However, the field is only a string now, not an array as the API would like it to be in order to be able to update the values.

Do you think you would be able to create a fix for this in the near future or should I create my own wrapper?

Regards,

**Comment by XiaoFaye** [comment]
Will this work by only change the parms type to <string, array>? or it requires changes to Woocommerce Rest API source code?

**Comment by Magnetize** [comment]
Hello!
Well I think that the best way would be to create a new object in the Order class, Order.meta_data and then take it from there.
I can set the new order status with Order.status = "completed" and that would be the best way if you ask me, just adding a Dictionary<string,string> to Order.meta_data.
I was not able to test this the whole way though, as I did not have time to rewrite your wrapper.

**Comment by Magnetize** [comment]
Oh yes, that is what I did.
However, I am not very familiar with serialization, so at first I was not able to attach my data to the request.

But now I got it working! Thank you for your assistance. :)

Code of request below:
```
Dictionary<string, string> metaData = new Dictionary<string, string>();
metaData.Add("postal_delivery_field", "itworks!");
OrderTest orderTest = new OrderTest();
orderTest.meta_data = metaData;       
var response = await _wc.UpdateOrder(orderID, orderTest);
```

Custom order class:
```
[KnownType(typeof(OrderTest))]
[DataContract]
public class OrderTest : Order
{
    [DataMember(EmitDefaultValue = false)]
    public Dictionary<string, string> meta_data;
}
```

**Comment by XiaoFaye** [comment]
@Magnetize  Thanks for the idea, I will add this in the next update.

**Comment by Magnetize** [comment]
Sounds great! Let me know when I should update. Thanks again! :)

**Comment by vankampenp** [comment]
@Magnetize just checking, but I think I have done what you are looking for. If so, I'd be happy to share more information.
I wanted to add custom order fields that my postal plugin requires.
So the first step I did was to add these fields for get_callback and update_callback to the WooCommerce REST API in the 'rest_api_init' action.

After that I added the custom fields to my custom order class in .NET, and pass this order class to WCObject on initialisation. This then allows me to get and set the custom order fields on the custom order class:
```
MyOrder order = new MyOrder();
order.billing_street_name = "my street";
order.billing_house_number = "101";
await wc.PostOrder(order)
```
If this is what you are looking for, I will be happy to add any parts of the code that you need clarification on.

**Comment by Magnetize** [comment]
Hey @vankampenp and thanks.
I did not think about adding my fields in the API actually, but that is one way to go.
My Windows service works with my way, using order.meta_data with my own Order class.
But it is good to know about how you solved the problem! :)

**Comment by vankampenp** [comment]
This extends the API for WooCommerce for a number of customer and order fields:
```
add_action( 'rest_api_init', 'slug_register_myfields' );
function slug_register_myfields() {

    foreach( array( 'billing_street_name', 'billing_house_number','billing_house_number_suffix',
                 'shipping_street_name', 'shipping_house_number','shipping_house_number_suffix') as $field ) {

        register_rest_field( 'customer', $field,
            array(
                'get_callback'    => 'get_customerMeta',
                'update_callback' => 'update_customerMeta',
                'schema'          => array(
                    'description' => __( 'Additional Fields', 'woocommerce' ),
                    'type' => 'string',
                    'context' => array( 'view', 'edit' ),
                ),
            )
        );
    };

    foreach( array( 'billing_street_name', 'billing_house_number','billing_house_number_suffix',                 'shipping_street_name','shipping_house_number','shipping_house_number_suffix','vat_number') as $field ) {
        register_rest_field( 'shop_order', $field,
            array(
                'get_callback'    =>'get_orderMeta',
                'update_callback' =>  'update_orderMeta',
                'schema'          => array(
                    'description' => __( 'MyParcel fields', 'woocommerce' ),
                    'type' => 'string',
                    'context' => array( 'view', 'edit' ),
                ),
            )
        );
    };
};

function get_customerMeta($data,$field_name,$request) {
    return get_user_meta( $data[ 'id' ], $field_name, true );
};
function update_customerMeta($value,$data,$field_name) {
    if ( ! $value || ! is_string( $value ) ) return;
    update_user_meta( $data->ID, $field_name, sanitize_text_field( $value ) );

};
function get_orderMeta($data,$field_name,$request) {
        return get_post_meta( $data[ 'id' ], '_' . $field_name, true );
};
function update_orderMeta($value,$data,$field_name) {
    if ( ! $value || ! is_string( $value ) ) return;
    update_post_meta( $data->ID, '_' . $field_name, sanitize_text_field( $value ) );

};
```

In my web app, I look up the current user/customer by email, and then can create an order with these custom fields
  my_Customer cus = await wc.GetCustomerByEmail(email, new Dictionary<string, string>() { { "role", "all" } });
   ...
```
my_Order order = new my_Order();
order.billing_street_name = cus.billing_street_name;
order.billing_house_number = cus.billing_house_number;
order.billing_house_number_suffix = cus.billing_house_number_suffix;
...other fields
await wc.PostOrder(order) 
```         

Works great!  Maybe there is a better way to store the meta fields than working directly on post_meta.

**Comment by Magnetize** [comment]
Ah I see. Nice! :)
Regarding post_meta, when WC 3.0 is released you will get a deprecated warning, so then we should use $order->update_meta_data() instead. They are preparing moving all order data to separate database tables, so they want us to use this method so they can change their CRUD handling without it affecting us. :)

**Comment by piotrgulbis** [comment]
@vankampenp This is exactly what I am looking for but I'm very new to writing Wordpress/Woocommerce functions.

Where would I add your code? Do I have to write my own Wordpress/Woocommerce plugin or can I add this in one of the existing Woocommerce/Wordpress files?

**Comment by vankampenp** [comment]
In the Wordpress Display/Editor, you can add it to functions.php of your child theme. If you do not yet use a child theme, this is the moment to start doing so. Get a child theme from your theme provider, or find out how to create one your self. 
In stead of adding the code above to functions.php, you can also create a separate WooCommerceExtensions.php and add the following in functions.php:
require_once FL_CHILD_THEME_DIR . '/woocommerceextensions.php';

**Comment by vankampenp** [comment]
@piotrgulbis Thanks, I saw that. But I have to wait for WC 3.0 to use the new CRUD functions I assume.

**Comment by XiaoFaye** [comment]
HI @vankampenp , source code of version 0.7.0 has been committed, however, I need to do more testing to release the new version in Nuget.

**Comment by XiaoFaye** [comment]
@piotrgulbis @vankampenp Version 0.7.0 is on nuget now.

**Comment by Magnetize** [comment]
@XiaoFaye Hey man and thank you. I tried the updated version just now and Woocommerce  gladly updated my custom meta field through your wrapper. 😄 
Thank you very much for this! 😃
