### ISSUE TITLE
Price and priceValue: different values

### ISSUE THREAD

**Issue by tiziana-git** [XiaoFaye/WooCommerce.NET#731]
Hello
why does price and priceValue have two different values? Same thing on regular_price and regular_priceValue
![immagine](https://user-images.githubusercontent.com/63848818/227912670-4dba6b31-ba1f-4594-b011-2ab20801aa61.png)

**Comment by tiziana-git** [comment]
I have found the issue, on BaseObject line 61
In this case price is 14.23 but it returns 1423:
![immagine](https://user-images.githubusercontent.com/63848818/228167217-3a787d9f-f56b-4d18-bcf5-be910c099b21.png)

![immagine](https://user-images.githubusercontent.com/63848818/228166981-555bb3e3-f409-4ea0-808e-57b34279d3ff.png)

**Comment by tiziana-git** [comment]
Value.ToString() is 14,23

**Comment by XiaoFaye** [comment]
@tiziana-git Version 0.8.6 has the ability to pass your own CultureInfo, this should fix the issue.
