### ISSUE TITLE
Parameter Description

### ISSUE THREAD

**Issue by swavans** [XiaoFaye/WooCommerce.NET#75]
Hi,

How can I use the parameters?

**Comment by XiaoFaye** [comment]
What do you mean by that?

**Comment by swavans** [comment]
How do I use the parameters in for example wc.Products.Get()
If I want to get products from page 34 for example.
Love the rest of the API btw

**Comment by XiaoFaye** [comment]
First of all, you can see all available parameters here: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

Then there is a GetProducts example in the project home page: https://github.com/XiaoFaye/WooCommerce.NET

**Comment by swavans** [comment]
Okay thnx.
Just create a new dictionary and first one is the parameter, second the value?

**Comment by XiaoFaye** [comment]
Yes, give it a try.
