### ISSUE TITLE
Getting error when just trying to get products.

### ISSUE THREAD

**Issue by mathis1337** [XiaoFaye/WooCommerce.NET#76]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
LAtest versions of all.
- Steps to replicate the issue
RestAPI rest = new RestAPI("http://zrodelta.com/dev/wp-json/wc/v1/", "***", "***");
WCObject wc = new WCObject(rest);

var products = await wc.GetProducts();

products.Dump();
- Details of the error message if there is any
I get this error message.
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

**Comment by XiaoFaye** [comment]
Please try the following:

RestAPI rest = new RestAPI("http://www.zrodelta.com/dev/wp-json/wc/v1/", "***", "***");

**Comment by mathis1337** [comment]
I have exactly that above. It doesn't change anything for me. I still get the same error.

**Comment by mathis1337** [comment]
If I do that on it's own. I don't get an error. Its only once I try to do any of the methods it breaks.

**Comment by XiaoFaye** [comment]
Can you send me a wc api key set so I can have a look? 

please send to xiaofaye(at)msn.com

**Comment by Darkool** [comment]
I get the same error 401 
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

I tried with 3 diferents keys

![image](https://cloud.githubusercontent.com/assets/10353702/23993522/278dbdf4-0a41-11e7-8734-13c401f54842.png)

**Comment by Darkool** [comment]
Okey, fixed, my bad, I removed "www." from my url and works like a charm!
