### ISSUE TITLE
Can i use multiple filter by attribute?

### ISSUE THREAD

**Issue by Poylar** [XiaoFaye/WooCommerce.NET#766]
Why this feature is not allow?
i wanna filter prodcuts by multiple variations with rest api

i can'T do this
`/products?attribute=pa_item_color&attribute_term=30&attribute=pa_item_size&attribute_term=4`
or this
`/products?attribute=pa_item_color=[ids]&pa_item_size=[ids]`

Why?
and what i shoud do, may be some plugin idk

**Comment by XiaoFaye** [comment]
Please check the available parameters here:

https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
