### ISSUE TITLE
Adding tags to a new product

### ISSUE THREAD

**Issue by aaronjohnsonwsu** [XiaoFaye/WooCommerce.NET#77]
WordPress Version: 4.7
WooCommerce Version: 2.6.11
WooCommerce.NET Version: 0.6.1

I am adding products using WooCommerce.NET and I can't figure out how to add a new part with tags. I am able to the part totally fine and I was able to add categories to the product by sending an list with a category id ( or creating a new category if it doesn't exist and then adding the category id to the list). I figured it would be very similar to add a tag but there is not method for adding a new tag or receiving a list of the existing tags. What is the bast way to add tags to a new product?

I tried just adding the tag names to the tags property of the product but that didn't work. This is what I have.

`var p = new Product()
							{
								name = reader[1].ToString().Trim(),
								title = reader[1].ToString().Trim(),
								description = reader[8].ToString().ToUpper(),
								sku = reader[0].ToString().Trim(),
								price = Convert.ToDecimal(reader[3]),
								regular_price = Convert.ToDecimal(reader[3]),
								stock_quantity = Convert.ToInt32(reader[2]),
								in_stock = true,
								backorders = "yes",
								weight = reader[9].ToString(),
								managing_stock = true,
								backorders_allowed = true,
							};

							var vendorname = reader[5].ToString().Trim();

							//ADD THE CATEGORY

							var category = categories.FirstOrDefault(c => c.name == vendorname);

							if (category == null)
							{
								await svc.AddCategory(new Product_Category() { name = vendorname });
							    categories = await svc.GetCategories();
								category = categories.FirstOrDefault(c => c.name == vendorname);
							}

							if (category != null)
                                p.categories = new List<object> { category.id.ToString() };

							

							//ADD THE TAGS

							var tag1 = reader[6].ToString().Trim();
							var tag2 = reader[7].ToString().Trim();
							p.tags = new List<object>() { tag1, tag2};

                            products.Add(p);`

**Comment by XiaoFaye** [comment]
Please check the issue #41

**Comment by aaronjohnsonwsu** [comment]
Thank you @XiaoFaye. Sorry I did not see this issue. When I read through issue I saw a lot on creating a new category and you mentioned that the wrapper is capable of creating a new tags but I was wondering how I can create them using the wrapper? Also, how can i get a list of all the existing tags?

**Comment by XiaoFaye** [comment]
The VS 2015 IDE should show you what you can do:

![image](https://cloud.githubusercontent.com/assets/6334728/21789664/9f2f5ff4-d73b-11e6-8787-6b6767b7e167.png)

**Comment by aaronjohnsonwsu** [comment]
I do not have that list. I am using VS 2015 and I have installed  WooCommerceNET 0.6.1 through nuget.

![capture](https://cloud.githubusercontent.com/assets/13227655/21789819/ae0d7812-d68c-11e6-857a-f32a3b90b160.PNG)

**Comment by XiaoFaye** [comment]
Are you using the legacy APIs? Which under the namespace **WooCommerceNET.WooCommerce.Legacy**

**Comment by aaronjohnsonwsu** [comment]
Yes, I was using the legacy API. I ended up switch my code to use the non legacy version and I got everything working great. Thank you so much for your help.
