### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by tdanti** [XiaoFaye/WooCommerce.NET#78]
Hi,
I run a test site on https://ecommerce.proteam4.it
- Wordpress 4.6.2 on IIS Windows 10 Italian Culture + WooCommerce 2.6.8. + WooCommerce.NET 0.6.1

The error seems only in deserialization of GET requests. 
I also try PUT and is ok.

WooCommerceNET.RestAPI rest = new WooCommerceNET.RestAPI("https://ecommerce.proteam4.it/wp-json/wc/v1/", mykey, mysecret);
WCObject wc = new WCObject(rest);
var pl = await wc.GetProducts();

"There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.Product, WooCommerceNET, Version=0.5.6.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character 'ï'."

I create a key and secret if you whis to test this site. 
ck_fe2072ccec47aa581b5067fbbf5a2ec2eaaadf37
cs_bc4808f78e253e2205852b5bc1c9a1c80d60aef4

I try also in: - Wordpress 4.7.1 on IIS Windows 10 Italian Culture + WooCommerce 2.6.12 + WooCommerce.NET 0.6.1
Same error.

Thank you!

**Comment by XiaoFaye** [comment]
There is a problem in the json that returned from your server, please see the third changes in version 0.6.0. https://www.nuget.org/packages/WooCommerceNET

what you can do is define a function as below:

```
        string trimstr(string json)
        {
            return json.Trim(new char[] { '\uFEFF', '\u200B' });
        }
```

Then assign it to the jsonDeserializeFilter 
```
rest2 = new RestAPI("https://ecommerce.proteam4.it/wp-json/wc/v1/",
                                    "ck_fe2072ccec47aa5xxx5067fbbf5a2ec2eaaadf37",
                                    "cs_bc4808f78e253e2205852bxxx1c9a1c80d60aef4", jsonDeserializeFilter: trimstr);
```

**Comment by tdanti** [comment]
It Works. Thank you!
