### ISSUE TITLE
WooCommerce Subscriptions

### ISSUE THREAD

**Issue by mistercorey** [XiaoFaye/WooCommerce.NET#79]
Hello. I just found this library today, and it is fantastic! 

I wonder if the WooCommerce Subscriptions plugin is in your worldview and on your road map for this library? If not, will you accept pull requests if I extend the project to cover some endpoints for that WooCommerce add-on?

**Comment by XiaoFaye** [comment]
No, it's no in my plan. But any pull requests are welcomed. :)
