### ISSUE TITLE
Getting a 401 error after switching site to https

### ISSUE THREAD

**Issue by aaronjohnsonwsu** [XiaoFaye/WooCommerce.NET#80]
My code was running great when my site was on http but i recently switched it over and now I am getting a 401 error:

`{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}`

I have created a new api key but still not having any luck.

```
            var rest = new RestAPI(_key.StoreUrl, _key.ConsumerKey, _key.ConsumerSecret);
            var wc = new WCObject(rest);
```

Is there a way to get this working?

My api url is: https://<sitename>.com/wp-json/wc/v1/

And when i navigate to the api url i am able to see the details. I have also tried setting the header = false.

**Comment by XiaoFaye** [comment]
This should be a permission issue on the server or Wordpress settings, please check with site administrator.

**Comment by aaronjohnsonwsu** [comment]
Okay, I will contact that hosting provider. Thank you!
