### ISSUE TITLE
Update Order - Method Not Allowed.

### ISSUE THREAD

**Issue by careldegoede** [XiaoFaye/WooCommerce.NET#81]
Aftternoon,

I am unable to update my order status, getting error "method not allowed".
However i can retrieve orders.
I have even loaded the API in code and stepped through.
As soon as i hit "WebResponse wr = await httpWebRequest.GetResponseAsync();" in the RestAPI, it throws an exception.

Any idee?
Your assistance would be appreciated.
regards

Carel

WordPress 4.7.1
WooCommerceNet version 0.5.6.0
WooCommerce 2.6.13

- Steps to replicate the issue
**Get order**
{http://localhost:8088/index.php/wp-json/wc/v1/orders?oauth_consumer_key=ck_3ded64b3f93cea1ebf17b6787ecf4ff3e2f5bb74&oauth_nonce=45f41929a7ef94aee045e15cf1da9eb213172c54&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1485263369&oauth_signature=3gRWYj%2B6F4goaIGg5OVrttawJhCyRbYXjkzBdNoR9QU%3D}

**Then update order from processing to completed**
{http://localhost:8088/index.php/wp-json/wc/v1/orders/23?oauth_consumer_key=ck_3ded64b3f93cea1ebf17b6787ecf4ff3e2f5bb74&oauth_nonce=8d23c71245c5103ccfb49adf9a4ac0649cbb01ef&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1485263297&status=completed&oauth_signature=NVDnMb9uYKnOBuHY2V%2Fv0IwHMGk8VfUkVezkrTmosDo%3D}

- Details of the error message if there is any
"The remote server returned an error: (405) Method Not Allowed."

===Code snippet===
static void Main(string[] args)
        {
            rest = new RestAPI("http://localhost:8088/index.php/wp-json/wc/v1/", "ck_3ded64b3f93cea1ebf17b6787ecf4ff3e2f5bb74", "cs_74dc40af9c1f224be456ef3e7465b72ea8ec96b9",false);
            wc = new WCObject(rest);

            var orders = GetOrders();
            foreach (var item in orders.Result)
            {
                try
                {
                    Updateorder(item);
                }
                catch (Exception ex)
                {

                    Console.WriteLine(ex.Message );
                }
            }
        }

        private static async void Updateorder(Order order)
        {
            var parms = new Dictionary<string, string>() { { "status", "completed" } };
            var response = await wc.UpdateOrder((int)order.id, new Order { status = "completed" });
            //var response = await wc.UpdateOrder((int)order.id, new Order { status = "completed" }, parms);
         }

        private static async Task<List<Order>> GetOrders()
        {
            var parms = new Dictionary<string, string>() { { "status", "processing" } };
            var orders = await wc.GetOrders();
            var result = orders;
            return result;
        }
==============

**Comment by XiaoFaye** [comment]
I assume that your API key set doesn't have the write access?

PS: it's good to hide your API key set in the comment for safety reason.

**Comment by careldegoede** [comment]
Hi, the key is just a test key.
Ill try and google with regards to write access.

Thanks for responding.
write access, i assume that is the read/write permssion when creating the key?

**Comment by careldegoede** [comment]
The solution to my problem was to remove webdav from iis via control panel - windows features
