### ISSUE TITLE
Best way to get all pages

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#83]
- Wordpress version: 4.7.1; WooCommerce version: 2.6.13; WooCommerce.NET version: 0.6.0

I have a doubt about how to do a get all, for example for products.
I'm using the following code to do it:
```
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("per_page", "100");
            int pageNumber = 1;
            dic.Add("page", pageNumber.ToString());
            List<Product> products = new List<Product>();
            bool endWhile = false;
            while (!endWhile)
            {
                var productsTemp = await wc.GetProducts(dic);
                if (productsTemp.Count > 0)
                {
                    products.AddRange(productsTemp);
                    pageNumber++;
                    dic["page"] = pageNumber.ToString();
                }
                else
                {
                    endWhile = true;
                }
            }
```
Is this a correct way of do it?
As I understand the header 'X-WP-TotalPages' of the post has the number of pages, but I don't know if it could be used.

**Comment by XiaoFaye** [comment]
Yes, that should be a way to do it.

**Comment by goguvi** [comment]
Thanks!!

**Comment by DemiladeA** [comment]
I have tried this but I keep getting the same 10 products on every new page

**Comment by goguvi** [comment]
@DemiladeA can you put part of your code?

**Comment by DemiladeA** [comment]
protected async override void OnAppearing()
        {

            dic.Add("per_page", "10");
            int pageNumber = 1;
            dic.Add("page", pageNumber.ToString());
            List<WooCommerceNET.WooCommerce.v2.Product> products = new List<WooCommerceNET.WooCommerce.v2.Product>();
            
            bool endWhile = false;
            while (!endWhile)
            {
                var productsTemp = await wc.Product.GetAll(dic);
                if (productsTemp.Count > 0)
                {
                    products.AddRange(productsTemp);
                    pageNumber++;
                    dic["page"] = pageNumber.ToString();
                }
                else
                {
                    endWhile = true;
                }
            }
            productlist.FlowItemsSource = products;
            base.OnAppearing();


        }

**Comment by DemiladeA** [comment]
@XiaoFaye @goguvi any help please

**Comment by XiaoFaye** [comment]
@DemiladeA Looking at your code, I can see that you had set per_page to 10, sure you will get 10 product per page.

**Comment by DemiladeA** [comment]
@XiaoFaye yes, the issue is I get the same 10 products so the loop never ends

**Comment by XiaoFaye** [comment]
@DemiladeA is it getting the same page every time?

**Comment by DemiladeA** [comment]
Yes it is, but the page number changes

**Comment by goguvi** [comment]
@DemiladeA I tested your code and it works for me.
It could be a WooCommerce error or some plugin.
Try to make an API call throw postman or a similar app and see if you get the same page there too.

![error page](https://user-images.githubusercontent.com/829427/30115449-0dd810f4-931b-11e7-819a-1ed84f1c78ac.png)

**Comment by DemiladeA** [comment]
@goguvi yes its a Woocommece error, that only affects products, pagination for orders work, is there a solution for this

**Comment by cooltechgy** [comment]
how do i get a list of all product id?

**Comment by christechno25** [comment]
Hello Sir. I tried using the above code and it works for retrieving products and categories, but not for ProductAttribute. I currently have 20 attributes and using the code above, the loop never stops. The page keeps incrementing and still I get the same count of the retrieved attributes regardless of the page number. On the second page it should end but it didn't. Is there any way to solve this? Thank you.

**Comment by rtmrodrigues** [comment]
This how I loop all pages (not for products but for orders but you should get there…)


Public Shared Function WC_GetOrderListBetweenDatesStatus(ByVal dateFrom As Date, ByVal dateTo As Date, ByVal status As String, Optional ByVal limit As Integer = 50) As List(Of Order)
            Dim res As New List(Of Order)
            Dim tmpRes As New List(Of Order)
            Dim page As Integer = 1
            Dim hasMorePages As Boolean = True
            Try
                Do While maisPaginas
                    tmpRes = WCAPI.Order.GetAll(New Dictionary(Of String, String)() From {
                                                {"status", status},
                                                {"after", dateFrom.ToString("s") + "Z"},
                                                {"before", dateTo.ToString("s") + "Z"},
                                                {"per_page", 5},
                                                {"page", page}
                                            }).Result

                    If tmpRes.Count <= 0 Then
                        maisPaginas = False
                    Else
                        res.AddRange(tmpRes)
                        page += 1
                    End If
                Loop
            Catch ex As Exception
                'error
                MessageBox.Show(ex.Message, "Error: ", MessageBoxButtons.OK, MessageBoxIcon.Error)
                Err.Clear()
            Finally
                page = Nothing
                tmpRes = Nothing
                hasMorePages = Nothing
            End Try
            Return res
        End Function


Hope it helps...
