### ISSUE TITLE
Updating Prices

### ISSUE THREAD

**Issue by parlights** [XiaoFaye/WooCommerce.NET#84]
I loop through products to update qty & pricing, my problem is when I make the 2nd or third api request my ticket is no longer any good:

products = Await wc.GetProducts(dict)
throws exception:
{"code":"woocommerce_rest_authentication_error","message":"Invalid nonce - nonce has already been used.","data":{"status":401}}

but not on the first 1 or two calls.

what should i be looking for here?

**Comment by XiaoFaye** [comment]
have you tried to give it a delay like Thread.Sleep(200) before each call?

**Comment by parlights** [comment]
I’ve been using
await Task.Delay(milliseconds);

but it does not help

Occasionally it flings:

An exception of type 'System.Net.WebException' occurred in mscorlib.dll but was not handled in user code

Additional information: The request was aborted: The request was canceled.

**Comment by XiaoFaye** [comment]
maybe you can try to do a batch update?

**Comment by parlights** [comment]
Thanks. It turned out to be the multiple Await statements in the async call.

.
