### ISSUE TITLE
Deserialize error: 'parent' is not a valid Boolean value

### ISSUE THREAD

**Issue by tdanti** [XiaoFaye/WooCommerce.NET#85]
Hi,
My test site: https://ecommerce.proteam4.it
Wordpress 4.7.2 on IIS Windows 10 Italian Culture + WooCommerce 2.6.13 + WooCommerce.NET 0.6.1

This one return deserialization error ('parent' is not a valid Boolean value)
var plerr = await wc.GetProducts(new Dictionary<string, string>() { { "sku", "145-132" } });

This one is ok
var plok = await wc.GetProducts(new Dictionary<string, string>() { { "sku", "145-144" } });

Seem this error occurs only on products with "manage_stock = true". 
Both 145-132 and 145-144 are variable product.

I create a key and secret if you whis to test this site.
ck_aab93b2ce749a77f3dcd1d57bb43e35e1b812756
cs_777fb86caf7cdf8224b20fdc834ad6b2c2db3a33

EDIT:
I forgot api call.
WooCommerceNET.RestAPI rest = new WooCommerceNET.RestAPI("https://ecommerce.proteam4.it/wp-json/wc/v1/", mykey, mysecret);
WCObject wc = new WCObject(rest);

Thank you.

**Comment by XiaoFaye** [comment]
In the class Variation, you will need to make changes as below:

Before:
`public bool? manage_stock { get; set; }`

After:
`public string manage_stock { get; set; }`

**Comment by tdanti** [comment]
Ok. Thank you.
I install woocommerce.net via nuget. 
I await next release.
Thank you.
