### ISSUE TITLE
Not saving sale_price

### ISSUE THREAD

**Issue by shawnvdb** [XiaoFaye/WooCommerce.NET#87]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
Latest

I cannot remove the sale_price;

- Steps to replicate the issue
1) I changed the sale price in woocommerce
2) In the code, I retrieve the product, ie myproduct
3) Set myproduct.sale_price = nothing
4) Save myproduct
5) Refresh the product page and the sale price remains

- Details of the error message if there is any
None

**Comment by XiaoFaye** [comment]
try to set the **on_sale** to false
