### ISSUE TITLE
wc.GetProducts() only returned 10 products

### ISSUE THREAD

**Issue by alongtheopenroads** [XiaoFaye/WooCommerce.NET#88]
Wordpress v4.7.2
WooCommerce v2.6.13
WooCommerce.NET v0.6.1

I've tried the sample codes but it only returned 10 products instead of all products. What else do I need to do to get `wc.GetProducts()` to return all products?  Thank you!

```
RestAPI rest = new RestAPI("http://www.yourstore.co.nz/wp-json/wc/v1/", "<WooCommerce Key>", "<WooCommerce Secret");
WCObject wc = new WCObject(rest);

//Get all products
var products = await wc.GetProducts();
```

**Comment by XiaoFaye** [comment]
This is by default, you need to change the page size to get more items.

Please refer to issue: #83

**Comment by alongtheopenroads** [comment]
Ok. Thanks!
