### ISSUE TITLE
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.Dimension]'

### ISSUE THREAD

**Issue by lexadecimal** [XiaoFaye/WooCommerce.NET#89]
Hi,

I'm currently working on a mobile app in Xamarin to display products from a WooCommerce site.

I use the following code to display the product names:

```
protected override async void OnAppearing()
{
	string result = await GetProducts();
	List<Product> product = JsonConvert.DeserializeObject<List<Product>>(result);
	List<string> names = product.Select(x => x.name).ToList();
	wooProductsList.ItemsSource = names;
}

public async Task<string> GetProducts()
{
	string url = "http://www.veluwepoortede.nl/wp-json/wc/v1";
	string key = ConfigurationManager.AppSettings["WcApiConsumerKey"];
	string secret = ConfigurationManager.AppSettings["WcApiConsumerSecret"];

	RestAPI rest = new RestAPI(url, key, secret);
	var result = await rest.GetRestful("/products");
	return result;
}
```

Currently I only have simple products added in WooCommerce, which make the code above work fine. However,  when I change one of the products to a variable product with it's attributes and variations set up, the code breaks. What I get is a message that the current JSON object cannot be deserialized. See details of the error below.

**Application version info:**
Wordpress version is 4.7.2
WooCommerce version 2.6.14
WooCommerce.NET version 0.6.1

- **Details of the error message:**
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WooCommerceNET.WooCommerce.Dimension]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '[0].variations[0].dimensions.length', line 1, position 2443.

**Comment by XiaoFaye** [comment]
can you send me a test api key to test?

**Comment by lexadecimal** [comment]
I have sent you an e-mail with the API key. Thanks in advance.

**Comment by XiaoFaye** [comment]
got it, will check ASAP.

**Comment by lexadecimal** [comment]
Issue has been solved by using the DeserializeJSon method in the RESTApi class instead of the JsonConvert.DeserializeObject method. As you have mentioned by e-mail, the JsonConvert.Deserialized method might not work properly.

**Comment by hikarushin** [comment]
@lexadecimal can you please post the exact code for the fix? I'm currently experiencing it at #122. Thanks

**Comment by bramachado** [comment]
ListMessages list = JsonConvert.DeserializeObject<ListMessages>(dados);

**Comment by bramachado** [comment]
ListMessages msg = JsonConvert.DeserializeObject<ListMessages>(dados);
