### ISSUE TITLE
Bind to DataGridView, Categories and tags appear wrong

### ISSUE THREAD

**Issue by jerryxcoke** [XiaoFaye/WooCommerce.NET#9]
If I try to Bind ProductList properties to DataGridView (as column), Categories and tags isn't appear in DataGridView, only show "(collection)".

**Comment by XiaoFaye** [comment]
the following article might be helpful:

How to: Bind Objects to Windows Forms DataGridView Controls
https://msdn.microsoft.com/en-us/library/y0wfd4yz(v=vs.110).aspx

**Comment by jerryxcoke** [comment]
I think its not actually working, or Am i wrong?

http://pastebin.com/DWVUcuPB

tags and categories:
![prbloem](https://cloud.githubusercontent.com/assets/9079898/16539591/eecd30d0-4047-11e6-861a-9724553906f5.png)

**Comment by XiaoFaye** [comment]
I have no idea how DataGridView works when there is a column value as list. But it seems it should be a customize column, Please check this one:

https://blogs.msdn.microsoft.com/msdnts/2007/01/19/how-to-bind-a-datagridview-column-to-a-second-level-property-of-a-data-source/

**Comment by AmazingPowerShell** [comment]
@jerryxcoke
Hi guys!

It seems you've binded directly the TAGS and CATEGORIES properties to the DG field.
Try to build a string first and only after pass its value to the field.

For example:
StringBuilder productTags = new StringBuilder();
int i = 1;
Foreach(string tag in wooProduct.tags)
{
    if(i < wooProduct.tags.Count)
{
    productTags.Append(tag+", ");
}
else
{
  productTags.Append(tag);
}
}

myDagaGridView.Row.tagsColumn.value = productTags.ToString(); // I don't remember how to mention the field in DGV, please correct the left side of this sentence.
