### ISSUE TITLE
Update by SKU number?

### ISSUE THREAD

**Issue by alongtheopenroads** [XiaoFaye/WooCommerce.NET#91]
This statement only updates by `productid`. Is there a way to update by `sku` number?
`await wc.UpdateProduct(128, new Product { name = "test 9" });`

Thank you,

**Comment by XiaoFaye** [comment]
No, this is not supported by WooCommerce. However, you can get products by sku and then update with the productid.

**Comment by alongtheopenroads** [comment]
I figured that's what I need to do after looking thru the API. 
Thank you
