### ISSUE TITLE
error while Getting child category for each parent category

### ISSUE THREAD

**Issue by ebadola** [XiaoFaye/WooCommerce.NET#92]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
 0.6.1
- Steps to replicate the issue

- Details of the error message if there is any

I got error i was getting top categories  and then for each category i request for each child category
then i get this errors 
![image](https://cloud.githubusercontent.com/assets/11830903/23693605/7b91196c-03ea-11e7-84b8-dfa9338cf3b1.png)

**Comment by XiaoFaye** [comment]
I have tried the same way, didn't get any error messages, can you provide more details?

![image](https://cloud.githubusercontent.com/assets/6334728/23695035/22054c62-0442-11e7-8cdf-636c2d0752e1.png)

**Comment by ebadola** [comment]
actually i'm doing exactly you way
some times it's occur
maybe it's happening because of my internet connection
