### ISSUE TITLE
How to use product attributes

### ISSUE THREAD

**Issue by shawnvdb** [XiaoFaye/WooCommerce.NET#96]
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version
Latest versions

- Steps to replicate the issue
1) I have manually created two product attributes under Products/Attributes
2) How do I though WooCommerce.NET add more items to the attribute?
3) How do I assign the productattribute to a product and select an item?

**Comment by XiaoFaye** [comment]
take a look at here #41
