### ISSUE TITLE
"manage_stock" always sets to "parent" when trying to set "manage_stock" on variation

### ISSUE THREAD

**Issue by arnarleifs** [XiaoFaye/WooCommerce.NET#97]
### Make sure you have included the below details when open an issue. Thank you.

Wordpress version: 4.7.3, WooCommerce version: 2.6.14 and WooCommerce.NET version: 0.6.1

`var message = await _wc.UpdateProduct(productLink.WCProductId, new Product
 {
     regular_price = (decimal?) product.UnitPrice1WithTax,
     sale_price = (decimal?) product.PropositionPrice,
     on_sale = product.PropositionDateTo > DateTime.Now,
     manage_stock = true,
     stock_quantity = (int?) product.TotalQuantityInWarehouse
 });`

This is the code being called. _wc is a WCObject. When running this code it updates everything correctly except the manage_stock, which reverts to the parent managing the stock, but I want the variation to manage it's own stock.

There are no visible error messages.

**Comment by goguvi** [comment]
As far as I understand in your code you are setting manage_stock to true in the general data, not in the data of the variation.

To get a 'parent' at manage_stock the product should manage stock and the variation should not.

I guess you have false at the general manage_stock as well as at product variation, so when you change general data to true the variation shows 'parent'

This is the function being called by the api:
`	/**
	 * Return if product manage stock.
	 *
	 * @since 2.7.0
	 * @param  string $context
	 * @return boolean|string true, false, or parent.
	 */
	public function get_manage_stock( $context = 'view' ) {
		$value = $this->get_prop( 'manage_stock', $context );

		// Inherit value from parent.
		if ( 'view' === $context && false === $value && true === wc_string_to_bool( $this->parent_data['manage_stock'] ) ) {
			$value = 'parent';
		}
		return $value;
	}`

**Comment by goguvi** [comment]
I'm testing the behavior of manage_stock field for variations.
I got the deserializing error commented in #85.
If I do as @XiaoFaye says in that issue (change 'public bool? manage_stock { get; set; }' to 'public string manage_stock { get; set; }') the json deserialization get the correct values to the property, but if I try to update the variation manage_stock to true the value is set to parent.
It seems to update value correctlly if I change the property type to object:
`public bool? manage_stock { get; set; }`
I'm testing the following copy:

```
            int product_id = 289;
            int v1_id = 290;
            int v2_id = 291;
            int v3_id = 292;

            Variation v1 = new Variation();
            v1.manage_stock = false;
            v1.id = v1_id;

            Variation v2 = new Variation();
            v2.manage_stock = true;
            v2.id = v2_id;

            Variation v3 = new Variation();
            v3.manage_stock = "parent";
            v3.id = v3_id;

            List<Variation> vl = new List<Variation> ();
            vl.Add(v1);
            vl.Add(v2);

            var json = await wc.UpdateProduct(
                product_id,
                new WCProduct {
                    manage_stock = false,
                    variations = vl,
                });

            var p = await wc.GetProduct(product_id);
```

**Comment by XiaoFaye** [comment]
@arnarleifs @goguvi This has been fixed in the latest commit, a nuget release is on the way.

**Comment by XiaoFaye** [comment]
@arnarleifs  BTW, manage_stock will always be "parent" if you are getting Variations, as Variations are under product.

**Comment by goguvi** [comment]
@XiaoFaye I've already seen #131 thanks for your work.

> manage_stock will always be "parent" if you are getting Variations, as Variations are under product.

That's not exactly true. See https://github.com/XiaoFaye/WooCommerce.NET/issues/97#issuecomment-290643535 

> To get a 'parent' at manage_stock the product should manage stock and the variation should not.

For example if both Product and Variation have manage_stock set to true both will return `"manage_stock": true,` at the JSON

**Comment by arnarleifs** [comment]
This is a late response! But the latest update covers this 👍
