### ISSUE TITLE
Result values when call Post methods

### ISSUE THREAD

**Issue by OscarLate** [XiaoFaye/WooCommerce.NET#98]
First thanks for this library, and my question is  how can I know the Id of Product when call PostProduct? I was expected something like _wc.PostProduct(product).Id_ or PostProduct returning a Product Object.

How do you do it?

Regards,

**Comment by XiaoFaye** [comment]
PostProduct returns the json string of the product, you can deserialize it into Product object.

**Comment by OscarLate** [comment]
Yes, thanks! I don't know how but I didn't see it
