### ISSUE TITLE
New version and my pull request

### ISSUE THREAD

**Issue by goguvi** [XiaoFaye/WooCommerce.NET#99]
I wonder if you're planing to implement the new version of the API that will be implemented in version 3 of WooCommerce
https://woocommerce.wordpress.com/2016/12/15/woocommerce-2-7-beta-1-is-here/

Also I want to know if there something wrong with the pull request XiaoFaye/WooCommerce.NET#82 as you never anwser it.

Thanks in advance.

**Comment by XiaoFaye** [comment]
It seems it's still in Beta version and the official REST docs has not been updated. Surely I will follow up when it's released. Thanks for the information.

Your pull request is all good, I was going to merge it when releasing the next version. Sorry for the confuse, I will merge it now. :)

**Comment by goguvi** [comment]
Yes you are right The new version of woocommerce is still in beta. But the documentation for the new version of the API is now available: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by XiaoFaye** [comment]
Yes, I have noticed that, will commence the v2 soon. :)

**Comment by vankampenp** [comment]
It has been renamed to Woocommerce V3 and is now in RC2.

**Comment by XiaoFaye** [comment]
@vankampenp I meant the API version v2. :)
some of the routes might work, but indeed there are lots of changes in api v2.
